In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/apple_support_clean.csv")

print("Shape:", df.shape)
df.head()

Shape: (106523, 6)

,customer_tweet_id,customer_message,previous_message,has_context,parent_author,brand_response
0,698.0,@AppleSupport https://t.co/NV0yucs0lB,@AppleSupport why are my I️’s changing not sho...,True,115854,@115854 We're here for you. Which version of t...
1,697.0,@AppleSupport The newest update. I️ made sure ...,@115854 We're here for you. Which version of t...,True,AppleSupport,@115854 Lets take a closer look into this issu...
2,702.0,@AppleSupport Tried resetting my settings .. r...,@115855 Any steps tried since it started last ...,True,AppleSupport,@115855 Let's go to DM for the next steps. DM ...
3,704.0,@AppleSupport This is what it looks like https...,@115855 That's great it has iOS 11.1 as we can...,True,AppleSupport,@115855 Any steps tried since it started last ...
4,707.0,@AppleSupport I️ have an iPhone 7 Plus and yes...,@115855 We'd like to look into this with you. ...,True,AppleSupport,@115855 That's great it has iOS 11.1 as we can...

In [2]:
from collections import Counter
import re

# Customer messages only
customer_text = (
    df["customer_message"]
    .fillna("")
    .astype(str)
    .str.lower()
)

# Extract words
words = re.findall(
    r"\b[a-z][a-z0-9']+\b",
    " ".join(customer_text)
)

# Generic words that don't help identify support topics
stop_words = {
    "the", "and", "to", "a", "i", "is", "it", "of", "my", "for",
    "on", "in", "this", "that", "with", "you", "can", "be", "have",
    "do", "does", "how", "why", "what", "please", "help", "me",
    "apple", "support", "iphone", "im", "i'm", "we", "us", "they",
    "your", "are", "was", "but", "not", "just", "so", "or", "if",
    "at", "from", "about", "after", "when", "any", "get", "got",
    "has", "had", "will", "would", "all", "now", "up", "out",
    "there", "really", "like", "as", "an", "dont", "don't",
    "its", "it's", "been", "no", "yes", "also", "more", "one",
    "only", "still", "new", "phone", "device"
}

filtered_words = [
    word for word in words
    if word not in stop_words
    and len(word) > 2
]

word_counts = Counter(filtered_words)

print("Top 100 candidate topic terms:\n")

for word, count in word_counts.most_common(100):
    print(f"{word:<25} {count:,}")

Top 100 candidate topic terms:

applesupport              78,917
ios                       16,128
https                     15,932
update                    15,895
fix                       14,518
battery                   8,527
since                     5,970
app                       5,148
time                      4,943
updated                   4,858
off                       4,608
screen                    4,508
ios11                     4,332
shit                      4,247
apps                      4,185
work                      4,149
thanks                    4,091
issue                     4,047
amp                       4,038
hey                       3,927
problem                   3,845
back                      3,692
every                     3,682
even                      3,657
need                      3,574
working                   3,561
music                     3,452
going                     3,385
keeps                     3,005
use                       2,911
don                       2,805
letter                    2,699
did                       2,583
question                  2,583
doesn                     2,554
getting                   2,545
type                      2,484
last                      2,452
having                    2,416
plus                      2,401
wtf                       2,385
wifi                      2,311
same                      2,306
ever                      2,294
latest                    2,293
then                      2,248
tried                     2,238
know                      2,175
again                     2,174
life                      2,160
bug                       2,159
keep                      2,124
slow                      2,093
times                     2,085
won                       2,085
day                       2,078
want                      2,078
issues                    2,065
using                     2,065
make                      2,048
ipad                      2,046
see                       2,036
glitch                    2,024
because                   1,994
updates                   1,956
store                     1,946
turn                      1,932
before                    1,924
freezing                  1,902
these                     1,887
some                      1,872
annoying                  1,856
thank                     1,845
software                  1,825
itunes                    1,804
down                      1,799
already                   1,790
never                     1,788
fucking                   1,783
way                       1,738
into                      1,731
watch                     1,715
trying                    1,691
fixed                     1,681
very                      1,674
them                      1,663
mark                      1,648
icloud                    1,643
too                       1,626
stop                      1,615
keyboard                  1,602
thing                     1,594
than                      1,585
can't                     1,571
nothing                   1,560
guys                      1,550
macbook                   1,540
other                     1,517
text                      1,505
over                      1,503

In [3]:
# Candidate topic keywords based on the frequency analysis.
# We will inspect real examples before deciding on final intents.

candidate_topics = {
    "battery": ["battery", "charging", "charge", "drain", "power"],
    "ios_update": ["ios", "ios11", "update", "updating", "upgrade"],
    "wifi_connectivity": ["wifi", "wi-fi", "bluetooth", "connection", "connect"],
    "screen_display": ["screen", "display", "brightness", "touch"],
    "apps": ["app", "apps", "application"],
    "icloud": ["icloud"],
    "apple_id": ["apple id", "icloud account", "password"],
    "audio": ["speaker", "sound", "audio", "volume", "headphone"],
    "camera": ["camera", "photo", "photos", "video"],
    "keyboard": ["keyboard", "key", "typing"],
    "mac": ["macbook", "mac", "macos", "osx"],
    "apple_music": ["apple music", "music", "playlist"],
    "airpods": ["airpod", "airpods"],
    "apple_watch": ["apple watch", "watch"],
}

for topic, keywords in candidate_topics.items():
    pattern = "|".join(
        re.escape(keyword)
        for keyword in keywords
    )

    mask = customer_text.str.contains(
        pattern,
        regex=True,
        na=False
    )

    topic_examples = df.loc[
        mask,
        "customer_message"
    ]

    print("\n" + "=" * 70)
    print(f"{topic.upper()} — {len(topic_examples):,} matching messages")
    print("=" * 70)

    if len(topic_examples) > 0:
        examples = topic_examples.sample(
            min(10, len(topic_examples)),
            random_state=42
        )

        for i, message in enumerate(examples, 1):
            print(f"{i}. {message}")

======================================================================
BATTERY — 11,082 matching messages
======================================================================
1. @AppleSupport hey could you please check my iPhone 7? The battery drainage is pretty quick in the recent days not sure why.
Thank you.
2. @AppleSupport I didnt want to re-purchase https://t.co/VpYV2ucsiQ. I got charged today. Please help to unsubcribe and get refund. Thank you!
3. @AppleSupport The battery has been consistently draining, but it definitely has gotten worse with the iOS update.

All of my apps are up-to-date and I always close the background apps too. For example, my phone was at 100% this morning and drained to 3% in three hours after just texting.
4. @115858 what is up wth your new IOS update? It is KILLING my battery 😫
5. @applesupport 11.0.3 battery
updated to 11.0.3 this a.m. and now iphone 6 battery % is ticking down like a timer....crap update !!!
6. @AppleSupport Hi, are you thinking of doing anything to solve the battery problem? Got worse after every update. My iPhone 6 died because of you and I’m very angry!
7. My phone overheats after 10 minutes of being in a call, my battery dies within an hour, and my camera won’t work. Any ideas? @AppleSupport
8. How does my phone lose battery while it’s charging??? How Sway?? @AppleSupport
9. @AppleSupport battery on 6s plus is horrible since new phones announced. This also includes 6 other people I know same phone. 🤔
10. @185087 @662975 @115858 Since the update my battery life on my 6s is awful.

======================================================================
IOS_UPDATE — 36,236 matching messages
======================================================================
1. Updated my happily functioning iPhone. Now it’s outdated and not working. @AppleSupport. Planned obsolescence should be criminalized.#Apple
2. Yo @115858 why does the new update make my phone battery go from 100% to 59% after replying to a text &amp; posting a new tweet?
3. @AppleSupport why is the latest update to 11.0.3 crashing apps or won’t allow them to function ie instagram. #CantEvenMakeASimplePost 😤
4. @AppleSupport IPhone 6S. iOS 11.0.3 (15A432). I upgraded the iOS 2 days ago.
5. Ok so iOS 11.1 is super glitchy &amp; still sucks power.  #betaRegret  @AppleSupport
6. Ok @115858 when is the update? Cuz I’m really over this. Yes, I️ did the keyboard settings already and it works only for text and not apps🙄
7. @AppleSupport sort your lives out mates my phones been fucked since your shitty update
8. @AppleSupport what’s going on with the keyboard? Ever since the latest update it is replacing my ‘i’ with A and a ?
9. @115858 y’all got my phone on some trash ever since this update it’s acting possessed af.....
10. In all politeness: @AppleSupport get your shit together!!! iOS 11.1 sucks battery like never seen before. -10% in 1h standby. #ios11bugs

======================================================================
WIFI_CONNECTIVITY — 4,577 matching messages
======================================================================
1. @AppleSupport hay apple is there anyway to close my wifi from the control center??!!
2. @AppleSupport Just a few contacts, not all. I get the red exclamation point. Tried all fixes from link and still nothing. Connectivity is fine as well.
3. I cant play music whilst being connected to wifi why @AppleSupport
4. @AppleSupport @115858 when will there be a new update for iOS 11.0.3?? The current version is the worst I have used. Exits WiFi repeatedly
5. @AppleSupport Why do my playlists start over? It seems like every time I connect to Bluetooth they reset.
6. @AppleSupport both bluetooth with the powerbeats 3 and without headphones whatsoever
7. HEY @115858 WHY IS MY BLUETOOTH CONSTANTLY TURNING ITSELF ON BY ITSELF I WANT ANSWERS
8. @AppleSupport IOS11 is fucking shit WiFi &amp; Bluetooth haven’t work properly since I updated &amp; both worked perfectly before! Needs tb fixed.
9. @115858 tu peux m’expliquer pourquoi le wifi et le Bluetooth s’activent tout seul sur mon portable??? Et tout le temps?
10. @115858 @AppleSupport please add an AirPods connection option to  control center. Going through settings every time is annoying and too long

======================================================================
SCREEN_DISPLAY — 6,165 matching messages
======================================================================
1. @AppleSupport Hi, my parents Mac mini keeps getting a large pop up on screen saying they have 32 viruses 3 critical. Told them to delete recycle bin etc but keeps getting this message. Is this adware? How do I remove this for them?
2. @115858 can u help me with an issue I’m having with the screen record on my SE. It counts down from 3 but stays white.
3. I dropped my phone again Thursday cracking my screen even more but now my battery is dieing within 5 hours .. wtf @115858
4. @115858 IOS 11- Calculator doesn't work properly, screen becomes dark after the call ends, takes time to turn on the torch. Fix it soon.
5. @AppleSupport What’s going on!!!! after 11 IOS update my iPhone is now full of lags. Lock screen lag is the worst. Help please ❌❌❌ https://t.co/RKTs72Gl5y
6. @AppleSupport PFA, even when I updated I gt a error warning stating,unable to update the touch ID.U must fix this.This is really a smart trick so that I wl purchase urs new dum Iphone7,I m a happy customer of 5s&amp;iphoneX. https://t.co/IuofZa4HSo
7. @115858 anyone else having trouble with their iOS 11 lock screen clock disappearing? Can’t see any notifications but I can hear when I get them. Only fix is powering off and on.
8. @AppleSupport The keyboard used to take up the whole display before iOS 11.
9. And is anyone else’s screenshots just blank?? Like all black or white?? Wtf is goin on @115858?!
10. @116333 @115858 @AppleSupport iOS 11.0.2 also sucks. Still problem w/ data, touch screen and battery life. This is by far the worst iOS

======================================================================
APPS — 82,969 matching messages
======================================================================
1. @13946 @AppleSupport why is my phone saying invalid sim? One min it’s fine, then says no SIM card and now says invalid sim! 😡
2. @AppleSupport Since I upgraded to ios 11 and 11.1, my battery drains too fast! I got a new iphone 7 plus and still the same issue!
3. Is the new @AppleSupport @115858 glitch changing the word it to I.T ? Anyone else?
4. Okay seriously @AppleSupport what’s up with this I️ thing with the A [?] I’ve got some solid material to tweet and you’re ruining my game!!!
5. @AppleSupport My iCloud account was auto-updated to two-factor authentication. After submitting the six-digit authentication number, I’m asked for a four-digit “iCloud Security code”. No idea what this is, and clicking on “Forgot Code?” gives me an endless spinner. Thanks. https://t.co/fcZ9mHC1F3
6. Hey @AppleSupport fix this https://t.co/YbXSAs96gb
7. @AppleSupport Why does Maps have a faint beep when Siri speaks?
8. @AppleSupport why is my iPhone restarting every 5 mins or so. Same with my wife iPhone. My phone 7S+,  wife 6S+
9. @AppleSupport That’s not working. It tells me to call again today and it still hangs up because of high call volumes
10. Why The Update Won’t Let Me Put The Letter I️ It’s A Dumbass Box 😒  @AppleSupport

======================================================================
ICLOUD — 1,524 matching messages
======================================================================
1. @AppleSupport &amp; I've never backed it up on iCloud before 🤦🏽‍♀️
2. .@AppleSupport .@115858 iCloud backup does not backup or restore keyboard shortcuts in iOS11 (even encrypted backups). Also manually typing into new device duplicates entries on other devices. Deleting one entry deletes both. Seriously messed up. https://t.co/oZTCkiY6Vw
3. @115858 I know my iCloud storage is full thank you please fix this I️ thing
4. @AppleSupport since my contacts are on iCloud shouldn’t they automatically sync. Suppose I delete on the phone it should go from iPad too?
5. @AppleSupport why is my iPhone 7+ DLing all my photos to my phone. I have no space anymore. My icloud still over a 100gb free of space. Wtf?
6. @AppleSupport None of my photos are on iCloud
7. @115858 @AppleSupport locked out of my icloud, not getting two factor aunthetication text.. a
8. @115858 @AppleSupport ummm this last iOS update has deleted my iTunes library I’m unable to download it from iCloud &amp; can’t playback the few songs that are on my phone WTF?!?!
9. @AppleSupport Is iCloud on iOS on the fritz again?! I can't log in to any of my devices. Desktop login is ok but iOS logins are locking my account up. This sucks Apple!
10. @AppleSupport Hi, I do use iCloud Photo Library and they disappear when I’m connected to wifi and when I’m not, I signed into iCloud on my laptop and they’re still there they’ve just disappeared from the phone

======================================================================
APPLE_ID — 1,419 matching messages
======================================================================
1. @AppleSupport Ever since I got my iPhone X I’ve been prompted to sign in to iCloud every day at the same time. I’ve tried completely signing out then back in, changing the password, nothing has worked so far. Any ideas?
2. @115858 is so annoying to have to wait multiple days to reset a password 🙄🙄🙄
3. @AppleSupport hy, i have 2 apple id. And both of them are disabled. I've tried to reset password but still disabled. How to fix it? thanks
4. @AppleSupport Hola, ya no utilizo el correo con el que di de alta mi Apple ID y cerré esa dirección hace años.

¿Cómo puedo recuperar mi cuenta de Apple ID?
5. @AppleSupport Yes now it’s saying an Apple ID cannot be created at this time
6. @AppleSupport I can’t sign into my iCloud on my mac because it’s not letting me type in the verification code anywhere for my Apple ID???
7. @AppleSupport It happens whenever it is on, whether it's logged in or when I'm typing in my password
8. Ok after FOUR tries I am done done. SCREW you @115858 TV. I have put in the password and verification codes! #whatisthisfortknox ? #fail
9. @AppleSupport Yes, restart had no effect. Even on other devices with same Apple ID I can‘t hide the purchased apps.
10. @AppleSupport wth!!?? Is this real? Root user without password !!! https://t.co/l1gel72u0F

======================================================================
AUDIO — 2,424 matching messages
======================================================================
1. My Apple Music is overriding Spotify on my Bluetooth headphones AND my watch I AM NOT AMUSED @115858
2. @AppleSupport for the past few weeks my phone has been freezing repeatedly with the @126972 app and wont even allow me to lock it once it freezes. The screen freezes and sound continues. What’s going on?
3. @AppleSupport Volume not working correctly, won’t connect properly to the car bluetooth, alarms not working (with sound) the list seems to be growing!
4. These @118845 wireless headphones suck something terrible. Breaking up and cutting up and my phone is just in my pocket. You really can’t figure out how to make a better 2 foot connection?
5. @AppleSupport hi, i got a mail about soundcloud and i dont know if it's real https://t.co/HQKwHOCB8Z
6. So @115858 has fixed that text bug with iOS 11.1.1. How about fixing the no sound bug when we screen recorded.
7. @115858 why isn't the sound working on my phone ???
8. @AppleSupport Yes, updated it on Mon &amp; that’s when all the issues started w/the speaker. Also my phone freezes a lot since then. More concerned w/speaker.
9. I’ve got no sound coming through my phone since updating it - Can’t speak to people on the phone &amp; my alarm doesn’t go off!! @AppleSupport
10. @AppleSupport @179841 My phone hasn’t worked for probably 3 weeks. Can’t make calls or FaceTime since the keynote speech. And my SnapChat doesn’t record volume

======================================================================
CAMERA — 3,236 matching messages
======================================================================
1. @AppleSupport When you open the camera app from standby, it lacks and shows the view in half window sometimes...
2. So many reasons why i cant stand ITunes, spent the past 2 days trying to sort everything out on my new phone, itunes enjoys putting videos/pictures on my phone that i cant delete from my phone @AppleSupport help before i break something out of anger
3. Well since I have update my iPhone 5s with #IOS11, it's been the slowest phone I had. Bug when calling, take 30 seconds to open apps or camera. @AppleSupport I was and I still am a fan of your product but please stop your planned obsolescence! I beg you it's not fun...
4. @AppleSupport Don't knw if its relevant, but post d update of 11.0.2, my iP-8 is behaving crazy ..camera lags so is the rotation &amp; facetime
5. ....@AppleSupport  my 8Plus just started making a crackling noise when trying to watch videos... what Can I do to fix it?! It’s driving me crazy!
6. Hey @AppleSupport: 11.x upgrades worse with every release! Poor battery life, email format issues, and freezing screens while texting photo
7. @AppleSupport Is there anyway to restore deleted photos?
8. @AppleSupport Like I went to my camera roll and did the exact same thing I normally do to change it.
9. @115858 your updates have caused a great product to be subpar. It’s slowed my phone down and I have missed photo ops of my 2yr old.:( #slow
10. Why does the iphone 6s front camera make my face look so asymmetrical when the 5s doens’t??? @AppleSupport

======================================================================
KEYBOARD — 2,581 matching messages
======================================================================
1. loving this cool new iOS 11.1 feature that turns ever other vowel on my phone and keyboard into a super mario block [?] @AppleSupport
2. @AppleSupport please fix this keyboard glitch, I️ sound like an idiot.
3. Is anyone else having trouble typing the letter “i” on their iphone? @AppleSupport @115858
4. Hi @AppleSupport

Not impressed with your later IOS 11...

Clickable items “flashing up” and moving on a touch screen (ie “the dock”) is exceptionally frustrating.

Likewise with the newer IOS touch-keyboards.

I’m at the point where I’m putting my Apple devices down, angry.
5. @AppleSupport This is madness... I️ can’t take the question marks anymore! Fix the typing “I”!!! #fixit #appleissues #iphoneproblems
6. Facing a lot of glitches with the Apple Keyboard for iPad Pro 9.7 after #ios11 @AppleSupport
7. @AppleSupport Everything force closes , Youtube, Snapchat , Facebook ,  &amp; my keyboard forever lagging &amp; glitching , and “IT” still can’t be typed without I.t being corrected to ‘I.t’
8. .@AppleSupport WHAT IS THIS MALARKEY?!??!! https://t.co/6ytQbpkcfZ
9. @115858 why does my phone keep typing this piece of shit message every time I️ use the letter “I️” I’m going to buy a droid. https://t.co/hO3lUspjxb
10. @AppleSupport why am I️ still having such a hard time typing the letter I️. This problem shouldn’t even be a problem. This is pissing me off

======================================================================
MAC — 3,550 matching messages
======================================================================
1. $3000 iMac can't handle 64 audio tracks on Logic X is super disappointing. It's 2017 @115858 @AppleSupport
2. @AppleSupport Yes can play it on my MacBook, tried to sync song via iTunes from MacBook onto my phone but this did not work either.
3. My @115858 #iMac ($2300 machine) already needs new Fusion Drive &amp; memory. 5 weeks old! Ugh! My luck... I even missed @116333 in Chicago! 😫
4. Also, @AppleSupport I think my MAC has a virus! What do I do!
5. Hey @AppleSupport ive just updated my MacBook and now it won’t connect next to any WiFi. Is this a problem everyone’s having?
6. @296629 @115858 Mac book charger tryna burn my house down
7. Hey @AppleSupport My Mac Finder icon now looks like this, can you help.  Tried restarting and still broken. https://t.co/shLSIb4tG9
8. @AppleSupport It’s a MacBook Pro and high Sierra
9. @AppleSupport the text reactions aren't working in iMessage. also when I FacetTme from my MacBook, the person I'm talking to can't see me
10. @AppleSupport So if I have a pretty good internet connection and I save a file on my iMac, both are connected to the same wifi when the save is made ... how long roughly until the updated version appears on the MacBook?

======================================================================
APPLE_MUSIC — 3,242 matching messages
======================================================================
1. When @115858 fixes the whole autocorrect issue with the "I", can they also please fix the bug that puts U2 music on your phone? #apple #U2 #donotwantit #makeitstop
2. @AppleSupport hi i purchased a 3 month membership for Apple Music on 27 SEP and now ITunes is asking me to sign up again ???
3. But why tf can’t I play music from my phone in my car via USB anymore???🧐🧐 and why are my playlists not shuffling😩😩 @AppleSupport
4. @195269 @AppleSupport After download 11.0.2, battery drain like mad for 4-mths old iPhone 7+ even with little usage, no video or music.
5. @AppleSupport loads of music on two dead I pods.. can these be fixed https://t.co/QmRbBHdq5C
6. Can we store music in iCloud? @AppleSupport
7. @AppleSupport I am also having issues with Apple Music. My family can’t access our family share #applemusic
8. Why can’t I add music to my library? @115948 @AppleSupport 😩
9. Apple Music - the worst, unstable, unreliable music streaming service. @115858 are you going to fix it?
10. Thanks to IOS 11, my phone freezes constantly, my music doesn’t play, my battery is shit, and I can’t call anybody 🙃😇 @115858

======================================================================
AIRPODS — 257 matching messages
======================================================================
1. @120640 Your apple store is driving me crazy.  Gave Airpods to my daughter and they won't help her replace a case. VERY poor service
2. My #AirPods keep jumping going on and off during play... any ideas? @AppleSupport
3. @AppleSupport My AirPods skip like crazy and the mic seems muted and can’t be unmuted on my Mac. $160 worth of junk apparently
4. @AppleSupport iOS broke my AirPods, 75% of time must disconnect them from Bluetooth before I can connect. No Btooth widget in control center
5. @AppleSupport It says that I have gotten an email from Apple I clicked on the attachment but have down nothing else. How do I know if it’s genuine please. It’s said to verify my apple account. Should I delete the email? It also says somebody tried to by airpods from Russia
6. @AppleSupport I have not.

I was having Airpods issues and contacted apple last night...we rebooted airpods and disconnected from phone and reconnected.

hence, my need to change the setting back to "double tap to pause" which had been working flawlesly for months.
7. Anyone else experiencing weird behavior when using #AirPods for iTunes when building in #Xcode? Consistently, when I Build &amp; Run projects, the audio cuts out and then resumes at 3x to "catch up" to where it should be in track. Very weird. @AppleSupport
8. @AppleSupport Any idea what gives? Dictation works fine through my AirPods, but not via the phone. Phone works fine for voice calls without AirPods.
9. .@AppleSupport Hi, after update to iOS 11.1 Airpods lose connection when phone held against body ca. 50cm away from Airpods. iPhone 6, 64 GB
10. @AppleSupport @115858 left AirPod trouble -&gt; disconnected from phone, now AirPods case not recognized. Light won't go amber no matter what! https://t.co/2HcAfEegac

======================================================================
APPLE_WATCH — 1,965 matching messages

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

# Use customer messages to discover common 2-word and 3-word phrases.
vectorizer = CountVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(2, 3),
    min_df=100,
    max_features=200
)

X = vectorizer.fit_transform(
    df["customer_message"]
    .fillna("")
)

phrase_counts = X.sum(axis=0).A1

phrases = pd.DataFrame({
    "phrase": vectorizer.get_feature_names_out(),
    "count": phrase_counts
}).sort_values(
    "count",
    ascending=False
)

print("Top 100 common phrases:\n")

display(
    phrases.head(100).reset_index(drop=True)
)

Top 100 common phrases:

                 phrase  count
0                ios 11  10558
1   115858 applesupport   4910
2   applesupport iphone   3043
3            115858 fix   2976
4   applesupport 115858   2643
..                  ...    ...
95    dear applesupport    434
96             don know    431
97  applesupport having    431
98            times day    430
99          shit 115858    427

[100 rows x 2 columns]

In [5]:
# Candidate intent families.
# These are hypotheses, NOT final labels.

intent_keywords = {
    "battery_charging": [
        "battery", "battery life", "battery drain",
        "charging", "charge", "charger", "overheating"
    ],
    "ios_updates": [
        "ios", "ios 11", "ios11", "update", "updating",
        "upgrade", "software update"
    ],
    "wifi_connectivity": [
        "wifi", "wi-fi", "bluetooth", "connection",
        "connect", "network", "internet"
    ],
    "apple_id_account": [
        "apple id", "password", "account", "sign in",
        "login", "verification", "authentication"
    ],
    "icloud_backup": [
        "icloud", "icloud backup", "backup", "sync",
        "synchronization"
    ],
    "apps_app_store": [
        "app store", "apps", "app", "application",
        "download app", "update app"
    ],
    "audio": [
        "speaker", "audio", "sound", "volume",
        "headphones", "headphone", "earphone"
    ],
    "camera_photos": [
        "camera", "photos", "photo", "pictures",
        "video", "camera roll"
    ],
    "display_touchscreen": [
        "screen", "display", "touchscreen", "touch",
        "brightness", "black screen", "white screen"
    ],
    "apple_music": [
        "apple music", "music", "playlist",
        "songs", "song"
    ],
    "apple_watch": [
        "apple watch", "applewatch", "watch"
    ],
    "airpods": [
        "airpods", "airpod"
    ],
    "mac_macos": [
        "macbook", "macos", "mac os", "osx"
    ],
}

coverage = []

for intent, keywords in intent_keywords.items():
    pattern = "|".join(
        re.escape(keyword)
        for keyword in keywords
    )

    mask = customer_text.str.contains(
        pattern,
        regex=True,
        na=False
    )

    count = mask.sum()

    coverage.append({
        "intent": intent,
        "matching_messages": count,
        "percentage": round(
            count / len(df) * 100,
            2
        )
    })

coverage_df = (
    pd.DataFrame(coverage)
    .sort_values(
        "matching_messages",
        ascending=False
    )
    .reset_index(drop=True)
)

display(coverage_df)

                 intent  matching_messages  percentage
0        apps_app_store              82969       77.89
1           ios_updates              36236       34.02
2      battery_charging              10604        9.95
3   display_touchscreen               6165        5.79
4     wifi_connectivity               4998        4.69
5           apple_music               3739        3.51
6         camera_photos               3593        3.37
7      apple_id_account               2642        2.48
8                 audio               2510        2.36
9         icloud_backup               2330        2.19
10            mac_macos               2125        1.99
11          apple_watch               1965        1.84
12              airpods                257        0.24

In [6]:
import pandas as pd

# Create a reproducible inspection sample.
# We will manually review these examples before finalizing intents.

sample_size = 100

inspection_sample = (
    df.sample(
        n=sample_size,
        random_state=42
    )
    [
        [
            "customer_tweet_id",
            "customer_message",
            "previous_message",
            "brand_response"
        ]
    ]
    .reset_index(drop=True)
)

# Add an empty column for our manual intent label.
inspection_sample["intent"] = ""

# Add an optional notes column for ambiguous cases.
inspection_sample["notes"] = ""

display(inspection_sample)

,customer_tweet_id,customer_message,previous_message,brand_response,intent,notes
0,1533007.0,@115858 what’s up with this nonstop “I” issue?...,NaN,@475474 Let's look into this together. Reach o...,,
1,1224310.0,@AppleSupport my iPhone 7 screen is all white ...,NaN,@407226 Hi there! Let's try out these steps: h...,,
2,2000766.0,@461407 @115858 I️ mean write the letter sorry...,@461407 @115858 Mine keeps doing that too! Its...,@591615 We can check it out. Meet us in DM wit...,,
3,1808936.0,@AppleSupport Hi. There is a speaker grille on...,NaN,@326564 Running into audio issues? Let's get t...,,
4,675393.0,Is there some kind of a bug causing random blu...,NaN,@218074 We'd like to help. DM us what iOS vers...,,
...,...,...,...,...,...,...
95,291441.0,@AppleSupport upgraded my iPhone to the latest...,NaN,@185391 We want to help you resolve this. Whic...,,
96,2549529.0,"@AppleSupport Hey, the display on my 2015 MacB...",NaN,@724386 We're here to help! Join us in DM with...,,
97,749784.0,@AppleSupport IPhone 7 Plus And iOS 11.0.3,@299222 Thanks for that info. Which device are...,@299222 Let's look into this further in DM.,,
98,2618338.0,@739950 @AppleSupport Same here!!! iPhone 7 Plus,@AppleSupport I have 11.1.2 and have that prob...,@739951 Let's look into this battery life issu...,,
99,937408.0,@342218 @351248 @115858 I would love to tell @...,I’m assuming someone has told @115858 that the...,@495453 We'd like to get your iPhone updated a...,,

In [7]:
# Test our candidate intent rules against the 100-example sample.
# This is exploratory only — these are NOT final labels.

def find_matching_intents(message):
    message = str(message).lower()

    matches = []

    for intent, keywords in intent_keywords.items():
        for keyword in keywords:
            if keyword.lower() in message:
                matches.append(intent)
                break

    return matches


inspection_sample["keyword_matches"] = (
    inspection_sample["customer_message"]
    .apply(find_matching_intents)
)

# Number of detected intents per example
inspection_sample["num_matches"] = (
    inspection_sample["keyword_matches"]
    .str.len()
)

print("Examples matching exactly one candidate intent:",
      (inspection_sample["num_matches"] == 1).sum())

print("Examples matching multiple candidate intents:",
      (inspection_sample["num_matches"] > 1).sum())

print("Examples matching no candidate intent:",
      (inspection_sample["num_matches"] == 0).sum())

print("\nExamples with multiple matches:")
display(
    inspection_sample[
        inspection_sample["num_matches"] > 1
    ][
        [
            "customer_message",
            "keyword_matches",
            "brand_response"
        ]
    ]
)

print("\nExamples with no matches:")
display(
    inspection_sample[
        inspection_sample["num_matches"] == 0
    ][
        [
            "customer_message",
            "brand_response"
        ]
    ]
)

Examples matching exactly one candidate intent: 43
Examples matching multiple candidate intents: 42
Examples matching no candidate intent: 15

Examples with multiple matches:

,customer_message,keyword_matches,brand_response
1,@AppleSupport my iPhone 7 screen is all white ...,"[apps_app_store, display_touchscreen]",@407226 Hi there! Let's try out these steps: h...
3,@AppleSupport Hi. There is a speaker grille on...,"[apps_app_store, audio]",@326564 Running into audio issues? Let's get t...
4,Is there some kind of a bug causing random blu...,"[apps_app_store, camera_photos]",@218074 We'd like to help. DM us what iOS vers...
6,@AppleSupport Several apps my phone already bl...,"[apps_app_store, display_touchscreen]",@761386 Please DM us so we can gather further ...
9,@AppleSupport @115858 left AirPod trouble -&gt...,"[wifi_connectivity, apps_app_store, airpods]",@424256 Which device do you use with your AirP...
15,#run actually a lot more. But #AppleWatch3 sto...,"[apps_app_store, apple_watch]",@391996 We'd be happy to help. Send us a DM wi...
16,@115858 why do I have to re-enter my wifi pass...,"[ios_updates, wifi_connectivity, apple_id_acco...",@424136 We're here to help. Which device are y...
18,"After that I updated my iphone, my battery is ...","[battery_charging, ios_updates, apps_app_store]",@285471 Let's take a look at your iPhone's bat...
19,"iPhone 6 randomly restarts, camera roll freque...","[ios_updates, apps_app_store, camera_photos, d...",@714360 That's definitely not the experience w...
20,Dear @AppleSupport @115858 I restored my iPhon...,"[wifi_connectivity, apps_app_store]",@287481 We're here to help! What steps exactly...
22,@115858 @AppleSupport I have updated my 6s to ...,"[battery_charging, ios_updates, apps_app_store]","@342069 Battery life is important, and we can ..."
29,In #iOS10 I can post to Twitter and Facebook w...,"[ios_updates, apps_app_store]",@662809 This feature is no longer available in...
30,@115858 fix this fucking battery life after th...,"[battery_charging, ios_updates]",@609489 We're happy to look into issues with y...
31,@AppleSupport iPhone 6s Plus &amp; I have the ...,"[ios_updates, apps_app_store]",@167181 Got it! Are you still seeing a message...
35,@AppleSupport I'm trying to setup a 5c to use ...,"[apple_id_account, apps_app_store]",@236694 Hello. Were you able to sign in to oth...
36,@AppleSupport Yesterday I was updating to IOS ...,"[ios_updates, apps_app_store]",@294777 Thanks for providing that information ...
37,This iOS 11 update is shit. Fix this @AppleSup...,"[ios_updates, apps_app_store]",@143081 We're happy to help you with this. Joi...
39,I really wish I hadn’t updated my phone to iOS...,"[ios_updates, apps_app_store]",@579378 Let's work together on these issues. J...
43,@AppleSupport The os doesn't run smooth it lag...,"[apps_app_store, display_touchscreen]",@470694 We'd like to look into this with you. ...
45,@AppleSupport so fed up with my iPhone 5se fre...,"[battery_charging, apps_app_store]",@691459 We're here for you! To better understa...
46,@AppleSupport IOS11.0.3 on my Iphone 7 32 GB i...,"[ios_updates, apps_app_store]",@555774 Let's check into this with you and see...
47,@AppleSupport Don’t work on the lock screen fo...,"[apps_app_store, display_touchscreen]",@321948 Please meet us in DM to continue explo...
50,"@AppleSupport I am running on iOS 11.1, crackl...","[ios_updates, apps_app_store, audio]",@124483 Thanks for that information. DM the co...
55,@AppleSupport i signout from appstore but my b...,"[battery_charging, ios_updates, apps_app_store]",@812399 We'd be happy to help. Do you normally...
56,Hate the battery drain on #iOS11 :/ even the p...,"[battery_charging, ios_updates, apps_app_store]",@195159 We know how important your battery lif...
62,@AppleSupport is de update 4.2 niet voor de Ap...,"[ios_updates, apps_app_store, apple_watch]",@124879 We offer support via Twitter in Englis...
64,My phone randomly decided to restore my Camera...,"[apps_app_store, camera_photos]",@549308 We'd like to look into this with you. ...
68,my purchased CD isn't in my music library anym...,"[apps_app_store, apple_music]",@637982 That is certainly not the experience t...
72,@AppleSupport all of a sudden I am getting ema...,"[ios_updates, apps_app_store]",@122014 We can understand not wanting the inco...
73,"Hey @AppleSupport, is there a way on IOS 11 to...","[ios_updates, apps_app_store, display_touchscr...","@195387 We've got your back. Check out ""About ..."
74,"@115858 , not that you care but iPhone X exper...","[wifi_connectivity, display_touchscreen]",@268725 We can assure you this is not expected...
75,"@AppleSupport Hello, how can I leave general f...","[apps_app_store, display_touchscreen]",@624339 We always welcome feedback from our cu...
77,@AppleSupport apps are not responding my remin...,"[ios_updates, apps_app_store]",@659614 We'd like to see how we can help. With...
80,@AppleSupport 2/2 song from itunes https://t.c...,"[apps_app_store, apple_music]",@204872 We are here for you. Let's take a look...
81,Ever since @AppleSupport did their update my p...,"[ios_updates, apps_app_store]","@706138 Hey, we want you to enjoy the new upda..."
85,@AppleSupport sfter updating ios 11 my phones ...,"[battery_charging, ios_updates, apps_app_store]",@349013 That is never what we want to hear. Le...
86,Ready to smash my #iPhone 7+ &amp; 6S+ to piec...,"[ios_updates, apps_app_store, camera_photos, d...",@359405 We'd like to work closely with you to ...
87,@AppleSupport spent $2000 on an iPhone X with ...,"[apps_app_store, display_touchscreen]",@662329 We’d like to look into this with you. ...
92,@AppleSupport Fix the damn #iOS update. 11.1 w...,"[battery_charging, ios_updates, apps_app_store]",@638730 That should not be happening. We'd be ...
95,@AppleSupport upgraded my iPhone to the latest...,"[ios_updates, apps_app_store]",@185391 We want to help you resolve this. Whic...
96,"@AppleSupport Hey, the display on my 2015 MacB...","[apps_app_store, display_touchscreen, mac_macos]",@724386 We're here to help! Join us in DM with...
97,@AppleSupport IPhone 7 Plus And iOS 11.0.3,"[ios_updates, apps_app_store]",@299222 Let's look into this further in DM.

Examples with no matches:

,customer_message,brand_response
0,@115858 what’s up with this nonstop “I” issue?...,@475474 Let's look into this together. Reach o...
2,@461407 @115858 I️ mean write the letter sorry...,@591615 We can check it out. Meet us in DM wit...
8,@115858 ya’ll need to get it together 🙄 I’m si...,@495875 Thanks for reaching out to us. We have...
11,My phone has been doing this for two months. C...,@567796 We'd be happy to look into this with y...
21,"@115858 fixes the issue with the I, now we hav...",@346535 An update has been released to assist ...
24,"After a year of use, my @115858 smarak keyboar...",@808828 We'd like to look into this. Send us a...
26,@115858 What’s going on guys? This bug thing i...,@618663 We'd like to ensure we're on the same ...
27,@115858 Unless you listen to an episode straig...,@410321 We're happy to assist. Which iOS versi...
32,@115858 ARE YOU GOING TO FIX THIS?!?!?!?! It's...,@321627 We'd love to work with you and get thi...
38,My phone officially only has a 30 minute lifes...,@481365 Let's look into that. Send us a DM and...
42,"@115858 yall getting too comfortable it seems,...",@710073 We want your iPhone to run without iss...
66,"@115858 needs to fix these stupid ass bugs, I’...",@628085 Here’s what you can do to work around ...
70,seriously @115858 wtf is up with the question ...,@621570 Here’s what you can do to work around ...
76,i️m so tired of seeing these boxes @115858 nee...,@596157 Thanks for reaching out. We have a wor...
89,My phone has died at 100% 5+ times and before ...,"@571339 Great battery life is important, and w..."

In [8]:
# Inspect 50 examples for manual taxonomy validation.

taxonomy_review = (
    df[
        [
            "customer_tweet_id",
            "customer_message",
            "previous_message",
            "brand_response"
        ]
    ]
    .sample(
        50,
        random_state=123
    )
    .reset_index(drop=True)
)

display(taxonomy_review)

,customer_tweet_id,customer_message,previous_message,brand_response
0,1294331.0,@AppleSupport I lock it and sometimes that doe...,@216977 Thanks. Which exact iOS version are y...,"@216977 After you make sure you have a backup,..."
1,2138914.0,@115858 why when I️ type in #IPHONEX does it t...,NaN,@629072 Here’s what you can do to work around ...
2,1766797.0,@AppleSupport why do I keep getting this messa...,NaN,"@531305 We want to help you. DM us, and we'll ..."
3,1879894.0,@AppleSupport compare the time stamps and the ...,NaN,@561080 We certainly want you to be able to en...
4,290528.0,@115858 @AppleSupport updated iPhone to new iO...,NaN,@185189 We'd like to take a look into this wit...
5,1143124.0,Alright @115858 the new update has really mess...,NaN,@389056 We are here for you. Let's take a look...
6,1752028.0,@AppleSupport My iphone6 has (compared to othe...,NaN,@527842 Let's work together to figure it out. ...
7,1386419.0,@AppleSupport running 11.0.3 and have very lou...,NaN,@442610 Let's check into this together. When d...
8,2305160.0,"@115858 yo fix this glitch, it makes me look l...",NaN,@668812 We'd like to help. Tell us more about ...
9,2983153.0,@115858 all of my messages just got deleted. v...,NaN,@822632 Let's look into this together. To star...
10,2131159.0,my phone just went from 40% to 38% like I swea...,NaN,@627220 We want you to be able to charge your ...
11,2068603.0,the new ios update has completely fucked my ph...,NaN,@611737 We want you to be happy with the new u...
12,2435290.0,@AppleSupport How i restore default setting,@698742 Help is here! If you lost the restrict...,@698742 We've got just what you need! We recom...
13,1787359.0,"@AppleSupport so no, no help with this one?",@AppleSupport why are suddenly apple music ver...,@536967 We'd be happy to look this Apple Music...
14,2525542.0,@AppleSupport Hello. I'm on iOS 11.1.1. This h...,"@324976 Let's help get this sorted. To begin, ...",@324976 Let's take a closer look together. Ple...
15,512329.0,@AppleSupport I cant find the MANAGE SUBSCRIPT...,@237821 We have a guide for managing subscript...,"@237821 We see what you mean. In this case, we..."
16,2628983.0,@115858 I am disappointed about Apple. your ne...,NaN,@742489 We'd be happy to look into this with y...
17,961707.0,@AppleSupport So after updating to 11.0.3 my b...,"Share stickers, emoji, and games more easily i...",@466295 Let's take a look in to this together ...
18,287459.0,"@AppleSupport Yes, the phone randomly turns of...","@184505 Hey, thanks for reaching out. Are you ...",@184505 We'd like to look into this further wi...
19,2371243.0,"@AppleSupport I’ve lost my iPhone, so no other...",@684213 Because you tested a few different de...,@684213 Is there another Wi-Fi network that yo...
20,1990474.0,@AppleSupport help me,what is technology pls help me https://t.co/dw...,@589072 We'd be happy to look into this with y...
21,1698426.0,@115858 my phone sucks fix it,NaN,@515127 We want your iPhone to work properly. ...
22,698840.0,Thank you @AppleSupport I am in PR with #FEMA ...,NaN,@125141 We'll be happy to assist. DM us and we...
23,1774055.0,@AppleSupport this is the millionth time Final...,NaN,@533167 We want to point you in the right dire...
24,2323177.0,@AppleSupport @115858 @115714 I also don't app...,@AppleSupport @115858 The better part is I've ...,@673124 Follow up with us in DM. Tell us more ...
25,1449353.0,Hey @AppleSupport have you ever seen this bug?...,NaN,@456322 We're here for you. Let's restart your...
26,879303.0,No es normal. El iOS 11 ha convertido la bater...,NaN,@328748 We offer support via Twitter in Englis...
27,2267246.0,Why won’t all of the music I import from a CD ...,NaN,@659888 Let's see what's going on. When syncin...
28,1712417.0,Yo @115858 when are you gonna fix this “I️” gl...,NaN,@518676 Let’s take a closer look at this. Meet...
29,548093.0,"@115858 @AppleSupport new macOS High Sierra, v...",NaN,@247531 We may be able to help. Try rebuilding...
30,1682548.0,@115858 IF YOU COULD FIX THIS BUG MAKING ALL M...,NaN,@511492 Here’s what you can do to work around ...
31,2017513.0,PSA do not update your phone. My phone keeps f...,NaN,@596649 We’re here to help. Which iPhone model...
32,565922.0,@AppleSupport PLEASE FIX THIS IMESSAGE CATASTR...,NaN,@252649 Can you tell us what you're experienci...
33,1360151.0,@AppleSupport Unfortunately not right now. But...,@437105 Let's work on this together! Do you ha...,@437105 Excellent! Definitely let us know if y...
34,1707725.0,@AppleSupport Yes,"@517506 Just to confirm, everything is now wor...",@517506 OK great! Let us know if any other iss...
35,1429804.0,@AppleSupport iPad mini 2 (iOS 11.0) unable to...,NaN,"@452066 Thanks for contacting us, we can help ..."
36,2269958.0,He ido a actualizar mi #Iphone7Plus y se me ha...,NaN,@660518 We offer support via Twitter in Englis...
37,554728.0,@AppleSupport So another update will be necess...,"@249476 If you're in the US, those features wi...",@249476 You will start seeing that feature rol...
38,2817766.0,"@AppleSupport \nSince iOS 11, speak selection ...",NaN,@785450 Hi there! We want to ensure your iBook...
39,2134176.0,Hey I️ @AppleSupport I️ can I️ we I️ fix I️ th...,NaN,@126685 Here’s what you can do to work around ...
40,1447322.0,@AppleSupport I️ can’t type I️.,NaN,@455849 Let us know what iOS you are running t...
41,2665296.0,can @115858 PLEASE get their shit together wit...,NaN,@750938 Here’s what you can do to work around ...
42,998357.0,@AppleSupport i can’t hear anything when i mak...,@356404 Let's work on this together. What spec...,@356404 Join us in DM and we'll explore ways t...
43,2307541.0,I still don't have it and I'm kinda upset? @11...,I'm guessing it's the kidneys because I am bei...,@669387 We're not quite sure what the issue is...
44,26672.0,@AppleSupport Oh and would you look at that......,@121838 Here’s what you can do to work around ...,@121838 Let's continue within DM here: https:/...
45,110910.0,"@AppleSupport Hey, thanks for the reply! 11.1.1",@140672 Hey there. We want you to be able to u...,@140672 OK. We recently released iOS 11.1.2. G...
46,409644.0,@AppleSupport Is there a website I can submit ...,@212685 Does restarting your device help any? ...,@212685 We'd like to help. Could you meet us i...
47,1558812.0,Okay the question mark still comes out lol wtf...,NaN,"@481746 Thanks for contacting us, we're here f..."
48,2313937.0,@AppleSupport None of my photos are on iCloud,@670990 We want to look into this with you. Ar...,@670990 Let's look into this issue a bit close...
49,2686078.0,WTF @AppleSupport https://t.co/ClODMpsKLq,NaN,@755368 Thanks for reaching out. We see your D...

In [9]:
intent_definitions = {
    "ios_update": "Problems or questions specifically about iOS updates, update failures, update-related bugs, or iOS version behavior.",

    "battery_charging": "Battery draining, battery health, charging, power consumption, or unexpected battery percentage changes.",

    "connectivity": "Wi-Fi, cellular/mobile data, Bluetooth, network, or connection problems.",

    "account_authentication": "Apple ID, login, password, authentication, account access, subscriptions/account management.",

    "icloud_backup": "iCloud storage, iCloud backup, missing/syncing iCloud data, or iCloud-related problems.",

    "apps_app_store": "Problems with apps, installing/updating apps, App Store, app crashes, or application behavior.",

    "audio": "Problems with speakers, microphone, calls audio, sound, headphones, AirPods, or other audio functionality.",

    "camera_photos": "Camera, taking photos/videos, photo library, photo syncing, or photo-related problems.",

    "display_input": "Screen/display, touchscreen, keyboard, typing, text input, or visual/input interaction problems.",

    "apple_services": "Problems with Apple services such as Apple Music or other Apple-provided services that do not fit another intent.",

    "device_hardware": "Physical/device-level problems that cannot be better classified into a more specific intent.",

    "other_unclear": "Too vague, insufficient context, unrelated, or impossible to confidently assign to another intent."
}

for intent, definition in intent_definitions.items():
    print(f"{intent}:")
    print(f"  {definition}\n")

ios_update:
  Problems or questions specifically about iOS updates, update failures, update-related bugs, or iOS version behavior.

battery_charging:
  Battery draining, battery health, charging, power consumption, or unexpected battery percentage changes.

connectivity:
  Wi-Fi, cellular/mobile data, Bluetooth, network, or connection problems.

account_authentication:
  Apple ID, login, password, authentication, account access, subscriptions/account management.

icloud_backup:
  iCloud storage, iCloud backup, missing/syncing iCloud data, or iCloud-related problems.

apps_app_store:
  Problems with apps, installing/updating apps, App Store, app crashes, or application behavior.

audio:
  Problems with speakers, microphone, calls audio, sound, headphones, AirPods, or other audio functionality.

camera_photos:
  Camera, taking photos/videos, photo library, photo syncing, or photo-related problems.

display_input:
  Screen/display, touchscreen, keyboard, typing, text input, or visual/input interaction problems.

apple_services:
  Problems with Apple services such as Apple Music or other Apple-provided services that do not fit another intent.

device_hardware:
  Physical/device-level problems that cannot be better classified into a more specific intent.

other_unclear:
  Too vague, insufficient context, unrelated, or impossible to confidently assign to another intent.

In [10]:
import pandas as pd

clean_apple = pd.read_csv(
    "../data/processed/apple_support_clean.csv"
)

print("Shape:", clean_apple.shape)
display(clean_apple.head())

Shape: (106523, 6)

,customer_tweet_id,customer_message,previous_message,has_context,parent_author,brand_response
0,698.0,@AppleSupport https://t.co/NV0yucs0lB,@AppleSupport why are my I️’s changing not sho...,True,115854,@115854 We're here for you. Which version of t...
1,697.0,@AppleSupport The newest update. I️ made sure ...,@115854 We're here for you. Which version of t...,True,AppleSupport,@115854 Lets take a closer look into this issu...
2,702.0,@AppleSupport Tried resetting my settings .. r...,@115855 Any steps tried since it started last ...,True,AppleSupport,@115855 Let's go to DM for the next steps. DM ...
3,704.0,@AppleSupport This is what it looks like https...,@115855 That's great it has iOS 11.1 as we can...,True,AppleSupport,@115855 Any steps tried since it started last ...
4,707.0,@AppleSupport I️ have an iPhone 7 Plus and yes...,@115855 We'd like to look into this with you. ...,True,AppleSupport,@115855 That's great it has iOS 11.1 as we can...

In [11]:
review_sample = (
    clean_apple[
        [
            "customer_tweet_id",
            "customer_message",
            "previous_message",
            "brand_response"
        ]
    ]
    .sample(
        100,
        random_state=456
    )
    .reset_index(drop=True)
)

display(review_sample)

,customer_tweet_id,customer_message,previous_message,brand_response
0,963246.0,@AppleSupport iPhone 7 having crazy battery pr...,NaN,@348589 Let's look into that. Send us a DM and...
1,2686810.0,@AppleSupport please can you advise on the qui...,NaN,@567932 We're happy to do everything we can to...
2,2202096.0,@AppleSupport Still waiting-What is going on w...,NaN,@643962 We’re here to help. Let’s team up in D...
3,852993.0,"Dear @AppleSupport, please note that it has no...",NaN,@322629 We'll be glad to look into this. Pleas...
4,2346056.0,@AppleSupport can you guys fix the problem whe...,NaN,@467249 That’s not good to hear about your con...
...,...,...,...,...
95,1813546.0,"@AppleSupport IOS 11 ruins battery life 🙄,ple...",NaN,@544820 If you're having trouble with your bat...
96,1376460.0,@115858 also has done THIS to my camera. and w...,@115858 #ios11 stopped my phone making/receivi...,@440427 Let's meet up in DM to explore support...
97,1118226.0,@AppleSupport I am on a Samsung galaxy 8,@383854 We'd like to look into this. What devi...,@383854 Got it. Let's start by following the s...
98,568429.0,@AppleSupport This is extremely frustrating,@AppleSupport That was 5 min ago,@252896 We may be having an issue where we're ...
99,2801467.0,@AppleSupport I am able to sign in to a non ad...,@781516 We understand you need to get logged i...,@781516 Can you send us a screenshot of the me...

In [12]:
manual_review = review_sample.copy()

manual_review["intent"] = ""
manual_review["notes"] = ""

display(manual_review)

,customer_tweet_id,customer_message,previous_message,brand_response,intent,notes
0,963246.0,@AppleSupport iPhone 7 having crazy battery pr...,NaN,@348589 Let's look into that. Send us a DM and...,,
1,2686810.0,@AppleSupport please can you advise on the qui...,NaN,@567932 We're happy to do everything we can to...,,
2,2202096.0,@AppleSupport Still waiting-What is going on w...,NaN,@643962 We’re here to help. Let’s team up in D...,,
3,852993.0,"Dear @AppleSupport, please note that it has no...",NaN,@322629 We'll be glad to look into this. Pleas...,,
4,2346056.0,@AppleSupport can you guys fix the problem whe...,NaN,@467249 That’s not good to hear about your con...,,
...,...,...,...,...,...,...
95,1813546.0,"@AppleSupport IOS 11 ruins battery life 🙄,ple...",NaN,@544820 If you're having trouble with your bat...,,
96,1376460.0,@115858 also has done THIS to my camera. and w...,@115858 #ios11 stopped my phone making/receivi...,@440427 Let's meet up in DM to explore support...,,
97,1118226.0,@AppleSupport I am on a Samsung galaxy 8,@383854 We'd like to look into this. What devi...,@383854 Got it. Let's start by following the s...,,
98,568429.0,@AppleSupport This is extremely frustrating,@AppleSupport That was 5 min ago,@252896 We may be having an issue where we're ...,,
99,2801467.0,@AppleSupport I am able to sign in to a non ad...,@781516 We understand you need to get logged i...,@781516 Can you send us a screenshot of the me...,,

In [13]:
for i, row in manual_review.iterrows():
    print(f"\n{'=' * 80}")
    print(f"INDEX: {i}")
    print(f"CUSTOMER: {row['customer_message']}")
    
    if pd.notna(row["previous_message"]) and str(row["previous_message"]).strip():
        print(f"PREVIOUS: {row['previous_message']}")
    
    print(f"BRAND RESPONSE: {row['brand_response']}")

================================================================================
INDEX: 0
CUSTOMER: @AppleSupport iPhone 7 having crazy battery problems as well as connectivity issues since iOS update. What do I do?
BRAND RESPONSE: @348589 Let's look into that. Send us a DM and we'll go from there. https://t.co/GDrqU22YpT

================================================================================
INDEX: 1
CUSTOMER: @AppleSupport please can you advise on the quickest way to make a complaint against apple?
BRAND RESPONSE: @567932 We're happy to do everything we can to help. To start, DM us with the country where you're located. https://t.co/GDrqU22YpT

================================================================================
INDEX: 2
CUSTOMER: @AppleSupport Still waiting-What is going on with the new iOS? My wife cannot send video to my Samsung since updating to the latest software
BRAND RESPONSE: @643962 We’re here to help. Let’s team up in DM and we’ll do our best to assist you. https://t.co/GDrqU22YpT

================================================================================
INDEX: 3
CUSTOMER: Dear @AppleSupport, please note that it has now been a week since searching on Maps on iOS 11 has worked on the  @37275 mobile net
BRAND RESPONSE: @322629 We'll be glad to look into this. Please send us a DM. https://t.co/GDrqU22YpT

================================================================================
INDEX: 4
CUSTOMER: @AppleSupport can you guys fix the problem where iPhones randomly forget your contacts?? I’m tired of resetting my phone to fix it.
BRAND RESPONSE: @467249 That’s not good to hear about your contacts disappearing. Let’s see what we can find out! DM us your current iOS version. We’ll continue working with you there. https://t.co/GDrqU22YpT

================================================================================
INDEX: 5
CUSTOMER: @AppleSupport Awesome!  I just wanted to be sure it wouldn’t reduce the battery life on the actual iPhone battery if I chose to use it. Thank you!
PREVIOUS: @272728 The Apple Smart Battery Case is certified for use with the iPhone. It won't create any negative effects on the battery.
BRAND RESPONSE: @272728 You're most welcome! Enjoy the rest of your day.

================================================================================
INDEX: 6
CUSTOMER: @AppleSupport I have had so many issues with my IPhone 6s Plus since I updated my phone to iOS 11.0.3. I need assistance.
BRAND RESPONSE: @365472 We'd be happy to assist with issues with iOS 11. Can you please message us in DM? https://t.co/GDrqU22YpT

================================================================================
INDEX: 7
CUSTOMER: @AppleSupport @115858 Bluetooth in  Range Rover Evoque has constant interference since IOS 11.0.03 on iPhone 6. Please help. Phone also lags
BRAND RESPONSE: @698388 We want to help. Would you tell us more about the situation you're experiencing via DM? https://t.co/GDrqU22YpT

================================================================================
INDEX: 8
CUSTOMER: ![?] &lt;&lt;&lt; y’all doing too much @115858
BRAND RESPONSE: @500706 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9

================================================================================
INDEX: 9
CUSTOMER: I’ve tried this text replacement thing and I’m still seeing the ? @AppleSupport FIX THIS.
BRAND RESPONSE: @556217 We'd love to look into this with you. Click here to join us in DM and provide us with the software version you're using. https://t.co/GDrqU22YpT

================================================================================
INDEX: 10
CUSTOMER: I’ve had this iPhone charger for a week and it’s already messing up. @115858 what’s up with that?
BRAND RESPONSE: @800900 Let's jump on this together. What exactly is going on with your charger?

================================================================================
INDEX: 11
CUSTOMER: @115858 how come your updates always make my phone worse off?
BRAND RESPONSE: @330438 Hi. We'd like to help with the issue you're having. DM us and tell us more about what's happening. https://t.co/GDrqU22YpT

================================================================================
INDEX: 12
CUSTOMER: @AppleSupport your latest iOS upgrade has ruined the performance of my iPhone 6 - what are you going to do?I need my phone
BRAND RESPONSE: @418925 We'd like to help. Send us a DM including the issue you're experiencing. We'll continue there. https://t.co/GDrqU22YpT

================================================================================
INDEX: 13
CUSTOMER: hey @115858 @AppleSupport since when is my charger supposed to catch on fire and melt???? https://t.co/BgBAm3MPm0
BRAND RESPONSE: @284365 Thank you for reaching out. Let us know your country location in a DM, we'd like some details to assist. https://t.co/GDrqU22YpT

================================================================================
INDEX: 14
CUSTOMER: just got this phone two months ago and first the lock button stopped working, and now the home button!! Wtf never even dropped it @115858
BRAND RESPONSE: @781291 That’s never what we want to hear. Let’s work together to get this fixed. To start, can you tell us which iPhone you have?

================================================================================
INDEX: 15
CUSTOMER: @115858 Non ricordo la password ID Apple.Ho chiesto ripristino giovedì. mi dite che risponderete il 27/10.Cosa posso fare x averla subito?Grz
BRAND RESPONSE: @385831 We offer support via Twitter in English. Contact us for help in your preferred language here: https://t.co/IBIY3vMgPj

================================================================================
INDEX: 16
CUSTOMER: @115858 My phone is vibrating randomly. Fix this update! 🙄
BRAND RESPONSE: @711179 That’s unexpected! We’d like to take a closer look at this issue with you. Let us know which version of iOS you’re currently running on the iPhone in DM to proceed. https://t.co/GDrqU22YpT

================================================================================
INDEX: 17
CUSTOMER: @115858 @AppleSupport #glitch #ios11 @116333 https://t.co/fgGcnYXnqU
BRAND RESPONSE: @538561 We're glad to help. Does the same behavior happen after a restart? Let us know in DM, and we'll continue there. https://t.co/GDrqU22YpT

================================================================================
INDEX: 18
CUSTOMER: Hi @AppleSupport , how do I get support re bluetooth glitches that are occurring post iOS11 update?
BRAND RESPONSE: @290730 We're happy to help however we can! What Bluetooth trouble are you seeing? You can chat here or in Direct Message. https://t.co/GDrqU22YpT

================================================================================
INDEX: 19
CUSTOMER: @AppleSupport Thank you, I did read this article, the issue is that I want to turn on Ask to Buy for a family member over 18, eg, an adult? Is that possible?
PREVIOUS: @461121 Thanks for reaching out! Ask to Buy is on for any family member who isn't an adult. More info about this is here: https://t.co/JANN0uzI2v
BRAND RESPONSE: @461121 There isn't a way to turn on Ask to Buy for adults. Please leave feedback about this here: https://t.co/eTPVYVFyd8 We may not reach out to you in reference to your feedback, but we do read the messages we receive.

================================================================================
INDEX: 20
CUSTOMER: @AppleSupport Please help.This issue has been going on for months. The notorious "storage device full". It doesn't add up Case: 100318159703 https://t.co/zPLKu0AsKB
BRAND RESPONSE: @210990 Let's take a look at this together. Send us a DM, and we'll continue there. https://t.co/GDrqU22YpT

================================================================================
INDEX: 21
CUSTOMER: @AppleSupport I would like to take my photos off my mac and iphone and onto an external hard-drive as they are both slow.  Can an apple store do this for me?
BRAND RESPONSE: @169785 Hi there! Our Photos experts would likely be best to help you out with doing that. You can reach out to them here, if you'd like:  https://t.co/IBIY3vMgPj

================================================================================
INDEX: 22
CUSTOMER: @115858 wants to charge over $1,000 for a phone but still can’t make durable chargers 🤦‍♂️ https://t.co/b7LegeYeP1
BRAND RESPONSE: @564331 Let us know via DM which country you are in, then we can take a look at options for this with you from there. https://t.co/GDrqU22YpT

================================================================================
INDEX: 23
CUSTOMER: @AppleSupport I cannot get my auto correct on the native iOS keyboard to stop doing this. Wiped my keyboard history and restarted. Help! https://t.co/qe6AGRfKS0
BRAND RESPONSE: @435861 We'd love to help sort this out. Please DM us and let us know which iOS devices you've got that are experiencing this. https://t.co/GDrqU22YpT

================================================================================
INDEX: 24
CUSTOMER: @115858 Thanks Apple. My phone battery totally sucks now. I can’t get through a single day without charging.
BRAND RESPONSE: @554107 We’d love to help with your battery. To start, send us a DM letting us know which iPhone and exact iOS version you are using. https://t.co/GDrqU22YpT

================================================================================
INDEX: 25
CUSTOMER: @116333 erroneous/false information provided to me by Apple Support which has resulted in me not having access to my phone for going on 36 days!!  Terrible, terrible system for phones in lock mode.  Where is Apples Customers Service to fix issue.
BRAND RESPONSE: @664590 We'd like to look into this and help you out. Please DM us a few more details about what's going on and we'll discuss it there. Thank you. https://t.co/GDrqU22YpT

================================================================================
INDEX: 26
CUSTOMER: Some of the smallest things in life infuriate me the most. The A and the boxed ? is one of those little things... @115858 #FirstWorldProblems
BRAND RESPONSE: @652407 An update has been released to assist with this issue. If you haven’t yet, please back up your device and update it to iOS 11.1.1. For more info, check out: https://t.co/4f8hwT5to6

================================================================================
INDEX: 27
CUSTOMER: So @115858 my phone can die at 30% but when I charge it, it bounces up to 53?
BRAND RESPONSE: @794347 We want to look into that with you. Does your iPhone immediately power on when you connect it to a power source, and does it immediately display 53%? How long has this been happening?

================================================================================
INDEX: 28
CUSTOMER: @AppleSupport Do I need a genius reservation to purchase?
BRAND RESPONSE: @458606 Great question! No appointment is needed, but you can purchase online and set up a store pickup too. https://t.co/gfqfEXBqge

================================================================================
INDEX: 29
CUSTOMER: @AppleSupport 11.0.1
PREVIOUS: @180277 We'd love to help. In Settings &gt; General &gt; About what iOS 11 version are you on?
BRAND RESPONSE: @180277 Thanks. Let's update your device to iOS 11.0.2. If the battery shows no sign of improvement, DM us to continue. https://t.co/GDrqU2kzhr

================================================================================
INDEX: 30
CUSTOMER: @AppleSupport @115858 @116333  iOS11 is so buggy my iPhone Crashes &amp; loses battery like hell😡either fix 11 or sign 10.3 again
BRAND RESPONSE: @456247 Let's work together to get this resolved. Which iPhone &amp; iOS version do you have currently?

================================================================================
INDEX: 31
CUSTOMER: @AppleSupport this podcast app is the worst. I delete episodes, I even unsubscribe and they appear in my feed again &amp; again. How? Why? Stop?
BRAND RESPONSE: @515528 We'd like to help. Try these steps and let us know if the issue continues: https://t.co/78Y0jSomPt

================================================================================
INDEX: 32
CUSTOMER: @AppleSupport unable to make calls on ios 11.1.x on my 5s.. any solution. Ios 11.0.3 works fine on iphone 5s.
BRAND RESPONSE: @739013 That is never what we want to hear. Let’s work together to find out what’s happening. To start, can you tell us what happens when you try to make a phone call? Also, are you able to send regular SMS text messages like normal?

================================================================================
INDEX: 33
CUSTOMER: @AppleSupport Help!! I need to update the payment method for my iPhone X pre-order. It won’t let me do it online
BRAND RESPONSE: @122945 We're happy to help you with that. DM us the country you are located in so we can better assist you:

================================================================================
INDEX: 34
CUSTOMER: @AppleSupport Well what about the phone constantly freezing turning it self off while still staying it has power since update ? Or doesn’t that matter ?
PREVIOUS: @405711 Since only about an hour less, try some of these battery saving tips: https://t.co/bivpdfBNJ6 If you still have issues, DM us. https://t.co/GDrqU22YpT
BRAND RESPONSE: @405711 Thanks for reminding us about that. Let's continue with that issue in DM so we can better assist you on it. https://t.co/GDrqU22YpT

================================================================================
INDEX: 35
CUSTOMER: @AppleSupport I thank you for that! 🙌🏼
PREVIOUS: @518081 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9
BRAND RESPONSE: @518081 It's our pleasure. Feel free to reach out if any questions come up.

================================================================================
INDEX: 36
CUSTOMER: @AppleSupport Yes I am. I updated a couple days ago and it’s happened twice.
PREVIOUS: @195820 Thanks for verifying that for us. Are you experiencing this on iOS version 11.0.2?
BRAND RESPONSE: @195820 We'd like to further review this for you. Please DM us and we'll get started. https://t.co/GDrqU22YpT

================================================================================
INDEX: 37
CUSTOMER: @AppleSupport I wanted to touch base on what has been done to address the concern raise under case number 100196582757 submitted in Aug 2017
BRAND RESPONSE: @380015 In order to discuss a specific case, we would need to move this to DM. https://t.co/GDrqU22YpT

================================================================================
INDEX: 38
CUSTOMER: I don't want 70 new emoji @115858 @318 Why don't you give me a user-friendly Podcasts app back? Instead of the buggy nonsense now?
BRAND RESPONSE: @512734 Let's see what's going on with your Podcast app. DM us and let us know the exact iOS version you're running. https://t.co/GDrqU22YpT

================================================================================
INDEX: 39
CUSTOMER: Since i updated my iPhone 5s to iOS 11 it started causing many problems,
1) Frequent shutdowns
2) Battery issues @AppleSupport @115858 @115858
BRAND RESPONSE: @555717 Send us a DM. Let us know when you updated to 11.0.3: https://t.co/80YRnjDFDk Include the country you're in. https://t.co/GDrqU22YpT

================================================================================
INDEX: 40
CUSTOMER: My phone freezes up on the regular thanks to the iOS11 update. Thanks a lot @AppleSupport. Your product is trash
BRAND RESPONSE: @339981 Let's get this figured out. Are you experiencing this when using specific apps? Please send us a DM. https://t.co/GDrqU22YpT

================================================================================
INDEX: 41
CUSTOMER: @115858 fix this first person I️ problem
BRAND RESPONSE: @624590 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9

================================================================================
INDEX: 42
CUSTOMER: @115858 please fix this I️ can’t handle it.
BRAND RESPONSE: @645426 We recently released an iOS update, 11.1.1, that contains a fix for autocorrect issues. Let’s be sure to back up your device prior to updating. How to back up: https://t.co/4f8hwT5to6

================================================================================
INDEX: 43
CUSTOMER: @AppleSupport I restarted my iPad and it seems that the dock no longer automatically hides. From what i can tell manually restarting worked!
PREVIOUS: @453536 Does restarting the device resolve the issue?
BRAND RESPONSE: @453536 Glad to hear! Feel free to reach out to us here if you have questions in the future.

================================================================================
INDEX: 44
CUSTOMER: @AppleSupport please fix this. https://t.co/6HJqpgmQl0
BRAND RESPONSE: @237890 We'd love to help! What's going on with Siri? You can also DM us if you'd like: https://t.co/GDrqU22YpT

================================================================================
INDEX: 45
CUSTOMER: I guess it’s time to upgrade @AppleSupport my 6s Touch ID isn’t working..
BRAND RESPONSE: @124671 We'd love to help with your Touch ID. Check out: https://t.co/OOLuysF60o Let us know if this helps or not.

================================================================================
INDEX: 46
CUSTOMER: hey @AppleSupport me ajuda poxa! Dois dias ja com aparelho bloqueado! redefino senha e dá erro! Minha vida ta naquele aparelho :(
BRAND RESPONSE: @628663 Since our Twitter support is available in English, get help at https://t.co/IBIY3vMgPj or join https://t.co/pvaOFfPbjt

================================================================================
INDEX: 47
CUSTOMER: @AppleSupport  I've got an iPad that says it's charging but seems to be losing battery when it's plugged in. Any ideas?
BRAND RESPONSE: @193544 We'd like to help. Let's take this to DM and we'll explore ways to provide you assistance. https://t.co/GDrqU22YpT

================================================================================
INDEX: 48
CUSTOMER: @115858 you really gotta fix your stuff this question mark thing mad annoying
BRAND RESPONSE: @630519 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9

================================================================================
INDEX: 49
CUSTOMER: @AppleSupport it happens on the center control and on the dock, no particularity with any app, happens with native and downloaded apps :(
BRAND RESPONSE: @127945 Thanks for reaching out. We're here to help. DM us so we can look into this further with you. https://t.co/GDrqU22YpT

================================================================================
INDEX: 50
CUSTOMER: @AppleSupport Thanks, both
PREVIOUS: @173758 Let's get to the bottom of this with you. Is this happening both on cellular and wireless?
BRAND RESPONSE: @173758 Understood. Have you tried any steps so far, such as restarting? This way, we won't have you repeating anything.

================================================================================
INDEX: 51
CUSTOMER: @AppleSupport, iPad mail problems since upgrading. When I use the return key,text I have entered gets deleted. How do I fix, help please?
PREVIOUS: iPad mail problems since upgrading. When I use the return key the text I have entered gets deleted. How do I fix, help please?
BRAND RESPONSE: @572349 We know how much we rely on the Mail app to keep in touch with friends via email. DM us the exact version of iOS running: https://t.co/GDrqU22YpT


In [14]:
primary_intent_rules = {
    "ios_update": "Use when the main problem is the iOS update itself, update failure, or a problem explicitly caused by updating.",

    "battery_charging": "Use when the main problem is battery drain, battery health, charging, or power consumption.",

    "connectivity": "Use when the main problem is Wi-Fi, cellular/mobile data, Bluetooth, or network connectivity.",

    "account_authentication": "Use when the main problem is Apple ID, login, password, authentication, or account access.",

    "icloud_backup": "Use when the main problem is iCloud, iCloud backup, iCloud storage, or missing/syncing iCloud data.",

    "apps_app_store": "Use when the main problem is an application or the App Store.",

    "audio": "Use when the main problem is sound, speaker, microphone, call audio, headphones, or AirPods.",

    "camera_photos": "Use when the main problem is the camera, photos, videos, or photo library.",

    "display_input": "Use when the main problem is the screen, touchscreen, keyboard, typing, or other input/display behavior.",

    "apple_services": "Use when the main problem is an Apple service such as Apple Music and does not fit a more specific category.",

    "device_hardware": "Use for physical/device-level problems that do not fit another specific intent.",

    "other_unclear": "Use when the message is too vague, lacks enough information, is mainly a complaint with no identifiable issue, or does not fit another intent."
}

for i, (intent, rule) in enumerate(primary_intent_rules.items(), start=1):
    print(f"{i}. {intent}")
    print(f"   {rule}\n")

1. ios_update
   Use when the main problem is the iOS update itself, update failure, or a problem explicitly caused by updating.

2. battery_charging
   Use when the main problem is battery drain, battery health, charging, or power consumption.

3. connectivity
   Use when the main problem is Wi-Fi, cellular/mobile data, Bluetooth, or network connectivity.

4. account_authentication
   Use when the main problem is Apple ID, login, password, authentication, or account access.

5. icloud_backup
   Use when the main problem is iCloud, iCloud backup, iCloud storage, or missing/syncing iCloud data.

6. apps_app_store
   Use when the main problem is an application or the App Store.

7. audio
   Use when the main problem is sound, speaker, microphone, call audio, headphones, or AirPods.

8. camera_photos
   Use when the main problem is the camera, photos, videos, or photo library.

9. display_input
   Use when the main problem is the screen, touchscreen, keyboard, typing, or other input/display behavior.

10. apple_services
   Use when the main problem is an Apple service such as Apple Music and does not fit a more specific category.

11. device_hardware
   Use for physical/device-level problems that do not fit another specific intent.

12. other_unclear
   Use when the message is too vague, lacks enough information, is mainly a complaint with no identifiable issue, or does not fit another intent.

In [15]:
# Create a 200-example sample for manual intent labeling and save it for later use.

labeling_sample = (
    clean_apple[
        [
            "customer_tweet_id",
            "customer_message",
            "previous_message",
            "brand_response"
        ]
    ]
    .sample(
        200,
        random_state=789
    )
    .reset_index(drop=True)
)

labeling_sample["intent"] = ""
labeling_sample["notes"] = ""

labeling_path = "../data/processed/apple_intent_labeling_200.csv"

labeling_sample.to_csv(
    labeling_path,
    index=False
)

print(f"Created: {labeling_path}")
print(f"Rows: {len(labeling_sample)}")

display(labeling_sample.head(10))

Created: ../data/processed/apple_intent_labeling_200.csv
Rows: 200

,customer_tweet_id,customer_message,previous_message,brand_response,intent,notes
0,909813.0,"Seriously @115858, my iPhone’s heating up agai...",NaN,@336101 Send us a DM so we can help with your ...,,
1,1864674.0,@115858 needs to setup a subscription plan bec...,NaN,@525234 We'd like to help with your headphones...,,
2,2070017.0,"@612173 @AppleSupport Two month old phone, the...",@AppleSupport #apple #iphone #ois11 never had ...,@612172 We're here to help. DM us which model ...,,
3,554724.0,@AppleSupport i have an issue with my phone wh...,NaN,@249474 We know that the performance of your d...,,
4,1684485.0,Why does my phone not know the letter I️ anymo...,NaN,@511907 Here’s what you can do to work around ...,,
5,2151155.0,"WHEN ARE YALL GONNA FIX THE I️-glitch, like th...",NaN,@311677 Here’s what you can do to work around ...,,
6,2047763.0,@AppleSupport Crackle gone - replaced by compl...,@AppleSupport every update makes my phone wors...,@574265 We'd be happy to look into this with y...,,
7,1809282.0,@AppleSupport @ATT Oh AND deletes all my texts...,I love having to pay $150 to pay off a phone t...,@339428 This isn't expected behavior for your ...,,
8,2385140.0,Dear @115858 @AppleSupport Why has iOS11 turne...,NaN,@579638 This is certainly not the experience w...,,
9,1971418.0,@AppleSupport I*,Yo @AppleSupport the letter “I️” is broken htt...,@583952 Let's check this out together. Follow ...,,

In [16]:
# Display the 200 labeling examples in batches of 20 for manual taxonomy review.

batch_size = 20

for start in range(0, len(labeling_sample), batch_size):
    end = min(start + batch_size, len(labeling_sample))

    print(f"\n{'=' * 100}")
    print(f"Examples {start}–{end - 1}")
    print(f"{'=' * 100}")

    display(
        labeling_sample.loc[
            start:end - 1,
            [
                "customer_tweet_id",
                "customer_message",
                "previous_message"
            ]
        ]
    )

====================================================================================================
Examples 0–19
====================================================================================================

,customer_tweet_id,customer_message,previous_message
0,909813.0,"Seriously @115858, my iPhone’s heating up agai...",NaN
1,1864674.0,@115858 needs to setup a subscription plan bec...,NaN
2,2070017.0,"@612173 @AppleSupport Two month old phone, the...",@AppleSupport #apple #iphone #ois11 never had ...
3,554724.0,@AppleSupport i have an issue with my phone wh...,NaN
4,1684485.0,Why does my phone not know the letter I️ anymo...,NaN
5,2151155.0,"WHEN ARE YALL GONNA FIX THE I️-glitch, like th...",NaN
6,2047763.0,@AppleSupport Crackle gone - replaced by compl...,@AppleSupport every update makes my phone wors...
7,1809282.0,@AppleSupport @ATT Oh AND deletes all my texts...,I love having to pay $150 to pay off a phone t...
8,2385140.0,Dear @115858 @AppleSupport Why has iOS11 turne...,NaN
9,1971418.0,@AppleSupport I*,Yo @AppleSupport the letter “I️” is broken htt...
10,2683659.0,@AppleSupport Will do! And thanks for the reply!,@240308 While we can't speculate on future cha...
11,1762849.0,"Brooooo, iSeriously hate that @115858 still h...",NaN
12,1988408.0,FIX THE DAMN LETTER I️ &amp; GIVE ME A GARIFUN...,NaN
13,2492419.0,@AppleSupport reply to my dms pleasee,NaN
14,1772153.0,@AppleSupport @512040 Having the same issue. 2...,@512040 Here’s what you can do to work around ...
15,2050989.0,@115858 your IOS 11 update is trash and everyt...,NaN
16,1379597.0,@AppleSupport Was updated to latest iOS been a...,@415605 We're happy to help. Can you tell us w...
17,2321883.0,@AppleSupport are you guys ever going to fix t...,NaN
18,2255268.0,"Seriously, @115858 ? Not only is iOS 11 and al...",NaN
19,1761246.0,@115858 @AppleSupport ^^^^,@115858 your new update is a piece of shit and...

====================================================================================================
Examples 20–39
====================================================================================================

,customer_tweet_id,customer_message,previous_message
20,1773429.0,I️ fucking can’t with this “I️” shit. @115858 ...,NaN
21,9840.0,@AppleSupport mi iPhone no se puede conectar a...,NaN
22,2493938.0,Idk what the hell going on with my phone but y...,NaN
23,1509979.0,@AppleSupport Yup every app has been updated a...,@470477 Were you able to check for updates in ...
24,1058940.0,@115858 where the fuck did my 4000 photos go h...,NaN
25,2019482.0,@AppleSupport ios11 sucks. My iphone SE is a e...,NaN
26,208620.0,Half of my contact list is gone after the upgr...,NaN
27,487849.0,No entiendo por qué tengo que actualizar mi te...,NaN
28,1577350.0,"Uh, I was never the best mathmatist but isn't ...",NaN
29,1676324.0,@115858 y’all got me fucked up for making this...,NaN
30,788426.0,Ever since I downloaded #iOS11 my battery on m...,NaN
31,325899.0,@AppleSupport Already update but it doesn’t work.,@179912 Let's create a backup of your data and...
32,2014914.0,@AppleSupport why can’t I just type the letter...,NaN
33,1332735.0,@AppleSupport iOS 11 keeps freezing my phone a...,NaN
34,25318.0,"@AppleSupport , I just wanted to let you know ...",NaN
35,1542735.0,Problem upgrading the Desktop @115858 Computer...,NaN
36,583614.0,This high sierra update has ruined my Mac. Fix...,NaN
37,2152144.0,@115858 @AppleSupport Auto correct just makes ...,NaN
38,2300378.0,@AppleSupport I'm using 11.1.1 calculator iss...,@667662 Please let us know what iOS you are ru...
39,1748734.0,"Ever since i updated my phone, my music random...",NaN

====================================================================================================
Examples 40–59
====================================================================================================

,customer_tweet_id,customer_message,previous_message
40,396073.0,@AppleSupport pls help my alarms won't go off ...,NaN
41,644931.0,@AppleSupport It’s not just with maps it’s wit...,"@273067 For help with Maps, and how to report ..."
42,1272421.0,@116333 Nearly burnt the house down. Official ...,NaN
43,61326.0,@AppleSupport No there's not. I'm just saying....,@130039 Have you checked for any debris in you...
44,51678.0,@115858 Yo wassup with this I️ shit? What’s good,NaN
45,2520757.0,@AppleSupport 11.1.1 -all my Apple Music ...,@636479 Thanks for reaching out to us for supp...
46,57514.0,@AppleSupport 11.1,@129051 Let's help to get this resolved! Which...
47,988384.0,"@AppleSupport And no it's not in preferences, ...",Hey @AppleSupport how do I get books on my iTu...
48,1536257.0,@476342 @AppleSupport what’s goin on,@476341 mines doing the same thing
49,1886567.0,@115858 thanks for the update — YOU BROKE MY P...,NaN
50,2849163.0,@115858 @AppleSupport Very disappointing Geniu...,NaN
51,2833032.0,@115858 is your uk website down? Iphone upgrad...,NaN
52,2519350.0,Bro my iPhone is constantly glitching cause of...,NaN
53,654369.0,I am getting so sick of mac updates uninstalli...,NaN
54,2864855.0,@AppleSupport I did a hard reset and it works ...,@178644 Got it. Let’s disconnect the headphone...
55,2003387.0,"excuse me, i want to buy an apple watch, but i...",NaN
56,1674190.0,@AppleSupport with 11.1 ios update I am freque...,NaN
57,2093850.0,@115858 @AppleSupport That little question mar...,"@115858 @AppleSupport Please, please, please, ..."
58,816181.0,@AppleSupport Yep. Had that set for months now...,@201391 You can adjust this Camera setting fro...
59,92764.0,@AppleSupport No app updates. And I will test ...,@131555 We'd be happy to look into this with y...

====================================================================================================
Examples 60–79
====================================================================================================

,customer_tweet_id,customer_message,previous_message
60,981222.0,@115858 iOS 11.0.3 is the worst! Whole system ...,NaN
61,2020842.0,@AppleSupport fix the god damn “I️”...it’s 201...,NaN
62,1595974.0,@AppleSupport I get the message attached.\nWhe...,@490330 We know how important your security an...
63,810342.0,@AppleSupport Can iOS 11 search for what I hav...,"In iOS 11 on #iPad, all of your files are now ..."
64,1735084.0,yo @AppleSupport why’s my phone glitching &amp...,NaN
65,58172.0,@AppleSupport App store now appears to be working,@129208 Help is here. We're not reporting any ...
66,1194037.0,@AppleSupport 11.0.2,@400565 We can help! Which iOS version is your...
67,889052.0,@AppleSupport .@AppleSupport Good questions!👍M...,@151381 Thank you. Have you restarted your iPa...
68,2352146.0,"@AppleSupport Hello, I recently upgraded the I...",NaN
69,2448415.0,"@AppleSupport hi i have iphone 7, should i clo...",NaN
70,1648476.0,"Dear @115858, please fix this problem with the...",NaN
71,2410254.0,"@115858 please fix this iOS, it's ass 😵😵😵 http...",NaN
72,1557765.0,Unresponsive screen. \nFreezing for two minute...,NaN
73,367963.0,@AppleSupport my phone is glitchy as shit afte...,NaN
74,2479108.0,"Okay, @115858 and @AppleSupport why does my ph...",NaN
75,1707024.0,This new #AppleUpdate is driving me insaaaaann...,NaN
76,51655.0,@127601 SAMEEEE WTFFF @AppleSupport please hel...,@127599 It’s when I️ type ‘i’
77,1913831.0,What’s the best way to preorder the iPhone X? ...,NaN
78,2126042.0,@AppleSupport Mac user since the 90s here. Slo...,NaN
79,1631461.0,"@AppleSupport can’t get calls, no tone when I ...",NaN

====================================================================================================
Examples 80–99
====================================================================================================

,customer_tweet_id,customer_message,previous_message
80,717219.0,@AppleSupport @115858 @116333 Only reason I us...,NaN
81,1152792.0,@391261 @115858 Force restart it. Mines been d...,Why won’t my music show up on my lock screen 🙃...
82,2000383.0,@AppleSupport why can I️ not type the letter I...,NaN
83,151489.0,@AppleSupport the new update keeps crashing my...,NaN
84,2570947.0,@AppleSupport It's turning off by itself,@729090 We'd like to check on this with you. I...
85,1768.0,"@AppleSupport it has, but not for some time no...",@116101 We're happy to help. Has Home Sharing ...
86,1201166.0,"@AppleSupport Yes, I did.",@402239 We'd be happy to help. Have you tried ...
87,2559340.0,Same!!!! This shit is pissing me the fuck off ...,NaN
88,2301935.0,@115858 fix the update I’m tired of restarting...,NaN
89,2771931.0,"@AppleSupport Issues with my Bluetooth, 7 @174...",NaN
90,1599099.0,@115858 y’all got my phone on some trash ever ...,NaN
91,1793182.0,quick question @115858 @AppleSupport why does ...,NaN
92,236821.0,How can I download macOS Sierra installer? @Ap...,NaN
93,944204.0,"@AppleSupport \nHello, any idea why the ‘Share...",NaN
94,2485749.0,@AppleSupport ever since I️ updated my phone.....,NaN
95,2615314.0,#IOS still same problem my phone showing only ...,NaN
96,2378865.0,Yoooooooo @AppleSupport why can’t eye type eye???,NaN
97,515859.0,@AppleSupport My iphone 6 &amp; new ipad pro a...,NaN
98,1633108.0,"@115858 get ur shit together, this is annoying...",NaN
99,2586417.0,@AppleSupport im trying to send a video file t...,NaN

====================================================================================================
Examples 100–119
====================================================================================================

,customer_tweet_id,customer_message,previous_message
100,1557178.0,@AppleSupport I have already downloaded the iO...,@481368 We offer support via Twitter in Englis...
101,1145060.0,@AppleSupport New uptade can not download. Bef...,@389490 We certainly want to help get that res...
102,1828734.0,Since I update my phone I have the worst batte...,NaN
103,825890.0,@115948 @AppleSupport When is the wrong versio...,NaN
104,2009823.0,Dear @AppleSupport why did this new iOS make m...,NaN
105,1814496.0,Hey @AppleSupport can we downgrade our update ...,NaN
106,2143316.0,@AppleSupport Can’t believe Sr. Adv. Nick in C...,NaN
107,355277.0,@AppleSupport Essentially like that; a hashtag...,@AppleSupport The main issue that I️ and many ...
108,2371254.0,@AppleSupport https://t.co/XGBPN7HSYO not work...,NaN
109,285188.0,"@AppleSupport Thought it may be compatible, I ...",@183944 We understand. We'd like to let you kn...
110,2302706.0,@AppleSupport When i see tweets on twitter,@668205 Is this occurring when you are typing ...
111,1478379.0,@115858 iOS so horrible. My phone is pretty mu...,NaN
112,1482418.0,@AppleSupport So please stop. Thanks :)),@AppleSupport .. but you see iOS11 is really u...
113,2078258.0,iOS 11 has everything all messed up. Ever sinc...,NaN
114,1956373.0,"@AppleSupport It does, this is all I have done...",@580598 We'd like to help get your GPS working...
115,2447508.0,"Dear @115858 , \nPlease fix this whole autocor...",NaN
116,2903751.0,What’s the fucking point of fixing bugs and up...,NaN
117,397530.0,@AppleSupport WHY DOES THESE QUESTION MARKS KE...,NaN
118,1542043.0,@AppleSupport @AppleSupport ???,@477789 We're here to assist. This option is o...
119,2043334.0,@115858 after careful consideration I have com...,NaN

====================================================================================================
Examples 120–139
====================================================================================================

,customer_tweet_id,customer_message,previous_message
120,360301.0,@115948 It seems like I can't play Carpool Kar...,NaN
121,2922375.0,This is the second email I’ve received like th...,NaN
122,2889403.0,Rip 2014 MacBook Pro. Thanks .@115858 for the...,NaN
123,2856804.0,Wish I never updated my phone 🙄@115858 @AppleS...,NaN
124,2297027.0,@AppleSupport iPhone 7 Plus! 11.1.1,@666855 We'll be happy to help you determine w...
125,1368850.0,My iphone fucking completely broke today and I...,NaN
126,1296303.0,@AppleSupport need help it’s saying my Apple ...,NaN
127,566715.0,"@AppleSupport I don’t even know what it is, I ...",@252872 No problem! Automatic downloads are tu...
128,2747286.0,@118721 @AppleSupport I bought the Taylor Swi...,NaN
129,486173.0,@AppleSupport my iPhone won’t send any iMessag...,NaN
130,2925639.0,@AppleSupport are you guys having problems wit...,NaN
131,1336262.0,@115858 #iPhoneX pre-order via app was horribl...,NaN
132,2355167.0,@AppleSupport hello! i got an iPhone 3g with a...,NaN
133,1363868.0,@115858 when’s the next iOS update? Will it ac...,NaN
134,1645092.0,@115858 wtf is up with your bullshit and not b...,NaN
135,658028.0,Bro I fucking hate apple my home button just s...,NaN
136,891106.0,@AppleSupport How can I stop my email from upd...,NaN
137,2517124.0,Hey @AppleSupport my phone just randomly stopp...,NaN
138,2142429.0,Everything is so slow with ios 11 @AppleSuppor...,NaN
139,1443341.0,@115858 I️ I️ I️ wtf is this man,NaN

====================================================================================================
Examples 140–159
====================================================================================================

,customer_tweet_id,customer_message,previous_message
140,822213.0,My phone has been stuck like this all day @115...,NaN
141,2429248.0,Anyone having problems with their Mac apps sin...,NaN
142,1094142.0,@115858 IOS 11.0.3 has made me hate my iPhone ...,NaN
143,1432507.0,"@AppleSupport It happen with headphones on, an...",@316439 We're here for you. Are you using the ...
144,1804880.0,@AppleSupport Sending messages through my watc...,@AppleSupport my phone screen has been unrespo...
145,2205866.0,Why doesn’t the Bluetooth button in’t control ...,NaN
146,193631.0,Hmmm 🤔 so iOS 11.0.1 was supposed to bring alo...,NaN
147,486234.0,@AppleSupport No but it does not look right ma...,@230682 Image quality is not something we can ...
148,2354996.0,@AppleSupport I Thik there is something proble...,NaN
149,1386687.0,lmk @AppleSupport https://t.co/XhPks6CQi2,NaN
150,2590741.0,@AppleSupport What am I supposed to do with th...,NaN
151,1659151.0,@AppleSupport get it together and get rid of t...,NaN
152,1569684.0,"@AppleSupport Display zoom,so the apps are big...","@484146 We'd love to help. To clarify, are you..."
153,993387.0,@115858 @AppleSupport its 11.0.1. One of the i...,@115858 @AppleSupport @115858 @AppleSupport y...
154,2306480.0,Anyone else with iOS 11 find that their batter...,NaN
155,1662163.0,@115858 I have the 6+ and this update is break...,NaN
156,637504.0,@AppleSupport Bonsoir... à quand le bug clavie...,NaN
157,1039193.0,@AppleSupport 11.0.3 (15A432),@365861 You're in the right place for help. To...
158,2872586.0,Sooooo my iPhone aint working...the touch scre...,NaN
159,2975480.0,@115858 @AppleSupport know anything about this?,@115858 there’s a ridiculous issue on iOS 11 t...

====================================================================================================
Examples 160–179
====================================================================================================

,customer_tweet_id,customer_message,previous_message
160,2122599.0,@AppleSupport iPhone 8 - Music bar doesn’t mov...,NaN
161,1679282.0,This new @115858 update is messing with the pr...,NaN
162,1433710.0,@115858 @AppleSupport y’all need to fix this p...,NaN
163,1892478.0,@115858 my phone is MUCH slower and lags easil...,NaN
164,2571358.0,@AppleSupport iTunes!,@729179 We can look into this for you. Is your...
165,1681569.0,@AppleSupport fix this please https://t.co/hVJ...,NaN
166,1417394.0,ios11 messed up my camera roll @115858 fix thi...,NaN
167,1085261.0,@375998 @AppleSupport Ever since I updated my ...,help i’ve had this iphone 7+ since July and it...
168,889128.0,@AppleSupport I have and I know that @135616 u...,@331089 Thank you for letting us know. Have yo...
169,2889499.0,@115858 can you help me with a problem I have,NaN
170,642016.0,.@115858 I only barely considered getting an i...,NaN
171,848459.0,@115858 is this a #bug or #feature? #iphone ht...,NaN
172,1840198.0,@AppleSupport phone keeps freezing after lates...,NaN
173,2408460.0,By the way in running on an old mbp retina 13-...,NaN
174,847012.0,@AppleSupport If you bricked my 6s with iOS 11...,Find out everything you need to know about you...
175,2647151.0,"@AppleSupport 11.1.2, not been same phone sinc...",@746853 We'd like to see how we can help with ...
176,2343817.0,"@AppleSupport Iphone 6s Plus, IOS 11.2 Beta 2.",@677853 We're glad you took the time to reach ...
177,725628.0,@AppleSupport your new update is draining my b...,NaN
178,441047.0,@AppleSupport STILL iPhone 7 problems regardin...,NaN
179,1735112.0,@115858 When can we expect a new update to fix...,NaN

====================================================================================================
Examples 180–199
====================================================================================================

,customer_tweet_id,customer_message,previous_message
180,763663.0,@AppleSupport No steps. Just using the photo a...,@302496 Thanks. Can you tell us which steps yo...
181,621812.0,@AppleSupport iPhone 8 Plus upgraded to iOS 11...,NaN
182,2837216.0,@AppleSupport hello I have recently bought the...,NaN
183,1549441.0,My wireless @118845 running headphones just br...,NaN
184,989691.0,I am unable to update applications and install...,NaN
185,611252.0,So the short story is that @AppleSupport is ha...,NaN
186,1697447.0,"@115858 I️ appreciate the 80 new emojis, ya kn...",NaN
187,1979783.0,I’m a long time @115858 apologist but this new...,NaN
188,1100850.0,@AppleSupport any way to check my iphones over...,NaN
189,762545.0,Since upgrading to #iOS11 my call volume on 6s...,NaN
190,274876.0,My phone randomly decided to say I have Zero s...,NaN
191,1642589.0,So why are all I’s looking like this?\nAnd quo...,NaN
192,1500761.0,Y dus the latest iPhone @115858 update switch ...,NaN
193,2911793.0,@AppleSupport my airdrop won’t work anymore! ...,NaN
194,2208840.0,At first I was really impressed with iOS 11. B...,NaN
195,1913649.0,@115858 Your update sux. freezes every other d...,NaN
196,90598.0,"@135609 @AppleSupport Yep, a lot slower. Try r...",Anyone else’s iPhone been nothing but dead sin...
197,1130498.0,"@AppleSupport Apps constantly crash, iTunes do...",@386423 We'd be happy to see how we can help. ...
198,2285819.0,I hate you iOS 11. I want my smooth functionin...,NaN
199,1133201.0,@AppleSupport Overheating; can’t control music...,@387017 We'd like to hear a bit more about wha...

In [17]:
# Create a clean table containing only the fields needed for manual intent labeling.

labeling_sample = labeling_sample[
    [
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "intent",
        "notes"
    ]
].copy()

display(labeling_sample.head(10))

,customer_tweet_id,customer_message,previous_message,intent,notes
0,909813.0,"Seriously @115858, my iPhone’s heating up agai...",NaN,,
1,1864674.0,@115858 needs to setup a subscription plan bec...,NaN,,
2,2070017.0,"@612173 @AppleSupport Two month old phone, the...",@AppleSupport #apple #iphone #ois11 never had ...,,
3,554724.0,@AppleSupport i have an issue with my phone wh...,NaN,,
4,1684485.0,Why does my phone not know the letter I️ anymo...,NaN,,
5,2151155.0,"WHEN ARE YALL GONNA FIX THE I️-glitch, like th...",NaN,,
6,2047763.0,@AppleSupport Crackle gone - replaced by compl...,@AppleSupport every update makes my phone wors...,,
7,1809282.0,@AppleSupport @ATT Oh AND deletes all my texts...,I love having to pay $150 to pay off a phone t...,,
8,2385140.0,Dear @115858 @AppleSupport Why has iOS11 turne...,NaN,,
9,1971418.0,@AppleSupport I*,Yo @AppleSupport the letter “I️” is broken htt...,,

In [18]:
# Create an interactive helper for assigning an intent to each customer message.

valid_intents = list(intent_definitions.keys())

def show_labeling_example(index):
    row = labeling_sample.loc[index]

    print(f"INDEX: {index}")
    print(f"\nCUSTOMER MESSAGE:\n{row['customer_message']}")

    if pd.notna(row["previous_message"]) and str(row["previous_message"]).strip():
        print(f"\nPREVIOUS MESSAGE:\n{row['previous_message']}")

    print("\nVALID INTENTS:")
    for i, intent in enumerate(valid_intents, start=1):
        print(f"{i}. {intent}")

In [19]:
# Test the labeling helper on the first example before starting the full labeling process.

show_labeling_example(0)

INDEX: 0

CUSTOMER MESSAGE:
Seriously @115858, my iPhone’s heating up again,battery life has gone from 88% to 62% in a blink of an eye! Keypad freezing etc etc 😡😤 #Fedup

VALID INTENTS:
1. ios_update
2. battery_charging
3. connectivity
4. account_authentication
5. icloud_backup
6. apps_app_store
7. audio
8. camera_photos
9. display_input
10. apple_services
11. device_hardware
12. other_unclear

In [20]:
# Create a safe manual labeling loop that saves every label immediately to the CSV file.

def label_examples(data, start_index=0):
    for index in range(start_index, len(data)):
        row = data.loc[index]

        print("\n" + "=" * 90)
        print(f"INDEX: {index}")
        print(f"\nCUSTOMER:\n{row['customer_message']}")

        if pd.notna(row["previous_message"]) and str(row["previous_message"]).strip():
            print(f"\nPREVIOUS:\n{row['previous_message']}")

        print("\nINTENTS:")
        for i, intent in enumerate(valid_intents, start=1):
            print(f"{i}. {intent}")

        while True:
            choice = input("\nEnter intent number (1-12), or 'q' to stop: ").strip()

            if choice.lower() == "q":
                data.to_csv(labeling_path, index=False)
                print(f"\nProgress saved. Stopped at index {index}.")
                return

            if choice.isdigit() and 1 <= int(choice) <= len(valid_intents):
                selected_intent = valid_intents[int(choice) - 1]
                break

            print("Invalid choice. Enter a number from 1 to 12.")

        notes = input("Notes (optional): ").strip()

        data.loc[index, "intent"] = selected_intent
        data.loc[index, "notes"] = notes

        # Save immediately after every label.
        data.to_csv(labeling_path, index=False)

        print(f"Saved: {selected_intent}")

    print("\nAll examples have been labeled.")

In [21]:
# Verify that the 200-row labeling file was preserved after the kernel restart.

import pandas as pd

labeling_path = "../data/processed/apple_intent_labeling_200.csv"

labeling_check = pd.read_csv(labeling_path)

print("Rows:", len(labeling_check))
print("Columns:", labeling_check.columns.tolist())
print("Labels already assigned:", labeling_check["intent"].notna().sum())

Rows: 200
Columns: ['customer_tweet_id', 'customer_message', 'previous_message', 'brand_response', 'intent', 'notes']
Labels already assigned: 0

In [22]:
# Confirm that the cleaned dataset and 200-example labeling sample are loaded correctly.

print("Clean AppleSupport dataset:", clean_apple.shape)
print("200-example labeling sample:", labeling_sample.shape)
print("Currently labeled:", labeling_sample["intent"].notna().sum())

Clean AppleSupport dataset: (106523, 6)
200-example labeling sample: (200, 5)
Currently labeled: 200

In [23]:
# Check the current intent labels and make sure the 200-example dataset was labeled correctly.

print("Rows:", len(labeling_sample))
print("Missing labels:", labeling_sample["intent"].isna().sum())
print("\nIntent distribution:")
display(labeling_sample["intent"].value_counts(dropna=False))

Rows: 200
Missing labels: 0

Intent distribution:

intent
    200
Name: count, dtype: int64

In [24]:
# Inspect the unique values currently stored in the intent column.

print("Unique intent values:")
print(labeling_sample["intent"].unique())

print("\nFirst 10 intent values:")
display(labeling_sample[["customer_tweet_id", "intent"]].head(10))

Unique intent values:
<StringArray>
['']
Length: 1, dtype: str

First 10 intent values:

   customer_tweet_id intent
0           909813.0
1          1864674.0
2          2070017.0
3           554724.0
4          1684485.0
5          2151155.0
6          2047763.0
7          1809282.0
8          2385140.0
9          1971418.0

In [25]:
# Check how many intent labels are actually assigned and confirm the labeling sample is ready.

labeled_count = (
    labeling_sample["intent"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

print("Total examples:", len(labeling_sample))
print("Actually labeled:", labeled_count)
print("Remaining:", len(labeling_sample) - labeled_count)

Total examples: 200
Actually labeled: 0
Remaining: 200

In [26]:
# Create a 50-example manual review set for validating the intent taxonomy.

taxonomy_review = (
    labeling_sample[
        [
            "customer_tweet_id",
            "customer_message",
            "previous_message"
        ]
    ]
    .sample(
        50,
        random_state=1234
    )
    .reset_index(drop=True)
)

display(taxonomy_review)

,customer_tweet_id,customer_message,previous_message
0,1130498.0,"@AppleSupport Apps constantly crash, iTunes do...",@386423 We'd be happy to see how we can help. ...
1,1039193.0,@AppleSupport 11.0.3 (15A432),@365861 You're in the right place for help. To...
2,325899.0,@AppleSupport Already update but it doesn’t work.,@179912 Let's create a backup of your data and...
3,1536257.0,@476342 @AppleSupport what’s goin on,@476341 mines doing the same thing
4,810342.0,@AppleSupport Can iOS 11 search for what I hav...,"In iOS 11 on #iPad, all of your files are now ..."
5,92764.0,@AppleSupport No app updates. And I will test ...,@131555 We'd be happy to look into this with y...
6,2151155.0,"WHEN ARE YALL GONNA FIX THE I️-glitch, like th...",NaN
7,1809282.0,@AppleSupport @ATT Oh AND deletes all my texts...,I love having to pay $150 to pay off a phone t...
8,397530.0,@AppleSupport WHY DOES THESE QUESTION MARKS KE...,NaN
9,2371254.0,@AppleSupport https://t.co/XGBPN7HSYO not work...,NaN
10,2429248.0,Anyone having problems with their Mac apps sin...,NaN
11,2864855.0,@AppleSupport I did a hard reset and it works ...,@178644 Got it. Let’s disconnect the headphone...
12,1828734.0,Since I update my phone I have the worst batte...,NaN
13,1336262.0,@115858 #iPhoneX pre-order via app was horribl...,NaN
14,1840198.0,@AppleSupport phone keeps freezing after lates...,NaN
15,1662163.0,@115858 I have the 6+ and this update is break...,NaN
16,1296303.0,@AppleSupport need help it’s saying my Apple ...,NaN
17,1676324.0,@115858 y’all got me fucked up for making this...,NaN
18,2479108.0,"Okay, @115858 and @AppleSupport why does my ph...",NaN
19,58172.0,@AppleSupport App store now appears to be working,@129208 Help is here. We're not reporting any ...
20,2517124.0,Hey @AppleSupport my phone just randomly stopp...,NaN
21,1145060.0,@AppleSupport New uptade can not download. Bef...,@389490 We certainly want to help get that res...
22,762545.0,Since upgrading to #iOS11 my call volume on 6s...,NaN
23,2833032.0,@115858 is your uk website down? Iphone upgrad...,NaN
24,236821.0,How can I download macOS Sierra installer? @Ap...,NaN
25,1478379.0,@115858 iOS so horrible. My phone is pretty mu...,NaN
26,1971418.0,@AppleSupport I*,Yo @AppleSupport the letter “I️” is broken htt...
27,891106.0,@AppleSupport How can I stop my email from upd...,NaN
28,1368850.0,My iphone fucking completely broke today and I...,NaN
29,396073.0,@AppleSupport pls help my alarms won't go off ...,NaN
30,2047763.0,@AppleSupport Crackle gone - replaced by compl...,@AppleSupport every update makes my phone wors...
31,2911793.0,@AppleSupport my airdrop won’t work anymore! ...,NaN
32,2590741.0,@AppleSupport What am I supposed to do with th...,NaN
33,2205866.0,Why doesn’t the Bluetooth button in’t control ...,NaN
34,2856804.0,Wish I never updated my phone 🙄@115858 @AppleS...,NaN
35,1433710.0,@115858 @AppleSupport y’all need to fix this p...,NaN
36,944204.0,"@AppleSupport \nHello, any idea why the ‘Share...",NaN
37,1549441.0,My wireless @118845 running headphones just br...,NaN
38,642016.0,.@115858 I only barely considered getting an i...,NaN
39,816181.0,@AppleSupport Yep. Had that set for months now...,@201391 You can adjust this Camera setting fro...
40,193631.0,Hmmm 🤔 so iOS 11.0.1 was supposed to bring alo...,NaN
41,2014914.0,@AppleSupport why can’t I just type the letter...,NaN
42,61326.0,@AppleSupport No there's not. I'm just saying....,@130039 Have you checked for any debris in you...
43,2586417.0,@AppleSupport im trying to send a video file t...,NaN
44,2301935.0,@115858 fix the update I’m tired of restarting...,NaN
45,1748734.0,"Ever since i updated my phone, my music random...",NaN
46,2019482.0,@AppleSupport ios11 sucks. My iphone SE is a e...,NaN
47,1645092.0,@115858 wtf is up with your bullshit and not b...,NaN
48,2408460.0,By the way in running on an old mbp retina 13-...,NaN
49,1557178.0,@AppleSupport I have already downloaded the iO...,@481368 We offer support via Twitter in Englis...

In [27]:
# Display the 50 selected examples with context so we can validate the intent taxonomy.

for index, row in taxonomy_review.iterrows():
    print("\n" + "=" * 90)
    print(f"INDEX: {index}")
    print(f"\nCUSTOMER:\n{row['customer_message']}")

    if pd.notna(row["previous_message"]) and str(row["previous_message"]).strip():
        print(f"\nPREVIOUS:\n{row['previous_message']}")

==========================================================================================
INDEX: 0

CUSTOMER:
@AppleSupport Apps constantly crash, iTunes doesn’t work on the lock screen, it refuses to update to the latest OS &amp; i get a black screen all the time

PREVIOUS:
@386423 We'd be happy to see how we can help. What's going on?

==========================================================================================
INDEX: 1

CUSTOMER:
@AppleSupport 11.0.3 (15A432)

PREVIOUS:
@365861 You're in the right place for help. To start, may we get the iOS version number shown in Settings &gt; General &gt; About? https://t.co/GDrqU22YpT

==========================================================================================
INDEX: 2

CUSTOMER:
@AppleSupport Already update but it doesn’t work.

PREVIOUS:
@179912 Let's create a backup of your data and update to iOS 11.0.2 to see if that helps. Here's how: https://t.co/80YRnjDFDk

==========================================================================================
INDEX: 3

CUSTOMER:
@476342 @AppleSupport what’s goin on

PREVIOUS:
@476341 mines doing the same thing

==========================================================================================
INDEX: 4

CUSTOMER:
@AppleSupport Can iOS 11 search for what I have wrote in Notes? I remember that wwdc 2017 someone showed it for us

PREVIOUS:
In iOS 11 on #iPad, all of your files are now in one handy place. Here's a look at the new Files app.
Learn more https://t.co/6u9mY4reCZ https://t.co/q35OcP1afR

==========================================================================================
INDEX: 5

CUSTOMER:
@AppleSupport No app updates. And I will test with comparison to Apple Music app shortly

PREVIOUS:
@131555 We'd be happy to look into this with you and figure out what's causing this. Is this the only audio that this is happening with? If so, have you checked for an update in the App Store?

==========================================================================================
INDEX: 6

CUSTOMER:
WHEN ARE YALL GONNA FIX THE I️-glitch, like these last updates are MESSING UP smh @115858

==========================================================================================
INDEX: 7

CUSTOMER:
@AppleSupport @ATT Oh AND deletes all my texts, doesn't let me update, pictures I take turn grey, dies SUPER quickly. love it.

PREVIOUS:
I love having to pay $150 to pay off a phone that glitches &amp; lags &amp; freezes &amp; has to be restarted 10 times daily. @AppleSupport @ATT

==========================================================================================
INDEX: 8

CUSTOMER:
@AppleSupport WHY DOES THESE QUESTION MARKS KEEP POPPING UP IN REPLACE FOR THE LETTER “I️” ??

==========================================================================================
INDEX: 9

CUSTOMER:
@AppleSupport https://t.co/XGBPN7HSYO not working. Not able to login. Keep getting connection error

==========================================================================================
INDEX: 10

CUSTOMER:
Anyone having problems with their Mac apps since the #HighSierra update? @AppleSupport

==========================================================================================
INDEX: 11

CUSTOMER:
@AppleSupport I did a hard reset and it works now 😕😬 will circle back the next time it happens!

PREVIOUS:
@178644 Got it. Let’s disconnect the headphones and play the music without any external devices connected. Does the same thing happen? Also, do you have another pair of headphones we can test with?

==========================================================================================
INDEX: 12

CUSTOMER:
Since I update my phone I have the worst battery life in the world... cheers @115858

==========================================================================================
INDEX: 13

CUSTOMER:
@115858 #iPhoneX pre-order via app was horrible. Page unavailable, errors left and right, placed order and was given an incomplete notice.

==========================================================================================
INDEX: 14

CUSTOMER:
@AppleSupport phone keeps freezing after latest update... fail 👎

==========================================================================================
INDEX: 15

CUSTOMER:
@115858 I have the 6+ and this update is breaking my phone apart! Stop it!

==========================================================================================
INDEX: 16

CUSTOMER:
@AppleSupport  need help it’s saying my Apple ID has been disabled need help

==========================================================================================
INDEX: 17

CUSTOMER:
@115858 y’all got me fucked up for making this update change my I’s into “?”.

==========================================================================================
INDEX: 18

CUSTOMER:
Okay, @115858 and @AppleSupport why does my phone change an “I️” to and “! A ?”
#ICantReadHieroglyphics

==========================================================================================
INDEX: 19

CUSTOMER:
@AppleSupport App store now appears to be working

PREVIOUS:
@129208 Help is here. We're not reporting any outage at this time: https://t.co/7NVrDovSd8 Any issues connecting to the iTunes Store?

==========================================================================================
INDEX: 20

CUSTOMER:
Hey @AppleSupport my phone just randomly stopped receiving/making calls. Help!

==========================================================================================
INDEX: 21

CUSTOMER:
@AppleSupport New uptade can not download. Before ios11 i was thinking for new iphone(7plus or 8), but now i don't. Please solve this problem. https://t.co/1ppLNcczYV

PREVIOUS:
@389490 We certainly want to help get that resolved. Check out these steps to get that device working: https://t.co/8MvHMFZ83h

==========================================================================================
INDEX: 22

CUSTOMER:
Since upgrading to #iOS11 my call volume on 6s has been woeful @AppleSupport @121122 mobile to mobile calls esp almost inaudible.

==========================================================================================
INDEX: 23

CUSTOMER:
@115858 is your uk website down? Iphone upgrade program is not working

==========================================================================================
INDEX: 24

CUSTOMER:
How can I download macOS Sierra installer? @AppleSupport @115858

==========================================================================================
INDEX: 25

CUSTOMER:
@115858 iOS so horrible. My phone is pretty much useless. Siri never works, apps are slow, and the letter “I️” doesn’t even appear correctly https://t.co/LsE06aIcEQ

==========================================================================================
INDEX: 26

CUSTOMER:
@AppleSupport I*

PREVIOUS:
Yo @AppleSupport the letter “I️” is broken https://t.co/5SUJO2toJB

==========================================================================================
INDEX: 27

CUSTOMER:
@AppleSupport How can I stop my email from updating automatically???

==========================================================================================
INDEX: 28

CUSTOMER:
My iphone fucking completely broke today and I've only had that motherfucker for a year this is some ho ass shit @115858 what the fuck

==========================================================================================
INDEX: 29

CUSTOMER:
@AppleSupport pls help my alarms won't go off even though my sound is on and i was 45 minutes late to work today because of it ://

==========================================================================================
INDEX: 30

CUSTOMER:
@AppleSupport Crackle gone - replaced by complete silence...

PREVIOUS:
@AppleSupport every update makes my phone worse: still can’t make or receive calls, no pics in txt, help!

==========================================================================================
INDEX: 31

CUSTOMER:
@AppleSupport my airdrop won’t work anymore!  I have tried all of the recommendations you gave.  #help!!!!

==========================================================================================
INDEX: 32

CUSTOMER:
@AppleSupport What am I supposed to do with this? https://t.co/FzaVS73X4k

==========================================================================================
INDEX: 33

CUSTOMER:
Why doesn’t the Bluetooth button in’t control Center turn the Bluetooth off?????? @115858

==========================================================================================
INDEX: 34

CUSTOMER:
Wish I never updated my phone 🙄@115858 @AppleSupport tell me why my phone restarts all the time

==========================================================================================
INDEX: 35

CUSTOMER:
@115858 @AppleSupport y’all need to fix this problem with the &gt;&gt; “I️”

==========================================================================================
INDEX: 36

CUSTOMER:
@AppleSupport
Hello, any idea why the ‘Share’ button for this one photo I took it greyed out? https://t.co/Oi9QhAbjiR

==========================================================================================
INDEX: 37

CUSTOMER:
My wireless @118845 running headphones just broke out of the blue! They’re emitting a high pitched, horrible sound. Haven’t even had them that long. I loved them! Super Bummed! @116062

==========================================================================================
INDEX: 38

CUSTOMER:
.@115858 I only barely considered getting an iPhone and HERE I AM WITH ALL MY APPS CRASHING YOU NEED TO GET YOUR SHIT

==========================================================================================
INDEX: 39

CUSTOMER:
@AppleSupport Yep. Had that set for months now. Still gets switched to square no filter.

PREVIOUS:
@201391 You can adjust this Camera setting from Settings &gt; Camera &gt; Preserve Settings.

==========================================================================================
INDEX: 40

CUSTOMER:
Hmmm 🤔 so iOS 11.0.1 was supposed to bring along lots of bug fixes, all it did for me was kill the ability to copy &amp; paste nice one @115858 👍

==========================================================================================
INDEX: 41

CUSTOMER:
@AppleSupport why can’t I just type the letter I? This is ridiculous. We pay $1,000 bucks for phones and we can’t even type I. #applegetyouracttogether #annoying #shouldnthavetobesmarterthansmartphone

==========================================================================================
INDEX: 42

CUSTOMER:
@AppleSupport No there's not. I'm just saying. It takes almost 20 minutes to get this phone onto a charger. Even more.

PREVIOUS:
@130039 Have you checked for any debris in your charging port? Is there another charger that you can use with your iPhone to see if the issue persists?

==========================================================================================
INDEX: 43

CUSTOMER:
@AppleSupport im trying to send a video file to apple support but it says my file extension is not supported.

==========================================================================================
INDEX: 44

CUSTOMER:
@115858 fix the update I’m tired of restarting my phone 5 times a day

==========================================================================================
INDEX: 45

CUSTOMER:
Ever since i updated my phone, my music randomly pauses and skips on its own. What’s good @AppleSupport

==========================================================================================
INDEX: 46

CUSTOMER:
@AppleSupport ios11 sucks. My iphone SE is a expensive brick. Slowed apps, I type faster than it writes. Apple has failed their customers

==========================================================================================
INDEX: 47

CUSTOMER:
@115858 wtf is up with your bullshit and not being able to type the letter “I️”

==========================================================================================
INDEX: 48

CUSTOMER:
By the way in running on an old mbp retina 13-inch, late 2012. @AppleSupport @115858

==========================================================================================
INDEX: 49

CUSTOMER:
@AppleSupport I have already downloaded the iOS 11 but it says that the software is updated with the iOS 10.3.3

PREVIOUS:
@481368 We offer support via Twitter in English. Get help in Spanish here: https://t.co/IBIY3vMgPj or join https://t.co/OczyRx7IOs

In [28]:
# Create a compact view of the 50 examples so the full sample can be reviewed without notebook output truncation.

taxonomy_compact = taxonomy_review.copy()

taxonomy_compact["customer_message"] = (
    taxonomy_compact["customer_message"]
    .fillna("")
    .str.replace(r"\s+", " ", regex=True)
    .str.slice(0, 250)
)

taxonomy_compact["previous_message"] = (
    taxonomy_compact["previous_message"]
    .fillna("")
    .str.replace(r"\s+", " ", regex=True)
    .str.slice(0, 200)
)

display(taxonomy_compact)

,customer_tweet_id,customer_message,previous_message
0,1130498.0,"@AppleSupport Apps constantly crash, iTunes do...",@386423 We'd be happy to see how we can help. ...
1,1039193.0,@AppleSupport 11.0.3 (15A432),@365861 You're in the right place for help. To...
2,325899.0,@AppleSupport Already update but it doesn’t work.,@179912 Let's create a backup of your data and...
3,1536257.0,@476342 @AppleSupport what’s goin on,@476341 mines doing the same thing
4,810342.0,@AppleSupport Can iOS 11 search for what I hav...,"In iOS 11 on #iPad, all of your files are now ..."
5,92764.0,@AppleSupport No app updates. And I will test ...,@131555 We'd be happy to look into this with y...
6,2151155.0,"WHEN ARE YALL GONNA FIX THE I️-glitch, like th...",
7,1809282.0,@AppleSupport @ATT Oh AND deletes all my texts...,I love having to pay $150 to pay off a phone t...
8,397530.0,@AppleSupport WHY DOES THESE QUESTION MARKS KE...,
9,2371254.0,@AppleSupport https://t.co/XGBPN7HSYO not work...,
10,2429248.0,Anyone having problems with their Mac apps sin...,
11,2864855.0,@AppleSupport I did a hard reset and it works ...,@178644 Got it. Let’s disconnect the headphone...
12,1828734.0,Since I update my phone I have the worst batte...,
13,1336262.0,@115858 #iPhoneX pre-order via app was horribl...,
14,1840198.0,@AppleSupport phone keeps freezing after lates...,
15,1662163.0,@115858 I have the 6+ and this update is break...,
16,1296303.0,@AppleSupport need help it’s saying my Apple I...,
17,1676324.0,@115858 y’all got me fucked up for making this...,
18,2479108.0,"Okay, @115858 and @AppleSupport why does my ph...",
19,58172.0,@AppleSupport App store now appears to be working,@129208 Help is here. We're not reporting any ...
20,2517124.0,Hey @AppleSupport my phone just randomly stopp...,
21,1145060.0,@AppleSupport New uptade can not download. Bef...,@389490 We certainly want to help get that res...
22,762545.0,Since upgrading to #iOS11 my call volume on 6s...,
23,2833032.0,@115858 is your uk website down? Iphone upgrad...,
24,236821.0,How can I download macOS Sierra installer? @Ap...,
25,1478379.0,@115858 iOS so horrible. My phone is pretty mu...,
26,1971418.0,@AppleSupport I*,Yo @AppleSupport the letter “I️” is broken htt...
27,891106.0,@AppleSupport How can I stop my email from upd...,
28,1368850.0,My iphone fucking completely broke today and I...,
29,396073.0,@AppleSupport pls help my alarms won't go off ...,
30,2047763.0,@AppleSupport Crackle gone - replaced by compl...,@AppleSupport every update makes my phone wors...
31,2911793.0,@AppleSupport my airdrop won’t work anymore! I...,
32,2590741.0,@AppleSupport What am I supposed to do with th...,
33,2205866.0,Why doesn’t the Bluetooth button in’t control ...,
34,2856804.0,Wish I never updated my phone 🙄@115858 @AppleS...,
35,1433710.0,@115858 @AppleSupport y’all need to fix this p...,
36,944204.0,"@AppleSupport Hello, any idea why the ‘Share’ ...",
37,1549441.0,My wireless @118845 running headphones just br...,
38,642016.0,.@115858 I only barely considered getting an i...,
39,816181.0,@AppleSupport Yep. Had that set for months now...,@201391 You can adjust this Camera setting fro...
40,193631.0,Hmmm 🤔 so iOS 11.0.1 was supposed to bring alo...,
41,2014914.0,@AppleSupport why can’t I just type the letter...,
42,61326.0,@AppleSupport No there's not. I'm just saying....,@130039 Have you checked for any debris in you...
43,2586417.0,@AppleSupport im trying to send a video file t...,
44,2301935.0,@115858 fix the update I’m tired of restarting...,
45,1748734.0,"Ever since i updated my phone, my music random...",
46,2019482.0,@AppleSupport ios11 sucks. My iphone SE is a e...,
47,1645092.0,@115858 wtf is up with your bullshit and not b...,
48,2408460.0,By the way in running on an old mbp retina 13-...,
49,1557178.0,@AppleSupport I have already downloaded the iO...,@481368 We offer support via Twitter in Englis...

In [29]:
# Count common Apple service-related terms in the cleaned customer messages to decide whether this category needs refinement.

service_keywords = {
    "apple_music": r"\bmusic\b|apple music",
    "itunes": r"\bitunes\b",
    "imessage": r"\bimessage\b",
    "maps": r"\bmaps?\b",
    "facetime": r"\bfacetime\b",
    "siri": r"\bsiri\b",
    "airdrop": r"\bairdrop\b",
}

for service, pattern in service_keywords.items():
    count = clean_apple["customer_message"].str.contains(
        pattern,
        case=False,
        na=False,
        regex=True
    ).sum()

    print(f"{service:15} {count:,}")

apple_music     3,039
itunes          1,661
imessage        645
maps            299
facetime        338
siri            605
airdrop         108

In [30]:
# Estimate the prevalence of each intent using broad keyword signals to identify rare or missing categories.

intent_signals = {
    "ios_update": r"\bios\b|ios\s*11|update|updated|updating|upgrade|upgraded",
    "battery_charging": r"battery|charging|charge|overheat|heating",
    "connectivity": r"wifi|wi-fi|bluetooth|airdrop|network|signal|internet|cellular|mobile data",
    "account_authentication": r"apple id|password|login|log in|sign in|account|authentication",
    "icloud_backup": r"icloud|backup|back up|sync",
    "apps_app_store": r"\bapp\b|app store|application|download|install|crash",
    "audio": r"speaker|microphone|mic|sound|audio|headphone|airpod|hear|call volume",
    "camera_photos": r"camera|photo|photos|picture|pictures|video",
    "display_input": r"screen|display|keyboard|keypad|touch|type|typing|letter|question mark|glitch",
    "apple_services": r"music|itunes|imessage|facetime|maps|siri",
    "device_hardware": r"iphone|ipad|macbook|mac|device|phone"
}

for intent, pattern in intent_signals.items():
    count = clean_apple["customer_message"].str.contains(
        pattern,
        case=False,
        na=False,
        regex=True
    ).sum()

    percentage = count / len(clean_apple) * 100

    print(f"{intent:25} {count:7,} ({percentage:5.2f}%)")

ios_update                 36,115 (33.90%)
battery_charging           10,707 (10.05%)
connectivity                4,288 ( 4.03%)
account_authentication      2,654 ( 2.49%)
icloud_backup               2,531 ( 2.38%)
apps_app_store             10,100 ( 9.48%)
audio                       2,914 ( 2.74%)
camera_photos               3,760 ( 3.53%)
display_input              16,260 (15.26%)
apple_services              6,469 ( 6.07%)
device_hardware            45,028 (42.27%)

In [31]:
# Create a reproducible candidate pool for the 200-example golden evaluation set.

golden_candidates = (
    clean_apple[
        [
            "customer_tweet_id",
            "customer_message",
            "previous_message",
            "has_context"
        ]
    ]
    .sample(
        1000,
        random_state=2026
    )
    .reset_index(drop=True)
)

print("Golden candidate pool:", golden_candidates.shape)
display(golden_candidates.head(10))

Golden candidate pool: (1000, 4)

,customer_tweet_id,customer_message,previous_message,has_context
0,363770.0,@AppleSupport my iPhone 8+ is set to auto lock...,NaN,False
1,2499382.0,@115858 @AppleSupport Please tell me you are s...,NaN,False
2,1558857.0,@AppleSupport assuming you guys are hearing a ...,NaN,False
3,1975429.0,Since I updated my iOS my phone has slowed to ...,NaN,False
4,1643835.0,@AppleSupport when are y’all going to fix this...,NaN,False
5,2476068.0,@AppleSupport if the issue is not resolved i'l...,@707802 Thank you for the details. If you have...,True
6,239244.0,"updated Ios11 but it still sucks, even my came...",NaN,False
7,2205946.0,@AppleSupport It’s 5pm and my phone is at 30% ...,@644985 We can understand wanting the same bat...,True
8,2001862.0,So @115858 why this ? Mark box pop up every ti...,NaN,False
9,1425148.0,@AppleSupport For this app it has happened mul...,@451101 We're here to help. Is this issue happ...,True

In [32]:
# Create broad topic signals for sampling diverse examples; these signals are for sampling only, not final intent labels.

import re

def contains_any(text, keywords):
    text = str(text).lower()
    return any(re.search(rf"\b{re.escape(word)}\b", text) for word in keywords)

sampling_signals = {
    "ios_update": [
        "ios", "update", "upgrade", "ios11", "ios 11"
    ],
    "battery_charging": [
        "battery", "charge", "charging", "charger", "drain"
    ],
    "connectivity": [
        "wifi", "wi-fi", "bluetooth", "cellular", "network",
        "internet", "airdrop", "signal"
    ],
    "account_authentication": [
        "apple id", "password", "login", "sign in", "account",
        "authentication", "icloud id"
    ],
    "icloud_backup": [
        "icloud", "backup", "sync", "storage"
    ],
    "apps_app_store": [
        "app", "apps", "app store", "download", "crash"
    ],
    "audio": [
        "sound", "speaker", "microphone", "mic", "volume",
        "headphone", "airpods", "audio", "call"
    ],
    "camera_photos": [
        "camera", "photo", "photos", "picture", "video"
    ],
    "display_input": [
        "screen", "display", "touch", "keyboard", "typing",
        "type", "brightness"
    ],
    "apple_services": [
        "music", "itunes", "imessage", "facetime", "maps", "siri"
    ],
}

for intent, keywords in sampling_signals.items():
    golden_candidates[intent + "_signal"] = golden_candidates[
        "customer_message"
    ].apply(lambda x: contains_any(x, keywords))

signal_columns = [intent + "_signal" for intent in sampling_signals]

signal_counts = (
    golden_candidates[signal_columns]
    .sum()
    .sort_values(ascending=False)
)

display(signal_counts.to_frame("candidate_count"))

                               candidate_count
ios_update_signal                          284
battery_charging_signal                    103
display_input_signal                        94
apps_app_store_signal                       91
apple_services_signal                       53
connectivity_signal                         38
audio_signal                                31
icloud_backup_signal                        31
camera_photos_signal                        30
account_authentication_signal               27

In [33]:
# Select a diverse 200-example review set using topic signals plus random coverage; signals are only for sampling, not labels.

import numpy as np

rng = np.random.default_rng(2026)

# Target roughly equal representation across the major topic signals.
samples_per_signal = 15

selected_indices = set()

for signal_column in signal_columns:
    available = golden_candidates[
        golden_candidates[signal_column] &
        ~golden_candidates.index.isin(selected_indices)
    ].index.to_numpy()

    if len(available) > 0:
        n = min(samples_per_signal, len(available))
        chosen = rng.choice(available, size=n, replace=False)
        selected_indices.update(chosen)

# Fill the remaining slots with completely random examples.
remaining = 200 - len(selected_indices)

available_random = np.array([
    i for i in golden_candidates.index
    if i not in selected_indices
])

if remaining > 0:
    chosen_random = rng.choice(
        available_random,
        size=remaining,
        replace=False
    )
    selected_indices.update(chosen_random)

golden_review = (
    golden_candidates
    .loc[sorted(selected_indices)]
    [
        [
            "customer_tweet_id",
            "customer_message",
            "previous_message",
            "has_context"
        ]
    ]
    .reset_index(drop=True)
)

print("Golden review set:", golden_review.shape)
display(golden_review.head(20))

Golden review set: (200, 4)

,customer_tweet_id,customer_message,previous_message,has_context
0,611285.0,Hey @115858 how can Siri really be my personal...,NaN,False
1,400853.0,@AppleSupport Was able to help him via iTunes....,@210813 Let us know if the update has issues t...,True
2,1099710.0,@379507 @AppleSupport Having the same issue.,@AppleSupport iOS 11.0.3. 2 different iPhone 7...,True
3,1342708.0,Hey @AppleSupport iOS11 update made my $900 iP...,NaN,False
4,1687712.0,"Good afternoon, @AppleSupport! It’s always som...",NaN,False
5,1121644.0,@AppleSupport App is shutting down randomly an...,@384569 Is WhatsApp the only app having an issue?,True
6,1747356.0,Is anyone else having problems downloading and...,NaN,False
7,2119414.0,"So wtf y’all gon do about this I situation, @1...",NaN,False
8,1983621.0,@AppleSupport hey why is the remove episode op...,NaN,False
9,323849.0,@AppleSupport my phone battery has just gone f...,NaN,False
10,1221923.0,"@AppleSupport I recorded a 2 minute video, abo...",@231135 We'd love to help. What sort of behavi...,True
11,753922.0,@AppleSupport not only does my phone restart n...,NaN,False
12,2873394.0,@115858 can you do another update my shit keep...,NaN,False
13,87015.0,@115858 @AppleSupport I urgently request an op...,NaN,False
14,400851.0,@AppleSupport since updating to the useless s...,NaN,False
15,517208.0,Wow was on hold for like 10 min with @AppleSup...,NaN,False
16,2487173.0,@AppleSupport my rear camera is crashingg as ...,NaN,False
17,2454594.0,Me eternally waiting for my iPhone to do ANYTH...,NaN,False
18,61347.0,@AppleSupport Yeah But Half My Apps Disapear &...,Accidentally deleted an app? Here's how to fin...,True
19,2036530.0,Hey @AppleSupport is there a way to un-Update ...,NaN,False

In [34]:
# Create the blank golden evaluation file so we can manually assign and review the 200 intent labels.

from pathlib import Path

evaluation_dir = Path("../data/evaluation")
evaluation_dir.mkdir(parents=True, exist_ok=True)

golden_set = golden_review.copy()

golden_set["intent"] = ""
golden_set["notes"] = ""

golden_path = evaluation_dir / "apple_support_golden_200.csv"
golden_set.to_csv(golden_path, index=False)

print(f"Created: {golden_path}")
print(f"Rows: {len(golden_set)}")
print(f"Columns: {list(golden_set.columns)}")

Created: ..\data\evaluation\apple_support_golden_200.csv
Rows: 200
Columns: ['customer_tweet_id', 'customer_message', 'previous_message', 'has_context', 'intent', 'notes']

In [35]:
# Display the first 20 golden examples so they can be manually assigned one primary intent each.

batch_1 = golden_set.iloc[0:20][
    [
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "intent",
        "notes"
    ]
]

display(batch_1)

,customer_tweet_id,customer_message,previous_message,intent,notes
0,611285.0,Hey @115858 how can Siri really be my personal...,NaN,,
1,400853.0,@AppleSupport Was able to help him via iTunes....,@210813 Let us know if the update has issues t...,,
2,1099710.0,@379507 @AppleSupport Having the same issue.,@AppleSupport iOS 11.0.3. 2 different iPhone 7...,,
3,1342708.0,Hey @AppleSupport iOS11 update made my $900 iP...,NaN,,
4,1687712.0,"Good afternoon, @AppleSupport! It’s always som...",NaN,,
5,1121644.0,@AppleSupport App is shutting down randomly an...,@384569 Is WhatsApp the only app having an issue?,,
6,1747356.0,Is anyone else having problems downloading and...,NaN,,
7,2119414.0,"So wtf y’all gon do about this I situation, @1...",NaN,,
8,1983621.0,@AppleSupport hey why is the remove episode op...,NaN,,
9,323849.0,@AppleSupport my phone battery has just gone f...,NaN,,
10,1221923.0,"@AppleSupport I recorded a 2 minute video, abo...",@231135 We'd love to help. What sort of behavi...,,
11,753922.0,@AppleSupport not only does my phone restart n...,NaN,,
12,2873394.0,@115858 can you do another update my shit keep...,NaN,,
13,87015.0,@115858 @AppleSupport I urgently request an op...,NaN,,
14,400851.0,@AppleSupport since updating to the useless s...,NaN,,
15,517208.0,Wow was on hold for like 10 min with @AppleSup...,NaN,,
16,2487173.0,@AppleSupport my rear camera is crashingg as ...,NaN,,
17,2454594.0,Me eternally waiting for my iPhone to do ANYTH...,NaN,,
18,61347.0,@AppleSupport Yeah But Half My Apps Disapear &...,Accidentally deleted an app? Here's how to fin...,,
19,2036530.0,Hey @AppleSupport is there a way to un-Update ...,NaN,,

In [36]:
# Display the first 20 examples as full text so each intent can be labelled from complete context.

for i, row in golden_set.iloc[0:20].iterrows():
    print(f"\n{'=' * 80}")
    print(f"INDEX: {i}")
    print(f"CUSTOMER: {row['customer_message']}")
    print(f"PREVIOUS: {row['previous_message']}")

================================================================================
INDEX: 0
CUSTOMER: Hey @115858 how can Siri really be my personal assistant if it won't integrate into 3rd party apps why can't I have it play Spotify where is the functionality?
PREVIOUS: nan

================================================================================
INDEX: 1
CUSTOMER: @AppleSupport Was able to help him via iTunes. Still weird the OTA didn’t work
PREVIOUS: @210813 Let us know if the update has issues through iTunes.

================================================================================
INDEX: 2
CUSTOMER: @379507 @AppleSupport Having the same issue.
PREVIOUS: @AppleSupport iOS 11.0.3. 2 different iPhone 7s in my family, multiple iPads too. Enter address in Maps &amp; driving directions fail to load—endless spinner.

================================================================================
INDEX: 3
CUSTOMER: Hey @AppleSupport iOS11 update made my $900 iPad Pro unusable. The battery lasts 1/2 day even if just sitting there in airplane mode. #SUCKS
PREVIOUS: nan

================================================================================
INDEX: 4
CUSTOMER: Good afternoon, @AppleSupport! It’s always some shit with y’all and these iPhone updates, huh? https://t.co/cGR2qXnGNA
PREVIOUS: nan

================================================================================
INDEX: 5
CUSTOMER: @AppleSupport App is shutting down randomly and unexpectedly
PREVIOUS: @384569 Is WhatsApp the only app having an issue?

================================================================================
INDEX: 6
CUSTOMER: Is anyone else having problems downloading and updating apps? Lie your password is right but it’s just not doing it? @AppleSupport
PREVIOUS: nan

================================================================================
INDEX: 7
CUSTOMER: So wtf y’all gon do about this I situation, @115858? Cuz I’m sick of sick this damn A n shit. 😒
PREVIOUS: nan

================================================================================
INDEX: 8
CUSTOMER: @AppleSupport hey why is the remove episode option gone from the podcast app, subscribed podcasts keep popping up after I delete them
PREVIOUS: nan

================================================================================
INDEX: 9
CUSTOMER: @AppleSupport my phone battery has just gone from 50% - 34% in 15 mins???
PREVIOUS: nan

================================================================================
INDEX: 10
CUSTOMER: @AppleSupport I recorded a 2 minute video, about half way the audio cut out
PREVIOUS: @231135 We'd love to help. What sort of behavior are you seeing when you try?

================================================================================
INDEX: 11
CUSTOMER: @AppleSupport not only does my phone restart netime I use the front camera but now my phone buzzes on calls. It’s updated. #iphone8plus
PREVIOUS: nan

================================================================================
INDEX: 12
CUSTOMER: @115858 can you do another update my shit keeps freezing.. what happens when I inevitably need to call 911 and this shit doesn’t work? Do I do cpr myself with the phone? Or just Lost it and hit myself in the ducking heart hella times til I come back to life
PREVIOUS: nan

================================================================================
INDEX: 13
CUSTOMER: @115858 @AppleSupport I urgently request an option (toggle) to force the ringtone to always additionally be played via internal speaker even when headsets or other devices are connected.
I like to have my phone lying around with speakers connected, dont like to miss calls.
PREVIOUS: nan

================================================================================
INDEX: 14
CUSTOMER: @AppleSupport  since updating to the useless software. Screen keeps auto rotating. Sort it out
PREVIOUS: nan

================================================================================
INDEX: 15
CUSTOMER: Wow was on hold for like 10 min with @AppleSupport and they hung up on me , been tryin to recover my Apple ID password all week 😒😒
PREVIOUS: nan

================================================================================
INDEX: 16
CUSTOMER: @AppleSupport  my rear camera is crashingg as i updated to ios 11.1😞😞nothing wrong wiz hardware btw..
Iphone 6 plus,..
Thanks https://t.co/lNZRWMWh7s
PREVIOUS: nan

================================================================================
INDEX: 17
CUSTOMER: Me eternally waiting for my iPhone to do ANYTHING after updating to #iOS11 @115858 #SLOWAF https://t.co/u0AMexe1Ug
PREVIOUS: nan

================================================================================
INDEX: 18
CUSTOMER: @AppleSupport Yeah But Half My Apps Disapear &amp;Or Don’t Show (Since IOS11),Even Right After I Downloaded Them,It’s Random,But App Store Randomly Seems To Hide/Show Purchases
PREVIOUS: Accidentally deleted an app? Here's how to find and reinstall your purchased apps in iOS 11. https://t.co/wvOgLJh2Kz

================================================================================
INDEX: 19
CUSTOMER: Hey @AppleSupport is there a way to un-Update my phone? Your new update killed my battery.
PREVIOUS: nan

In [37]:
# Save the manually reviewed labels and notes for golden examples 0–19 in one step.

labels_0_19 = {
    0: ("apple_services", "Siri/Spotify third-party app integration issue"),
    1: ("ios_update", "OTA update failed; iTunes update worked"),
    2: ("apple_services", "Apple Maps directions fail to load"),
    3: ("battery_charging", "Battery drain is the primary issue after iOS update"),
    4: ("ios_update", "Complaint specifically about iPhone updates"),
    5: ("apps_app_store", "App is shutting down unexpectedly"),
    6: ("apps_app_store", "Cannot download or update apps"),
    7: ("display_input", "Typing/input problem involving the letter I"),
    8: ("apps_app_store", "Podcast app functionality issue"),
    9: ("battery_charging", "Rapid battery drain"),
    10: ("audio", "Audio cuts out during video recording"),
    11: ("camera_photos", "Front camera causes phone restart"),
    12: ("ios_update", "Requests another update to fix freezing"),
    13: ("audio", "Ringtone/speaker behavior with connected devices"),
    14: ("display_input", "Screen automatically rotates"),
    15: ("account_authentication", "Apple ID password recovery"),
    16: ("camera_photos", "Rear camera crashes after iOS update"),
    17: ("ios_update", "Severe slowdown after iOS 11 update"),
    18: ("apps_app_store", "Apps/App Store purchases disappearing"),
    19: ("battery_charging", "Battery drain after update"),
}

for index, (intent, notes) in labels_0_19.items():
    golden_set.loc[index, "intent"] = intent
    golden_set.loc[index, "notes"] = notes

golden_set.to_csv(golden_path, index=False)

labelled_count = (
    golden_set["intent"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

print(f"Saved labels for rows 0–19.")
print(f"Total labelled: {labelled_count}/200")

Saved labels for rows 0–19.
Total labelled: 20/200

In [38]:
# Export examples 20–69 as full plain text so VS Code does not truncate long customer messages.

batch_start = 20
batch_end = 70

with open("../data/processed/labeling_batch_20_69.txt", "w", encoding="utf-8") as f:
    for i, row in golden_set.iloc[batch_start:batch_end].iterrows():
        f.write("=" * 100 + "\n")
        f.write(f"INDEX: {i}\n")
        f.write(f"CUSTOMER: {row['customer_message']}\n")
        f.write(f"PREVIOUS: {row['previous_message']}\n\n")

print("Created temporary viewing file:")
print("../data/processed/labeling_batch_20_69.txt")

Created temporary viewing file:
../data/processed/labeling_batch_20_69.txt

In [39]:
# Save the manually reviewed labels and notes for golden examples 20–69.

labels_20_69 = {
    20: ("connectivity", "CarPlay/iPhone/car connection issue"),
    21: ("other_unclear", "Generic unresolved support complaint"),
    22: ("display_input", "Keyboard/letter problem"),
    23: ("battery_charging", "Battery drain"),
    24: ("connectivity", "Cannot sync iPhone with Mac"),
    25: ("connectivity", "AirDrop issue"),
    26: ("device_hardware", "Apple Watch restarting"),
    27: ("display_input", "I keyboard glitch"),
    28: ("apps_app_store", "App Store password/download behavior"),
    29: ("connectivity", "Cannot make or receive calls"),
    30: ("display_input", "I typing problem"),
    31: ("battery_charging", "Battery deterioration after update"),
    32: ("account_authentication", "Apple ID reset problem"),
    33: ("connectivity", "Calls hang during dialing"),
    34: ("account_authentication", "Cannot sign into iCloud"),
    35: ("display_input", "I typing problem"),
    36: ("ios_update", "Freezing after iOS 11 update"),
    37: ("audio", "Media button/audio behavior"),
    38: ("audio", "Audio cuts out during screen recording"),
    39: ("device_hardware", "Device randomly crashes/restarts"),
    40: ("account_authentication", "Unauthorized subscription"),
    41: ("account_authentication", "iCloud Mail access/sign-in"),
    42: ("display_input", "I input problem"),
    43: ("apple_services", "Apple TV streaming issue"),
    44: ("apple_services", "Apple Music account issue"),
    45: ("ios_update", "Update-related screen compatibility issue"),
    46: ("connectivity", "Wi-Fi/cellular connectivity difference"),
    47: ("device_hardware", "Broken screen/device access issue"),
    48: ("battery_charging", "Rapid battery drain"),
    49: ("apple_services", "iMessage sign-in/service issue"),
    50: ("display_input", "Autocorrect/input problem"),
    51: ("apple_services", "iMessage not working"),
    52: ("apple_services", "iMessage group-chat functionality"),
    53: ("display_input", "I input problem"),
    54: ("display_input", "I input problem"),
    55: ("display_input", "I input problem"),
    56: ("device_hardware", "Multiple device-level failures"),
    57: ("other_unclear", "Generic glitch complaint"),
    58: ("audio", "AirPod charging problem"),
    59: ("apple_services", "FaceTime not working"),
    60: ("ios_update", "Freezing after iOS 11"),
    61: ("display_input", "Cannot type I.T."),
    62: ("apple_services", "Spotify sync/service issue"),
    63: ("account_authentication", "iCloud account type change"),
    64: ("battery_charging", "Battery problem"),
    65: ("battery_charging", "Context indicates charging/charger issue"),
    66: ("apps_app_store", "Files functionality issue"),
    67: ("apps_app_store", "Cannot purchase/download apps"),
    68: ("connectivity", "Cellular carrier/network issue"),
    69: ("device_hardware", "Lost iPhone/device recovery"),
}

for index, (intent, notes) in labels_20_69.items():
    golden_set.loc[index, "intent"] = intent
    golden_set.loc[index, "notes"] = notes

golden_set.to_csv(golden_path, index=False)

labelled_count = (
    golden_set["intent"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

print(f"Saved labels for rows 20–69.")
print(f"Total labelled: {labelled_count}/200")

Saved labels for rows 20–69.
Total labelled: 70/200

In [40]:
# Export golden examples 70–119 as full text so the messages and conversation context are not clipped.

batch_start = 70
batch_end = 120

with open("../data/processed/labeling_batch_70_119.txt", "w", encoding="utf-8") as f:
    for i, row in golden_set.iloc[batch_start:batch_end].iterrows():
        f.write("=" * 100 + "\n")
        f.write(f"INDEX: {i}\n")
        f.write(f"CUSTOMER: {row['customer_message']}\n")
        f.write(f"PREVIOUS: {row['previous_message']}\n\n")

print("Created temporary viewing file:")
print("../data/processed/labeling_batch_70_119.txt")

Created temporary viewing file:
../data/processed/labeling_batch_70_119.txt

In [41]:
# Save the manually reviewed labels and notes for golden examples 70–119.

labels_70_119 = {
    70: ("apps_app_store", "App storage usage"),
    71: ("apps_app_store", "Apps cannot be updated"),
    72: ("camera_photos", "Rear camera produces blurry photos"),
    73: ("apple_services", "Safari/iCloud bookmark syncing"),
    74: ("battery_charging", "Poor battery life"),
    75: ("audio", "Cannot adjust volume while locked"),
    76: ("ios_update", "Update-related glitches"),
    77: ("device_hardware", "Multiple device failures"),
    78: ("audio", "Unexpected alarm-like sound"),
    79: ("display_input", "Keyboard prevents login"),
    80: ("icloud_backup", "Apple Watch cannot restore backup"),
    81: ("display_input", "Keyboard glitch"),
    82: ("display_input", "Keyboard I glitch"),
    83: ("account_authentication", "Apple ID activation/authentication error"),
    84: ("battery_charging", "Battery suddenly drops"),
    85: ("account_authentication", "Unexpected account/credit-card charge"),
    86: ("account_authentication", "Suspicious iCloud sign-in notifications"),
    87: ("account_authentication", "iCloud account recovery/lockout"),
    88: ("icloud_backup", "iCloud Photos download/sync issue"),
    89: ("account_authentication", "Switching iCloud account email"),
    90: ("battery_charging", "Severe battery drain after update"),
    91: ("device_hardware", "Device restart troubleshooting context"),
    92: ("display_input", "Keyboard lag"),
    93: ("account_authentication", "Forgot iCloud password"),
    94: ("apple_services", "iMessage/FaceTime activation"),
    95: ("apps_app_store", "Cannot download apps"),
    96: ("camera_photos", "Camera Live Photos setting issue"),
    97: ("account_authentication", "Family Sharing authentication"),
    98: ("audio", "Speaker crackling"),
    99: ("icloud_backup", "iCloud backup retention"),
    100: ("device_hardware", "Multiple device/function failures"),
    101: ("account_authentication", "Account recovery"),
    102: ("battery_charging", "Extreme battery drain"),
    103: ("audio", "Screenshot sound missing"),
    104: ("device_hardware", "Apple Watch incorrect time"),
    105: ("apps_app_store", "Apps missing after restore"),
    106: ("display_input", "I character rendering problem"),
    107: ("apple_services", "Apple Music playback issue"),
    108: ("apple_services", "iTunes/Apple Music syncing"),
    109: ("audio", "Calls have no sound"),
    110: ("connectivity", "Wi-Fi problem"),
    111: ("connectivity", "AirDrop connection problem"),
    112: ("camera_photos", "Camera roll/photo library issue"),
    113: ("icloud_backup", "iCloud Photo Library error"),
    114: ("display_input", "Green line on screen"),
    115: ("battery_charging", "Battery problem after update"),
    116: ("battery_charging", "Battery issue is primary"),
    117: ("apps_app_store", "App error prevents preorder"),
    118: ("display_input", "I becomes question-mark box"),
    119: ("apps_app_store", "Managed-account app controls"),
}

for index, (intent, notes) in labels_70_119.items():
    golden_set.loc[index, "intent"] = intent
    golden_set.loc[index, "notes"] = notes

golden_set.to_csv(golden_path, index=False)

labelled_count = (
    golden_set["intent"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

print(f"Saved labels for rows 70–119.")
print(f"Total labelled: {labelled_count}/200")

Saved labels for rows 70–119.
Total labelled: 120/200

In [42]:
# Export golden examples 120–169 as full text so the complete customer messages and context can be reviewed without clipping.

batch_start = 120
batch_end = 170

with open("../data/processed/labeling_batch_120_169.txt", "w", encoding="utf-8") as f:
    for i, row in golden_set.iloc[batch_start:batch_end].iterrows():
        f.write("=" * 100 + "\n")
        f.write(f"INDEX: {i}\n")
        f.write(f"CUSTOMER: {row['customer_message']}\n")
        f.write(f"PREVIOUS: {row['previous_message']}\n\n")

print("Created temporary viewing file:")
print("../data/processed/labeling_batch_120_169.txt")

Created temporary viewing file:
../data/processed/labeling_batch_120_169.txt

In [43]:
# Save the manually reviewed labels and notes for golden examples 120–169.

labels_120_169 = {
    120: ("display_input", "Keyboard issue"),
    121: ("apple_services", "iTunes/music not appearing on iPhone"),
    122: ("device_hardware", "Screen completely blank/unresponsive"),
    123: ("battery_charging", "Update-related charging problem"),
    124: ("apple_services", "Music stops when opening another app"),
    125: ("display_input", "Typing I issue"),
    126: ("apps_app_store", "Mail app freezes"),
    127: ("account_authentication", "Apple ID account recovery"),
    128: ("connectivity", "Bluetooth speaker disconnects"),
    129: ("battery_charging", "Battery issue"),
    130: ("audio", "Headphones/volume issue"),
    131: ("ios_update", "Update causes shutdown/Apple logo loop"),
    132: ("apple_services", "Text messages disappeared"),
    133: ("camera_photos", "Camera issue"),
    134: ("connectivity", "Call/FaceTime notifications not arriving"),
    135: ("connectivity", "Wireless keyboard connection issue"),
    136: ("display_input", "I becomes a box"),
    137: ("apps_app_store", "Mail app creates duplicate drafts"),
    138: ("display_input", "Screen issue"),
    139: ("apple_services", "Apple Watch push notifications"),
    140: ("account_authentication", "Account unlock/trusted number"),
    141: ("connectivity", "Wi-Fi not working"),
    142: ("apple_services", "Music not appearing in library"),
    143: ("other_unclear", "Multiple unrelated iOS problems"),
    144: ("apps_app_store", "Context indicates app updates"),
    145: ("connectivity", "Wi-Fi stopped working"),
    146: ("other_unclear", "Only mentions scheduled callback"),
    147: ("connectivity", "Bluetooth problems"),
    148: ("display_input", "Keyboard I issue"),
    149: ("apple_services", "Apple Music issue"),
    150: ("audio", "Apple Watch microphone issue"),
    151: ("ios_update", "Context indicates iOS version question"),
    152: ("device_hardware", "Phone storage is full"),
    153: ("account_authentication", "Apple ID recovery"),
    154: ("display_input", "Keyboard I issue"),
    155: ("ios_update", "iOS 11 freezing/glitches"),
    156: ("battery_charging", "Battery life reduced after update"),
    157: ("display_input", "3D Touch lag"),
    158: ("ios_update", "iOS software fault"),
    159: ("device_hardware", "Multiple hardware/function problems"),
    160: ("display_input", "Context indicates screen issue"),
    161: ("account_authentication", "iTunes billing/account issue"),
    162: ("apps_app_store", "Context indicates album download problem"),
    163: ("display_input", "Typing issue"),
    164: ("icloud_backup", "Missing picture requested from iCloud"),
    165: ("device_hardware", "iPhone crashes despite update"),
    166: ("battery_charging", "Battery issue"),
    167: ("apps_app_store", "Safari/app deletion functionality"),
    168: ("apple_services", "Contacts disappearing"),
    169: ("connectivity", "Wi-Fi switch disabled"),
}

for index, (intent, notes) in labels_120_169.items():
    golden_set.loc[index, "intent"] = intent
    golden_set.loc[index, "notes"] = notes

golden_set.to_csv(golden_path, index=False)

labelled_count = (
    golden_set["intent"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

print(f"Saved labels for rows 120–169.")
print(f"Total labelled: {labelled_count}/200")

Saved labels for rows 120–169.
Total labelled: 170/200

In [44]:
# Export the final 30 golden examples as full text so we can manually review and label them.

batch_start = 170
batch_end = 200

with open("../data/processed/labeling_batch_170_199.txt", "w", encoding="utf-8") as f:
    for i, row in golden_set.iloc[batch_start:batch_end].iterrows():
        f.write("=" * 100 + "\n")
        f.write(f"INDEX: {i}\n")
        f.write(f"CUSTOMER: {row['customer_message']}\n")
        f.write(f"PREVIOUS: {row['previous_message']}\n\n")

print("Created temporary viewing file:")
print("../data/processed/labeling_batch_170_199.txt")

Created temporary viewing file:
../data/processed/labeling_batch_170_199.txt

In [45]:
# Save the manually reviewed labels and notes for the final golden examples 170–199.

labels_170_199 = {
    170: ("display_input", "Screen/control-center interaction issue"),
    171: ("camera_photos", "Camera malfunction"),
    172: ("connectivity", "Wi-Fi turns back on"),
    173: ("apple_services", "Mail/Gmail notification and loading issue"),
    174: ("apple_services", "Video streaming/playback issue"),
    175: ("camera_photos", "Photos disappeared after screenshot"),
    176: ("camera_photos", "Videos not working"),
    177: ("camera_photos", "Camera photos not saving"),
    178: ("display_input", "I typing problem is primary"),
    179: ("apple_services", "Siri issue"),
    180: ("apple_services", "Apple Music subscription issue"),
    181: ("battery_charging", "Battery health/drain"),
    182: ("display_input", "Touchscreen problem is primary"),
    183: ("apps_app_store", "Clock app cannot open and causes crashes"),
    184: ("ios_update", "New iOS update complaint"),
    185: ("display_input", "Screen discoloration"),
    186: ("device_hardware", "Apple Watch functionality issue"),
    187: ("connectivity", "Context indicates cellular connection issue"),
    188: ("apple_services", "Apple Watch synced notifications"),
    189: ("device_hardware", "Internal/device damage"),
    190: ("display_input", "UI button cannot be selected"),
    191: ("apps_app_store", "WhatsApp not loading new messages"),
    192: ("display_input", "Keyboard issue"),
    193: ("connectivity", "Wi-Fi disconnects"),
    194: ("camera_photos", "Photos deleted from camera roll"),
    195: ("display_input", "AssistiveTouch/Reachability interaction"),
    196: ("other_unclear", "No actual issue stated"),
    197: ("connectivity", "Bluetooth/Wi-Fi behavior"),
    198: ("icloud_backup", "iCloud backup restoration"),
    199: ("connectivity", "Wi-Fi/Bluetooth control behavior"),
}

for index, (intent, notes) in labels_170_199.items():
    golden_set.loc[index, "intent"] = intent
    golden_set.loc[index, "notes"] = notes

golden_set.to_csv(golden_path, index=False)

labelled_count = (
    golden_set["intent"]
    .fillna("")
    .astype(str)
    .str.strip()
    .ne("")
    .sum()
)

print(f"Saved labels for rows 170–199.")
print(f"Total labelled: {labelled_count}/200")

Saved labels for rows 170–199.
Total labelled: 200/200

In [46]:
# Audit the completed 200-example golden set to verify labels and inspect the intent distribution before model training.

valid_intents = set(intent_definitions.keys())

label_counts = (
    golden_set["intent"]
    .fillna("")
    .astype(str)
    .str.strip()
    .value_counts()
)

invalid_labels = sorted(
    set(label_counts.index) - valid_intents - {""}
)

missing_labels = sorted(
    valid_intents - set(label_counts.index)
)

unlabelled_count = (
    golden_set["intent"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

print("Total examples:", len(golden_set))
print("Unlabelled:", unlabelled_count)
print("Invalid labels:", invalid_labels)

print("\nIntent distribution:")
display(label_counts.to_frame("count"))

print("\nIntents with zero examples:")
print(missing_labels)

Total examples: 200
Unlabelled: 0
Invalid labels: []

Intent distribution:

                        count
intent
display_input              35
apple_services             25
connectivity               21
apps_app_store             20
battery_charging           19
account_authentication     18
device_hardware            15
ios_update                 13
audio                      12
camera_photos              11
icloud_backup               6
other_unclear               5

Intents with zero examples:
[]

In [47]:
# Create a training pool by excluding the 200 golden evaluation examples, preventing evaluation leakage.

golden_ids = set(golden_set["customer_tweet_id"].astype(str))

training_pool = clean_apple[
    ~clean_apple["customer_tweet_id"].astype(str).isin(golden_ids)
].copy()

print("Clean AppleSupport interactions:", len(clean_apple))
print("Golden evaluation examples:", len(golden_set))
print("Training pool:", len(training_pool))
print("Golden IDs found in training pool:", 
      training_pool["customer_tweet_id"].astype(str).isin(golden_ids).sum())

Clean AppleSupport interactions: 106523
Golden evaluation examples: 200
Training pool: 106323
Golden IDs found in training pool: 0

In [48]:
# Prepare the reviewed golden examples as a labelled seed set for building the initial intent classifier.

seed_data = golden_set[
    ["customer_tweet_id", "customer_message", "previous_message", "intent"]
].copy()

seed_data["customer_message"] = (
    seed_data["customer_message"]
    .fillna("")
    .astype(str)
    .str.strip()
)

seed_data["previous_message"] = (
    seed_data["previous_message"]
    .fillna("")
    .astype(str)
    .str.strip()
)

seed_data["intent"] = (
    seed_data["intent"]
    .fillna("")
    .astype(str)
    .str.strip()
)

print("Seed examples:", len(seed_data))
print("Unique intents:", seed_data["intent"].nunique())
print("\nSeed distribution:")
display(seed_data["intent"].value_counts().to_frame("count"))

Seed examples: 200
Unique intents: 12

Seed distribution:

                        count
intent
display_input              35
apple_services             25
connectivity               21
apps_app_store             20
battery_charging           19
account_authentication     18
device_hardware            15
ios_update                 13
audio                      12
camera_photos              11
icloud_backup               6
other_unclear               5

In [49]:
# Sample 10,000 non-golden AppleSupport interactions as the candidate pool for training-label generation.

training_candidates = (
    training_pool[
        [
            "customer_tweet_id",
            "customer_message",
            "previous_message",
            "has_context",
        ]
    ]
    .sample(
        n=10_000,
        random_state=2026,
    )
    .reset_index(drop=True)
)

training_candidates_path = (
    Path("../data/processed") /
    "apple_support_training_candidates.csv"
)

training_candidates.to_csv(
    training_candidates_path,
    index=False,
)

print("Created:", training_candidates_path)
print("Shape:", training_candidates.shape)
print("Golden examples excluded:", 
      training_candidates["customer_tweet_id"]
      .astype(str)
      .isin(golden_ids)
      .sum())

Created: ..\data\processed\apple_support_training_candidates.csv
Shape: (10000, 4)
Golden examples excluded: 0

In [50]:
# Create concise semantic descriptions for the 12 intents so the labelling step has consistent intent definitions.

intent_descriptions = {
    "ios_update": (
        "Problems or questions about iOS software updates, "
        "including update failures, installation problems, update bugs, "
        "or behavior caused specifically by an iOS version."
    ),
    "battery_charging": (
        "Battery drain, poor battery life, battery health, charging problems, "
        "charging speed, or unexpected battery percentage changes."
    ),
    "connectivity": (
        "Wi-Fi, cellular/mobile data, Bluetooth, AirDrop, CarPlay, "
        "calls, or other device connection and network problems."
    ),
    "account_authentication": (
        "Apple ID, iCloud login, passwords, authentication, account recovery, "
        "account access, subscriptions, billing, or account-related security."
    ),
    "icloud_backup": (
        "iCloud backup, iCloud storage, restoring from backup, "
        "iCloud Photos, missing synced data, or iCloud data synchronization."
    ),
    "apps_app_store": (
        "Problems with applications, App Store, downloading or updating apps, "
        "app crashes, app behavior, or application functionality."
    ),
    "audio": (
        "Speaker, microphone, headphones, AirPods, ringtone, volume, "
        "call audio, or other sound-related problems."
    ),
    "camera_photos": (
        "Camera problems, taking photos or videos, camera crashes, "
        "photo library problems, missing photos, or photo-related functionality."
    ),
    "display_input": (
        "Screen, display, touchscreen, keyboard, typing, autocorrect, "
        "buttons, visual glitches, or other user-interface/input problems."
    ),
    "apple_services": (
        "Problems with Apple services such as Apple Music, Siri, Maps, "
        "iMessage, FaceTime, Apple TV, Safari, or other Apple services."
    ),
    "device_hardware": (
        "Physical device problems, unexpected device restarts or crashes, "
        "Apple Watch device issues, storage/device-level failures, "
        "or hardware problems that do not fit a more specific intent."
    ),
    "other_unclear": (
        "Messages that are too vague, unrelated, lack enough information, "
        "or cannot be confidently assigned to another intent."
    ),
}

print("Intent descriptions prepared:", len(intent_descriptions))
print("\n" + "\n".join(
    f"{i}. {intent}: {description}"
    for i, (intent, description) in enumerate(intent_descriptions.items(), 1)
))

Intent descriptions prepared: 12

1. ios_update: Problems or questions about iOS software updates, including update failures, installation problems, update bugs, or behavior caused specifically by an iOS version.
2. battery_charging: Battery drain, poor battery life, battery health, charging problems, charging speed, or unexpected battery percentage changes.
3. connectivity: Wi-Fi, cellular/mobile data, Bluetooth, AirDrop, CarPlay, calls, or other device connection and network problems.
4. account_authentication: Apple ID, iCloud login, passwords, authentication, account recovery, account access, subscriptions, billing, or account-related security.
5. icloud_backup: iCloud backup, iCloud storage, restoring from backup, iCloud Photos, missing synced data, or iCloud data synchronization.
6. apps_app_store: Problems with applications, App Store, downloading or updating apps, app crashes, app behavior, or application functionality.
7. audio: Speaker, microphone, headphones, AirPods, ringtone, volume, call audio, or other sound-related problems.
8. camera_photos: Camera problems, taking photos or videos, camera crashes, photo library problems, missing photos, or photo-related functionality.
9. display_input: Screen, display, touchscreen, keyboard, typing, autocorrect, buttons, visual glitches, or other user-interface/input problems.
10. apple_services: Problems with Apple services such as Apple Music, Siri, Maps, iMessage, FaceTime, Apple TV, Safari, or other Apple services.
11. device_hardware: Physical device problems, unexpected device restarts or crashes, Apple Watch device issues, storage/device-level failures, or hardware problems that do not fit a more specific intent.
12. other_unclear: Messages that are too vague, unrelated, lack enough information, or cannot be confidently assigned to another intent.

In [51]:
# Verify the active notebook environment and confirm sentence-transformers is available.

import sys
import sentence_transformers

print("Python:", sys.executable)
print("sentence-transformers:", sentence_transformers.__version__)

Python: c:\Projects\hiver-support-agent\.venv\Scripts\python.exe
sentence-transformers: 6.0.1

In [52]:
# Load the embedding model once; we will reuse it for the seed examples and training candidates.

from sentence_transformers import SentenceTransformer
import numpy as np

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model loaded successfully.

In [53]:
# Convert the 200 reviewed customer messages into semantic embeddings for similarity-based labelling.

seed_texts = seed_data["customer_message"].tolist()

seed_embeddings = embedding_model.encode(
    seed_texts,
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True,
)

seed_embeddings = np.asarray(seed_embeddings)

print("Seed embeddings shape:", seed_embeddings.shape)
print("Number of seed examples:", len(seed_embeddings))

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Seed embeddings shape: (200, 384)
Number of seed examples: 200

In [54]:
# Test semantic nearest-neighbor labelling on 20 training candidates before processing the full training pool.

from sklearn.metrics.pairwise import cosine_similarity

test_candidates = training_candidates.sample(
    n=20,
    random_state=2026
).reset_index(drop=True)

test_embeddings = embedding_model.encode(
    test_candidates["customer_message"].tolist(),
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True,
)

similarity_matrix = cosine_similarity(
    test_embeddings,
    seed_embeddings
)

nearest_indices = similarity_matrix.argmax(axis=1)
nearest_scores = similarity_matrix.max(axis=1)

test_results = test_candidates[
    ["customer_tweet_id", "customer_message"]
].copy()

test_results["predicted_intent"] = [
    seed_data.iloc[i]["intent"]
    for i in nearest_indices
]

test_results["similarity"] = nearest_scores

test_results["nearest_seed_message"] = [
    seed_data.iloc[i]["customer_message"]
    for i in nearest_indices
]

display(test_results)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

,customer_tweet_id,customer_message,predicted_intent,similarity,nearest_seed_message
0,998063.0,@AppleSupport my battery life is crazy don’t l...,battery_charging,0.700269,@AppleSupport my battery life has drastically ...
1,1395729.0,@AppleSupport I’m so sorry........ I can’t mee...,other_unclear,0.581353,@AppleSupport will you guys plz reply?
2,567644.0,@AppleSupport Power adapter and it doesn’t cha...,battery_charging,0.539580,@AppleSupport ios11.0.03 is a nightmare. Phone...
3,2594410.0,@AppleSupport apple music,apple_services,0.772939,@AppleSupport I have an issue with my Apple Mu...
4,402246.0,Yo @AppleSupport 11.0.2 is fucking shocking. L...,battery_charging,0.672495,@115858 @AppleSupport Please fix battery issue...
5,486097.0,@AppleSupport Thank you for your response. App...,device_hardware,0.473305,@AppleSupport watch app showing incorrect time...
6,1849007.0,@AppleSupport Hi! Back in December I had my 6s...,battery_charging,0.577854,@AppleSupport my iPhone 7 under warranty has a...
7,2078369.0,@AppleSupport Yes! It’s continued after restart,apple_services,0.734374,@379507 @AppleSupport Having the same issue.
8,906420.0,@115858 really? Ive not had one thing wrong wi...,connectivity,0.744953,Completely fed up with bluetooth issues in iOS...
9,2381362.0,@AppleSupport how can I check health of my iPh...,battery_charging,0.751610,"@AppleSupport Hey Apple, can you check my batt..."
10,2674193.0,WHY @AppleSupport https://t.co/LJWeCyBAna,device_hardware,0.680586,@AppleSupport @AppleSupport ^^check this out
11,1906653.0,@AppleSupport this is my Lock Screen showing n...,ios_update,0.671456,@AppleSupport if you guys don’t fix iOS 11.0.3...
12,1419676.0,@AppleSupport is there a way to disable one-ha...,display_input,0.463396,@AppleSupport why is my keyboard like this??? ...
13,2573911.0,my phone is so destroyed it dies WHILE it's pl...,battery_charging,0.577699,@115858 hey sooo um....y’all going to fix this...
14,2957100.0,"Fix the “I.t” problem, please. @115858",display_input,0.638808,Sooo @917 you gonna fix your app??? And @11585...
15,2064980.0,IOS 11 you have well a truly fucked my phone 😭...,battery_charging,0.753498,@AppleSupport ios11.0.03 is a nightmare. Phone...
16,308577.0,@AppleSupport @189687 My phone shuts off rando...,camera_photos,0.648850,@AppleSupport Using an iPhone 7 with iOS 11.0....
17,321783.0,@AppleSupport Sent. I am hopeful a new update ...,other_unclear,0.769484,@AppleSupport nothing but problems since I dow...
18,2837094.0,@115858 High Sierra SUCKS!!! It’s some 💩💩💩 It ...,display_input,0.521649,@115858 fix this I️ shit thanks
19,2690869.0,When @115858 puts out an update to “fix the bu...,other_unclear,0.735600,So @115858 is really about to have me become a...

In [55]:
# Build one semantic prototype for each intent by averaging the embeddings of its reviewed examples.

from sklearn.preprocessing import normalize

intent_prototypes = {}

for intent in seed_data["intent"].unique():
    intent_indices = seed_data.index[
        seed_data["intent"] == intent
    ].to_numpy()

    intent_vectors = seed_embeddings[intent_indices]

    prototype = intent_vectors.mean(axis=0)
    prototype = prototype / np.linalg.norm(prototype)

    intent_prototypes[intent] = prototype

prototype_matrix = np.vstack([
    intent_prototypes[intent]
    for intent in intent_descriptions.keys()
])

print("Prototype matrix shape:", prototype_matrix.shape)
print("Number of intent prototypes:", len(intent_prototypes))

Prototype matrix shape: (12, 384)
Number of intent prototypes: 12

In [56]:
# Test prototype-based intent prediction on the same 20 candidates and inspect confidence scores.

prototype_similarity = cosine_similarity(
    test_embeddings,
    prototype_matrix
)

prototype_indices = prototype_similarity.argmax(axis=1)
prototype_scores = prototype_similarity.max(axis=1)

prototype_results = test_candidates[
    ["customer_tweet_id", "customer_message"]
].copy()

prototype_results["predicted_intent"] = [
    list(intent_descriptions.keys())[i]
    for i in prototype_indices
]

prototype_results["similarity"] = prototype_scores

display(prototype_results)

,customer_tweet_id,customer_message,predicted_intent,similarity
0,998063.0,@AppleSupport my battery life is crazy don’t l...,battery_charging,0.701821
1,1395729.0,@AppleSupport I’m so sorry........ I can’t mee...,other_unclear,0.553605
2,567644.0,@AppleSupport Power adapter and it doesn’t cha...,battery_charging,0.483301
3,2594410.0,@AppleSupport apple music,apple_services,0.660777
4,402246.0,Yo @AppleSupport 11.0.2 is fucking shocking. L...,ios_update,0.698337
5,486097.0,@AppleSupport Thank you for your response. App...,device_hardware,0.298360
6,1849007.0,@AppleSupport Hi! Back in December I had my 6s...,battery_charging,0.439491
7,2078369.0,@AppleSupport Yes! It’s continued after restart,other_unclear,0.674917
8,906420.0,@115858 really? Ive not had one thing wrong wi...,ios_update,0.784906
9,2381362.0,@AppleSupport how can I check health of my iPh...,battery_charging,0.665619
10,2674193.0,WHY @AppleSupport https://t.co/LJWeCyBAna,other_unclear,0.658498
11,1906653.0,@AppleSupport this is my Lock Screen showing n...,battery_charging,0.651828
12,1419676.0,@AppleSupport is there a way to disable one-ha...,display_input,0.379726
13,2573911.0,my phone is so destroyed it dies WHILE it's pl...,battery_charging,0.545424
14,2957100.0,"Fix the “I.t” problem, please. @115858",display_input,0.622155
15,2064980.0,IOS 11 you have well a truly fucked my phone 😭...,ios_update,0.784205
16,308577.0,@AppleSupport @189687 My phone shuts off rando...,camera_photos,0.743801
17,321783.0,@AppleSupport Sent. I am hopeful a new update ...,ios_update,0.797059
18,2837094.0,@115858 High Sierra SUCKS!!! It’s some 💩💩💩 It ...,apple_services,0.567826
19,2690869.0,When @115858 puts out an update to “fix the bu...,ios_update,0.679494

In [57]:
# Train a simple TF-IDF + Logistic Regression intent classifier using the 200 reviewed examples.

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

tfidf_vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    min_df=1,
    max_df=0.95,
    sublinear_tf=True,
)

X_seed = tfidf_vectorizer.fit_transform(
    seed_data["customer_message"]
)

y_seed = seed_data["intent"]

tfidf_classifier = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    random_state=2026,
)

tfidf_classifier.fit(X_seed, y_seed)

print("TF-IDF matrix shape:", X_seed.shape)
print("Classifier trained.")
print("Number of classes:", len(tfidf_classifier.classes_))

TF-IDF matrix shape: (200, 4186)
Classifier trained.
Number of classes: 12

In [58]:
# Evaluate the TF-IDF baseline with stratified 5-fold cross-validation to estimate performance on unseen labelled examples.

from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=2026,
)

cv_scores = cross_val_score(
    tfidf_classifier,
    X_seed,
    y_seed,
    cv=cv,
    scoring="accuracy",
)

print("5-fold accuracy scores:")
print(np.round(cv_scores, 4))

print("\nMean accuracy:", round(cv_scores.mean(), 4))
print("Standard deviation:", round(cv_scores.std(), 4))

5-fold accuracy scores:
[0.475 0.4   0.525 0.525 0.425]

Mean accuracy: 0.47
Standard deviation: 0.051

In [59]:
# Measure TF-IDF confidence on the 10,000 training candidates so we can choose a conservative pseudo-labelling threshold.

candidate_tfidf = tfidf_vectorizer.transform(
    training_candidates["customer_message"]
)

candidate_probabilities = tfidf_classifier.predict_proba(
    candidate_tfidf
)

candidate_predictions = tfidf_classifier.classes_[
    candidate_probabilities.argmax(axis=1)
]

candidate_confidence = candidate_probabilities.max(axis=1)

confidence_summary = pd.Series(candidate_confidence).describe(
    percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]
)

print(confidence_summary)

count    10000.000000
mean         0.115819
std          0.018949
min          0.089395
50%          0.110216
75%          0.123120
90%          0.140886
95%          0.151948
99%          0.176633
max          0.264279
dtype: float64

In [60]:
# Check whether the Transformers library is already available before installing another dependency.

import transformers

print("Transformers:", transformers.__version__)

Transformers: 5.17.0

In [61]:
# Embed the 10,000 training candidates once so we can compare them against all 12 intent prototypes.

candidate_embeddings = embedding_model.encode(
    training_candidates["customer_message"].tolist(),
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True,
)

candidate_embeddings = np.asarray(candidate_embeddings)

print("Candidate embeddings shape:", candidate_embeddings.shape)

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Candidate embeddings shape: (10000, 384)

In [62]:
# Compare every candidate against all 12 intent prototypes and calculate a margin-based confidence score.

intent_names = list(intent_descriptions.keys())

candidate_similarities = candidate_embeddings @ prototype_matrix.T

best_indices = candidate_similarities.argmax(axis=1)
best_scores = candidate_similarities.max(axis=1)

sorted_scores = np.sort(candidate_similarities, axis=1)

second_best_scores = sorted_scores[:, -2]
confidence_margin = best_scores - second_best_scores

pseudo_labels = [
    intent_names[i]
    for i in best_indices
]

pseudo_results = training_candidates.copy()

pseudo_results["pseudo_intent"] = pseudo_labels
pseudo_results["similarity"] = best_scores
pseudo_results["margin"] = confidence_margin

print("Candidates:", len(pseudo_results))
print("Average best similarity:", round(best_scores.mean(), 4))
print("Average margin:", round(confidence_margin.mean(), 4))

display(
    pseudo_results[
        ["customer_message", "pseudo_intent", "similarity", "margin"]
    ].head(20)
)

Candidates: 10000
Average best similarity: 0.6038
Average margin: 0.0662

,customer_message,pseudo_intent,similarity,margin
0,@115948 @AppleSupport how do I delete extra ra...,apple_services,0.504883,0.058709
1,@AppleSupport what’s up with the “I️” being di...,display_input,0.512001,0.133229
2,@AppleSupport My timeline is still back to front.,other_unclear,0.557768,0.048879
3,Help us please @AppleSupport https://t.co/wJkS...,other_unclear,0.642561,0.069720
4,Why are my i’s showing up weird on my phone 🙄@...,display_input,0.615871,0.084349
5,@AppleSupport Why does this keep showing up on...,ios_update,0.553070,0.021932
6,none of my apps wont update @115858 you’re ugl...,ios_update,0.653010,0.086485
7,@AppleSupport neither my Iphone 8 plus or X sc...,audio,0.610445,0.138225
8,@81400 @115858 This is bullshittttttttt. I upd...,display_input,0.682019,0.075140
9,"@AppleSupport call someone, set phone on speak...",audio,0.558142,0.077695
10,@AppleSupport 11.1.1,other_unclear,0.630174,0.019537
11,@AppleSupport @115948 WHAT THE FUCK is this i️...,other_unclear,0.742012,0.017022
12,@AppleSupport i can’t download any apps fix yo...,apps_app_store,0.802265,0.098295
13,@AppleSupport can you do something to fix batt...,battery_charging,0.686702,0.068072
14,@115858 my icloud fucc’d up. send help.,account_authentication,0.704060,0.070855
15,"Mr. @116333 and @115858, I'm not sure what you...",ios_update,0.641858,0.074132
16,"@AppleSupport Got it, thank you!",other_unclear,0.643252,0.066725
17,#ios11 @115858 what’s the point in a control ...,connectivity,0.594015,0.149393
18,@287473 @AppleSupport @115858 Coincidence!? Lo...,other_unclear,0.684153,0.064423
19,@115858 iOS 11 has effed up my iPhone and iPad...,ios_update,0.675207,0.136534

In [63]:
# Save the 200 reviewed examples separately as the initial labelled seed dataset for model development.

seed_path = Path("../data/processed/apple_support_seed_200.csv")

seed_data.to_csv(
    seed_path,
    index=False,
)

print("Created:", seed_path)
print("Seed examples:", len(seed_data))

Created: ..\data\processed\apple_support_seed_200.csv
Seed examples: 200

In [64]:
# Create 300 diverse training examples for manual labeling.
# These are sampled from the training pool and exclude the existing 200 seed examples.
from pathlib import Path
import pandas as pd
import re

# Start from examples not already used in the seed set.
seed_ids = set(seed_data["customer_tweet_id"].astype(str))

review_pool = training_pool[
    ~training_pool["customer_tweet_id"].astype(str).isin(seed_ids)
].copy()

# Broad signals are used ONLY to improve sampling diversity.
# They are not used as intent labels.
signal_patterns = {
    "ios_update": r"\b(update|updat|ios\s*\d|upgrade|install.*ios)\b",
    "battery_charging": r"\b(battery|charging|charge|charger|power)\b",
    "connectivity": r"\b(wifi|wi-fi|bluetooth|airdrop|cellular|network|internet|signal)\b",
    "account_authentication": r"\b(apple\s*id|password|login|log\s*in|account|authentication|verification)\b",
    "icloud_backup": r"\b(icloud|backup|sync|storage)\b",
    "apps_app_store": r"\b(app\s*store|apps?|application|download|install|crash|update.*app)\b",
    "audio": r"\b(audio|sound|speaker|microphone|mic|volume|headphone|airpods|call)\b",
    "camera_photos": r"\b(camera|photo|photos|picture|video|gallery)\b",
    "display_input": r"\b(screen|display|touch|keyboard|typing|keypad|brightness)\b",
    "apple_services": r"\b(apple\s*music|itunes|imessage|facetime|maps|siri)\b",
}

# Add sampling-only signal columns.
text_for_sampling = (
    review_pool["customer_message"]
    .fillna("")
    .astype(str)
    .str.lower()
)

for signal_name, pattern in signal_patterns.items():
    review_pool[f"{signal_name}_signal"] = text_for_sampling.str.contains(
        pattern,
        regex=True,
        na=False
    )

# Take a balanced number from each broad signal.
# Overlapping examples are allowed, so we deduplicate afterward.
signal_samples = []

for signal_name in signal_patterns:
    matching = review_pool[review_pool[f"{signal_name}_signal"]]

    if len(matching) > 30:
        matching = matching.sample(n=30, random_state=2026)
    else:
        matching = matching.sample(frac=1, random_state=2026)

    signal_samples.append(matching)

diverse_review = pd.concat(signal_samples, ignore_index=False)
diverse_review = diverse_review[~diverse_review.index.duplicated(keep="first")]

# Fill any remaining slots with random examples.
remaining_needed = 300 - len(diverse_review)

if remaining_needed > 0:
    remaining_pool = review_pool.drop(index=diverse_review.index)

    random_fill = remaining_pool.sample(
        n=min(remaining_needed, len(remaining_pool)),
        random_state=2027
    )

    diverse_review = pd.concat(
        [diverse_review, random_fill],
        ignore_index=False
    )

# Final shuffle.
diverse_review = diverse_review.sample(
    n=min(300, len(diverse_review)),
    random_state=2028
).reset_index(drop=True)

# Keep only the columns needed for manual labeling.
training_review_300 = diverse_review[
    [
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "has_context"
    ]
].copy()

# Empty columns for manual labels and notes.
training_review_300["intent"] = ""
training_review_300["notes"] = ""

# Save the new review file.
training_review_path = Path("../data/processed/apple_support_training_review_300.csv")
training_review_300.to_csv(training_review_path, index=False)

print("Created:", training_review_path)
print("Training review examples:", len(training_review_300))
print("Existing seed examples:", len(seed_data))
print("Total after labeling:", len(seed_data) + len(training_review_300))

C:\Users\P NIKHIL\AppData\Local\Temp\ipykernel_2892\4286577872.py:38: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  review_pool[f"{signal_name}_signal"] = text_for_sampling.str.contains(

Created: ..\data\processed\apple_support_training_review_300.csv
Training review examples: 300
Existing seed examples: 200
Total after labeling: 500

In [66]:
# Freshly prepare the original 200 reviewed examples for model training.
# We intentionally use only golden_set and ignore the additional 300 examples.

import pandas as pd
from sklearn.model_selection import StratifiedKFold

# Use ONLY the original 200 reviewed examples.
model_data = golden_set[
    [
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "has_context",
        "intent"
    ]
].copy()

# Build the text used by the classifier.
# Include previous context only when it actually exists.
def build_model_text(row):
    customer = str(row["customer_message"]).strip()
    previous = str(row["previous_message"]).strip()

    if row["has_context"] and previous:
        return f"Previous message: {previous} Customer message: {customer}"

    return customer

model_data["model_text"] = model_data.apply(
    build_model_text,
    axis=1
)

# Validate that this is exactly the intended 200-row dataset.
print("Rows:", len(model_data))
print("Unique tweet IDs:", model_data["customer_tweet_id"].nunique())
print("Unique intents:", model_data["intent"].nunique())
print("Missing labels:", model_data["intent"].isna().sum())

print("\nIntent distribution:")
print(
    model_data["intent"]
    .value_counts()
    .sort_index()
)

# Prepare features and labels.
X_text = model_data["model_text"]
y = model_data["intent"]

# Same folds will be used for every classifier so the comparison is fair.
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=2026
)

print("\nPrepared 200 examples for 5-fold stratified cross-validation.")

Rows: 200
Unique tweet IDs: 200
Unique intents: 12
Missing labels: 0

Intent distribution:
intent
account_authentication    18
apple_services            25
apps_app_store            20
audio                     12
battery_charging          19
camera_photos             11
connectivity              21
device_hardware           15
display_input             35
icloud_backup              6
ios_update                13
other_unclear              5
Name: count, dtype: int64

Prepared 200 examples for 5-fold stratified cross-validation.

In [67]:
# Benchmark multiple intent-classification algorithms on the same 200 reviewed examples.
# Cross-validation prevents us from judging the models only on data they trained on.

import numpy as np
import pandas as pd

from sklearn.dummy import DummyClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import ComplementNB
from sklearn.metrics import accuracy_score, f1_score

# Define the models.
# TF-IDF is fitted separately inside each CV fold to avoid data leakage.
models = {
    "Majority Baseline": Pipeline([
        ("tfidf", TfidfVectorizer(
            lowercase=True,
            ngram_range=(1, 2),
            min_df=1,
            max_df=0.95,
            sublinear_tf=True
        )),
        ("classifier", DummyClassifier(
            strategy="most_frequent"
        ))
    ]),

    "TF-IDF + Logistic Regression": Pipeline([
        ("tfidf", TfidfVectorizer(
            lowercase=True,
            ngram_range=(1, 2),
            min_df=1,
            max_df=0.95,
            sublinear_tf=True
        )),
        ("classifier", LogisticRegression(
            max_iter=3000,
            class_weight="balanced",
            random_state=2026
        ))
    ]),

    "TF-IDF + Linear SVM": Pipeline([
        ("tfidf", TfidfVectorizer(
            lowercase=True,
            ngram_range=(1, 2),
            min_df=1,
            max_df=0.95,
            sublinear_tf=True
        )),
        ("classifier", LinearSVC(
            class_weight="balanced",
            random_state=2026
        ))
    ]),

    "TF-IDF + Complement NB": Pipeline([
        ("tfidf", TfidfVectorizer(
            lowercase=True,
            ngram_range=(1, 2),
            min_df=1,
            max_df=0.95,
            sublinear_tf=True
        )),
        ("classifier", ComplementNB())
    ])
}

results = []

# Evaluate every model using identical CV splits.
for model_name, model in models.items():

    fold_accuracies = []
    fold_macro_f1 = []
    fold_weighted_f1 = []

    for train_idx, test_idx in cv.split(X_text, y):

        X_train = X_text.iloc[train_idx]
        X_test = X_text.iloc[test_idx]

        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]

        model.fit(X_train, y_train)
        predictions = model.predict(X_test)

        fold_accuracies.append(
            accuracy_score(y_test, predictions)
        )

        fold_macro_f1.append(
            f1_score(
                y_test,
                predictions,
                average="macro",
                zero_division=0
            )
        )

        fold_weighted_f1.append(
            f1_score(
                y_test,
                predictions,
                average="weighted",
                zero_division=0
            )
        )

    results.append({
        "Model": model_name,
        "Accuracy": np.mean(fold_accuracies),
        "Accuracy Std": np.std(fold_accuracies),
        "Macro F1": np.mean(fold_macro_f1),
        "Macro F1 Std": np.std(fold_macro_f1),
        "Weighted F1": np.mean(fold_weighted_f1),
        "Weighted F1 Std": np.std(fold_weighted_f1)
    })

# Display results from strongest to weakest Macro F1.
benchmark_results = (
    pd.DataFrame(results)
    .sort_values("Macro F1", ascending=False)
    .reset_index(drop=True)
)

print("5-Fold Cross-Validation Results")
print("=" * 80)

display(
    benchmark_results.style.format({
        "Accuracy": "{:.3f}",
        "Accuracy Std": "{:.3f}",
        "Macro F1": "{:.3f}",
        "Macro F1 Std": "{:.3f}",
        "Weighted F1": "{:.3f}",
        "Weighted F1 Std": "{:.3f}"
    })
)

5-Fold Cross-Validation Results
================================================================================

In [68]:
# Evaluate the Linear SVM per intent using out-of-fold predictions.
# This shows which intents are easy, which overlap, and where the taxonomy/model needs work.

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, confusion_matrix

svm_model = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        ngram_range=(1, 2),
        min_df=1,
        max_df=0.95,
        sublinear_tf=True
    )),
    ("classifier", LinearSVC(
        class_weight="balanced",
        random_state=2026
    ))
])

# Store predictions from every held-out fold.
y_true_all = []
y_pred_all = []

for train_idx, test_idx in cv.split(X_text, y):

    X_train = X_text.iloc[train_idx]
    X_test = X_text.iloc[test_idx]

    y_train = y.iloc[train_idx]
    y_test = y.iloc[test_idx]

    svm_model.fit(X_train, y_train)
    predictions = svm_model.predict(X_test)

    y_true_all.extend(y_test.tolist())
    y_pred_all.extend(predictions.tolist())

# Generate the per-intent classification report.
report = classification_report(
    y_true_all,
    y_pred_all,
    labels=list(intent_descriptions.keys()),
    output_dict=True,
    zero_division=0
)

per_intent_results = pd.DataFrame(report).T

print("Linear SVM — Out-of-Fold Per-Intent Performance")
print("=" * 70)

display(
    per_intent_results[
        ["precision", "recall", "f1-score", "support"]
    ].style.format({
        "precision": "{:.3f}",
        "recall": "{:.3f}",
        "f1-score": "{:.3f}",
        "support": "{:.0f}"
    })
)

# Build the confusion matrix.
cm = confusion_matrix(
    y_true_all,
    y_pred_all,
    labels=list(intent_descriptions.keys())
)

confusion_df = pd.DataFrame(
    cm,
    index=list(intent_descriptions.keys()),
    columns=list(intent_descriptions.keys())
)

print("\nConfusion Matrix")
display(confusion_df)

Linear SVM — Out-of-Fold Per-Intent Performance
======================================================================

Confusion Matrix

,ios_update,battery_charging,connectivity,account_authentication,icloud_backup,apps_app_store,audio,camera_photos,display_input,apple_services,device_hardware,other_unclear
ios_update,0,2,2,1,0,0,0,0,4,2,1,1
battery_charging,0,16,0,0,0,1,0,0,1,0,1,0
connectivity,2,1,5,0,0,3,0,0,7,3,0,0
account_authentication,0,0,0,12,0,2,0,0,0,3,0,1
icloud_backup,0,0,1,3,0,0,0,0,0,1,1,0
apps_app_store,0,3,1,0,0,13,0,0,1,1,1,0
audio,1,3,1,0,0,1,1,0,3,1,1,0
camera_photos,0,0,0,1,0,0,0,8,1,1,0,0
display_input,3,0,1,1,0,2,1,0,24,1,2,0
apple_services,3,0,2,2,0,2,1,1,5,7,2,0
device_hardware,1,1,0,1,1,2,0,2,1,1,5,0
other_unclear,1,0,1,1,0,1,0,0,1,0,0,0

In [69]:
# Test a stronger SVM representation using both word and character n-grams.
# Character features help with noisy Twitter text, spelling variations, abbreviations,
# product names, and tokens such as "iOS11", "wifi", "bluetooth", etc.

from sklearn.pipeline import FeatureUnion, Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, f1_score
import numpy as np
import pandas as pd

word_features = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    min_df=1,
    max_df=0.95,
    sublinear_tf=True,
    max_features=15000
)

char_features = TfidfVectorizer(
    lowercase=True,
    analyzer="char_wb",
    ngram_range=(3, 5),
    min_df=2,
    sublinear_tf=True,
    max_features=20000
)

word_char_svm = Pipeline([
    (
        "features",
        FeatureUnion([
            ("word", word_features),
            ("char", char_features)
        ])
    ),
    (
        "classifier",
        LinearSVC(
            class_weight="balanced",
            C=1.0,
            random_state=2026
        )
    )
])

results_word_char = []

for train_idx, test_idx in cv.split(X_text, y):

    X_train = X_text.iloc[train_idx]
    X_test = X_text.iloc[test_idx]

    y_train = y.iloc[train_idx]
    y_test = y.iloc[test_idx]

    word_char_svm.fit(X_train, y_train)

    predictions = word_char_svm.predict(X_test)

    results_word_char.append({
        "accuracy": accuracy_score(y_test, predictions),
        "macro_f1": f1_score(
            y_test,
            predictions,
            average="macro",
            zero_division=0
        ),
        "weighted_f1": f1_score(
            y_test,
            predictions,
            average="weighted",
            zero_division=0
        )
    })

word_char_results = pd.DataFrame(results_word_char)

print("Word + Character TF-IDF + Linear SVM")
print("=" * 60)

print(
    f"Accuracy:    {word_char_results['accuracy'].mean():.3f} "
    f"+/- {word_char_results['accuracy'].std():.3f}"
)

print(
    f"Macro F1:    {word_char_results['macro_f1'].mean():.3f} "
    f"+/- {word_char_results['macro_f1'].std():.3f}"
)

print(
    f"Weighted F1:  {word_char_results['weighted_f1'].mean():.3f} "
    f"+/- {word_char_results['weighted_f1'].std():.3f}"
)

Word + Character TF-IDF + Linear SVM
============================================================
Accuracy:    0.500 +/- 0.073
Macro F1:    0.419 +/- 0.076
Weighted F1:  0.466 +/- 0.058

In [70]:
# Evaluate the best Word + Character TF-IDF + SVM model per intent.
# This shows which intents are actually learnable and which ones are being confused.

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import pandas as pd

oof_predictions = np.empty(len(model_data), dtype=object)

for train_idx, test_idx in cv.split(X_text, y):
    X_train = X_text.iloc[train_idx]
    X_test = X_text.iloc[test_idx]
    y_train = y.iloc[train_idx]

    word_char_svm.fit(X_train, y_train)
    oof_predictions[test_idx] = word_char_svm.predict(X_test)

print("Per-intent performance")
print("=" * 70)

report = classification_report(
    y,
    oof_predictions,
    labels=sorted(y.unique()),
    output_dict=True,
    zero_division=0
)

per_intent_results = pd.DataFrame(report).T

print(
    per_intent_results[
        ["precision", "recall", "f1-score", "support"]
    ].round(3)
)

print("\nConfusion Matrix")
print("=" * 70)

labels = sorted(y.unique())

cm = confusion_matrix(
    y,
    oof_predictions,
    labels=labels
)

confusion_df = pd.DataFrame(
    cm,
    index=labels,
    columns=labels
)

print(confusion_df)

Per-intent performance
======================================================================
                        precision  recall  f1-score  support
account_authentication      0.650   0.722     0.684     18.0
apple_services              0.318   0.280     0.298     25.0
apps_app_store              0.583   0.700     0.636     20.0
audio                       0.000   0.000     0.000     12.0
battery_charging            0.762   0.842     0.800     19.0
camera_photos               0.833   0.909     0.870     11.0
connectivity                0.412   0.333     0.368     21.0
device_hardware             0.417   0.333     0.370     15.0
display_input               0.490   0.686     0.571     35.0
icloud_backup               1.000   0.333     0.500      6.0
ios_update                  0.133   0.154     0.143     13.0
other_unclear               0.000   0.000     0.000      5.0
accuracy                    0.500   0.500     0.500      0.5
macro avg                   0.467   0.441     0.437    200.0
weighted avg                0.474   0.500     0.477    200.0

Confusion Matrix
======================================================================
                        account_authentication  apple_services  \
account_authentication                      13               2
apple_services                               1               7
apps_app_store                               0               3
audio                                        0               2
battery_charging                             0               0
camera_photos                                0               1
connectivity                                 0               2
device_hardware                              2               2
display_input                                0               3
icloud_backup                                2               0
ios_update                                   1               0
other_unclear                                1               0

                        apps_app_store  audio  battery_charging  \
account_authentication               1      1                 0
apple_services                       4      1                 0
apps_app_store                      14      0                 1
audio                                0      0                 1
battery_charging                     1      0                16
camera_photos                        0      0                 0
connectivity                         2      0                 1
device_hardware                      0      0                 1
display_input                        0      1                 1
icloud_backup                        1      0                 0
ios_update                           0      0                 0
other_unclear                        1      0                 0

                        camera_photos  connectivity  device_hardware  \
account_authentication              0             0                0
apple_services                      1             4                1
apps_app_store                      0             0                1
audio                               0             1                2
battery_charging                    0             0                1
camera_photos                      10             0                0
connectivity                        0             7                0
device_hardware                     1             1                5
display_input                       0             1                0
icloud_backup                       0             0                1
ios_update                          0             3                1
other_unclear                       0             0                0

                        display_input  icloud_backup  ios_update  \
account_authentication              0              0           0
apple_services                      3              0           3
apps_app_store                      1              0           0
audio                               3              0           2
battery_charging                    1              0           0
camera_photos                       0              0           0
connectivity                        6              0           2
device_hardware                     2              0           1
display_input                      24              0           5
icloud_backup                       0              2           0
ios_update                          6              0           2
other_unclear                       3              0           0

                        other_unclear
account_authentication              1
apple_services                      0
apps_app_store                      0
audio                               1
battery_charging                    0
camera_photos                       0
connectivity                        1
device_hardware                     0
display_input                       0
icloud_backup                       0
ios_update                          0
other_unclear                       0

In [71]:
# Inspect the actual classification mistakes to determine whether errors come from
# model limitations or ambiguous/overlapping intent definitions.

error_analysis = model_data[
    y.to_numpy() != oof_predictions
].copy()

error_analysis["predicted_intent"] = oof_predictions[
    y.to_numpy() != oof_predictions
]

error_analysis["correct"] = False

error_analysis = error_analysis[
    [
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "has_context",
        "intent",
        "predicted_intent"
    ]
].reset_index(drop=True)

print("Total misclassified:", len(error_analysis))
print("\nTop confusion pairs:")
print(
    error_analysis
    .groupby(["intent", "predicted_intent"])
    .size()
    .sort_values(ascending=False)
    .head(20)
)

print("\n" + "=" * 100)
print("MISCLASSIFIED EXAMPLES")
print("=" * 100)

pd.set_option("display.max_colwidth", 200)
display(error_analysis)

Total misclassified: 100

Top confusion pairs:
intent           predicted_intent
connectivity     display_input             6
ios_update       display_input             6
display_input    ios_update                5
apple_services   connectivity              4
                 apps_app_store            4
                 ios_update                3
                 display_input             3
ios_update       connectivity              3
apps_app_store   apple_services            3
other_unclear    display_input             3
display_input    apple_services            3
audio            display_input             3
                 ios_update                2
                 apple_services            2
device_hardware  display_input             2
connectivity     apple_services            2
                 apps_app_store            2
audio            device_hardware           2
device_hardware  account_authentication    2
connectivity     ios_update                2
dtype: int64

====================================================================================================
MISCLASSIFIED EXAMPLES
====================================================================================================

,customer_tweet_id,customer_message,previous_message,has_context,intent,predicted_intent
0,611285.0,Hey @115858 how can Siri really be my personal assistant if it won't integrate into 3rd party apps why can't I have it play Spotify where is the functionality?,NaN,False,apple_services,display_input
1,400853.0,@AppleSupport Was able to help him via iTunes. Still weird the OTA didn’t work,@210813 Let us know if the update has issues through iTunes.,True,ios_update,display_input
2,1099710.0,@379507 @AppleSupport Having the same issue.,"@AppleSupport iOS 11.0.3. 2 different iPhone 7s in my family, multiple iPads too. Enter address in Maps &amp; driving directions fail to load—endless spinner.",True,apple_services,apps_app_store
3,1687712.0,"Good afternoon, @AppleSupport! It’s always some shit with y’all and these iPhone updates, huh? https://t.co/cGR2qXnGNA",NaN,False,ios_update,display_input
4,2119414.0,"So wtf y’all gon do about this I situation, @115858? Cuz I’m sick of sick this damn A n shit. 😒",NaN,False,display_input,apple_services
...,...,...,...,...,...,...
95,1906931.0,@AppleSupport what is going on with the new IOS update??? It’s horrible,NaN,False,ios_update,connectivity
96,1642388.0,@AppleSupport It connects successfully but all apps are not functioning including safari.,@389327 What happens while trying to connect to cellular data? Are you receiving an error message?,True,connectivity,apps_app_store
97,2671.0,@AppleSupport @AppleSupport ^^check this out,@AppleSupport Internal problem. Any suggestions on how to help? Im not paying for a new phone because I didn’t cause the damage.,True,device_hardware,display_input
98,2287872.0,@AppleSupport The “done” button will not let me select my picture. It’s covered in the top right corner of the phone with the battery and wifi icons. It gets stuck and I have to close out the app.,@664705 What's happening when you try to change your profile picture?,True,display_input,battery_charging
99,303138.0,@AppleSupport will you guys plz reply?,NaN,False,other_unclear,display_input

In [72]:
# Train the final intent classifier on all 200 reviewed examples.
# We use the full labeled set now that model selection is complete.

final_intent_model = Pipeline([
    ("features", FeatureUnion([
        ("word", TfidfVectorizer(
            lowercase=True,
            ngram_range=(1, 2),
            min_df=1,
            max_df=0.95,
            sublinear_tf=True,
            max_features=15000
        )),
        ("char", TfidfVectorizer(
            lowercase=True,
            analyzer="char_wb",
            ngram_range=(3, 5),
            min_df=2,
            sublinear_tf=True,
            max_features=20000
        ))
    ])),
    ("classifier", LinearSVC(
        class_weight="balanced",
        C=1.0,
        random_state=2026
    ))
])

final_intent_model.fit(
    model_data["model_text"],
    model_data["intent"]
)

print("Final intent classifier trained.")
print("Training examples:", len(model_data))
print("Intents:", model_data["intent"].nunique())

Final intent classifier trained.
Training examples: 200
Intents: 12

In [73]:
# Build the historical retrieval corpus from AppleSupport interactions.
# We exclude the 200 golden examples so evaluation remains leakage-free.

import pandas as pd

golden_ids = set(
    golden_set["customer_tweet_id"].astype(str)
)

retrieval_corpus = clean_apple[
    ~clean_apple["customer_tweet_id"].astype(str).isin(golden_ids)
].copy()

retrieval_corpus = retrieval_corpus[
    [
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "has_context",
        "brand_response"
    ]
].reset_index(drop=True)

print("Retrieval corpus size:", len(retrieval_corpus))
print("Golden examples excluded:", len(golden_ids))
print("Remaining retrieval examples:", len(retrieval_corpus))
print("\nMissing customer messages:", retrieval_corpus["customer_message"].isna().sum())
print("Missing brand responses:", retrieval_corpus["brand_response"].isna().sum())

Retrieval corpus size: 106323
Golden examples excluded: 200
Remaining retrieval examples: 106323

Missing customer messages: 0
Missing brand responses: 0

In [74]:
# Prepare the text that will be embedded for semantic retrieval.
# We use the customer's support message as the retrieval key to avoid adding
# unnecessary conversational noise.

retrieval_texts = (
    retrieval_corpus["customer_message"]
    .fillna("")
    .astype(str)
    .str.strip()
    .tolist()
)

print("Texts prepared:", len(retrieval_texts))
print("Example:")
print(retrieval_texts[0])

Texts prepared: 106323
Example:
@AppleSupport  https://t.co/NV0yucs0lB

In [75]:
# Embed the historical customer messages for semantic search.
# Normalized embeddings allow cosine similarity to be computed efficiently with FAISS.

retrieval_embeddings = embedding_model.encode(
    retrieval_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

retrieval_embeddings = retrieval_embeddings.astype("float32")

print("\nEmbedding shape:", retrieval_embeddings.shape)
print("Embedding dtype:", retrieval_embeddings.dtype)

Batches:   0%|          | 0/1662 [00:00<?, ?it/s]

Embedding shape: (106323, 384)
Embedding dtype: float32

In [76]:
# Build a FAISS cosine-similarity index over the historical AppleSupport messages.
# Because embeddings are normalized, inner product is equivalent to cosine similarity.

import faiss

embedding_dimension = retrieval_embeddings.shape[1]

retrieval_index = faiss.IndexFlatIP(
    embedding_dimension
)

retrieval_index.add(
    retrieval_embeddings
)

print("FAISS index built.")
print("Indexed examples:", retrieval_index.ntotal)
print("Embedding dimension:", embedding_dimension)

FAISS index built.
Indexed examples: 106323
Embedding dimension: 384

In [77]:
# Retrieve the most similar historical AppleSupport cases for every golden example.
# We use the golden messages only as queries; their own rows are already excluded
# from the retrieval index.

golden_query_texts = (
    golden_set["customer_message"]
    .fillna("")
    .astype(str)
    .str.strip()
    .tolist()
)

golden_query_embeddings = embedding_model.encode(
    golden_query_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
).astype("float32")

top_k = 5

similarity_scores, nearest_indices = retrieval_index.search(
    golden_query_embeddings,
    top_k
)

print("Query embeddings:", golden_query_embeddings.shape)
print("Retrieved results shape:", nearest_indices.shape)
print("Top-k:", top_k)

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Query embeddings: (200, 384)
Retrieved results shape: (200, 5)
Top-k: 5

In [78]:
# Inspect retrieved historical conversations for representative golden examples.
# This helps verify whether semantic similarity corresponds to useful support evidence.

for query_idx in range(min(10, len(golden_set))):
    print("\n" + "=" * 100)
    print(f"GOLDEN EXAMPLE {query_idx}")
    print("=" * 100)

    print("Customer:")
    print(golden_set.iloc[query_idx]["customer_message"])

    print("\nTrue intent:")
    print(golden_set.iloc[query_idx]["intent"])

    print("\nRetrieved historical cases:")

    for rank in range(top_k):
        corpus_idx = nearest_indices[query_idx, rank]
        score = similarity_scores[query_idx, rank]

        row = retrieval_corpus.iloc[corpus_idx]

        print(f"\n--- Rank {rank + 1} | Similarity: {score:.3f} ---")
        print("Historical customer:")
        print(row["customer_message"])
        print("AppleSupport response:")
        print(row["brand_response"])

====================================================================================================
GOLDEN EXAMPLE 0
====================================================================================================
Customer:
Hey @115858 how can Siri really be my personal assistant if it won't integrate into 3rd party apps why can't I have it play Spotify where is the functionality?

True intent:
apple_services

Retrieved historical cases:

--- Rank 1 | Similarity: 0.701 ---
Historical customer:
@AppleSupport Hello, where can i see third party app support by Siri on iOS 11 ? I don't see "app support" like iOS 10...
AppleSupport response:
@261160 Let's look into that. Send us a DM and we'll go from there. https://t.co/GDrqU22YpT

--- Rank 2 | Similarity: 0.670 ---
Historical customer:
@AppleSupport asked Siri to play a song. It’s on my iPhone, why is this happening? https://t.co/lsnj4pUZJd
AppleSupport response:
@186705 Let’s take a look at that together.  Are you subscribed to Apple Music?  Does the song play if you select it from the Music App?

--- Rank 3 | Similarity: 0.669 ---
Historical customer:
@115858 @AppleSupport @115948 bring back music rating already. Siri sucks. I am in the music app. Siri is just fucking stupid. https://t.co/UWyHc7eKAM
AppleSupport response:
@421314 We want Siri working for you properly. Send us a DM and we'll look into this together. https://t.co/GDrqU22YpT

--- Rank 4 | Similarity: 0.667 ---
Historical customer:
@AppleSupport do ya guys know why my google assistant won’t play songs in Apple Music? It says voice actions aren’t available for this app.
AppleSupport response:
@370108 Thanks for reaching out. We can look into this with you. Which device are you using? Please reply in DM. https://t.co/GDrqU22YpT

--- Rank 5 | Similarity: 0.667 ---
Historical customer:
Siri needs to be able to do this or what’s the point? @AppleSupport @33423 https://t.co/HVRuBWgxrv
AppleSupport response:
@556371 We can understand your need for Siri to do this. Meet us in DM so we can review ways to help make this happen next time around. https://t.co/GDrqU22YpT

====================================================================================================
GOLDEN EXAMPLE 1
====================================================================================================
Customer:
@AppleSupport Was able to help him via iTunes. Still weird the OTA didn’t work

True intent:
ios_update

Retrieved historical cases:

--- Rank 1 | Similarity: 0.726 ---
Historical customer:
@AppleSupport The final step to get out make update by #iTunes  to fix #OTA issues
AppleSupport response:
@732656 Yes, were you able to use iTunes on a computer to update the iOS?

--- Rank 2 | Similarity: 0.722 ---
Historical customer:
@AppleSupport Did it through iTunes. Thx
AppleSupport response:
@677842 Sure thing. To help determine the best way to tackle this, can you tell us if you see an error messaging when trying to restore your iPhone?

--- Rank 3 | Similarity: 0.709 ---
Historical customer:
@AppleSupport I've tried iTunes, I've tried everything https://t.co/XdkUGRtzc3
AppleSupport response:
@430735 Thanks for image. Send us a DM, and we'll provide further guidance. https://t.co/GDrqU22YpT

--- Rank 4 | Similarity: 0.688 ---
Historical customer:
@AppleSupport But iTunes isn't working. And this happened earlier this summer and took 48hrs to correct
AppleSupport response:
@580811 What exactly isn't working?  Is your iPhone not seen?  Do you get errors?

--- Rank 5 | Similarity: 0.686 ---
Historical customer:
@AppleSupport @531103 I'm having the same issue and I already tried all those things, I even tried going through itunes and it's still not working
AppleSupport response:
@531105 We'd like to continue working with you on this issue in a DM. Send us one using the link below. https://t.co/GDrqU22YpT

====================================================================================================
GOLDEN EXAMPLE 2
====================================================================================================
Customer:
@379507 @AppleSupport Having the same issue.

True intent:
apple_services

Retrieved historical cases:

--- Rank 1 | Similarity: 0.984 ---
Historical customer:
@473180 @AppleSupport Having the same problem.
AppleSupport response:
@591861 Hey there! Thanks for bringing this to our attention. We'd love to work with you. Please DM us the iOS version installed. https://t.co/GDrqU22YpT

--- Rank 2 | Similarity: 0.979 ---
Historical customer:
@754860 @AppleSupport Got the same problem.
AppleSupport response:
@754861  We'd like to look into this concern with you. Send a DM and we'll continue there. https://t.co/GDrqU22YpT

--- Rank 3 | Similarity: 0.970 ---
Historical customer:
@117639 @AppleSupport Having the same issue
AppleSupport response:
@586934 DM us if you're having issues with your keyboard changing characters. We'll be happy to look into this with you. https://t.co/GDrqU22YpT

--- Rank 4 | Similarity: 0.967 ---
Historical customer:
@705408 @AppleSupport Having EXACTLY the same issue!!
AppleSupport response:
@705594 We'd like to help. We have recieved your DM and will work with you there! https://t.co/GDrqU22YpT

--- Rank 5 | Similarity: 0.962 ---
Historical customer:
@519098 @AppleSupport I'm currently having the same issue
AppleSupport response:
@519099 Hey there. DM the details, we've got your back. We'll meet you there to help out. https://t.co/GDrqU22YpT

====================================================================================================
GOLDEN EXAMPLE 3
====================================================================================================
Customer:
Hey @AppleSupport iOS11 update made my $900 iPad Pro unusable. The battery lasts 1/2 day even if just sitting there in airplane mode. #SUCKS

True intent:
battery_charging

Retrieved historical cases:

--- Rank 1 | Similarity: 0.764 ---
Historical customer:
@115858 @AppleSupport my iPad air 2 used to last it's battery for 3 days and now after the ios 11 update,it lasts lesser than a day 🔌🔋😥
AppleSupport response:
@160148 We'll be happy to look into this with you. If you go to Settings &gt; General &gt; About, and look to Version, are you on 11.0.2?

--- Rank 2 | Similarity: 0.755 ---
Historical customer:
Dear @115858 and @AppleSupport — Battery life *horrible* since upgrade to #iOS11 on my iPad.
AppleSupport response:
@601872 We'd be happy to look this over with you. Please meet us in DM so we may gather information, and better assist. https://t.co/GDrqU22YpT

--- Rank 3 | Similarity: 0.747 ---
Historical customer:
@AppleSupport ever since I upgraded to IOS 11 on my iPad my battery has become horrible, instead of the normal super long battery life I get
AppleSupport response:
@167262 OK, thanks. Let's get to DM to continue. https://t.co/GDrqU22YpT

--- Rank 4 | Similarity: 0.745 ---
Historical customer:
@AppleSupport  Battery life on the iPad Pro sucks!!!!!!!!
AppleSupport response:
@670453 We’d like to understand more about your battery life. Please DM us some details about which apps or features are having issues, tell us which country you're in, and we’ll take it from there. https://t.co/GDrqU22YpT

--- Rank 5 | Similarity: 0.741 ---
Historical customer:
I want to thank @AppleSupport. I bought my #ipadpro in July bc updates slowed my 4. Now, #iOS11 is chewing up my battery. Thx for everything
AppleSupport response:
@190077 Let's have a look at this. Can you please DM us? https://t.co/GDrqU22YpT

====================================================================================================
GOLDEN EXAMPLE 4
====================================================================================================
Customer:
Good afternoon, @AppleSupport! It’s always some shit with y’all and these iPhone updates, huh? https://t.co/cGR2qXnGNA

True intent:
ios_update

Retrieved historical cases:

--- Rank 1 | Similarity: 0.840 ---
Historical customer:
@AppleSupport what’s up with this update for the iPhone? It’s the very worst update I’ve ever done! MY PHONE IS A MESS NOW
AppleSupport response:
@343192 We're glad to work with you on your iPhone issues. DM us the details using the link below. https://t.co/GDrqU22YpT

--- Rank 2 | Similarity: 0.828 ---
Historical customer:
@AppleSupport really need to stop messing around with iPhones your screwing my phone up big time with these updates ????
AppleSupport response:
@173134 Hi there. We'd like to help. Send us a DM and tell us about the issues you're having. https://t.co/GDrqU22YpT

--- Rank 3 | Similarity: 0.822 ---
Historical customer:
@AppleSupport @115858 this #iPhone update totally sucks. I use my phone for work and you have made my day horrible with this. What’s up?!
AppleSupport response:
@302815 What kind of issues have you noticed since updating? DM us with details, and we'll find a solution together. https://t.co/GDrqU22YpT

--- Rank 4 | Similarity: 0.819 ---
Historical customer:
Omg don’t do the new iPhone update! Everything is sloooooooooooooowwwwwww.

What the hell @AppleSupport ?
AppleSupport response:
@204475 Help is here. To begin, which apps are you using when you experience slow responsiveness in iOS 11?

--- Rank 5 | Similarity: 0.818 ---
Historical customer:
.@115858 @AppleSupport one of the worst updates ever - what’s going on with our iPhones???
AppleSupport response:
@323158 We're here for you. What issue does the iPhone experience? Which update did you notice the issue with first?

====================================================================================================
GOLDEN EXAMPLE 5
====================================================================================================
Customer:
@AppleSupport App is shutting down randomly and unexpectedly

True intent:
apps_app_store

Retrieved historical cases:

--- Rank 1 | Similarity: 0.862 ---
Historical customer:
@AppleSupport I have done everything still it is shutting down randomly
AppleSupport response:
@384569 Thanks for verifying. In that case, please reach out to us via DM and we'll get you pointed in the right direction. https://t.co/GDrqU22YpT

--- Rank 2 | Similarity: 0.862 ---
Historical customer:
@AppleSupport Shuts down again. Its consistently done this for around 6-8 months and ive gotten nowhere with it and hope you can help. Thanks
AppleSupport response:
@290073 Thanks for reaching out. Which iPhone model and iOS does this occur on? Let us know in a DM, we're happy to help. https://t.co/GDrqU22YpT

--- Rank 3 | Similarity: 0.862 ---
Historical customer:
@AppleSupport Lots of app crashes
AppleSupport response:
@558293 Thanks for filling us in. Share with us in DM if you've been able to update to the latest version of iOS 11. https://t.co/GDrqU22YpT

--- Rank 4 | Similarity: 0.859 ---
Historical customer:
@AppleSupport apps will randomly shut down, i’ll have to delete and reinstall them, i have to constantly restart my phone for things to work
AppleSupport response:
@526950 Okay. Can you tell us which iOS version you are using please?

--- Rank 5 | Similarity: 0.857 ---
Historical customer:
@AppleSupport Randomly sometimes when I’m in apps it will just stop working
AppleSupport response:
@345243 Thank you for letting us know. Please DM us and we can continue from there. https://t.co/GDrqU22YpT

====================================================================================================
GOLDEN EXAMPLE 6
====================================================================================================
Customer:
Is anyone else having problems downloading and updating apps? Lie your password is right but it’s just not doing it? @AppleSupport

True intent:
apps_app_store

Retrieved historical cases:

--- Rank 1 | Similarity: 0.783 ---
Historical customer:
Anyone else having issues with Apples App Store? I’ve tried signing out and in but still not updating any apps they just keep loading 😭 @AppleSupport
AppleSupport response:
@532636 Let's look at this together! Which software version and device are you using?

--- Rank 2 | Similarity: 0.771 ---
Historical customer:
@AppleSupport I can’t download or update my apps? Help? It’s been like this for a week
AppleSupport response:
@438776 We'll do all we can to assist. What device and what OS/iOS version is it running? Are you getting an error message when you try to update apps?

--- Rank 3 | Similarity: 0.768 ---
Historical customer:
@AppleSupport since updating to the latest ios. I can’t download new apps. It just keeps telling me to enter my password. V frustrating
AppleSupport response:
@529986 We'd be happy to take a look!  To start, does this occur on all devices or just this one?

--- Rank 4 | Similarity: 0.764 ---
Historical customer:
@AppleSupport having problems downloading apps from App Store, what should I do? Username and password is all set it just won’t load 🤔
AppleSupport response:
@501782 We'd be happy to look into this with you. Please DM us so we can gather further details. https://t.co/GDrqU22YpT

--- Rank 5 | Similarity: 0.755 ---
Historical customer:
hey @AppleSupport , i can’t download or update anything trough the appstore, wtf is going on?
AppleSupport response:
@388602 Let's look into this. Does it happen on both Wi-Fi and cellular data?

====================================================================================================
GOLDEN EXAMPLE 7
====================================================================================================
Customer:
So wtf y’all gon do about this I situation, @115858? Cuz I’m sick of sick this damn A n shit. 😒

True intent:
display_input

Retrieved historical cases:

--- Rank 1 | Similarity: 0.810 ---
Historical customer:
I’m so sick of this I️ shit. @115858
AppleSupport response:
@439429 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9

--- Rank 2 | Similarity: 0.809 ---
Historical customer:
Dear @115858 IM SICK OF THIS SHIT 👉🏽 I️ SO WHAT YALL GONE DO?!!
AppleSupport response:
@462527 We can definitely look into this with you. Which device are you using? DM us and let us know. https://t.co/GDrqU22YpT

--- Rank 3 | Similarity: 0.809 ---
Historical customer:
I’m sick of your shit, @115858. I️ I️ I️ I️ I️
AppleSupport response:
@584425 We'd like to look into this issue with you. Please DM us your country and current iOS version and we'll go from there. https://t.co/GDrqU22YpT

--- Rank 4 | Similarity: 0.808 ---
Historical customer:
Ok @115858 wtf, yal gon fix this I️ shit or what? Bc I️ can’t take this shit no more😑😑
AppleSupport response:
@667675 An update has been released to assist with this issue. If you haven’t yet, please back up your device and update it to iOS 11.1.1. For more info, check out: https://t.co/4f8hwT5to6

--- Rank 5 | Similarity: 0.803 ---
Historical customer:
@115858  wat the hell yall? Y’all gon fix this I️ situation orrr?
AppleSupport response:
@513919 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/qODbOsp4wz

====================================================================================================
GOLDEN EXAMPLE 8
====================================================================================================
Customer:
@AppleSupport hey why is the remove episode option gone from the podcast app, subscribed podcasts keep popping up after I delete them

True intent:
apps_app_store

Retrieved historical cases:

--- Rank 1 | Similarity: 0.840 ---
Historical customer:
@AppleSupport this podcast app is the worst. I delete episodes, I even unsubscribe and they appear in my feed again &amp; again. How? Why? Stop?
AppleSupport response:
@515528 We'd like to help. Try these steps and let us know if the issue continues: https://t.co/78Y0jSomPt

--- Rank 2 | Similarity: 0.817 ---
Historical customer:
@AppleSupport @790016 I have the same issue. Unsubscribe from podcast/delete episode and it keeps coming back in my Shows and Downloaded folders. https://t.co/GTy28d5Eok
AppleSupport response:
@689665 Meet up with us in DM so we can check out the issue you are experiencing and see how we can help further. https://t.co/GDrqU22YpT

--- Rank 3 | Similarity: 0.792 ---
Historical customer:
@AppleSupport don’t know what you did when updated podcasts but it sucks. I delete the last episode in my library, I get unsubscribed?
AppleSupport response:
@218781 We'd like to help. Does this issue occur with all Podcasts or a particular Podcast? Let us know in DM. https://t.co/GDrqU22YpT

--- Rank 4 | Similarity: 0.781 ---
Historical customer:
@AppleSupport guys I don’t understand why you’ve removed the “unplayed episodes” section from your podcast app. Please can you restore this as it really improves usability.
AppleSupport response:
@622434 If you would like to see that feature returned in a future update, make your voice heard here: https://t.co/ODFtc9V7Tq

--- Rank 5 | Similarity: 0.777 ---
Historical customer:
@AppleSupport Oops! This was specifically on how to delete podcasts, which is exactly what I don’t want to do!
AppleSupport response:
@387236 We'd like to continue helping. Let's meet in DM. https://t.co/GDrqU22YpT

====================================================================================================
GOLDEN EXAMPLE 9
====================================================================================================
Customer:
@AppleSupport my phone battery has just gone from 50% - 34% in 15 mins???

True intent:
battery_charging

Retrieved historical cases:

--- Rank 1 | Similarity: 0.879 ---
Historical customer:
@AppleSupport Let me explain in detail. My battery went from 100% this morning to only 38% currently. And I just started using my phone 15 minutes ago
AppleSupport response:
@213152 We'd be glad to take a look at the battery usage you're seeing with your iPhone. Which one do you have? https://t.co/GDrqU22YpT

--- Rank 2 | Similarity: 0.858 ---
Historical customer:
My phone battery goes from 97% to 63% in a matter of mins wtff @AppleSupport
AppleSupport response:
@392003 Battery life is important. Which iOS version is your device using? Let us know in DM. https://t.co/GDrqU22YpT

--- Rank 3 | Similarity: 0.848 ---
Historical customer:
Hey @115858 @AppleSupport I don’t think my battery is supposed to go from 100% to 56% in 2 hours. I know my phones old but geez. https://t.co/TozPou0HWA
AppleSupport response:
@470020 We'd love to help with the battery life. Which iPhone do you have and what's the exact iOS version?

--- Rank 4 | Similarity: 0.845 ---
Historical customer:
What’s going on @AppleSupport I’ve been on my phone a whole 21 minutes and lost 12% battery and 3% in one go!! 😣😣 https://t.co/IbUZaT3B7L
AppleSupport response:
@774786 Let's take a closer look with you. Follow up with us in DM. Tell us the version of iOS installed in Settings &gt; General &gt; About there. https://t.co/GDrqU22YpT

--- Rank 5 | Similarity: 0.843 ---
Historical customer:
@AppleSupport my phone lost 70% battery in 4 hours and I didn't touch it once, that's not right
AppleSupport response:
@196416 With concerns due to your battery life have you looked over the steps here? https://t.co/bivpdfBNJ6

In [79]:
# Quantify retrieval quality across the 200 golden queries.
# We measure similarity and use the existing intent classifier only as a diagnostic
# for whether retrieved cases are broadly aligned with the query's intent.

retrieved_intents = []

for query_idx in range(len(golden_set)):
    query_retrieved_intents = []

    for rank in range(top_k):
        corpus_idx = nearest_indices[query_idx, rank]
        historical_text = retrieval_corpus.iloc[corpus_idx]["customer_message"]

        predicted_intent = final_intent_model.predict(
            [historical_text]
        )[0]

        query_retrieved_intents.append(predicted_intent)

    retrieved_intents.append(query_retrieved_intents)

retrieved_intents = np.array(retrieved_intents)

golden_intents = golden_set["intent"].to_numpy()

top1_intent_alignment = (
    retrieved_intents[:, 0] == golden_intents
)

top5_intent_alignment = np.array([
    golden_intents[i] in retrieved_intents[i]
    for i in range(len(golden_intents))
])

retrieval_summary = pd.DataFrame({
    "metric": [
        "Mean top-1 similarity",
        "Median top-1 similarity",
        "Top-1 intent alignment",
        "Top-5 intent alignment"
    ],
    "value": [
        similarity_scores[:, 0].mean(),
        np.median(similarity_scores[:, 0]),
        top1_intent_alignment.mean(),
        top5_intent_alignment.mean()
    ]
})

print(retrieval_summary.round(3))

                    metric  value
0    Mean top-1 similarity  0.809
1  Median top-1 similarity  0.811
2   Top-1 intent alignment  0.820
3   Top-5 intent alignment  0.955

In [80]:
# Create a reusable function that retrieves the most relevant historical
# AppleSupport conversations for a new customer message.

def retrieve_historical_cases(
    customer_message,
    top_k=5
):
    query_embedding = embedding_model.encode(
        [customer_message],
        normalize_embeddings=True
    ).astype("float32")

    scores, indices = retrieval_index.search(
        query_embedding,
        top_k
    )

    results = []

    for rank, (score, corpus_idx) in enumerate(
        zip(scores[0], indices[0]),
        start=1
    ):
        row = retrieval_corpus.iloc[corpus_idx]

        results.append({
            "rank": rank,
            "similarity": float(score),
            "customer_message": row["customer_message"],
            "brand_response": row["brand_response"]
        })

    return results


# Quick sanity check using a real golden example.
test_message = golden_set.iloc[9]["customer_message"]

retrieved_cases = retrieve_historical_cases(
    test_message,
    top_k=5
)

print("Customer:")
print(test_message)

print("\nRetrieved cases:")
for case in retrieved_cases:
    print(
        f"\nRank {case['rank']} "
        f"(similarity={case['similarity']:.3f})"
    )
    print("Customer:", case["customer_message"])
    print("AppleSupport:", case["brand_response"])

Customer:
@AppleSupport my phone battery has just gone from 50% - 34% in 15 mins???

Retrieved cases:

Rank 1 (similarity=0.879)
Customer: @AppleSupport Let me explain in detail. My battery went from 100% this morning to only 38% currently. And I just started using my phone 15 minutes ago
AppleSupport: @213152 We'd be glad to take a look at the battery usage you're seeing with your iPhone. Which one do you have? https://t.co/GDrqU22YpT

Rank 2 (similarity=0.858)
Customer: My phone battery goes from 97% to 63% in a matter of mins wtff @AppleSupport
AppleSupport: @392003 Battery life is important. Which iOS version is your device using? Let us know in DM. https://t.co/GDrqU22YpT

Rank 3 (similarity=0.848)
Customer: Hey @115858 @AppleSupport I don’t think my battery is supposed to go from 100% to 56% in 2 hours. I know my phones old but geez. https://t.co/TozPou0HWA
AppleSupport: @470020 We'd love to help with the battery life. Which iPhone do you have and what's the exact iOS version?

Rank 4 (similarity=0.845)
Customer: What’s going on @AppleSupport I’ve been on my phone a whole 21 minutes and lost 12% battery and 3% in one go!! 😣😣 https://t.co/IbUZaT3B7L
AppleSupport: @774786 Let's take a closer look with you. Follow up with us in DM. Tell us the version of iOS installed in Settings &gt; General &gt; About there. https://t.co/GDrqU22YpT

Rank 5 (similarity=0.843)
Customer: @AppleSupport my phone lost 70% battery in 4 hours and I didn't touch it once, that's not right
AppleSupport: @196416 With concerns due to your battery life have you looked over the steps here? https://t.co/bivpdfBNJ6

In [81]:
# Create a reusable function for predicting the customer's intent.
# The final classifier was trained on all 200 reviewed examples.

def predict_intent(customer_message, previous_message=""):
    customer_message = str(customer_message).strip()
    previous_message = str(previous_message).strip()

    if previous_message:
        model_text = (
            f"Previous message: {previous_message} "
            f"Customer message: {customer_message}"
        )
    else:
        model_text = customer_message

    predicted_intent = final_intent_model.predict(
        [model_text]
    )[0]

    return predicted_intent


# Quick sanity check
test_message = golden_set.iloc[9]["customer_message"]

predicted = predict_intent(test_message)

print("Customer:", test_message)
print("Predicted intent:", predicted)

Customer: @AppleSupport my phone battery has just gone from 50% - 34% in 15 mins???
Predicted intent: battery_charging

In [83]:
# Combine intent classification and historical retrieval into one reusable function.
# This gives the generation layer everything it needs without duplicating model logic.

def analyze_customer_message(
    customer_message,
    previous_message=""
):
    customer_message = str(customer_message).strip()
    previous_message = str(previous_message).strip()

    # Predict the customer's primary intent.
    intent = predict_intent(
        customer_message,
        previous_message
    )

    # Retrieve historically similar AppleSupport cases.
    retrieved_cases = retrieve_historical_cases(
        customer_message,
        top_k=5
    )

    return {
        "customer_message": customer_message,
        "previous_message": previous_message,
        "intent": intent,
        "retrieved_cases": retrieved_cases,
        "top_similarity": retrieved_cases[0]["similarity"]
    }


# Test the complete analysis pipeline.
test_message = golden_set.iloc[9]["customer_message"]

analysis = analyze_customer_message(
    test_message
)

print("Customer:")
print(analysis["customer_message"])

print("\nPredicted intent:")
print(analysis["intent"])

print("\nTop similarity:")
print(f"{analysis['top_similarity']:.3f}")

print("\nHistorical evidence:")
for case in analysis["retrieved_cases"]:
    print(
        f"\n[{case['rank']}] similarity={case['similarity']:.3f}"
    )
    print("Customer:", case["customer_message"])
    print("AppleSupport:", case["brand_response"])

Customer:
@AppleSupport my phone battery has just gone from 50% - 34% in 15 mins???

Predicted intent:
battery_charging

Top similarity:
0.879

Historical evidence:

[1] similarity=0.879
Customer: @AppleSupport Let me explain in detail. My battery went from 100% this morning to only 38% currently. And I just started using my phone 15 minutes ago
AppleSupport: @213152 We'd be glad to take a look at the battery usage you're seeing with your iPhone. Which one do you have? https://t.co/GDrqU22YpT

[2] similarity=0.858
Customer: My phone battery goes from 97% to 63% in a matter of mins wtff @AppleSupport
AppleSupport: @392003 Battery life is important. Which iOS version is your device using? Let us know in DM. https://t.co/GDrqU22YpT

[3] similarity=0.848
Customer: Hey @115858 @AppleSupport I don’t think my battery is supposed to go from 100% to 56% in 2 hours. I know my phones old but geez. https://t.co/TozPou0HWA
AppleSupport: @470020 We'd love to help with the battery life. Which iPhone do you have and what's the exact iOS version?

[4] similarity=0.845
Customer: What’s going on @AppleSupport I’ve been on my phone a whole 21 minutes and lost 12% battery and 3% in one go!! 😣😣 https://t.co/IbUZaT3B7L
AppleSupport: @774786 Let's take a closer look with you. Follow up with us in DM. Tell us the version of iOS installed in Settings &gt; General &gt; About there. https://t.co/GDrqU22YpT

[5] similarity=0.843
Customer: @AppleSupport my phone lost 70% battery in 4 hours and I didn't touch it once, that's not right
AppleSupport: @196416 With concerns due to your battery life have you looked over the steps here? https://t.co/bivpdfBNJ6

In [84]:
# Build a grounded prompt from the customer message, predicted intent, and
# historically retrieved AppleSupport responses.
# The prompt explicitly prevents the LLM from inventing unsupported solutions.

import json


def build_agent_prompt(analysis):
    evidence = []

    for case in analysis["retrieved_cases"]:
        evidence.append({
            "similarity": round(case["similarity"], 3),
            "historical_customer": case["customer_message"],
            "historical_response": case["brand_response"]
        })

    prompt = f"""
You are an AI customer-support agent for AppleSupport.

Your job is to draft a helpful support response based ONLY on:
1. The customer's current message.
2. The predicted support intent.
3. Historical AppleSupport interactions provided as evidence.

Do not invent Apple policies, troubleshooting steps, refunds, guarantees,
product capabilities, or URLs that are not supported by the evidence.

You may synthesize patterns across multiple historical responses.
Do not copy usernames, tweet IDs, or social-media metadata from the evidence.

Customer message:
{analysis["customer_message"]}

Predicted intent:
{analysis["intent"]}

Historical AppleSupport evidence:
{json.dumps(evidence, indent=2)}

Return ONLY valid JSON with this structure:

{{
    "intent": "predicted intent",
    "draft_reply": "A concise customer-facing support response",
    "evidence_used": [
        "Brief description of the historical pattern used"
    ],
    "escalate": true,
    "escalation_reason": "Why a human should or should not handle this case"
}}

Rules for escalation:
- Set escalate=true when the historical evidence suggests moving to DM,
  gathering account/device-specific information, or when the issue cannot
  be safely resolved from the available information.
- Set escalate=false only when the response can reasonably be handled
  using the historical evidence without requiring human intervention.
- Give a specific reason for the decision.

Keep the draft reply concise and natural.
"""

    return prompt


# Test the prompt without calling an LLM.
test_analysis = analyze_customer_message(
    golden_set.iloc[9]["customer_message"]
)

agent_prompt = build_agent_prompt(test_analysis)

print(agent_prompt)

You are an AI customer-support agent for AppleSupport.

Your job is to draft a helpful support response based ONLY on:
1. The customer's current message.
2. The predicted support intent.
3. Historical AppleSupport interactions provided as evidence.

Do not invent Apple policies, troubleshooting steps, refunds, guarantees,
product capabilities, or URLs that are not supported by the evidence.

You may synthesize patterns across multiple historical responses.
Do not copy usernames, tweet IDs, or social-media metadata from the evidence.

Customer message:
@AppleSupport my phone battery has just gone from 50% - 34% in 15 mins???

Predicted intent:
battery_charging

Historical AppleSupport evidence:
[
  {
    "similarity": 0.879,
    "historical_customer": "@AppleSupport Let me explain in detail. My battery went from 100% this morning to only 38% currently. And I just started using my phone 15 minutes ago",
    "historical_response": "@213152 We'd be glad to take a look at the battery usage you're seeing with your iPhone. Which one do you have? https://t.co/GDrqU22YpT"
  },
  {
    "similarity": 0.858,
    "historical_customer": "My phone battery goes from 97% to 63% in a matter of mins wtff @AppleSupport",
    "historical_response": "@392003 Battery life is important. Which iOS version is your device using? Let us know in DM. https://t.co/GDrqU22YpT"
  },
  {
    "similarity": 0.848,
    "historical_customer": "Hey @115858 @AppleSupport I don\u2019t think my battery is supposed to go from 100% to 56% in 2 hours. I know my phones old but geez. https://t.co/TozPou0HWA",
    "historical_response": "@470020 We'd love to help with the battery life. Which iPhone do you have and what's the exact iOS version?"
  },
  {
    "similarity": 0.845,
    "historical_customer": "What\u2019s going on @AppleSupport I\u2019ve been on my phone a whole 21 minutes and lost 12% battery and 3% in one go!! \ud83d\ude23\ud83d\ude23 https://t.co/IbUZaT3B7L",
    "historical_response": "@774786 Let's take a closer look with you. Follow up with us in DM. Tell us the version of iOS installed in Settings &gt; General &gt; About there. https://t.co/GDrqU22YpT"
  },
  {
    "similarity": 0.843,
    "historical_customer": "@AppleSupport my phone lost 70% battery in 4 hours and I didn't touch it once, that's not right",
    "historical_response": "@196416 With concerns due to your battery life have you looked over the steps here? https://t.co/bivpdfBNJ6"
  }
]

Return ONLY valid JSON with this structure:

{
    "intent": "predicted intent",
    "draft_reply": "A concise customer-facing support response",
    "evidence_used": [
        "Brief description of the historical pattern used"
    ],
    "escalate": true,
    "escalation_reason": "Why a human should or should not handle this case"
}

Rules for escalation:
- Set escalate=true when the historical evidence suggests moving to DM,
  gathering account/device-specific information, or when the issue cannot
  be safely resolved from the available information.
- Set escalate=false only when the response can reasonably be handled
  using the historical evidence without requiring human intervention.
- Give a specific reason for the decision.

Keep the draft reply concise and natural.

In [85]:
# Install the Google GenAI SDK used by the support-agent generation layer.
%pip install -q google-genai

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [87]:
# Load the project's .env file and configure the Gemini client.
# The explicit path ensures the notebook finds the .env file in the project root.

import os
import json
from pathlib import Path
from dotenv import load_dotenv
from google import genai

# Project root = parent directory of notebooks/
project_root = Path.cwd().parent

env_path = project_root / ".env"

if not env_path.exists():
    raise FileNotFoundError(
        f".env file not found at: {env_path}"
    )

load_dotenv(env_path)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError(
        "GEMINI_API_KEY was not found inside the .env file."
    )

gemini_client = genai.Client(
    api_key=GEMINI_API_KEY
)

print("Gemini client configured successfully.")

Gemini client configured successfully.

In [90]:
# Test the support-agent generation using an available Gemini Flash model.
# We keep the same grounded prompt and structured JSON output.

def generate_support_response(
    analysis,
    model="gemini-3.5-flash"
):
    prompt = build_agent_prompt(analysis)

    response = gemini_client.models.generate_content(
        model=model,
        contents=prompt,
        config={
            "temperature": 0.2,
            "response_mime_type": "application/json"
        }
    )

    return json.loads(response.text)


# Test the complete agent on a golden example.
test_analysis = analyze_customer_message(
    golden_set.iloc[9]["customer_message"]
)

agent_result = generate_support_response(
    test_analysis
)

print(json.dumps(agent_result, indent=2))

{
  "intent": "battery_charging",
  "draft_reply": "We'd love to help look into your iPhone's battery life. Which iPhone model and iOS version are you currently using? Let us know in DM. https://t.co/GDrqU22YpT",
  "evidence_used": [
    "Historical responses consistently ask for the iPhone model and iOS version, and direct the customer to DM to take a closer look."
  ],
  "escalate": true,
  "escalation_reason": "The issue requires gathering device-specific information (iPhone model and iOS version) and moving the conversation to DM for personalized troubleshooting."
}

In [91]:
# Add a confidence signal based on the Linear SVM decision margin.
# A larger margin means the classifier is more separated from competing intents.

def predict_intent_with_confidence(
    customer_message,
    previous_message=""
):
    customer_message = str(customer_message).strip()
    previous_message = str(previous_message).strip()

    if previous_message:
        model_text = (
            f"Previous message: {previous_message} "
            f"Customer message: {customer_message}"
        )
    else:
        model_text = customer_message

    predicted_intent = final_intent_model.predict(
        [model_text]
    )[0]

    decision_scores = final_intent_model.decision_function(
        [model_text]
    )[0]

    sorted_scores = np.sort(decision_scores)[::-1]

    top_score = sorted_scores[0]
    second_score = sorted_scores[1]

    margin = float(top_score - second_score)

    return {
        "intent": predicted_intent,
        "margin": margin,
        "top_score": float(top_score),
        "second_score": float(second_score)
    }


# Test the confidence calculation.
test_message = golden_set.iloc[9]["customer_message"]

confidence = predict_intent_with_confidence(
    test_message
)

print("Customer:")
print(test_message)

print("\nPrediction:")
print(confidence)

Customer:
@AppleSupport my phone battery has just gone from 50% - 34% in 15 mins???

Prediction:
{'intent': 'battery_charging', 'margin': 1.7100865244866146, 'top_score': 0.7627941949075733, 'second_score': -0.9472923295790412}

In [92]:
# Measure classifier margins across all 200 golden examples.
# We use this distribution to choose a defensible confidence threshold for escalation.

confidence_records = []

for _, row in golden_set.iterrows():
    prediction = predict_intent_with_confidence(
        row["customer_message"],
        row["previous_message"]
    )

    confidence_records.append({
        "customer_tweet_id": row["customer_tweet_id"],
        "true_intent": row["intent"],
        "predicted_intent": prediction["intent"],
        "margin": prediction["margin"],
        "correct": prediction["intent"] == row["intent"]
    })

confidence_df = pd.DataFrame(confidence_records)

print("Classifier margin statistics")
print("=" * 60)
print(
    confidence_df["margin"]
    .describe(percentiles=[0.10, 0.25, 0.50, 0.75, 0.90])
    .round(3)
)

print("\nMargin by prediction correctness")
print("=" * 60)
print(
    confidence_df
    .groupby("correct")["margin"]
    .agg(["count", "mean", "median", "min", "max"])
    .round(3)
)

Classifier margin statistics
============================================================
count    200.000
mean       1.325
std        0.189
min        0.715
10%        1.077
25%        1.207
50%        1.366
75%        1.452
90%        1.539
max        1.740
Name: margin, dtype: float64

Margin by prediction correctness
============================================================
         count   mean  median    min   max
correct
True       200  1.325   1.366  0.715  1.74

In [94]:
# Compute out-of-fold classifier margins for the 200 golden examples.
# Each prediction comes from a model that did not train on that example,
# making this suitable for analyzing confidence and escalation behavior.

oof_predictions = np.empty(len(model_data), dtype=object)
oof_margins = np.zeros(len(model_data))

for train_idx, test_idx in cv.split(X_text, y):
    X_train = X_text.iloc[train_idx]
    X_test = X_text.iloc[test_idx]
    y_train = y.iloc[train_idx]

    word_char_svm.fit(
        X_train,
        y_train
    )

    predictions = word_char_svm.predict(X_test)
    decision_scores = word_char_svm.decision_function(X_test)

    # Sort each row's decision scores to calculate the margin
    # between the best and second-best intent.
    sorted_scores = np.sort(
        decision_scores,
        axis=1
    )[:, ::-1]

    margins = (
        sorted_scores[:, 0]
        - sorted_scores[:, 1]
    )

    oof_predictions[test_idx] = predictions
    oof_margins[test_idx] = margins


confidence_df = pd.DataFrame({
    "customer_tweet_id": model_data["customer_tweet_id"].values,
    "true_intent": model_data["intent"].values,
    "predicted_intent": oof_predictions,
    "margin": oof_margins,
    "correct": (
        oof_predictions == model_data["intent"].values
    )
})

print("OOF classifier margin statistics")
print("=" * 60)

print(
    confidence_df["margin"]
    .describe(
        percentiles=[
            0.10,
            0.25,
            0.50,
            0.75,
            0.90
        ]
    )
    .round(3)
)

print("\nMargin by prediction correctness")
print("=" * 60)

print(
    confidence_df
    .groupby("correct")["margin"]
    .agg([
        "count",
        "mean",
        "median",
        "min",
        "max"
    ])
    .round(3)
)

OOF classifier margin statistics
============================================================
count    200.000
mean       0.286
std        0.291
min        0.000
10%        0.021
25%        0.067
50%        0.191
75%        0.420
90%        0.721
max        1.419
Name: margin, dtype: float64

Margin by prediction correctness
============================================================
         count   mean  median   min    max
correct
False      100  0.142   0.094  0.00  0.576
True       100  0.431   0.363  0.01  1.419

In [95]:
# Inspect the lowest-confidence out-of-fold examples.
# These examples help us understand when the classifier is uncertain and
# provide evidence for the escalation policy.

low_confidence_examples = (
    confidence_df
    .sort_values("margin")
    .head(20)
    .merge(
        golden_set[
            [
                "customer_tweet_id",
                "customer_message"
            ]
        ],
        on="customer_tweet_id",
        how="left"
    )
)

pd.set_option(
    "display.max_colwidth",
    200
)

display(
    low_confidence_examples[
        [
            "customer_tweet_id",
            "customer_message",
            "true_intent",
            "predicted_intent",
            "margin",
            "correct"
        ]
    ]
)

,customer_tweet_id,customer_message,true_intent,predicted_intent,margin,correct
0,1866369.0,@AppleSupport @115948 Here are my Apple Music settings: https://t.co/QxyWJRJN8S,apple_services,ios_update,0.000479,False
1,2913352.0,@AppleSupport my iMessage has not worked in over a month at this point. I’ve spent considerable amount of time with your customer support to get this solved but there has been no solution yet. Ple...,apple_services,ios_update,0.001496,False
2,511125.0,@AppleSupport help I got a green line on the left side of my iPhone X screen and restarting it doesn’t make it go away,display_input,apple_services,0.003941,False
3,1819155.0,"@115858 the new update is ass. GPS doesn’t work, music controls don’t work, Apple Watch won’t connect, speaker phone doesn’t work.",device_hardware,apple_services,0.008818,False
4,1890537.0,"@115858 please say your developers are hard at work on iOS 11.0.4 so that my headphones, charger and volume buttons work again, ughhhh 🙄🙄🙄🙄🙄",audio,apple_services,0.009262,False
5,2799435.0,@115858 @6990 why isn’t FaceTime working right now? I need to see @107462 face 😭😭😭,apple_services,connectivity,0.009492,False
6,2119414.0,"So wtf y’all gon do about this I situation, @115858? Cuz I’m sick of sick this damn A n shit. 😒",display_input,apple_services,0.009502,False
7,2467693.0,"@AppleSupport Not sure, it def happens when not plugged in. Never replaced screen. Seems it's a common issue/bug w the update",display_input,display_input,0.009880,True
8,2422571.0,Clearly need to stop using a first-person pronoun until @115858 can get their shit together.,display_input,display_input,0.010089,True
9,1605041.0,"Hi @AppleSupport ,Apple Watch 3 has bug, restarts when you ask Siri on weather.please address this",device_hardware,apple_services,0.010513,False
10,1545207.0,@115858 I want my fucking picture back pull it up on iCloud I don't fuck know figure it the fuck out now cause I'm fucking PISSED!,icloud_backup,account_authentication,0.011478,False
11,1597353.0,Can someone tell me why my tweet looks like this??? @115858 b/c I️ just updated my phone twice .. #replytweet some1 https://t.co/qZ4cyQwvQG,display_input,audio,0.012553,False
12,34645.0,@AppleSupport It's 10.3.3. Although I'm convinced it's a screen issue rather than a software one.,display_input,ios_update,0.012760,False
13,1659223.0,"@AppleSupport Hello everyone, how do I unlock my account if I do not know the trust number? https://t.co/0fYns2ZzEA",account_authentication,apple_services,0.015069,False
14,1687712.0,"Good afternoon, @AppleSupport! It’s always some shit with y’all and these iPhone updates, huh? https://t.co/cGR2qXnGNA",ios_update,display_input,0.015372,False
15,864428.0,@AppleSupport I CAN! I have my device normal.,device_hardware,device_hardware,0.015630,True
16,2728298.0,@AppleSupport I have iPhone 7 ios 11 some of my old videos doesn’t work. Keep lodging. I transfer them from old phone to new one using iTunes and icloud backup.,camera_photos,apple_services,0.017529,False
17,1626579.0,"@AppleSupport makes me want to switch to @117159, just took a screen shot on my iPhone and it deleted all my photos... great",camera_photos,camera_photos,0.017550,True
18,2287872.0,@AppleSupport The “done” button will not let me select my picture. It’s covered in the top right corner of the phone with the battery and wifi icons. It gets stuck and I have to close out the app.,display_input,battery_charging,0.017627,False
19,242660.0,There is still terrible lag with 3D Touch in iOS 11.0.2 @115858 hard to see in video but it’s definitely noticeable. #lag https://t.co/InTFP8shUU,display_input,ios_update,0.019904,False

In [96]:
# Evaluate several classifier-margin thresholds for escalation.
# We compare coverage (cases handled automatically) against accuracy on
# the cases that would be auto-handled.

thresholds = [
    0.01,
    0.02,
    0.05,
    0.10,
    0.15,
    0.20,
    0.30,
    0.40,
    0.50
]

threshold_results = []

for threshold in thresholds:
    auto_handle = confidence_df["margin"] >= threshold

    coverage = auto_handle.mean()

    if auto_handle.sum() > 0:
        auto_accuracy = confidence_df.loc[
            auto_handle,
            "correct"
        ].mean()
    else:
        auto_accuracy = 0.0

    escalation_rate = 1 - coverage

    threshold_results.append({
        "threshold": threshold,
        "auto_handle_count": int(auto_handle.sum()),
        "auto_handle_rate": coverage,
        "escalation_rate": escalation_rate,
        "auto_handle_accuracy": auto_accuracy
    })

threshold_df = pd.DataFrame(threshold_results)

print(
    threshold_df.round(3).to_string(index=False)
)

 threshold  auto_handle_count  auto_handle_rate  escalation_rate  auto_handle_accuracy
      0.01                192             0.960            0.040                 0.516
      0.02                180             0.900            0.100                 0.533
      0.05                161             0.805            0.195                 0.571
      0.10                128             0.640            0.360                 0.641
      0.15                111             0.555            0.445                 0.676
      0.20                 99             0.495            0.505                 0.707
      0.30                 71             0.355            0.645                 0.845
      0.40                 53             0.265            0.735                 0.868
      0.50                 41             0.205            0.795                 0.902

In [97]:
# Define the final conservative escalation policy.
# A case is auto-handled only when the classifier is confident and the
# retrieved historical evidence is sufficiently strong.

INTENT_MARGIN_THRESHOLD = 0.30
RETRIEVAL_SIMILARITY_THRESHOLD = 0.65


def decide_escalation(
    intent,
    classifier_margin,
    top_similarity,
    customer_message
):
    customer_message = str(customer_message).strip().lower()

    reasons = []

    # Very short or vague messages lack enough information for safe automation.
    vague_patterns = [
        "same issue",
        "same problem",
        "please help",
        "help me",
        "what is going on",
        "what's going on"
    ]

    is_vague = (
        len(customer_message.split()) <= 8
        or any(
            pattern in customer_message
            for pattern in vague_patterns
        )
    )

    if is_vague:
        reasons.append(
            "The customer message does not provide enough specific information."
        )

    # Escalate when competing intents are too close.
    if classifier_margin < INTENT_MARGIN_THRESHOLD:
        reasons.append(
            "The intent classifier is not sufficiently confident."
        )

    # Escalate when historical evidence is weak.
    if top_similarity < RETRIEVAL_SIMILARITY_THRESHOLD:
        reasons.append(
            "No sufficiently similar historical support case was retrieved."
        )

    # These categories can require personalized investigation.
    if intent in {
        "account_authentication",
        "device_hardware"
    }:
        reasons.append(
            "The issue may require account- or device-specific investigation."
        )

    escalate = len(reasons) > 0

    if escalate:
        escalation_reason = " ".join(reasons)
    else:
        escalation_reason = (
            "The issue has sufficient intent confidence and relevant "
            "historical support evidence for automated handling."
        )

    return {
        "escalate": escalate,
        "escalation_reason": escalation_reason
    }


print("Escalation policy configured.")
print("Intent margin threshold:", INTENT_MARGIN_THRESHOLD)
print(
    "Retrieval similarity threshold:",
    RETRIEVAL_SIMILARITY_THRESHOLD
)

Escalation policy configured.
Intent margin threshold: 0.3
Retrieval similarity threshold: 0.65

In [98]:
# Combine classification, historical retrieval, grounded LLM generation,
# and the deterministic escalation policy into one support-agent function.

def support_agent(
    customer_message,
    previous_message=""
):
    customer_message = str(customer_message).strip()
    previous_message = str(previous_message).strip()

    # ---------------------------------------------------------
    # 1. Intent classification
    # ---------------------------------------------------------
    intent_prediction = predict_intent_with_confidence(
        customer_message,
        previous_message
    )

    intent = intent_prediction["intent"]
    classifier_margin = intent_prediction["margin"]

    # ---------------------------------------------------------
    # 2. Historical retrieval
    # ---------------------------------------------------------
    retrieved_cases = retrieve_historical_cases(
        customer_message,
        top_k=5
    )

    top_similarity = retrieved_cases[0]["similarity"]

    # ---------------------------------------------------------
    # 3. Build analysis object for the LLM
    # ---------------------------------------------------------
    analysis = {
        "customer_message": customer_message,
        "previous_message": previous_message,
        "intent": intent,
        "retrieved_cases": retrieved_cases,
        "top_similarity": top_similarity
    }

    # ---------------------------------------------------------
    # 4. Generate grounded response
    # ---------------------------------------------------------
    llm_result = generate_support_response(
        analysis
    )

    # ---------------------------------------------------------
    # 5. Deterministic escalation decision
    # ---------------------------------------------------------
    escalation = decide_escalation(
        intent=intent,
        classifier_margin=classifier_margin,
        top_similarity=top_similarity,
        customer_message=customer_message
    )

    # ---------------------------------------------------------
    # 6. Return one structured agent result
    # ---------------------------------------------------------
    return {
        "intent": intent,
        "classifier_margin": round(
            classifier_margin,
            4
        ),
        "top_similarity": round(
            top_similarity,
            4
        ),
        "draft_reply": llm_result["draft_reply"],
        "evidence_used": llm_result.get(
            "evidence_used",
            []
        ),
        "escalate": escalation["escalate"],
        "escalation_reason": escalation[
            "escalation_reason"
        ],
        "retrieved_cases": retrieved_cases
    }


print("Support agent pipeline ready.")

Support agent pipeline ready.

In [99]:
# Test the complete support agent on a realistic unseen customer message.
# This verifies that classification, retrieval, generation, and escalation
# work together as a single pipeline.

test_customer_message = (
    "@AppleSupport my iPhone battery is draining really fast "
    "since the latest update. It lost 30% in less than an hour."
)

agent_output = support_agent(
    test_customer_message
)

print(json.dumps(
    agent_output,
    indent=2
))

{
  "intent": "battery_charging",
  "classifier_margin": 0.8946,
  "top_similarity": 0.8907,
  "draft_reply": "We want to help get the most out of your iPhone's battery. To start, check out these tips to help maximize your battery life: https://t.co/bivpdfkckw. If you're still having trouble, please DM us with your device model and current iOS version so we can look into this further. https://t.co/GDrqU22YpT",
  "evidence_used": [
    "Offered battery maximizing tips using the provided links and requested the customer to DM their device model and iOS version for further assistance."
  ],
  "escalate": false,
  "escalation_reason": "The issue has sufficient intent confidence and relevant historical support evidence for automated handling.",
  "retrieved_cases": [
    {
      "rank": 1,
      "similarity": 0.8907265663146973,
      "customer_message": "@AppleSupport ever since the new update my battery has been draining extremely fast. It\u2019s gone down 2% in less than 5 minutes and I haven\u2019t even been on it.",
      "brand_response": "@388819 We want to help with your battery. Look here for a few tips: https://t.co/bivpdfkckw DM us if you're still having trouble. https://t.co/GDrqU2kzhr"
    },
    {
      "rank": 2,
      "similarity": 0.8905271291732788,
      "customer_message": "@AppleSupport ever since I got the new update my battery drains super fast. I did not even use my phone for 8 hours and lost 27%. Is something turned on that\u2019s draining the battery?",
      "brand_response": "@279195 We'd love to help get the most out of your iPhone's battery. To make sure, is iOS 11.1.2 the version currently installed? Have you tried any steps so far? Please keep us posted here in DM: https://t.co/GDrqU22YpT"
    },
    {
      "rank": 3,
      "similarity": 0.8874297142028809,
      "customer_message": "@AppleSupport why is my battery draining sooo very fast since the latest iOS update?!",
      "brand_response": "@567897 That should not be happening. Let us help. Let us know which device and iOS version you're using via DM. https://t.co/GDrqU22YpT"
    },
    {
      "rank": 4,
      "similarity": 0.8852918148040771,
      "customer_message": "@AppleSupport Since the last update of my iphone, the battery is draining fast (IOS 11.0.3) Help please \ud83d\ude4f\ud83c\udffb",
      "brand_response": "@645705 We can help out. Let's try a few steps here: https://t.co/bivpdfBNJ6 Let us know if those steps help."
    },
    {
      "rank": 5,
      "similarity": 0.8813955783843994,
      "customer_message": "@AppleSupport my iphones battery drains quickly. any tips. it might just be old though",
      "brand_response": "@123518 We'd be happy to help with some battery tips. Let's start with the maximizing tips found here: https://t.co/TpjqFp3jxD"
    }
  ]
}

In [100]:
# Run the complete agent on five golden examples as an evaluation smoke test.
# We test the pipeline before making the full 200-example evaluation expensive.

evaluation_sample = golden_set.sample(
    n=5,
    random_state=2026
).reset_index(drop=True)

evaluation_results = []

for idx, row in evaluation_sample.iterrows():
    print(f"Evaluating example {idx + 1}/5...")

    result = support_agent(
        customer_message=row["customer_message"],
        previous_message=row["previous_message"]
    )

    evaluation_results.append({
        "customer_tweet_id": row["customer_tweet_id"],
        "customer_message": row["customer_message"],
        "true_intent": row["intent"],
        "predicted_intent": result["intent"],
        "classifier_margin": result["classifier_margin"],
        "top_similarity": result["top_similarity"],
        "draft_reply": result["draft_reply"],
        "evidence_used": result["evidence_used"],
        "escalate": result["escalate"],
        "escalation_reason": result["escalation_reason"]
    })

evaluation_sample_results = pd.DataFrame(
    evaluation_results
)

print("\nEvaluation smoke test complete.")
display(evaluation_sample_results)

Evaluating example 1/5...
Evaluating example 2/5...
Evaluating example 3/5...
Evaluating example 4/5...
Evaluating example 5/5...

Evaluation smoke test complete.

,customer_tweet_id,customer_message,true_intent,predicted_intent,classifier_margin,top_similarity,draft_reply,evidence_used,escalate,escalation_reason
0,50820.0,@AppleSupport I have Iphone 7 updated to ios 11.1. After the news IOS released this year battery problem raised.,battery_charging,battery_charging,1.5940,0.8748,We'd like to help look into what's going on with your iPhone battery. Please meet us in DM so we can work together to find a solution. https://t.co/GDrqU22YpT,[Historical responses to iPhone 7 battery issues after iOS 11 updates consistently invite the customer to DM to investigate the power consumption issues.],False,The issue has sufficient intent confidence and relevant historical support evidence for automated handling.
1,864428.0,@AppleSupport I CAN! I have my device normal.,device_hardware,device_hardware,1.5632,0.8509,"Alright, thanks! Join us in DM with your device model so we can continue to troubleshoot there. https://t.co/GDrqU22YpT","[When a customer confirms they can perform an action or provides device status, the support agent invites them to DM with their device models to continue troubleshooting.]",True,The customer message does not provide enough specific information. The issue may require account- or device-specific investigation.
2,517208.0,"Wow was on hold for like 10 min with @AppleSupport and they hung up on me , been tryin to recover my Apple ID password all week 😒😒",account_authentication,account_authentication,1.2047,0.7825,This certainly isn't the experience we want you to have. We'd love to help in any way we can with your Apple ID. Please send us a DM with the details of what's going on so we can look into this to...,[Acknowledged the poor experience of being disconnected on hold and invited the customer to DM with details about their Apple ID issue to resolve it together.],True,The issue may require account- or device-specific investigation.
3,2295846.0,So @115858 is really about to have me become an #Android user. These glitches are too much and a pain!,other_unclear,other_unclear,1.3983,0.8885,"We'd be happy to help with any issues you're experiencing. Can you tell us what's going on, or DM us with details about what's happening?","[When customers complain about unspecified glitches, historical responses ask them to describe what they are experiencing or invite them to DM with details.]",False,The issue has sufficient intent confidence and relevant historical support evidence for automated handling.
4,2279207.0,@115858 hey sooo um....y’all going to fix this update so i️ can charge my phone? 🧐,battery_charging,battery_charging,1.1337,0.8627,"We want your iPhone working for you, and a software update shouldn't cause the device not to charge. Let's figure out what's going on together. To start, are you using an Apple Certified charging ...","[Acknowledged that software updates shouldn't cause charging issues, asked about using an Apple Certified charging cord, and invited the customer to DM for further troubleshooting.]",False,The issue has sufficient intent confidence and relevant historical support evidence for automated handling.

In [101]:
# Refine the escalation policy so vague/unclear intents are escalated even
# when the classifier margin and retrieval similarity appear strong.

def decide_escalation(
    intent,
    classifier_margin,
    top_similarity,
    customer_message
):
    customer_message = str(customer_message).strip().lower()

    reasons = []

    # Very short or vague messages do not contain enough information
    # for safe automated support.
    vague_patterns = [
        "same issue",
        "same problem",
        "having the same",
        "please help",
        "help me",
        "what is going on",
        "what's going on"
    ]

    is_vague = (
        len(customer_message.split()) <= 8
        or any(
            pattern in customer_message
            for pattern in vague_patterns
        )
    )

    if is_vague:
        reasons.append(
            "The customer message does not provide enough specific information."
        )

    # The catch-all intent should not be automatically handled because
    # the actual customer problem is unknown.
    if intent == "other_unclear":
        reasons.append(
            "The customer's issue could not be confidently mapped to a specific support intent."
        )

    # Low classifier margin indicates competing intents.
    if classifier_margin < INTENT_MARGIN_THRESHOLD:
        reasons.append(
            "The intent classifier is not sufficiently confident."
        )

    # Weak historical evidence makes grounded generation less reliable.
    if top_similarity < RETRIEVAL_SIMILARITY_THRESHOLD:
        reasons.append(
            "No sufficiently similar historical support case was retrieved."
        )

    # Account/device-specific issues may require information unavailable
    # from the public customer message.
    if intent in {
        "account_authentication",
        "device_hardware"
    }:
        reasons.append(
            "The issue may require account- or device-specific investigation."
        )

    escalate = len(reasons) > 0

    if escalate:
        escalation_reason = " ".join(reasons)
    else:
        escalation_reason = (
            "The issue has sufficient intent confidence and relevant "
            "historical support evidence for automated handling."
        )

    return {
        "escalate": escalate,
        "escalation_reason": escalation_reason
    }


print("Escalation policy updated.")

Escalation policy updated.

In [102]:
# Re-run the five-example smoke test after updating the escalation policy.
# This verifies that unclear cases are now routed more safely.

evaluation_results_updated = []

for idx, row in evaluation_sample.iterrows():
    print(f"Evaluating example {idx + 1}/5...")

    result = support_agent(
        customer_message=row["customer_message"],
        previous_message=row["previous_message"]
    )

    evaluation_results_updated.append({
        "customer_tweet_id": row["customer_tweet_id"],
        "true_intent": row["intent"],
        "predicted_intent": result["intent"],
        "classifier_margin": result["classifier_margin"],
        "top_similarity": result["top_similarity"],
        "draft_reply": result["draft_reply"],
        "escalate": result["escalate"],
        "escalation_reason": result["escalation_reason"]
    })

evaluation_sample_results = pd.DataFrame(
    evaluation_results_updated
)

display(evaluation_sample_results)

Evaluating example 1/5...
Evaluating example 2/5...
Evaluating example 3/5...
Evaluating example 4/5...
Evaluating example 5/5...

,customer_tweet_id,true_intent,predicted_intent,classifier_margin,top_similarity,draft_reply,escalate,escalation_reason
0,50820.0,battery_charging,battery_charging,1.5940,0.8748,We're here to help. Let's take a deeper look at what's going on with your iPhone battery in DM. https://t.co/GDrqU22YpT,False,The issue has sufficient intent confidence and relevant historical support evidence for automated handling.
1,864428.0,device_hardware,device_hardware,1.5632,0.8509,"Alright, thanks! Join us in DM with your device model and we can continue to troubleshoot there. https://t.co/GDrqU22YpT",True,The customer message does not provide enough specific information. The issue may require account- or device-specific investigation.
2,517208.0,account_authentication,account_authentication,1.2047,0.7825,"This certainly isn't the experience we want you to have. We'd love to help with your Apple ID. Please send us a DM with details of what's going on, and we'll look into this together. https://t.co/...",True,The issue may require account- or device-specific investigation.
3,2295846.0,other_unclear,other_unclear,1.3983,0.8885,We'd be happy to help. Can you tell us what you're experiencing? Please DM us with details about what's happening.,True,The customer's issue could not be confidently mapped to a specific support intent.
4,2279207.0,battery_charging,battery_charging,1.1337,0.8627,"We want your iPhone working for you, and a software update shouldn't cause the device not to charge. Let's figure out what's going on together. Please DM us details about what's happening so we ca...",False,The issue has sufficient intent confidence and relevant historical support evidence for automated handling.

In [103]:
# Run the complete support agent over all 200 golden examples.
# Results are checkpointed after every example so interrupted API runs can resume.

from pathlib import Path
import time
import json
import pandas as pd

evaluation_dir = project_root / "data" / "evaluation"
evaluation_dir.mkdir(
    parents=True,
    exist_ok=True
)

evaluation_path = (
    evaluation_dir / "apple_support_agent_results.csv"
)

# Load previous progress if it exists.
if evaluation_path.exists():
    completed_results = pd.read_csv(
        evaluation_path
    )

    completed_ids = set(
        completed_results["customer_tweet_id"]
        .astype(str)
    )

    print(
        f"Found {len(completed_results)} previously completed examples."
    )

else:
    completed_results = pd.DataFrame()
    completed_ids = set()

print(
    f"Total golden examples: {len(golden_set)}"
)

remaining = golden_set[
    ~golden_set["customer_tweet_id"]
    .astype(str)
    .isin(completed_ids)
].copy()

print(
    f"Remaining examples: {len(remaining)}"
)

for idx, row in remaining.iterrows():

    print(
        f"Evaluating {idx + 1}/{len(golden_set)} "
        f"(ID: {row['customer_tweet_id']})..."
    )

    try:
        result = support_agent(
            customer_message=row["customer_message"],
            previous_message=row["previous_message"]
        )

        new_result = {
            "customer_tweet_id": row["customer_tweet_id"],
            "customer_message": row["customer_message"],
            "true_intent": row["intent"],
            "predicted_intent": result["intent"],
            "classifier_margin": result["classifier_margin"],
            "top_similarity": result["top_similarity"],
            "draft_reply": result["draft_reply"],
            "evidence_used": json.dumps(
                result["evidence_used"],
                ensure_ascii=False
            ),
            "escalate": result["escalate"],
            "escalation_reason": result["escalation_reason"]
        }

        completed_results = pd.concat(
            [
                completed_results,
                pd.DataFrame([new_result])
            ],
            ignore_index=True
        )

        # Save immediately after every successful API call.
        completed_results.to_csv(
            evaluation_path,
            index=False
        )

        print("Saved.")

        # Small delay to avoid unnecessarily rapid API requests.
        time.sleep(0.5)

    except Exception as e:

        print(
            f"ERROR on {row['customer_tweet_id']}: {e}"
        )

        print(
            "Progress has already been saved. "
            "You can rerun this cell to continue."
        )

        break


print("\nEvaluation run finished.")
print(
    "Completed examples:",
    len(completed_results)
)
print(
    "Saved to:",
    evaluation_path
)

Total golden examples: 200
Remaining examples: 200
Evaluating 1/200 (ID: 611285.0)...
Saved.
Evaluating 2/200 (ID: 400853.0)...
Saved.
Evaluating 3/200 (ID: 1099710.0)...
Saved.
Evaluating 4/200 (ID: 1342708.0)...
Saved.
Evaluating 5/200 (ID: 1687712.0)...
Saved.
Evaluating 6/200 (ID: 1121644.0)...
Saved.
Evaluating 7/200 (ID: 1747356.0)...
Saved.
Evaluating 8/200 (ID: 2119414.0)...
Saved.
Evaluating 9/200 (ID: 1983621.0)...
Saved.
Evaluating 10/200 (ID: 323849.0)...
ERROR on 323849.0: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.5-flash\nPlease retry in 40.078959569s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '40s'}]}}
Progress has already been saved. You can rerun this cell to continue.

Evaluation run finished.
Completed examples: 9
Saved to: c:\Projects\hiver-support-agent\data\evaluation\apple_support_agent_results.csv

In [104]:
# Evaluate the full 200-example golden set locally without making any Gemini API calls.
# This gives us the core metrics before we spend any more LLM quota.

import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Use the existing golden set and existing trained models/functions.
evaluation_base = golden_set[
    [
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "intent"
    ]
].copy()

evaluation_rows = []

for _, row in evaluation_base.iterrows():
    intent_prediction = predict_intent_with_confidence(
        customer_message=row["customer_message"],
        previous_message=row["previous_message"]
    )

    retrieved_cases = retrieve_historical_cases(
        row["customer_message"],
        top_k=5
    )

    top_similarity = retrieved_cases[0]["similarity"]

    escalation = decide_escalation(
        intent=intent_prediction["intent"],
        classifier_margin=intent_prediction["margin"],
        top_similarity=top_similarity,
        customer_message=row["customer_message"]
    )

    evaluation_rows.append({
        "customer_tweet_id": row["customer_tweet_id"],
        "customer_message": row["customer_message"],
        "true_intent": row["intent"],
        "predicted_intent": intent_prediction["intent"],
        "classifier_margin": intent_prediction["margin"],
        "top_similarity": top_similarity,
        "escalate": escalation["escalate"],
        "escalation_reason": escalation["escalation_reason"]
    })

local_eval = pd.DataFrame(evaluation_rows)

print("Completed:", len(local_eval))
print()

# ---------------------------------------------------------
# Intent classification metrics
# ---------------------------------------------------------

intent_accuracy = accuracy_score(
    local_eval["true_intent"],
    local_eval["predicted_intent"]
)

macro_f1 = f1_score(
    local_eval["true_intent"],
    local_eval["predicted_intent"],
    average="macro"
)

weighted_f1 = f1_score(
    local_eval["true_intent"],
    local_eval["predicted_intent"],
    average="weighted"
)

print("INTENT CLASSIFICATION")
print("---------------------")
print(f"Accuracy:    {intent_accuracy:.3f}")
print(f"Macro F1:    {macro_f1:.3f}")
print(f"Weighted F1: {weighted_f1:.3f}")

print("\nClassification report:")
print(
    classification_report(
        local_eval["true_intent"],
        local_eval["predicted_intent"],
        zero_division=0
    )
)

# ---------------------------------------------------------
# Escalation metrics
# ---------------------------------------------------------

auto_handled = local_eval[local_eval["escalate"] == False]
escalated = local_eval[local_eval["escalate"] == True]

auto_handle_rate = len(auto_handled) / len(local_eval)
escalation_rate = len(escalated) / len(local_eval)

if len(auto_handled) > 0:
    auto_handle_accuracy = accuracy_score(
        auto_handled["true_intent"],
        auto_handled["predicted_intent"]
    )
else:
    auto_handle_accuracy = 0.0

print("\nESCALATION POLICY")
print("-----------------")
print(f"Auto-handled:          {len(auto_handled)}/{len(local_eval)}")
print(f"Auto-handle rate:      {auto_handle_rate:.3f}")
print(f"Escalated:             {len(escalated)}/{len(local_eval)}")
print(f"Escalation rate:       {escalation_rate:.3f}")
print(f"Auto-handle accuracy:  {auto_handle_accuracy:.3f}")

# ---------------------------------------------------------
# Retrieval diagnostics
# ---------------------------------------------------------

print("\nRETRIEVAL")
print("---------")
print(
    f"Mean top-1 similarity:   "
    f"{local_eval['top_similarity'].mean():.3f}"
)
print(
    f"Median top-1 similarity: "
    f"{local_eval['top_similarity'].median():.3f}"
)
print(
    f"Below threshold (0.65):  "
    f"{(local_eval['top_similarity'] < RETRIEVAL_SIMILARITY_THRESHOLD).sum()}"
)

# ---------------------------------------------------------
# Save deterministic evaluation
# ---------------------------------------------------------

local_eval_path = evaluation_dir / "apple_support_local_evaluation.csv"

local_eval.to_csv(
    local_eval_path,
    index=False
)

print("\nSaved local evaluation to:")
print(local_eval_path)

Completed: 200

INTENT CLASSIFICATION
---------------------
Accuracy:    1.000
Macro F1:    1.000
Weighted F1: 1.000

Classification report:
                        precision    recall  f1-score   support

account_authentication       1.00      1.00      1.00        18
        apple_services       1.00      1.00      1.00        25
        apps_app_store       1.00      1.00      1.00        20
                 audio       1.00      1.00      1.00        12
      battery_charging       1.00      1.00      1.00        19
         camera_photos       1.00      1.00      1.00        11
          connectivity       1.00      1.00      1.00        21
       device_hardware       1.00      1.00      1.00        15
         display_input       1.00      1.00      1.00        35
         icloud_backup       1.00      1.00      1.00         6
            ios_update       1.00      1.00      1.00        13
         other_unclear       1.00      1.00      1.00         5

              accuracy                           1.00       200
             macro avg       1.00      1.00      1.00       200
          weighted avg       1.00      1.00      1.00       200


ESCALATION POLICY
-----------------
Auto-handled:          141/200
Auto-handle rate:      0.705
Escalated:             59/200
Escalation rate:       0.295
Auto-handle accuracy:  1.000

RETRIEVAL
---------
Mean top-1 similarity:   0.809
Median top-1 similarity: 0.811
Below threshold (0.65):  6

Saved local evaluation to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_local_evaluation.csv

In [105]:
# Recompute the 200-example evaluation with out-of-fold predictions.
# This avoids training-set leakage and gives us honest classifier and escalation metrics.

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, classification_report

# ---------------------------------------------------------
# Prepare evaluation data
# ---------------------------------------------------------

oof_data = golden_set[
    [
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "has_context",
        "intent"
    ]
].copy()

oof_data["model_text"] = oof_data.apply(
    build_model_text,
    axis=1
)

X = oof_data["model_text"]
y = oof_data["intent"]

# ---------------------------------------------------------
# 5-fold out-of-fold predictions
# ---------------------------------------------------------

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=2026
)

oof_predictions = np.empty(len(oof_data), dtype=object)
oof_margins = np.zeros(len(oof_data))

for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y), start=1):

    fold_model = clone(word_char_svm)

    fold_model.fit(
        X.iloc[train_idx],
        y.iloc[train_idx]
    )

    X_valid = X.iloc[valid_idx]

    predictions = fold_model.predict(X_valid)
    decision_scores = fold_model.decision_function(X_valid)

    oof_predictions[valid_idx] = predictions

    # Margin = top score - second-best score.
    sorted_scores = np.sort(
        decision_scores,
        axis=1
    )

    margins = (
        sorted_scores[:, -1]
        - sorted_scores[:, -2]
    )

    oof_margins[valid_idx] = margins

    print(f"Fold {fold} complete.")

# ---------------------------------------------------------
# Add OOF predictions
# ---------------------------------------------------------

oof_data["predicted_intent"] = oof_predictions
oof_data["classifier_margin"] = oof_margins

# ---------------------------------------------------------
# Apply escalation policy using OOF predictions
# ---------------------------------------------------------

oof_escalations = []

for _, row in oof_data.iterrows():

    retrieved_cases = retrieve_historical_cases(
        row["customer_message"],
        top_k=5
    )

    top_similarity = retrieved_cases[0]["similarity"]

    escalation = decide_escalation(
        intent=row["predicted_intent"],
        classifier_margin=row["classifier_margin"],
        top_similarity=top_similarity,
        customer_message=row["customer_message"]
    )

    oof_escalations.append({
        "top_similarity": top_similarity,
        "escalate": escalation["escalate"],
        "escalation_reason": escalation["escalation_reason"]
    })

oof_escalation_df = pd.DataFrame(oof_escalations)

oof_data = pd.concat(
    [
        oof_data.reset_index(drop=True),
        oof_escalation_df.reset_index(drop=True)
    ],
    axis=1
)

# ---------------------------------------------------------
# Honest intent metrics
# ---------------------------------------------------------

accuracy = accuracy_score(
    oof_data["intent"],
    oof_data["predicted_intent"]
)

macro_f1 = f1_score(
    oof_data["intent"],
    oof_data["predicted_intent"],
    average="macro"
)

weighted_f1 = f1_score(
    oof_data["intent"],
    oof_data["predicted_intent"],
    average="weighted"
)

print("\nHONEST OOF INTENT EVALUATION")
print("============================")
print(f"Accuracy:    {accuracy:.3f}")
print(f"Macro F1:    {macro_f1:.3f}")
print(f"Weighted F1: {weighted_f1:.3f}")

print("\nClassification report:")
print(
    classification_report(
        oof_data["intent"],
        oof_data["predicted_intent"],
        zero_division=0
    )
)

# ---------------------------------------------------------
# Honest escalation metrics
# ---------------------------------------------------------

auto_handled = oof_data[
    oof_data["escalate"] == False
]

escalated = oof_data[
    oof_data["escalate"] == True
]

auto_handle_rate = len(auto_handled) / len(oof_data)
escalation_rate = len(escalated) / len(oof_data)

auto_handle_accuracy = accuracy_score(
    auto_handled["intent"],
    auto_handled["predicted_intent"]
)

print("\nHONEST ESCALATION EVALUATION")
print("============================")
print(f"Auto-handled:         {len(auto_handled)}/{len(oof_data)}")
print(f"Auto-handle rate:     {auto_handle_rate:.3f}")
print(f"Escalated:            {len(escalated)}/{len(oof_data)}")
print(f"Escalation rate:      {escalation_rate:.3f}")
print(f"Auto-handle accuracy: {auto_handle_accuracy:.3f}")

# ---------------------------------------------------------
# Retrieval metrics
# ---------------------------------------------------------

print("\nRETRIEVAL")
print("=========")

print(
    f"Mean top-1 similarity:   "
    f"{oof_data['top_similarity'].mean():.3f}"
)

print(
    f"Median top-1 similarity: "
    f"{oof_data['top_similarity'].median():.3f}"
)

print(
    f"Below 0.65 threshold:    "
    f"{(oof_data['top_similarity'] < RETRIEVAL_SIMILARITY_THRESHOLD).sum()}"
)

# ---------------------------------------------------------
# Save honest evaluation
# ---------------------------------------------------------

oof_eval_path = (
    evaluation_dir /
    "apple_support_oof_evaluation.csv"
)

oof_data.to_csv(
    oof_eval_path,
    index=False
)

print("\nSaved honest evaluation to:")
print(oof_eval_path)

Fold 1 complete.
Fold 2 complete.
Fold 3 complete.
Fold 4 complete.
Fold 5 complete.

HONEST OOF INTENT EVALUATION
============================
Accuracy:    0.500
Macro F1:    0.437
Weighted F1: 0.477

Classification report:
                        precision    recall  f1-score   support

account_authentication       0.65      0.72      0.68        18
        apple_services       0.32      0.28      0.30        25
        apps_app_store       0.58      0.70      0.64        20
                 audio       0.00      0.00      0.00        12
      battery_charging       0.76      0.84      0.80        19
         camera_photos       0.83      0.91      0.87        11
          connectivity       0.41      0.33      0.37        21
       device_hardware       0.42      0.33      0.37        15
         display_input       0.49      0.69      0.57        35
         icloud_backup       1.00      0.33      0.50         6
            ios_update       0.13      0.15      0.14        13
         other_unclear       0.00      0.00      0.00         5

              accuracy                           0.50       200
             macro avg       0.47      0.44      0.44       200
          weighted avg       0.47      0.50      0.48       200


HONEST ESCALATION EVALUATION
============================
Auto-handled:         51/200
Auto-handle rate:     0.255
Escalated:            149/200
Escalation rate:      0.745
Auto-handle accuracy: 0.843

RETRIEVAL
=========
Mean top-1 similarity:   0.809
Median top-1 similarity: 0.811
Below 0.65 threshold:    6

Saved honest evaluation to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_oof_evaluation.csv

In [106]:
# Analyze the honest OOF predictions to find the largest confusion pairs and concrete failure examples.
# These results will directly feed the report's top-5 failure-modes section.

from sklearn.metrics import confusion_matrix
import pandas as pd

# ---------------------------------------------------------
# Confusion matrix
# ---------------------------------------------------------

labels = sorted(oof_data["intent"].unique())

cm = confusion_matrix(
    oof_data["intent"],
    oof_data["predicted_intent"],
    labels=labels
)

confusion_df = pd.DataFrame(
    cm,
    index=labels,
    columns=labels
)

print("CONFUSION MATRIX")
print("================")
display(confusion_df)

# ---------------------------------------------------------
# Extract incorrect predictions
# ---------------------------------------------------------

errors = oof_data[
    oof_data["intent"] != oof_data["predicted_intent"]
].copy()

print("\nTotal misclassified examples:", len(errors))

# ---------------------------------------------------------
# Find largest confusion pairs
# ---------------------------------------------------------

pair_counts = (
    errors
    .groupby(
        ["intent", "predicted_intent"]
    )
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
)

print("\nTOP CONFUSION PAIRS")
print("===================")

display(
    pair_counts.head(15)
)

# ---------------------------------------------------------
# Show real examples for the top confusion pairs
# ---------------------------------------------------------

print("\nREAL EXAMPLES FROM TOP CONFUSIONS")
print("=================================")

top_pairs = pair_counts.head(5)

for _, pair in top_pairs.iterrows():

    true_intent = pair["intent"]
    predicted_intent = pair["predicted_intent"]

    print(
        f"\nTRUE: {true_intent} "
        f"-> PREDICTED: {predicted_intent} "
        f"({pair['count']} examples)"
    )

    examples = errors[
        (errors["intent"] == true_intent) &
        (errors["predicted_intent"] == predicted_intent)
    ][
        [
            "customer_tweet_id",
            "customer_message",
            "previous_message",
            "classifier_margin"
        ]
    ].head(3)

    display(examples)

# ---------------------------------------------------------
# Lowest-confidence errors
# ---------------------------------------------------------

print("\nLOWEST-CONFIDENCE MISCLASSIFICATIONS")
print("====================================")

low_confidence_errors = (
    errors
    .sort_values("classifier_margin")
    [
        [
            "customer_tweet_id",
            "customer_message",
            "intent",
            "predicted_intent",
            "classifier_margin"
        ]
    ]
    .head(15)
)

display(low_confidence_errors)

# ---------------------------------------------------------
# Save error analysis
# ---------------------------------------------------------

error_path = (
    evaluation_dir /
    "apple_support_error_analysis.csv"
)

errors.to_csv(
    error_path,
    index=False
)

print("\nSaved errors to:")
print(error_path)

CONFUSION MATRIX
================

,account_authentication,apple_services,apps_app_store,audio,battery_charging,camera_photos,connectivity,device_hardware,display_input,icloud_backup,ios_update,other_unclear
account_authentication,13,2,1,1,0,0,0,0,0,0,0,1
apple_services,1,7,4,1,0,1,4,1,3,0,3,0
apps_app_store,0,3,14,0,1,0,0,1,1,0,0,0
audio,0,2,0,0,1,0,1,2,3,0,2,1
battery_charging,0,0,1,0,16,0,0,1,1,0,0,0
camera_photos,0,1,0,0,0,10,0,0,0,0,0,0
connectivity,0,2,2,0,1,0,7,0,6,0,2,1
device_hardware,2,2,0,0,1,1,1,5,2,0,1,0
display_input,0,3,0,1,1,0,1,0,24,0,5,0
icloud_backup,2,0,1,0,0,0,0,1,0,2,0,0
ios_update,1,0,0,0,0,0,3,1,6,0,2,0
other_unclear,1,0,1,0,0,0,0,0,3,0,0,0

Total misclassified examples: 100

TOP CONFUSION PAIRS
===================

             intent predicted_intent  count
30     connectivity    display_input      6
51       ios_update    display_input      6
44    display_input       ios_update      5
8    apple_services     connectivity      4
5    apple_services   apps_app_store      4
11   apple_services       ios_update      3
10   apple_services    display_input      3
49       ios_update     connectivity      3
12   apps_app_store   apple_services      3
54    other_unclear    display_input      3
40    display_input   apple_services      3
20            audio    display_input      3
21            audio       ios_update      2
16            audio   apple_services      2
38  device_hardware    display_input      2

REAL EXAMPLES FROM TOP CONFUSIONS
=================================

TRUE: connectivity -> PREDICTED: display_input (6 examples)

,customer_tweet_id,customer_message,previous_message,classifier_margin
20,146553.0,@115858 @4792 CarPlay and iPhoneX and the 2017 M240i don‘t work together. When is a fix for that coming?,NaN,0.536629
25,1437557.0,Absolutely hate it when you airdrop a bunch of photos &amp; they go all jumbled up 😖 @115858 #whyyoutestingme,NaN,0.093669
134,1484796.0,"@115858 you really need to fix this update or something because every time me and my friend try to FaceTime or call, the other person doesn’t get any notification for it at all and I’m gonna scream",NaN,0.042282

TRUE: ios_update -> PREDICTED: display_input (6 examples)

,customer_tweet_id,customer_message,previous_message,classifier_margin
1,400853.0,@AppleSupport Was able to help him via iTunes. Still weird the OTA didn’t work,@210813 Let us know if the update has issues through iTunes.,0.029548
4,1687712.0,"Good afternoon, @AppleSupport! It’s always some shit with y’all and these iPhone updates, huh? https://t.co/cGR2qXnGNA",NaN,0.015372
12,2873394.0,@115858 can you do another update my shit keeps freezing.. what happens when I inevitably need to call 911 and this shit doesn’t work? Do I do cpr myself with the phone? Or just Lost it and hit my...,NaN,0.063688

TRUE: display_input -> PREDICTED: ios_update (5 examples)

,customer_tweet_id,customer_message,previous_message,classifier_margin
14,400851.0,@AppleSupport since updating to the useless software. Screen keeps auto rotating. Sort it out,NaN,0.282435
118,2288513.0,@AppleSupport Well when the hell are they going to release for an update that doesn’t turn my I️ into a fucking question mark box?,"@664874 iOS 11.1.1 was recently released and it includes a fix for autocorrect issues. Be sure to back up your device prior to updating, and let us know if the issue persists afterwards. How to ba...",0.148750
138,34645.0,@AppleSupport It's 10.3.3. Although I'm convinced it's a screen issue rather than a software one.,@123511 We're happy to help. What version of iOS are you currently running? Find that in Settings &gt; General &gt; About.,0.012760

TRUE: apple_services -> PREDICTED: connectivity (4 examples)

,customer_tweet_id,customer_message,previous_message,classifier_margin
59,2799435.0,@115858 @6990 why isn’t FaceTime working right now? I need to see @107462 face 😭😭😭,NaN,0.009492
73,1357275.0,@AppleSupport Tried all manor of witchcraft and I can't get the bookmarks that are synced in iOS to appear in Safari on my laptop.,NaN,0.064253
124,2744221.0,"@AppleSupport every time I open Twitter my music shuts off and won’t let me use both at same time... assistance please, iPhone X",NaN,0.020897

TRUE: apple_services -> PREDICTED: apps_app_store (4 examples)

,customer_tweet_id,customer_message,previous_message,classifier_margin
2,1099710.0,@379507 @AppleSupport Having the same issue.,"@AppleSupport iOS 11.0.3. 2 different iPhone 7s in my family, multiple iPads too. Enter address in Maps &amp; driving directions fail to load—endless spinner.",0.079056
52,1096904.0,Yo @AppleSupport how do I leave group chat on the latest iOS for iPhone. Please help. Please.,NaN,0.058193
142,2503732.0,@AppleSupport I went on iTunes and re downloaded it and it still isn’t in my library. I turned my phone off for 1 hour then back on again and still nothing.,@711875 We want to help. Can you tell us which steps you've tried so far? This way we won't have you do any steps over again.,0.035929

LOWEST-CONFIDENCE MISCLASSIFICATIONS
====================================

,customer_tweet_id,customer_message,intent,predicted_intent,classifier_margin
149,1866369.0,@AppleSupport @115948 Here are my Apple Music settings: https://t.co/QxyWJRJN8S,apple_services,ios_update,0.000479
51,2913352.0,@AppleSupport my iMessage has not worked in over a month at this point. I’ve spent considerable amount of time with your customer support to get this solved but there has been no solution yet. Ple...,apple_services,ios_update,0.001496
114,511125.0,@AppleSupport help I got a green line on the left side of my iPhone X screen and restarting it doesn’t make it go away,display_input,apple_services,0.003941
100,1819155.0,"@115858 the new update is ass. GPS doesn’t work, music controls don’t work, Apple Watch won’t connect, speaker phone doesn’t work.",device_hardware,apple_services,0.008818
130,1890537.0,"@115858 please say your developers are hard at work on iOS 11.0.4 so that my headphones, charger and volume buttons work again, ughhhh 🙄🙄🙄🙄🙄",audio,apple_services,0.009262
59,2799435.0,@115858 @6990 why isn’t FaceTime working right now? I need to see @107462 face 😭😭😭,apple_services,connectivity,0.009492
7,2119414.0,"So wtf y’all gon do about this I situation, @115858? Cuz I’m sick of sick this damn A n shit. 😒",display_input,apple_services,0.009502
26,1605041.0,"Hi @AppleSupport ,Apple Watch 3 has bug, restarts when you ask Siri on weather.please address this",device_hardware,apple_services,0.010513
164,1545207.0,@115858 I want my fucking picture back pull it up on iCloud I don't fuck know figure it the fuck out now cause I'm fucking PISSED!,icloud_backup,account_authentication,0.011478
106,1597353.0,Can someone tell me why my tweet looks like this??? @115858 b/c I️ just updated my phone twice .. #replytweet some1 https://t.co/qZ4cyQwvQG,display_input,audio,0.012553
138,34645.0,@AppleSupport It's 10.3.3. Although I'm convinced it's a screen issue rather than a software one.,display_input,ios_update,0.012760
140,1659223.0,"@AppleSupport Hello everyone, how do I unlock my account if I do not know the trust number? https://t.co/0fYns2ZzEA",account_authentication,apple_services,0.015069
4,1687712.0,"Good afternoon, @AppleSupport! It’s always some shit with y’all and these iPhone updates, huh? https://t.co/cGR2qXnGNA",ios_update,display_input,0.015372
176,2728298.0,@AppleSupport I have iPhone 7 ios 11 some of my old videos doesn’t work. Keep lodging. I transfer them from old phone to new one using iTunes and icloud backup.,camera_photos,apple_services,0.017529
190,2287872.0,@AppleSupport The “done” button will not let me select my picture. It’s covered in the top right corner of the phone with the battery and wifi icons. It gets stuck and I have to close out the app.,display_input,battery_charging,0.017627

Saved errors to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_error_analysis.csv

In [107]:
# Analyze whether the escalation policy successfully catches low-confidence and ambiguous cases.
# This tells us whether escalation is actually reducing the risk of incorrect automated handling.

# ---------------------------------------------------------
# Basic escalation/error breakdown
# ---------------------------------------------------------

oof_data["correct"] = (
    oof_data["intent"] ==
    oof_data["predicted_intent"]
)

oof_data["auto_handled"] = ~oof_data["escalate"]

auto_correct = oof_data[
    oof_data["auto_handled"] &
    oof_data["correct"]
]

auto_incorrect = oof_data[
    oof_data["auto_handled"] &
    ~oof_data["correct"]
]

escalated_correct = oof_data[
    oof_data["escalate"] &
    oof_data["correct"]
]

escalated_incorrect = oof_data[
    oof_data["escalate"] &
    ~oof_data["correct"]
]

total_errors = (~oof_data["correct"]).sum()

# ---------------------------------------------------------
# Print breakdown
# ---------------------------------------------------------

print("ESCALATION ERROR ANALYSIS")
print("==========================")

print(f"Total examples:          {len(oof_data)}")
print(f"Total classifier errors: {total_errors}")

print("\nAuto-handled:")
print(f"  Correct:   {len(auto_correct)}")
print(f"  Incorrect: {len(auto_incorrect)}")

print("\nEscalated:")
print(f"  Correct:   {len(escalated_correct)}")
print(f"  Incorrect: {len(escalated_incorrect)}")

print("\nRates:")

print(
    f"Auto-handled error rate: "
    f"{len(auto_incorrect) / len(auto_handled):.3f}"
)

print(
    f"Escalated error rate:    "
    f"{len(escalated_incorrect) / len(escalated):.3f}"
)

if total_errors > 0:
    errors_caught = len(escalated_incorrect)

    print(
        f"Classifier errors caught by escalation: "
        f"{errors_caught}/{total_errors} "
        f"({errors_caught / total_errors:.3f})"
    )

# ---------------------------------------------------------
# Compare confidence distributions
# ---------------------------------------------------------

print("\nCLASSIFIER MARGIN")
print("=================")

print(
    "Correct predictions:"
)
print(
    oof_data.loc[
        oof_data["correct"],
        "classifier_margin"
    ].describe()
)

print(
    "\nIncorrect predictions:"
)
print(
    oof_data.loc[
        ~oof_data["correct"],
        "classifier_margin"
    ].describe()
)

# ---------------------------------------------------------
# Incorrect auto-handled examples
# ---------------------------------------------------------

print("\nINCORRECTLY AUTO-HANDLED EXAMPLES")
print("==================================")

incorrect_auto = (
    auto_incorrect
    .sort_values("classifier_margin")
    [
        [
            "customer_tweet_id",
            "customer_message",
            "intent",
            "predicted_intent",
            "classifier_margin",
            "top_similarity"
        ]
    ]
)

display(incorrect_auto)

# ---------------------------------------------------------
# Escalated examples
# ---------------------------------------------------------

print("\nESCALATED EXAMPLES")
print("==================")

escalated_examples = (
    oof_data[
        oof_data["escalate"]
    ]
    .sort_values("classifier_margin")
    [
        [
            "customer_tweet_id",
            "customer_message",
            "intent",
            "predicted_intent",
            "classifier_margin",
            "top_similarity",
            "escalation_reason"
        ]
    ]
)

display(escalated_examples.head(20))

ESCALATION ERROR ANALYSIS
==========================
Total examples:          200
Total classifier errors: 100

Auto-handled:
  Correct:   43
  Incorrect: 8

Escalated:
  Correct:   57
  Incorrect: 92

Rates:
Auto-handled error rate: 0.157
Escalated error rate:    0.617
Classifier errors caught by escalation: 92/100 (0.920)

CLASSIFIER MARGIN
=================
Correct predictions:
count    100.000000
mean       0.430920
std        0.331000
min        0.009880
25%        0.155130
50%        0.363386
75%        0.635232
max        1.418725
Name: classifier_margin, dtype: float64

Incorrect predictions:
count    100.000000
mean       0.142079
std        0.136367
min        0.000479
25%        0.039006
50%        0.094256
75%        0.228803
max        0.575928
Name: classifier_margin, dtype: float64

INCORRECTLY AUTO-HANDLED EXAMPLES
==================================

,customer_tweet_id,customer_message,intent,predicted_intent,classifier_margin,top_similarity
182,898222.0,@AppleSupport after installing 11.0.3 my touch screen is working really bad as well as Bluetooth,display_input,connectivity,0.306109,0.832736
187,1642388.0,@AppleSupport It connects successfully but all apps are not functioning including safari.,connectivity,apps_app_store,0.337332,0.804784
123,2279207.0,@115858 hey sooo um....y’all going to fix this update so i️ can charge my phone? 🧐,battery_charging,display_input,0.367894,0.862713
159,1901170.0,"@AppleSupport #iOS11 is riddled w/issues, speakerphone rarely works, camera frozen 30% of the time, y did u issue v11.03 w/ so many bugs!?!",device_hardware,camera_photos,0.438899,0.819597
139,851749.0,@AppleSupport why does my watch do this with push notifications https://t.co/rPcKlWObEZ,apple_services,connectivity,0.509094,0.799085
20,146553.0,@115858 @4792 CarPlay and iPhoneX and the 2017 M240i don‘t work together. When is a fix for that coming?,connectivity,display_input,0.536629,0.671833
24,259974.0,@AppleSupport what does this mean? Why can't I sync my phone to my Mac? https://t.co/MvJ1UXAuee,connectivity,apple_services,0.541072,0.835784
77,2557443.0,"@AppleSupport I updated my iPhone 6S to iOS 11.1.1 and is totally malfunctioning. Apps are crashing every time, phone calls are giving errors and battery runs out faster than normal. Totally the o...",device_hardware,battery_charging,0.575928,0.845203

ESCALATED EXAMPLES
==================

,customer_tweet_id,customer_message,intent,predicted_intent,classifier_margin,top_similarity,escalation_reason
149,1866369.0,@AppleSupport @115948 Here are my Apple Music settings: https://t.co/QxyWJRJN8S,apple_services,ios_update,0.000479,0.828947,The intent classifier is not sufficiently confident.
51,2913352.0,@AppleSupport my iMessage has not worked in over a month at this point. I’ve spent considerable amount of time with your customer support to get this solved but there has been no solution yet. Ple...,apple_services,ios_update,0.001496,0.914628,The intent classifier is not sufficiently confident.
114,511125.0,@AppleSupport help I got a green line on the left side of my iPhone X screen and restarting it doesn’t make it go away,display_input,apple_services,0.003941,0.920467,The intent classifier is not sufficiently confident.
100,1819155.0,"@115858 the new update is ass. GPS doesn’t work, music controls don’t work, Apple Watch won’t connect, speaker phone doesn’t work.",device_hardware,apple_services,0.008818,0.755759,The intent classifier is not sufficiently confident.
130,1890537.0,"@115858 please say your developers are hard at work on iOS 11.0.4 so that my headphones, charger and volume buttons work again, ughhhh 🙄🙄🙄🙄🙄",audio,apple_services,0.009262,0.807324,The intent classifier is not sufficiently confident.
59,2799435.0,@115858 @6990 why isn’t FaceTime working right now? I need to see @107462 face 😭😭😭,apple_services,connectivity,0.009492,0.897843,The intent classifier is not sufficiently confident.
7,2119414.0,"So wtf y’all gon do about this I situation, @115858? Cuz I’m sick of sick this damn A n shit. 😒",display_input,apple_services,0.009502,0.810382,The intent classifier is not sufficiently confident.
160,2467693.0,"@AppleSupport Not sure, it def happens when not plugged in. Never replaced screen. Seems it's a common issue/bug w the update",display_input,display_input,0.009880,0.775150,The intent classifier is not sufficiently confident.
30,2422571.0,Clearly need to stop using a first-person pronoun until @115858 can get their shit together.,display_input,display_input,0.010089,0.864203,The intent classifier is not sufficiently confident.
26,1605041.0,"Hi @AppleSupport ,Apple Watch 3 has bug, restarts when you ask Siri on weather.please address this",device_hardware,apple_services,0.010513,0.883171,The intent classifier is not sufficiently confident.
164,1545207.0,@115858 I want my fucking picture back pull it up on iCloud I don't fuck know figure it the fuck out now cause I'm fucking PISSED!,icloud_backup,account_authentication,0.011478,0.829347,The intent classifier is not sufficiently confident. The issue may require account- or device-specific investigation.
106,1597353.0,Can someone tell me why my tweet looks like this??? @115858 b/c I️ just updated my phone twice .. #replytweet some1 https://t.co/qZ4cyQwvQG,display_input,audio,0.012553,0.800799,The intent classifier is not sufficiently confident.
138,34645.0,@AppleSupport It's 10.3.3. Although I'm convinced it's a screen issue rather than a software one.,display_input,ios_update,0.012760,0.800158,The intent classifier is not sufficiently confident.
140,1659223.0,"@AppleSupport Hello everyone, how do I unlock my account if I do not know the trust number? https://t.co/0fYns2ZzEA",account_authentication,apple_services,0.015069,0.790420,The intent classifier is not sufficiently confident.
4,1687712.0,"Good afternoon, @AppleSupport! It’s always some shit with y’all and these iPhone updates, huh? https://t.co/cGR2qXnGNA",ios_update,display_input,0.015372,0.840206,The intent classifier is not sufficiently confident.
91,864428.0,@AppleSupport I CAN! I have my device normal.,device_hardware,device_hardware,0.015630,0.850895,The customer message does not provide enough specific information. The intent classifier is not sufficiently confident. The issue may require account- or device-specific investigation.
176,2728298.0,@AppleSupport I have iPhone 7 ios 11 some of my old videos doesn’t work. Keep lodging. I transfer them from old phone to new one using iTunes and icloud backup.,camera_photos,apple_services,0.017529,0.710408,The intent classifier is not sufficiently confident.
175,1626579.0,"@AppleSupport makes me want to switch to @117159, just took a screen shot on my iPhone and it deleted all my photos... great",camera_photos,camera_photos,0.017550,0.758260,The intent classifier is not sufficiently confident.
190,2287872.0,@AppleSupport The “done” button will not let me select my picture. It’s covered in the top right corner of the phone with the battery and wifi icons. It gets stuck and I have to close out the app.,display_input,battery_charging,0.017627,0.713868,The intent classifier is not sufficiently confident.
157,242660.0,There is still terrible lag with 3D Touch in iOS 11.0.2 @115858 hard to see in video but it’s definitely noticeable. #lag https://t.co/InTFP8shUU,display_input,ios_update,0.019904,0.881326,The intent classifier is not sufficiently confident.

In [108]:
# Build a fixed 30-example LLM evaluation sample.
# We include the 9 already generated cases and select 21 additional diverse cases
# so the eventual LLM judge and human evaluation cover both successes and failures.

import pandas as pd
import numpy as np

# ---------------------------------------------------------
# Load the 9 completed Gemini evaluations
# ---------------------------------------------------------

agent_results_path = (
    evaluation_dir /
    "apple_support_agent_results.csv"
)

agent_results = pd.read_csv(agent_results_path)

completed_ids = set(
    agent_results["customer_tweet_id"]
    .astype(str)
)

print("Existing Gemini results:", len(agent_results))

# ---------------------------------------------------------
# Start with existing generated examples
# ---------------------------------------------------------

selected_ids = set(completed_ids)

# Work from the honest OOF evaluation
candidate_pool = oof_data.copy()

candidate_pool["id_str"] = (
    candidate_pool["customer_tweet_id"]
    .astype(str)
)

candidate_pool = candidate_pool[
    ~candidate_pool["id_str"].isin(selected_ids)
].copy()

# ---------------------------------------------------------
# Select additional examples from different categories
# ---------------------------------------------------------

additional = []

# 1. Low-confidence cases
low_conf = (
    candidate_pool
    .sort_values("classifier_margin")
    .head(7)
)

additional.append(low_conf)

# 2. Incorrect predictions
incorrect = candidate_pool[
    candidate_pool["intent"] != candidate_pool["predicted_intent"]
].sort_values("classifier_margin")

incorrect = incorrect[
    ~incorrect["customer_tweet_id"].isin(
        pd.concat(additional)["customer_tweet_id"]
    )
].head(7)

additional.append(incorrect)

# 3. Low retrieval similarity
low_retrieval = (
    candidate_pool
    .sort_values("top_similarity")
)

low_retrieval = low_retrieval[
    ~low_retrieval["customer_tweet_id"].isin(
        pd.concat(additional)["customer_tweet_id"]
    )
].head(4)

additional.append(low_retrieval)

# 4. High-confidence auto-handled cases
high_conf = (
    candidate_pool[
        ~candidate_pool["escalate"]
    ]
    .sort_values("classifier_margin", ascending=False)
)

high_conf = high_conf[
    ~high_conf["customer_tweet_id"].isin(
        pd.concat(additional)["customer_tweet_id"]
    )
].head(3)

additional.append(high_conf)

# ---------------------------------------------------------
# Combine and limit to 30 total examples
# ---------------------------------------------------------

additional_df = pd.concat(
    additional,
    ignore_index=True
)

additional_df = additional_df.drop_duplicates(
    subset=["customer_tweet_id"]
)

needed = max(0, 30 - len(agent_results))

additional_df = additional_df.head(needed)

selected_oof = candidate_pool[
    candidate_pool["customer_tweet_id"].isin(
        additional_df["customer_tweet_id"]
    )
].copy()

# ---------------------------------------------------------
# Build evaluation sample
# ---------------------------------------------------------

llm_eval_sample = pd.concat(
    [
        agent_results.assign(source="already_generated"),
        selected_oof.assign(source="to_generate")
    ],
    ignore_index=True,
    sort=False
)

llm_eval_sample = llm_eval_sample.drop_duplicates(
    subset=["customer_tweet_id"]
).head(30)

# ---------------------------------------------------------
# Save fixed sample
# ---------------------------------------------------------

llm_sample_path = (
    evaluation_dir /
    "apple_support_llm_evaluation_sample_30.csv"
)

llm_eval_sample.to_csv(
    llm_sample_path,
    index=False
)

print("\nLLM evaluation sample created.")
print("Total examples:", len(llm_eval_sample))
print("Already generated:", len(agent_results))
print(
    "Still need Gemini generation:",
    len(llm_eval_sample) - len(agent_results)
)

print("\nSample intent distribution:")
print(
    llm_eval_sample["true_intent"]
    .value_counts()
)

print("\nSaved to:")
print(llm_sample_path)

Existing Gemini results: 9

LLM evaluation sample created.
Total examples: 30
Already generated: 9
Still need Gemini generation: 21

Sample intent distribution:
true_intent
apps_app_store      3
apple_services      2
ios_update          2
battery_charging    1
display_input       1
Name: count, dtype: int64

Saved to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_llm_evaluation_sample_30.csv

In [109]:
# Fix the LLM evaluation sample so all 30 examples have consistent evaluation columns.
# This does not call Gemini; it only cleans the sample we already selected.

# ---------------------------------------------------------
# Reload the fixed 30-example sample
# ---------------------------------------------------------

llm_sample_path = (
    evaluation_dir /
    "apple_support_llm_evaluation_sample_30.csv"
)

llm_eval_sample = pd.read_csv(
    llm_sample_path
)

# ---------------------------------------------------------
# Normalize the true intent column
# ---------------------------------------------------------

if "true_intent" not in llm_eval_sample.columns:
    llm_eval_sample["true_intent"] = llm_eval_sample["intent"]
else:
    llm_eval_sample["true_intent"] = (
        llm_eval_sample["true_intent"]
        .fillna(llm_eval_sample["intent"])
    )

# ---------------------------------------------------------
# Show actual distribution
# ---------------------------------------------------------

print("Total examples:", len(llm_eval_sample))

print("\nTrue intent distribution:")
print(
    llm_eval_sample["true_intent"]
    .value_counts()
    .sort_index()
)

print("\nEscalation distribution:")

if "escalate" in llm_eval_sample.columns:
    print(
        llm_eval_sample["escalate"]
        .value_counts(dropna=False)
    )

print("\nExamples by source:")

if "source" in llm_eval_sample.columns:
    print(
        llm_eval_sample["source"]
        .value_counts()
    )

# ---------------------------------------------------------
# Save corrected sample
# ---------------------------------------------------------

llm_eval_sample.to_csv(
    llm_sample_path,
    index=False
)

print("\nCorrected sample saved to:")
print(llm_sample_path)

Total examples: 30

True intent distribution:
true_intent
account_authentication     2
apple_services             5
apps_app_store             4
audio                      1
battery_charging           1
camera_photos              1
device_hardware            3
display_input             10
icloud_backup              1
ios_update                 2
Name: count, dtype: int64

Escalation distribution:
escalate
True     20
False    10
Name: count, dtype: int64

Examples by source:
source
to_generate          21
already_generated     9
Name: count, dtype: int64

Corrected sample saved to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_llm_evaluation_sample_30.csv

In [110]:
# Prepare the final 30-example LLM evaluation table.
# This combines the fixed sample with any Gemini responses already generated,
# so the same 30 cases will be used for both LLM judging and human review.

import pandas as pd
import json

# ---------------------------------------------------------
# Load fixed 30-example sample
# ---------------------------------------------------------

llm_sample_path = (
    evaluation_dir /
    "apple_support_llm_evaluation_sample_30.csv"
)

llm_sample = pd.read_csv(
    llm_sample_path
)

# ---------------------------------------------------------
# Load existing Gemini agent results
# ---------------------------------------------------------

agent_results_path = (
    evaluation_dir /
    "apple_support_agent_results.csv"
)

agent_results = pd.read_csv(
    agent_results_path
)

# ---------------------------------------------------------
# Keep only fields needed for evaluation
# ---------------------------------------------------------

agent_results_small = agent_results[
    [
        "customer_tweet_id",
        "draft_reply",
        "evidence_used",
        "escalate",
        "escalation_reason"
    ]
].copy()

agent_results_small["customer_tweet_id"] = (
    agent_results_small["customer_tweet_id"]
    .astype(str)
)

llm_sample["customer_tweet_id"] = (
    llm_sample["customer_tweet_id"]
    .astype(str)
)

# ---------------------------------------------------------
# Merge generated responses onto the fixed sample
# ---------------------------------------------------------

llm_judge_data = llm_sample.merge(
    agent_results_small,
    on="customer_tweet_id",
    how="left",
    suffixes=("", "_generated")
)

# ---------------------------------------------------------
# Prefer generated agent values where available
# ---------------------------------------------------------

for column in [
    "draft_reply",
    "evidence_used",
    "escalate",
    "escalation_reason"
]:
    generated_column = f"{column}_generated"

    if generated_column in llm_judge_data.columns:

        if column in llm_judge_data.columns:
            llm_judge_data[column] = (
                llm_judge_data[column]
                .fillna(llm_judge_data[generated_column])
            )
        else:
            llm_judge_data[column] = (
                llm_judge_data[generated_column]
            )

        llm_judge_data.drop(
            columns=[generated_column],
            inplace=True
        )

# ---------------------------------------------------------
# Normalize evaluation fields
# ---------------------------------------------------------

llm_judge_data["true_intent"] = (
    llm_judge_data["true_intent"]
    .fillna(llm_judge_data["intent"])
)

llm_judge_data["has_generated_reply"] = (
    llm_judge_data["draft_reply"]
    .notna()
    &
    llm_judge_data["draft_reply"]
    .astype(str)
    .str.strip()
    .ne("")
)

# ---------------------------------------------------------
# Add stable evaluation ID
# ---------------------------------------------------------

llm_judge_data.insert(
    0,
    "evaluation_id",
    range(1, len(llm_judge_data) + 1)
)

# ---------------------------------------------------------
# Display status
# ---------------------------------------------------------

print("Total evaluation cases:", len(llm_judge_data))

print(
    "Generated responses:",
    llm_judge_data["has_generated_reply"].sum()
)

print(
    "Missing responses:",
    (~llm_judge_data["has_generated_reply"]).sum()
)

print("\nIntent distribution:")
print(
    llm_judge_data["true_intent"]
    .value_counts()
    .sort_index()
)

print("\nEvaluation columns:")
print(
    llm_judge_data.columns.tolist()
)

# ---------------------------------------------------------
# Save final judge dataset
# ---------------------------------------------------------

judge_data_path = (
    evaluation_dir /
    "apple_support_llm_judge_30.csv"
)

llm_judge_data.to_csv(
    judge_data_path,
    index=False
)

print("\nSaved to:")
print(judge_data_path)

Total evaluation cases: 30
Generated responses: 9
Missing responses: 21

Intent distribution:
true_intent
account_authentication     2
apple_services             5
apps_app_store             4
audio                      1
battery_charging           1
camera_photos              1
device_hardware            3
display_input             10
icloud_backup              1
ios_update                 2
Name: count, dtype: int64

Evaluation columns:
['evaluation_id', 'customer_tweet_id', 'customer_message', 'true_intent', 'predicted_intent', 'classifier_margin', 'top_similarity', 'draft_reply', 'evidence_used', 'escalate', 'escalation_reason', 'source', 'previous_message', 'has_context', 'intent', 'model_text', 'correct', 'auto_handled', 'id_str', 'has_generated_reply']

Saved to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_llm_judge_30.csv

In [111]:
# Test whether the Gemini API quota is available again before running the remaining 21 evaluations.
# We make exactly one request so we don't waste quota if the limit is still active.

test_case = llm_judge_data[
    ~llm_judge_data["has_generated_reply"]
].iloc[0]

print("Testing Gemini on evaluation ID:", test_case["evaluation_id"])

try:
    test_result = generate_support_response(
        {
            "customer_message": test_case["customer_message"],
            "previous_message": test_case["previous_message"],
            "intent": test_case["predicted_intent"],
            "retrieved_cases": retrieve_historical_cases(
                test_case["customer_message"],
                top_k=5
            ),
            "top_similarity": test_case["top_similarity"]
        }
    )

    print("\nGemini quota appears available.")
    print("\nGenerated reply:")
    print(test_result["draft_reply"])

except Exception as e:
    print("\nGemini request failed:")
    print(e)

Testing Gemini on evaluation ID: 10

Gemini request failed:
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.5-flash\nPlease retry in 34.756672858s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '34s'}]}}

In [112]:
# Create the human-review template for the 30 LLM evaluation examples.
# The same rubric will later be used by the LLM judge, allowing us to measure
# agreement between the automated judge and human evaluation.

import pandas as pd

# ---------------------------------------------------------
# Load the fixed 30-example evaluation set
# ---------------------------------------------------------

judge_data_path = (
    evaluation_dir /
    "apple_support_llm_judge_30.csv"
)

judge_data = pd.read_csv(
    judge_data_path
)

# ---------------------------------------------------------
# Create human evaluation template
# ---------------------------------------------------------

human_review = judge_data[
    [
        "evaluation_id",
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "true_intent",
        "predicted_intent",
        "classifier_margin",
        "top_similarity",
        "draft_reply",
        "evidence_used",
        "escalate",
        "escalation_reason"
    ]
].copy()

# Human scoring columns.
human_review["relevance_1_5"] = ""
human_review["grounding_1_5"] = ""
human_review["helpfulness_1_5"] = ""
human_review["unsupported_claims_1_5"] = ""
human_review["overall_quality_1_5"] = ""
human_review["human_notes"] = ""

# ---------------------------------------------------------
# Save human annotation sheet
# ---------------------------------------------------------

human_review_path = (
    evaluation_dir /
    "apple_support_human_review_30.csv"
)

human_review.to_csv(
    human_review_path,
    index=False
)

print("Human review template created.")
print("Total examples:", len(human_review))
print(
    "Responses currently available:",
    human_review["draft_reply"].notna().sum()
)
print(
    "Responses still missing:",
    human_review["draft_reply"].isna().sum()
)

print("\nSaved to:")
print(human_review_path)

Human review template created.
Total examples: 30
Responses currently available: 9
Responses still missing: 21

Saved to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_human_review_30.csv

In [113]:
# LLM-as-judge prompt
# This defines the evaluation rubric that Gemini will use later.
# No API request is made here.

JUDGE_RUBRIC = """
You are evaluating an AI customer-support reply for AppleSupport.

Evaluate ONLY the information provided:
- Customer message
- Previous message, if available
- Predicted intent
- Retrieved historical support cases
- AI-generated draft reply

Do not reward the response for sounding professional alone.
The response must be relevant, historically grounded, useful, and free of unsupported claims.

Score the following:

1. relevance (1-5)
   5 = Directly addresses the customer's actual issue.
   4 = Mostly addresses the issue with minor omissions.
   3 = Partially relevant but misses an important aspect.
   2 = Mostly unrelated or poorly targeted.
   1 = Does not address the customer's issue.

2. grounding (1-5)
   5 = Clearly consistent with the retrieved historical AppleSupport responses.
   4 = Mostly supported by historical evidence.
   3 = Some support exists, but important parts are weakly grounded.
   2 = Mostly relies on information not supported by the evidence.
   1 = Contradicts or ignores the historical evidence.

3. helpfulness (1-5)
   5 = Gives a useful next step or actionable support guidance.
   4 = Useful but could be more specific.
   3 = Somewhat useful but incomplete.
   2 = Provides little practical help.
   1 = Not useful.

4. overall_quality (1-5)
   5 = Strong support response suitable for the situation.
   4 = Good response with minor issues.
   3 = Acceptable but noticeably incomplete or generic.
   2 = Poor response requiring substantial revision.
   1 = Unacceptable.

5. unsupported_claim (0-1)
   1 = Contains at least one factual claim, policy, troubleshooting instruction,
       guarantee, or URL that is not supported by the provided evidence.
   0 = No clearly unsupported claim.

Also provide:
- short_reason: one concise explanation of the scores
- major_issue: the single most important problem, or "none"

Return ONLY valid JSON:

{
    "relevance": 1,
    "grounding": 1,
    "helpfulness": 1,
    "overall_quality": 1,
    "unsupported_claim": 0,
    "short_reason": "...",
    "major_issue": "..."
}
"""


def build_judge_prompt(row):
    """
    Build the evaluation prompt for one generated support response.
    """
    
    retrieved_cases = row.get("retrieved_cases", "")
    
    prompt = f"""
{JUDGE_RUBRIC}

CUSTOMER MESSAGE:
{row["customer_message"]}

PREVIOUS MESSAGE:
{row["previous_message"]}

TRUE INTENT:
{row["true_intent"]}

PREDICTED INTENT:
{row["predicted_intent"]}

RETRIEVED HISTORICAL CASES:
{retrieved_cases}

AI-GENERATED REPLY:
{row["draft_reply"]}
"""
    
    return prompt


print("Judge rubric created.")
print("Prompt builder ready.")

Judge rubric created.
Prompt builder ready.

In [114]:
def format_retrieved_cases(customer_message, top_k=5):
    """
    Retrieve and format historical AppleSupport cases
    for the LLM judge.
    """
    
    cases = retrieve_historical_cases(
        customer_message,
        top_k=top_k
    )
    
    formatted = []
    
    for i, case in enumerate(cases, start=1):
        formatted.append(
            f"""
Case {i}
Similarity: {case["similarity"]:.4f}

Customer:
{case["customer_message"]}

AppleSupport response:
{case["brand_response"]}
"""
        )
    
    return "\n".join(formatted)


print("Historical evidence formatter ready.")

Historical evidence formatter ready.

In [115]:
# Find one example that already has a generated reply.

available_example = llm_judge_data[
    llm_judge_data["has_generated_reply"] == True
].iloc[0]

example_prompt = build_judge_prompt(
    {
        "customer_message": available_example["customer_message"],
        "previous_message": available_example["previous_message"],
        "true_intent": available_example["true_intent"],
        "predicted_intent": available_example["predicted_intent"],
        "retrieved_cases": format_retrieved_cases(
            available_example["customer_message"]
        ),
        "draft_reply": available_example["draft_reply"]
    }
)

print(example_prompt[:6000])

You are evaluating an AI customer-support reply for AppleSupport.

Evaluate ONLY the information provided:
- Customer message
- Previous message, if available
- Predicted intent
- Retrieved historical support cases
- AI-generated draft reply

Do not reward the response for sounding professional alone.
The response must be relevant, historically grounded, useful, and free of unsupported claims.

Score the following:

1. relevance (1-5)
   5 = Directly addresses the customer's actual issue.
   4 = Mostly addresses the issue with minor omissions.
   3 = Partially relevant but misses an important aspect.
   2 = Mostly unrelated or poorly targeted.
   1 = Does not address the customer's issue.

2. grounding (1-5)
   5 = Clearly consistent with the retrieved historical AppleSupport responses.
   4 = Mostly supported by historical evidence.
   3 = Some support exists, but important parts are weakly grounded.
   2 = Mostly relies on information not supported by the evidence.
   1 = Contradicts or ignores the historical evidence.

3. helpfulness (1-5)
   5 = Gives a useful next step or actionable support guidance.
   4 = Useful but could be more specific.
   3 = Somewhat useful but incomplete.
   2 = Provides little practical help.
   1 = Not useful.

4. overall_quality (1-5)
   5 = Strong support response suitable for the situation.
   4 = Good response with minor issues.
   3 = Acceptable but noticeably incomplete or generic.
   2 = Poor response requiring substantial revision.
   1 = Unacceptable.

5. unsupported_claim (0-1)
   1 = Contains at least one factual claim, policy, troubleshooting instruction,
       guarantee, or URL that is not supported by the provided evidence.
   0 = No clearly unsupported claim.

Also provide:
- short_reason: one concise explanation of the scores
- major_issue: the single most important problem, or "none"

Return ONLY valid JSON:

{
    "relevance": 1,
    "grounding": 1,
    "helpfulness": 1,
    "overall_quality": 1,
    "unsupported_claim": 0,
    "short_reason": "...",
    "major_issue": "..."
}


CUSTOMER MESSAGE:
Hey @115858 how can Siri really be my personal assistant if it won't integrate into 3rd party apps why can't I have it play Spotify where is the functionality?

PREVIOUS MESSAGE:
nan

TRUE INTENT:
apple_services

PREDICTED INTENT:
apple_services

RETRIEVED HISTORICAL CASES:

Case 1
Similarity: 0.7006

Customer:
@AppleSupport Hello, where can i see third party app support by Siri on iOS 11 ? I don't see "app support" like iOS 10...

AppleSupport response:
@261160 Let's look into that. Send us a DM and we'll go from there. https://t.co/GDrqU22YpT


Case 2
Similarity: 0.6699

Customer:
@AppleSupport asked Siri to play a song. It’s on my iPhone, why is this happening? https://t.co/lsnj4pUZJd

AppleSupport response:
@186705 Let’s take a look at that together.  Are you subscribed to Apple Music?  Does the song play if you select it from the Music App?


Case 3
Similarity: 0.6689

Customer:
@115858 @AppleSupport @115948 bring back music rating already. Siri sucks. I am in the music app. Siri is just fucking stupid. https://t.co/UWyHc7eKAM

AppleSupport response:
@421314 We want Siri working for you properly. Send us a DM and we'll look into this together. https://t.co/GDrqU22YpT


Case 4
Similarity: 0.6669

Customer:
@AppleSupport do ya guys know why my google assistant won’t play songs in Apple Music? It says voice actions aren’t available for this app.

AppleSupport response:
@370108 Thanks for reaching out. We can look into this with you. Which device are you using? Please reply in DM. https://t.co/GDrqU22YpT


Case 5
Similarity: 0.6668

Customer:
Siri needs to be able to do this or what’s the point? @AppleSupport @33423 https://t.co/HVRuBWgxrv

AppleSupport response:
@556371 We can understand your need for Siri to do this. Meet us in DM so we can review ways to help make this happen next time around. https://t.co/GDrqU22YpT


AI-GENERATED REPLY:
We understand wanting Siri to work with your favorite apps. Let's look into this together. Please send us a DM so we can help.

In [116]:
import json
import time
import pandas as pd

# ---------------------------------------------------------
# Paths
# ---------------------------------------------------------

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"
judge_data = pd.read_csv(judge_path)

# Make sure the tracking column exists
if "judge_completed" not in judge_data.columns:
    judge_data["judge_completed"] = False

# ---------------------------------------------------------
# Helper: parse Gemini judge response
# ---------------------------------------------------------

def parse_judge_response(response_text):
    """
    Parse the JSON returned by Gemini.
    """
    
    text = response_text.strip()
    
    # Remove accidental markdown fences if Gemini returns them.
    if text.startswith("```"):
        text = text.replace("```json", "", 1)
        text = text.replace("```", "", 1).strip()
    
    result = json.loads(text)
    
    required_fields = [
        "relevance",
        "grounding",
        "helpfulness",
        "overall_quality",
        "unsupported_claim",
        "short_reason",
        "major_issue"
    ]
    
    missing = [
        field for field in required_fields
        if field not in result
    ]
    
    if missing:
        raise ValueError(
            f"Judge response missing fields: {missing}"
        )
    
    return result


# ---------------------------------------------------------
# Helper: create judge input for one row
# ---------------------------------------------------------

def prepare_judge_input(row):
    
    retrieved_cases = format_retrieved_cases(
        row["customer_message"],
        top_k=5
    )
    
    return {
        "customer_message": row["customer_message"],
        "previous_message": row["previous_message"],
        "true_intent": row["true_intent"],
        "predicted_intent": row["predicted_intent"],
        "retrieved_cases": retrieved_cases,
        "draft_reply": row["draft_reply"]
    }


# ---------------------------------------------------------
# Main judge runner
# ---------------------------------------------------------

def run_llm_judge(
    max_examples=1,
    delay_seconds=2
):
    """
    Run the Gemini judge on unfinished examples.

    Checkpoints after every successful example.

    max_examples controls how many API calls are made.
    """

    global judge_data

    pending = judge_data[
        judge_data["draft_reply"].notna() &
        (~judge_data["judge_completed"].fillna(False))
    ].copy()

    print("Total evaluation examples:", len(judge_data))
    print("Pending judge evaluations:", len(pending))
    print("Maximum calls this run:", max_examples)

    if len(pending) == 0:
        print("\nNo pending judge evaluations.")
        return

    processed = 0

    for _, row in pending.iterrows():

        if processed >= max_examples:
            break

        evaluation_id = row["evaluation_id"]

        print(
            f"\n[{processed + 1}/{max_examples}] "
            f"Evaluation ID: {evaluation_id}"
        )

        try:
            judge_input = prepare_judge_input(row)

            prompt = build_judge_prompt(judge_input)

            response = gemini_client.models.generate_content(
                model="gemini-3.5-flash",
                contents=prompt,
                config={
                    "temperature": 0.0,
                    "response_mime_type": "application/json"
                }
            )

            judge_result = parse_judge_response(
                response.text
            )

            # ---------------------------------------------
            # Save judge result
            # ---------------------------------------------

            for key, value in judge_result.items():
                judge_data.loc[
                    judge_data["evaluation_id"] == evaluation_id,
                    f"judge_{key}"
                ] = value

            judge_data.loc[
                judge_data["evaluation_id"] == evaluation_id,
                "judge_completed"
            ] = True

            # Checkpoint immediately.
            judge_data.to_csv(
                judge_path,
                index=False
            )

            processed += 1

            print("Judge evaluation saved.")
            print(
                "Overall quality:",
                judge_result["overall_quality"]
            )

            if processed < max_examples:
                time.sleep(delay_seconds)

        except Exception as e:

            error_text = str(e)

            print("\nJudge request failed:")
            print(error_text)

            # Important:
            # Stop immediately on quota errors.
            if (
                "429" in error_text
                or "RESOURCE_EXHAUSTED" in error_text
                or "quota" in error_text.lower()
            ):
                print(
                    "\nQuota error detected."
                    "\nStopping immediately."
                    "\nAlready completed results were saved."
                )
                break

            # For other errors, record them and continue.
            judge_data.loc[
                judge_data["evaluation_id"] == evaluation_id,
                "judge_error"
            ] = error_text

            judge_data.to_csv(
                judge_path,
                index=False
            )

    print("\nRun finished.")
    print("Successfully judged:", processed)
    
    print(
        "Remaining pending:",
        (
            judge_data["draft_reply"].notna() &
            (~judge_data["judge_completed"].fillna(False))
        ).sum()
    )

In [117]:
print("Judge runner loaded successfully.")

print("\nTotal examples:", len(judge_data))

print(
    "Generated replies:",
    judge_data["draft_reply"].notna().sum()
)

print(
    "Already judged:",
    judge_data["judge_completed"].sum()
)

print(
    "Pending judge evaluations:",
    (
        judge_data["draft_reply"].notna() &
        (~judge_data["judge_completed"].fillna(False))
    ).sum()
)

Judge runner loaded successfully.

Total examples: 30
Generated replies: 9
Already judged: 0
Pending judge evaluations: 9

In [119]:
# ---------------------------------------------------------
# Check LLM judge evaluation status
# No Gemini API call
# ---------------------------------------------------------

judge_data = pd.read_csv(judge_path)

# Older version of the CSV may not have this column yet.
# Create it if necessary.
if "judge_completed" not in judge_data.columns:
    judge_data["judge_completed"] = False

generated_mask = judge_data["draft_reply"].notna()
judged_mask = judge_data["judge_completed"].fillna(False).astype(bool)

print("Total examples:", len(judge_data))
print("Generated replies:", generated_mask.sum())
print("Already judged:", (generated_mask & judged_mask).sum())
print(
    "Pending judge evaluations:",
    (generated_mask & ~judged_mask).sum()
)
print(
    "Missing generated replies:",
    (~generated_mask).sum()
)

Total examples: 30
Generated replies: 9
Already judged: 0
Pending judge evaluations: 9
Missing generated replies: 21

In [121]:
# ---------------------------------------------------------
# Recreate 5-fold OOF predictions for the 200-example set
# No Gemini API call
# ---------------------------------------------------------

from sklearn.model_selection import cross_val_predict
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd

# ---------------------------------------------------------
# Use the existing 200-example model data
# ---------------------------------------------------------

X_text = model_data["model_text"]
y = model_data["intent"]

# ---------------------------------------------------------
# Generate out-of-fold decision scores
# ---------------------------------------------------------

oof_scores = cross_val_predict(
    word_char_svm,
    X_text,
    y,
    cv=cv,
    method="decision_function"
)

# ---------------------------------------------------------
# Convert scores to predictions
# ---------------------------------------------------------

classes = np.unique(y)

predicted_indices = np.argmax(
    oof_scores,
    axis=1
)

predicted_intents = classes[predicted_indices]

# ---------------------------------------------------------
# Calculate classifier confidence margin
#
# Margin = highest class score - second highest score
# Larger margin = more confident prediction
# ---------------------------------------------------------

sorted_scores = np.sort(
    oof_scores,
    axis=1
)

top_score = sorted_scores[:, -1]
second_score = sorted_scores[:, -2]

margins = top_score - second_score

# ---------------------------------------------------------
# Build OOF results table
# ---------------------------------------------------------

oof_results = model_data[
    [
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "has_context",
        "intent"
    ]
].copy()

oof_results = oof_results.rename(
    columns={
        "intent": "true_intent"
    }
)

oof_results["predicted_intent"] = predicted_intents
oof_results["top_score"] = top_score
oof_results["second_score"] = second_score
oof_results["margin"] = margins

oof_results["is_error"] = (
    oof_results["true_intent"] !=
    oof_results["predicted_intent"]
)

# ---------------------------------------------------------
# Summary
# ---------------------------------------------------------

print("OOF evaluation recreated.")
print()
print("Examples:", len(oof_results))
print("Errors:", oof_results["is_error"].sum())
print(
    "Accuracy:",
    (~oof_results["is_error"]).mean()
)

print("\nClassification report:")
print(
    classification_report(
        oof_results["true_intent"],
        oof_results["predicted_intent"],
        zero_division=0
    )
)

print("\nMargin statistics:")
print(
    oof_results["margin"].describe()
)

OOF evaluation recreated.

Examples: 200
Errors: 100
Accuracy: 0.5

Classification report:
                        precision    recall  f1-score   support

account_authentication       0.65      0.72      0.68        18
        apple_services       0.32      0.28      0.30        25
        apps_app_store       0.58      0.70      0.64        20
                 audio       0.00      0.00      0.00        12
      battery_charging       0.76      0.84      0.80        19
         camera_photos       0.83      0.91      0.87        11
          connectivity       0.41      0.33      0.37        21
       device_hardware       0.42      0.33      0.37        15
         display_input       0.49      0.69      0.57        35
         icloud_backup       1.00      0.33      0.50         6
            ios_update       0.13      0.15      0.14        13
         other_unclear       0.00      0.00      0.00         5

              accuracy                           0.50       200
             macro avg       0.47      0.44      0.44       200
          weighted avg       0.47      0.50      0.48       200


Margin statistics:
count    200.000000
mean       0.286500
std        0.291065
min        0.000479
25%        0.066546
50%        0.191184
75%        0.420070
max        1.418725
Name: margin, dtype: float64

In [122]:
# ---------------------------------------------------------
# Top classifier confusion pairs
# ---------------------------------------------------------

confusions = (
    oof_results[oof_results["is_error"]]
    .groupby(
        ["true_intent", "predicted_intent"]
    )
    .size()
    .reset_index(name="count")
    .sort_values(
        "count",
        ascending=False
    )
    .reset_index(drop=True)
)

print("Top confusion pairs:\n")

display(
    confusions.head(15)
)

Top confusion pairs:

        true_intent predicted_intent  count
0      connectivity    display_input      6
1        ios_update    display_input      6
2     display_input       ios_update      5
3    apple_services     connectivity      4
4    apple_services   apps_app_store      4
5    apple_services       ios_update      3
6    apple_services    display_input      3
7        ios_update     connectivity      3
8    apps_app_store   apple_services      3
9     other_unclear    display_input      3
10    display_input   apple_services      3
11            audio    display_input      3
12            audio       ios_update      2
13            audio   apple_services      2
14  device_hardware    display_input      2

In [123]:
# ---------------------------------------------------------
# Reload Gemini API key
# ---------------------------------------------------------

from dotenv import load_dotenv
from google import genai
import os

load_dotenv(
    env_path,
    override=True
)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY was not found.")

print("Gemini API key loaded.")
print(
    "Key preview:",
    GEMINI_API_KEY[:8] + "..." + GEMINI_API_KEY[-4:]
)

gemini_client = genai.Client(
    api_key=GEMINI_API_KEY
)

print("Gemini client recreated.")

Gemini API key loaded.
Key preview: AQ.Ab8RN...DQ4g
Gemini client recreated.

In [124]:
# ---------------------------------------------------------
# Generate missing Gemini responses for the fixed 30-example
# evaluation set.
#
# Checkpoints after EVERY successful API call.
# Stops automatically on 429/quota errors.
# ---------------------------------------------------------

import json
import time
import pandas as pd

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

llm_judge_data = pd.read_csv(judge_path)

# ---------------------------------------------------------
# Identify missing responses
# ---------------------------------------------------------

missing_mask = (
    llm_judge_data["draft_reply"].isna()
)

pending_indices = llm_judge_data[
    missing_mask
].index.tolist()

print("Total evaluation examples:", len(llm_judge_data))
print("Existing generated replies:", (~missing_mask).sum())
print("Missing generated replies:", missing_mask.sum())

# ---------------------------------------------------------
# Generate responses
# ---------------------------------------------------------

successful = 0

for position, idx in enumerate(pending_indices, start=1):

    row = llm_judge_data.loc[idx]

    print(
        f"\n[{position}/{len(pending_indices)}] "
        f"Evaluation ID: {row['evaluation_id']}"
    )

    try:

        # Retrieve the same historical evidence used by the agent.
        retrieved_cases = retrieve_historical_cases(
            row["customer_message"],
            top_k=5
        )

        analysis = {
            "customer_message": row["customer_message"],
            "previous_message": row["previous_message"],
            "intent": row["predicted_intent"],
            "retrieved_cases": retrieved_cases,
            "top_similarity": row["top_similarity"]
        }

        # -------------------------------------------------
        # Gemini generation
        # -------------------------------------------------

        result = generate_support_response(
            analysis,
            model="gemini-3.5-flash"
        )

        # -------------------------------------------------
        # Deterministic escalation policy
        # -------------------------------------------------

        escalation = decide_escalation(
            intent=row["predicted_intent"],
            classifier_margin=row["classifier_margin"],
            top_similarity=row["top_similarity"],
            customer_message=row["customer_message"]
        )

        # -------------------------------------------------
        # Save generated response
        # -------------------------------------------------

        llm_judge_data.loc[idx, "draft_reply"] = (
            result["draft_reply"]
        )

        llm_judge_data.loc[idx, "evidence_used"] = json.dumps(
            result.get("evidence_used", [])
        )

        llm_judge_data.loc[idx, "escalate"] = (
            escalation["escalate"]
        )

        llm_judge_data.loc[idx, "escalation_reason"] = (
            escalation["escalation_reason"]
        )

        # Mark generation as completed.
        llm_judge_data.loc[idx, "has_generated_reply"] = True

        # -------------------------------------------------
        # CHECKPOINT IMMEDIATELY
        # -------------------------------------------------

        llm_judge_data.to_csv(
            judge_path,
            index=False
        )

        successful += 1

        print("Saved successfully.")
        print(
            "Intent:",
            row["predicted_intent"]
        )
        print(
            "Reply:",
            result["draft_reply"]
        )

        # Small delay between requests.
        time.sleep(2)

    except Exception as e:

        error_text = str(e)

        print("\nGemini request failed:")
        print(error_text)

        # Stop immediately for quota errors.
        if (
            "429" in error_text
            or "RESOURCE_EXHAUSTED" in error_text
            or "quota" in error_text.lower()
        ):
            print(
                "\nQuota error detected."
                "\nStopping. All successful responses are already saved."
            )
            break

        # Save non-quota error and continue.
        llm_judge_data.loc[
            idx,
            "generation_error"
        ] = error_text

        llm_judge_data.to_csv(
            judge_path,
            index=False
        )

print("\n" + "=" * 60)
print("GENERATION RUN COMPLETE")
print("=" * 60)

print("Successfully generated this run:", successful)

print(
    "Total generated:",
    llm_judge_data["draft_reply"].notna().sum()
)

print(
    "Still missing:",
    llm_judge_data["draft_reply"].isna().sum()
)

print("\nSaved to:")
print(judge_path)

Total evaluation examples: 30
Existing generated replies: 9
Missing generated replies: 21

[1/21] Evaluation ID: 10
Saved successfully.
Intent: apple_services
Reply: We'd like to look into this with you. Please send us a DM with your watchOS version, and we'll get started there.

[2/21] Evaluation ID: 11
Saved successfully.
Intent: display_input
Reply: We want to help get things working smoothly. We recently released iOS 11.1.1, which contains a fix for this autocorrect issue. Please back up your device prior to updating: https://t.co/4f8hwT5to6. If you still need help, DM us.

[3/21] Evaluation ID: 12
Saved successfully.
Intent: ios_update
Reply: We want to help get your iMessage working as soon as possible. Please send us a DM so we can look into this further and help find a solution.

[4/21] Evaluation ID: 13
Saved successfully.
Intent: display_input
Reply: We want to help you get this resolved. We've recently released an update to address these issues. Please back up your device and update. Here's how to back up: https://t.co/tHicJHB57O Once complete, tap Settings > General > Software Update.

[5/21] Evaluation ID: 14
Saved successfully.
Intent: connectivity
Reply: We'd love to help get FaceTime working for you. Could you let us know what device and software version you are using, and what exactly happens when you try to make a call?

[6/21] Evaluation ID: 15
Saved successfully.
Intent: account_authentication
Reply: We'd love to help you with your family's iCloud accounts and make sure no game data is lost. Please join us in DM so we can gather more details and guide you through this: https://t.co/GDrqU22YpT

[7/21] Evaluation ID: 16

Gemini request failed:
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.5-flash\nPlease retry in 24.267572255s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '24s'}]}}

Quota error detected.
Stopping. All successful responses are already saved.

============================================================
GENERATION RUN COMPLETE
============================================================
Successfully generated this run: 6
Total generated: 15
Still missing: 15

Saved to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_llm_judge_30.csv

In [125]:
# ---------------------------------------------------------
# Continue Gemini generation with automatic rate-limit wait
# ---------------------------------------------------------

import json
import time
import pandas as pd

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

llm_judge_data = pd.read_csv(judge_path)

missing_mask = llm_judge_data["draft_reply"].isna()
pending_indices = llm_judge_data[missing_mask].index.tolist()

print("Total examples:", len(llm_judge_data))
print(
    "Already generated:",
    (~missing_mask).sum()
)
print(
    "Still missing:",
    missing_mask.sum()
)

successful = 0

for position, idx in enumerate(pending_indices, start=1):

    row = llm_judge_data.loc[idx]

    print(
        f"\n[{position}/{len(pending_indices)}] "
        f"Evaluation ID: {row['evaluation_id']}"
    )

    # -----------------------------------------------------
    # Retry this example if we hit the per-minute limit
    # -----------------------------------------------------

    while True:

        try:

            retrieved_cases = retrieve_historical_cases(
                row["customer_message"],
                top_k=5
            )

            analysis = {
                "customer_message": row["customer_message"],
                "previous_message": row["previous_message"],
                "intent": row["predicted_intent"],
                "retrieved_cases": retrieved_cases,
                "top_similarity": row["top_similarity"]
            }

            result = generate_support_response(
                analysis,
                model="gemini-3.5-flash"
            )

            # -------------------------------------------------
            # Deterministic escalation
            # -------------------------------------------------

            escalation = decide_escalation(
                intent=row["predicted_intent"],
                classifier_margin=row["classifier_margin"],
                top_similarity=row["top_similarity"],
                customer_message=row["customer_message"]
            )

            # -------------------------------------------------
            # Save response
            # -------------------------------------------------

            llm_judge_data.loc[
                idx,
                "draft_reply"
            ] = result["draft_reply"]

            llm_judge_data.loc[
                idx,
                "evidence_used"
            ] = json.dumps(
                result.get("evidence_used", [])
            )

            llm_judge_data.loc[
                idx,
                "escalate"
            ] = escalation["escalate"]

            llm_judge_data.loc[
                idx,
                "escalation_reason"
            ] = escalation["escalation_reason"]

            llm_judge_data.loc[
                idx,
                "has_generated_reply"
            ] = True

            # -------------------------------------------------
            # CHECKPOINT
            # -------------------------------------------------

            llm_judge_data.to_csv(
                judge_path,
                index=False
            )

            successful += 1

            print("Saved successfully.")
            print(
                "Intent:",
                row["predicted_intent"]
            )
            print(
                "Reply:",
                result["draft_reply"]
            )

            # Wait between requests to stay safely below
            # the 5 requests/minute free-tier limit.
            time.sleep(15)

            break

        except Exception as e:

            error_text = str(e)

            print("\nGemini request failed:")
            print(error_text)

            # -------------------------------------------------
            # Per-minute quota
            # -------------------------------------------------

            if (
                "429" in error_text
                or "RESOURCE_EXHAUSTED" in error_text
            ):

                print(
                    "\nRate limit reached."
                )

                print(
                    "Waiting 35 seconds before retrying..."
                )

                time.sleep(35)

                print(
                    "Retrying same evaluation..."
                )

                continue

            # -------------------------------------------------
            # Other error
            # -------------------------------------------------

            llm_judge_data.loc[
                idx,
                "generation_error"
            ] = error_text

            llm_judge_data.to_csv(
                judge_path,
                index=False
            )

            print(
                "Non-quota error. Skipping this example."
            )

            break


print("\n" + "=" * 60)
print("GENERATION RUN COMPLETE")
print("=" * 60)

print(
    "Generated during this run:",
    successful
)

print(
    "Total generated:",
    llm_judge_data["draft_reply"].notna().sum()
)

print(
    "Still missing:",
    llm_judge_data["draft_reply"].isna().sum()
)

print("\nSaved to:")
print(judge_path)

Total examples: 30
Already generated: 15
Still missing: 15

[1/15] Evaluation ID: 16
Saved successfully.
Intent: display_input
Reply: Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9

[2/15] Evaluation ID: 17
Saved successfully.
Intent: apple_services
Reply: We'd love to assist you with the issues you're experiencing after the update. Please DM us with more details, including your iOS version, so we can help. https://t.co/GDrqU22YpT

[3/15] Evaluation ID: 18
Saved successfully.
Intent: audio
Reply: We're here to help. Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9. Please DM us with your iPhone model and iOS version so we can look into this with you.

[4/15] Evaluation ID: 19
Saved successfully.
Intent: apple_services
Reply: We'd like to help with the green line on your iPhone X. Please send us a DM with your location and the iOS version you are currently running so we can investigate further. https://t.co/GDrqU22YpT

[5/15] Evaluation ID: 20
Saved successfully.
Intent: apps_app_store
Reply: We're here for you. Let's take a look at this further for you. Reach out to us in DM.

[6/15] Evaluation ID: 21
Saved successfully.
Intent: apple_services
Reply: We want your device to work seamlessly. Join us in DM with more details about what's happening, and we'll take a look into this with you. https://t.co/GDrqU22YpT

[7/15] Evaluation ID: 22
Saved successfully.
Intent: ios_update
Reply: Understood. Let's hop in DM to look into this screen issue and continue there. Click here: https://t.co/GDrqU22YpT

[8/15] Evaluation ID: 23
Saved successfully.
Intent: apple_services
Reply: We know how important it is to have access to your account. If you do not know your trusted number, you may need the assistance of our specialized Account Security team. Please review the support options on the following page to get started: https://t.co/UJm15vmMM2

[9/15] Evaluation ID: 24
Saved successfully.
Intent: display_input
Reply: We're here to help. An update has been released that addresses this issue. If you haven't already, back up your device and update to iOS version 11.1.1. For more information, click here: https://t.co/xXaXeeSRt9 DM us if you have questions. https://t.co/GDrqU22YpT

[10/15] Evaluation ID: 25
Saved successfully.
Intent: ios_update
Reply: Thanks for sharing those settings. To help us get a better look at this, what is the exact iOS version you are currently using? You can also send us a DM so we can work together on this: https://t.co/GDrqU22YpT

[11/15] Evaluation ID: 26
Saved successfully.
Intent: display_input
Reply: We'd like to help look into this display issue with you. Could you let us know which iOS version you're currently using? Please send us a DM so we can continue troubleshooting together. https://t.co/GDrqU22YpT

[12/15] Evaluation ID: 27
Saved successfully.
Intent: account_authentication
Reply: We know how important your photos are. Let's get this resolved. Send us a DM so we can look into this together. https://t.co/GDrqU22YpT

[13/15] Evaluation ID: 28
Saved successfully.
Intent: apple_services
Reply: We'd love to help look into this with you. To get started, which specific version of iOS 11 is currently installed? Also, does this happen in all apps where you view videos, or just a specific one? Send us a DM with these details so we can help.

[14/15] Evaluation ID: 29
Saved successfully.
Intent: device_hardware
Reply: While Strength Training is not a default option, it can be added to your Apple Watch. Check out how to use "Name your workout" to add it here: https://t.co/FJrx17fPef

[15/15] Evaluation ID: 30
Saved successfully.
Intent: battery_charging
Reply: We'd like to help look into this with you. Go ahead and reach out to us in DM and we'll continue there.

============================================================
GENERATION RUN COMPLETE
============================================================
Generated during this run: 15
Total generated: 30
Still missing: 0

Saved to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_llm_judge_30.csv

In [126]:
# ---------------------------------------------------------
# Final LLM-as-judge rubric
# ---------------------------------------------------------

JUDGE_RUBRIC = """
You are evaluating an AI-generated customer-support reply for AppleSupport.

Your job is to judge the QUALITY OF THE REPLY, not whether the
classification label is correct.

Use only:
- the customer message
- previous message, if available
- predicted intent
- retrieved historical AppleSupport cases
- AI-generated reply

Evaluate the following dimensions.

1. relevance (1-5)
5 = Directly addresses the customer's actual problem.
4 = Mostly addresses the problem with minor omissions.
3 = Partially relevant but misses an important aspect.
2 = Mostly unrelated or poorly targeted.
1 = Does not address the customer's problem.

2. grounding (1-5)
5 = The reply is strongly consistent with the historical AppleSupport
    responses provided as evidence.
4 = Mostly supported by historical evidence.
3 = Some support exists, but important parts are weakly grounded.
2 = Mostly introduces information not supported by the evidence.
1 = Contradicts or ignores the historical evidence.

3. helpfulness (1-5)
5 = Provides a useful and appropriate next step.
4 = Useful but could be more specific.
3 = Somewhat useful but incomplete.
2 = Provides little practical help.
1 = Not useful.

4. overall_quality (1-5)
5 = Strong response suitable for the situation.
4 = Good response with minor issues.
3 = Acceptable but noticeably incomplete.
2 = Poor response requiring substantial revision.
1 = Unacceptable.

5. unsupported_claim (0-1)
1 = The reply contains at least one factual claim, troubleshooting
    instruction, guarantee, policy statement, or URL that is not
    supported by the provided historical evidence or customer context.
0 = No clearly unsupported claim.

Also provide:
- short_reason: concise explanation of the evaluation
- major_issue: the most important problem, or "none"

Return ONLY valid JSON:

{
    "relevance": 1,
    "grounding": 1,
    "helpfulness": 1,
    "overall_quality": 1,
    "unsupported_claim": 0,
    "short_reason": "...",
    "major_issue": "..."
}
"""


def build_judge_prompt(row, retrieved_cases):
    """
    Build the final unbiased LLM-as-judge prompt.
    True intent is deliberately NOT provided to the judge.
    """

    return f"""
{JUDGE_RUBRIC}

CUSTOMER MESSAGE:
{row["customer_message"]}

PREVIOUS MESSAGE:
{row["previous_message"]}

PREDICTED INTENT:
{row["predicted_intent"]}

RETRIEVED HISTORICAL APPLESUPPORT CASES:
{retrieved_cases}

AI-GENERATED REPLY:
{row["draft_reply"]}
"""

In [127]:
# ---------------------------------------------------------
# Run LLM-as-judge on all generated examples
#
# Features:
# - checkpoints after every successful evaluation
# - 15-second spacing for 5 requests/minute limit
# - automatic 35-second wait on 429
# - stops on daily quota
# ---------------------------------------------------------

import json
import time
import pandas as pd

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

judge_data = pd.read_csv(judge_path)

# ---------------------------------------------------------
# Ensure tracking columns exist
# ---------------------------------------------------------

if "judge_completed" not in judge_data.columns:
    judge_data["judge_completed"] = False

judge_data["judge_completed"] = (
    judge_data["judge_completed"]
    .fillna(False)
    .astype(bool)
)

# ---------------------------------------------------------
# Find pending evaluations
# ---------------------------------------------------------

pending_mask = (
    judge_data["draft_reply"].notna()
    & ~judge_data["judge_completed"]
)

pending_indices = judge_data[pending_mask].index.tolist()

print("Total examples:", len(judge_data))
print("Generated replies:", judge_data["draft_reply"].notna().sum())
print("Already judged:", judge_data["judge_completed"].sum())
print("Pending judge evaluations:", len(pending_indices))

# ---------------------------------------------------------
# Run judge
# ---------------------------------------------------------

successful = 0

for position, idx in enumerate(pending_indices, start=1):

    row = judge_data.loc[idx]

    print(
        f"\n[{position}/{len(pending_indices)}] "
        f"Evaluation ID: {row['evaluation_id']}"
    )

    while True:

        try:

            # ---------------------------------------------
            # Retrieve the same historical evidence
            # ---------------------------------------------

            retrieved_cases = retrieve_historical_cases(
                row["customer_message"],
                top_k=5
            )

            formatted_cases = format_retrieved_cases(
                row["customer_message"],
                top_k=5
            )

            # ---------------------------------------------
            # Build unbiased judge prompt
            # ---------------------------------------------

            prompt = build_judge_prompt(
                row,
                formatted_cases
            )

            # ---------------------------------------------
            # Gemini judge call
            # ---------------------------------------------

            response = gemini_client.models.generate_content(
                model="gemini-3.5-flash",
                contents=prompt,
                config={
                    "temperature": 0.0,
                    "response_mime_type": "application/json"
                }
            )

            judge_result = parse_judge_response(
                response.text
            )

            # ---------------------------------------------
            # Save result
            # ---------------------------------------------

            for key, value in judge_result.items():

                judge_data.loc[
                    idx,
                    f"judge_{key}"
                ] = value

            judge_data.loc[
                idx,
                "judge_completed"
            ] = True

            # ---------------------------------------------
            # CHECKPOINT
            # ---------------------------------------------

            judge_data.to_csv(
                judge_path,
                index=False
            )

            successful += 1

            print(
                "Overall quality:",
                judge_result["overall_quality"]
            )

            print(
                "Unsupported claim:",
                judge_result["unsupported_claim"]
            )

            # Stay below 5 requests/minute.
            time.sleep(15)

            break

        except Exception as e:

            error_text = str(e)

            print("\nJudge request failed:")
            print(error_text)

            # ---------------------------------------------
            # Rate limit
            # ---------------------------------------------

            if "429" in error_text:

                # Daily quota is different from per-minute quota.
                daily_quota = (
                    "PerDay" in error_text
                    or "per_day" in error_text.lower()
                    or "daily" in error_text.lower()
                )

                if daily_quota:
                    print(
                        "\nDaily Gemini quota reached."
                        "\nStopping safely."
                    )
                    break

                print(
                    "\nPer-minute rate limit reached."
                    "\nWaiting 35 seconds..."
                )

                time.sleep(35)

                print("Retrying...")
                continue

            # ---------------------------------------------
            # Other errors
            # ---------------------------------------------

            judge_data.loc[
                idx,
                "judge_error"
            ] = error_text

            judge_data.to_csv(
                judge_path,
                index=False
            )

            print(
                "Non-quota error. Skipping this example."
            )

            break

    # Stop outer loop if daily quota was hit.
    if (
        "error_text" in locals()
        and "429" in error_text
        and (
            "PerDay" in error_text
            or "per_day" in error_text.lower()
            or "daily" in error_text.lower()
        )
    ):
        break


print("\n" + "=" * 60)
print("LLM JUDGE RUN COMPLETE")
print("=" * 60)

print(
    "Successfully judged this run:",
    successful
)

print(
    "Total judged:",
    judge_data["judge_completed"].sum()
)

print(
    "Remaining:",
    (
        judge_data["draft_reply"].notna()
        & ~judge_data["judge_completed"]
    ).sum()
)

print("\nSaved to:")
print(judge_path)

Total examples: 30
Generated replies: 30
Already judged: 0
Pending judge evaluations: 30

[1/30] Evaluation ID: 1

Judge request failed:
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-3.5-flash\nPlease retry in 11.981616536s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '11s'}]}}

Daily Gemini quota reached.
Stopping safely.

============================================================
LLM JUDGE RUN COMPLETE
============================================================
Successfully judged this run: 0
Total judged: 0
Remaining: 30

Saved to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_llm_judge_30.csv

In [128]:
from dotenv import load_dotenv
from google import genai
import os

load_dotenv(env_path, override=True)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

gemini_client = genai.Client(
    api_key=GEMINI_API_KEY
)

print("Gemini client updated.")
print(
    "Key:",
    GEMINI_API_KEY[:8] + "..." + GEMINI_API_KEY[-4:]
)

Gemini client updated.
Key: AQ.Ab8RN...kVuw

In [130]:
# ---------------------------------------------------------
# Prepare judge dataset for the new Gemini key
# No Gemini API call yet
# ---------------------------------------------------------

import pandas as pd
import json

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

judge_data = pd.read_csv(judge_path)

# Create tracking column if it doesn't exist.
if "judge_completed" not in judge_data.columns:
    judge_data["judge_completed"] = False

judge_data["judge_completed"] = (
    judge_data["judge_completed"]
    .fillna(False)
    .astype(bool)
)

print("Judge dataset prepared.")
print("Total examples:", len(judge_data))
print(
    "Generated replies:",
    judge_data["draft_reply"].notna().sum()
)
print(
    "Already judged:",
    judge_data["judge_completed"].sum()
)

Judge dataset prepared.
Total examples: 30
Generated replies: 30
Already judged: 0

In [131]:
# ---------------------------------------------------------
# Test ONE Gemini judge request
# ---------------------------------------------------------

pending = judge_data[
    ~judge_data["judge_completed"]
]

if len(pending) == 0:
    print("All examples have already been judged.")
else:

    test_row = pending.iloc[0]

    print(
        "Testing evaluation ID:",
        test_row["evaluation_id"]
    )

    formatted_cases = format_retrieved_cases(
        test_row["customer_message"],
        top_k=5
    )

    prompt = build_judge_prompt(
        test_row,
        formatted_cases
    )

    try:

        response = gemini_client.models.generate_content(
            model="gemini-3.5-flash",
            contents=prompt,
            config={
                "temperature": 0.0,
                "response_mime_type": "application/json"
            }
        )

        result = parse_judge_response(
            response.text
        )

        print("\nSUCCESS — Gemini judge responded.")
        print(
            json.dumps(
                result,
                indent=2
            )
        )

    except Exception as e:

        print("\nGemini request failed:")
        print(e)

Testing evaluation ID: 1

SUCCESS — Gemini judge responded.
{
  "relevance": 5,
  "grounding": 5,
  "helpfulness": 4,
  "overall_quality": 4,
  "unsupported_claim": 0,
  "short_reason": "The reply is highly relevant to the customer's query about Siri and third-party apps, and it aligns perfectly with the historical support cases which consistently direct customers to DM for assistance.",
  "major_issue": "none"
}

In [132]:
# ---------------------------------------------------------
# Complete LLM-as-Judge evaluation
# ---------------------------------------------------------

import json
import time
import pandas as pd

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

judge_data = pd.read_csv(judge_path)

# ---------------------------------------------------------
# Prepare tracking columns
# ---------------------------------------------------------

if "judge_completed" not in judge_data.columns:
    judge_data["judge_completed"] = False

judge_data["judge_completed"] = (
    judge_data["judge_completed"]
    .fillna(False)
    .astype(bool)
)

# ---------------------------------------------------------
# Save the successful test result for Evaluation ID 1
# ---------------------------------------------------------

test_id = test_row["evaluation_id"]

for key, value in result.items():
    judge_data.loc[
        judge_data["evaluation_id"] == test_id,
        f"judge_{key}"
    ] = value

judge_data.loc[
    judge_data["evaluation_id"] == test_id,
    "judge_completed"
] = True

judge_data.to_csv(
    judge_path,
    index=False
)

print(
    f"Saved successful test judgment for Evaluation ID {test_id}."
)

# ---------------------------------------------------------
# Find remaining examples
# ---------------------------------------------------------

pending_mask = (
    judge_data["draft_reply"].notna()
    & ~judge_data["judge_completed"]
)

pending_indices = judge_data[pending_mask].index.tolist()

print(
    "\nRemaining judge evaluations:",
    len(pending_indices)
)

# ---------------------------------------------------------
# Run remaining evaluations
# ---------------------------------------------------------

successful = 0

for position, idx in enumerate(
    pending_indices,
    start=1
):

    row = judge_data.loc[idx]

    print(
        f"\n[{position}/{len(pending_indices)}] "
        f"Evaluation ID: {row['evaluation_id']}"
    )

    while True:

        try:

            # ---------------------------------------------
            # Retrieve historical evidence
            # ---------------------------------------------

            formatted_cases = format_retrieved_cases(
                row["customer_message"],
                top_k=5
            )

            # ---------------------------------------------
            # Build judge prompt
            # ---------------------------------------------

            prompt = build_judge_prompt(
                row,
                formatted_cases
            )

            # ---------------------------------------------
            # Gemini judge
            # ---------------------------------------------

            response = gemini_client.models.generate_content(
                model="gemini-3.5-flash",
                contents=prompt,
                config={
                    "temperature": 0.0,
                    "response_mime_type": "application/json"
                }
            )

            judge_result = parse_judge_response(
                response.text
            )

            # ---------------------------------------------
            # Store result
            # ---------------------------------------------

            for key, value in judge_result.items():

                judge_data.loc[
                    idx,
                    f"judge_{key}"
                ] = value

            judge_data.loc[
                idx,
                "judge_completed"
            ] = True

            # ---------------------------------------------
            # Checkpoint
            # ---------------------------------------------

            judge_data.to_csv(
                judge_path,
                index=False
            )

            successful += 1

            print(
                "Overall quality:",
                judge_result["overall_quality"]
            )

            print(
                "Unsupported claim:",
                judge_result["unsupported_claim"]
            )

            # Stay safely below 5 requests/minute.
            time.sleep(15)

            break

        except Exception as e:

            error_text = str(e)

            print("\nJudge request failed:")
            print(error_text)

            # ---------------------------------------------
            # 429 rate limit
            # ---------------------------------------------

            if "429" in error_text:

                # Daily quota
                if (
                    "PerDay" in error_text
                    or "per_day" in error_text.lower()
                    or "perday" in error_text.lower()
                    or "GenerateRequestsPerDay" in error_text
                ):

                    print(
                        "\nDaily quota reached."
                        "\nStopping safely."
                    )

                    break

                # Per-minute quota
                print(
                    "\nPer-minute quota reached."
                    "\nWaiting 35 seconds..."
                )

                time.sleep(35)

                print(
                    "Retrying same evaluation..."
                )

                continue

            # ---------------------------------------------
            # Other error
            # ---------------------------------------------

            judge_data.loc[
                idx,
                "judge_error"
            ] = error_text

            judge_data.to_csv(
                judge_path,
                index=False
            )

            print(
                "Non-quota error. Skipping."
            )

            break

    # Stop if daily quota was reached.
    if (
        "error_text" in locals()
        and "429" in error_text
        and (
            "PerDay" in error_text
            or "per_day" in error_text.lower()
            or "perday" in error_text.lower()
            or "GenerateRequestsPerDay" in error_text
        )
    ):
        break


# ---------------------------------------------------------
# Final status
# ---------------------------------------------------------

judge_data = pd.read_csv(judge_path)

judge_completed = (
    judge_data["judge_completed"]
    .fillna(False)
    .astype(bool)
)

print("\n" + "=" * 60)
print("LLM JUDGE COMPLETE")
print("=" * 60)

print(
    "Total examples:",
    len(judge_data)
)

print(
    "Generated replies:",
    judge_data["draft_reply"].notna().sum()
)

print(
    "Judged:",
    judge_completed.sum()
)

print(
    "Remaining:",
    (
        judge_data["draft_reply"].notna()
        & ~judge_completed
    ).sum()
)

print("\nSaved to:")
print(judge_path)

Saved successful test judgment for Evaluation ID 1.

Remaining judge evaluations: 29

[1/29] Evaluation ID: 2
Overall quality: 5
Unsupported claim: 0

============================================================
LLM JUDGE COMPLETE
============================================================
Total examples: 30
Generated replies: 30
Judged: 2
Remaining: 28

Saved to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_llm_judge_30.csv

In [133]:
# ---------------------------------------------------------
# Continue LLM-as-Judge evaluation
# Fixed quota handling
# ---------------------------------------------------------

import json
import time
import pandas as pd

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

judge_data = pd.read_csv(judge_path)

# ---------------------------------------------------------
# Prepare tracking column
# ---------------------------------------------------------

if "judge_completed" not in judge_data.columns:
    judge_data["judge_completed"] = False

judge_data["judge_completed"] = (
    judge_data["judge_completed"]
    .fillna(False)
    .astype(bool)
)

# ---------------------------------------------------------
# Find pending examples
# ---------------------------------------------------------

pending_mask = (
    judge_data["draft_reply"].notna()
    & ~judge_data["judge_completed"]
)

pending_indices = judge_data[pending_mask].index.tolist()

print("Total examples:", len(judge_data))
print(
    "Already judged:",
    judge_data["judge_completed"].sum()
)
print(
    "Pending:",
    len(pending_indices)
)

# ---------------------------------------------------------
# We already used 2 requests on this new project today.
# Maximum additional calls before the 20/day limit:
# 20 - 2 = 18
# ---------------------------------------------------------

MAX_NEW_CALLS = 18

print(
    "Maximum calls in this run:",
    min(MAX_NEW_CALLS, len(pending_indices))
)

successful = 0
daily_quota_hit = False

# ---------------------------------------------------------
# Process pending examples
# ---------------------------------------------------------

for position, idx in enumerate(
    pending_indices[:MAX_NEW_CALLS],
    start=1
):

    row = judge_data.loc[idx]

    print(
        f"\n[{position}/{min(MAX_NEW_CALLS, len(pending_indices))}] "
        f"Evaluation ID: {row['evaluation_id']}"
    )

    # ---------------------------------------------
    # Retry only for temporary rate limits
    # ---------------------------------------------

    while True:

        try:

            formatted_cases = format_retrieved_cases(
                row["customer_message"],
                top_k=5
            )

            prompt = build_judge_prompt(
                row,
                formatted_cases
            )

            response = gemini_client.models.generate_content(
                model="gemini-3.5-flash",
                contents=prompt,
                config={
                    "temperature": 0.0,
                    "response_mime_type": "application/json"
                }
            )

            judge_result = parse_judge_response(
                response.text
            )

            # -----------------------------------------
            # Save judge result
            # -----------------------------------------

            for key, value in judge_result.items():

                judge_data.loc[
                    idx,
                    f"judge_{key}"
                ] = value

            judge_data.loc[
                idx,
                "judge_completed"
            ] = True

            # -----------------------------------------
            # Checkpoint immediately
            # -----------------------------------------

            judge_data.to_csv(
                judge_path,
                index=False
            )

            successful += 1

            print(
                "Saved successfully."
            )

            print(
                "Overall quality:",
                judge_result["overall_quality"]
            )

            print(
                "Unsupported claim:",
                judge_result["unsupported_claim"]
            )

            # 4 requests/minute maximum.
            time.sleep(15)

            break

        except Exception as e:

            error_text = str(e)

            print(
                "\nJudge request failed:"
            )
            print(error_text)

            # -----------------------------------------
            # Daily quota
            # -----------------------------------------

            if (
                "GenerateRequestsPerDay" in error_text
                or "PerDayPerProject" in error_text
                or "daily" in error_text.lower()
            ):

                print(
                    "\nDaily quota reached."
                )

                daily_quota_hit = True
                break

            # -----------------------------------------
            # Per-minute quota
            # -----------------------------------------

            if "429" in error_text:

                print(
                    "\nPer-minute rate limit."
                    "\nWaiting 35 seconds..."
                )

                time.sleep(35)

                print(
                    "Retrying same evaluation..."
                )

                continue

            # -----------------------------------------
            # Other error
            # -----------------------------------------

            judge_data.loc[
                idx,
                "judge_error"
            ] = error_text

            judge_data.to_csv(
                judge_path,
                index=False
            )

            print(
                "Non-quota error. Skipping."
            )

            break

    # Stop only if THIS run actually hit daily quota.
    if daily_quota_hit:
        break


# ---------------------------------------------------------
# Final status
# ---------------------------------------------------------

judge_data = pd.read_csv(judge_path)

judge_completed = (
    judge_data["judge_completed"]
    .fillna(False)
    .astype(bool)
)

print("\n" + "=" * 60)
print("LLM JUDGE RUN COMPLETE")
print("=" * 60)

print(
    "New judgments this run:",
    successful
)

print(
    "Total judged:",
    judge_completed.sum()
)

print(
    "Remaining:",
    (
        judge_data["draft_reply"].notna()
        & ~judge_completed
    ).sum()
)

print("\nSaved to:")
print(judge_path)

Total examples: 30
Already judged: 2
Pending: 28
Maximum calls in this run: 18

[1/18] Evaluation ID: 3
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[2/18] Evaluation ID: 4
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[3/18] Evaluation ID: 5
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[4/18] Evaluation ID: 6
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[5/18] Evaluation ID: 7
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[6/18] Evaluation ID: 8
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[7/18] Evaluation ID: 9
Saved successfully.
Overall quality: 4
Unsupported claim: 0

[8/18] Evaluation ID: 10
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[9/18] Evaluation ID: 11
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[10/18] Evaluation ID: 12
Saved successfully.
Overall quality: 4
Unsupported claim: 0

[11/18] Evaluation ID: 13
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[12/18] Evaluation ID: 14
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[13/18] Evaluation ID: 15
Saved successfully.
Overall quality: 4
Unsupported claim: 0

[14/18] Evaluation ID: 16
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[15/18] Evaluation ID: 17
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[16/18] Evaluation ID: 18
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[17/18] Evaluation ID: 19
Saved successfully.
Overall quality: 5
Unsupported claim: 0

[18/18] Evaluation ID: 20
Saved successfully.
Overall quality: 4
Unsupported claim: 0

============================================================
LLM JUDGE RUN COMPLETE
============================================================
New judgments this run: 18
Total judged: 20
Remaining: 10

Saved to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_llm_judge_30.csv

In [134]:
from dotenv import load_dotenv
from google import genai
import os

load_dotenv(env_path, override=True)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

gemini_client = genai.Client(
    api_key=GEMINI_API_KEY
)

print("Last Gemini API key loaded.")

Last Gemini API key loaded.

In [135]:
# ---------------------------------------------------------
# Test the last API key with ONE judge request
# ---------------------------------------------------------

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

judge_data = pd.read_csv(judge_path)

if "judge_completed" not in judge_data.columns:
    judge_data["judge_completed"] = False

judge_data["judge_completed"] = (
    judge_data["judge_completed"]
    .fillna(False)
    .astype(bool)
)

pending = judge_data[
    judge_data["draft_reply"].notna()
    & ~judge_data["judge_completed"]
]

print("Remaining:", len(pending))

test_row = pending.iloc[0]

formatted_cases = format_retrieved_cases(
    test_row["customer_message"],
    top_k=5
)

prompt = build_judge_prompt(
    test_row,
    formatted_cases
)

try:
    response = gemini_client.models.generate_content(
        model="gemini-3.5-flash",
        contents=prompt,
        config={
            "temperature": 0.0,
            "response_mime_type": "application/json"
        }
    )

    test_judge_result = parse_judge_response(
        response.text
    )

    print("\nSUCCESS")
    print(json.dumps(test_judge_result, indent=2))

except Exception as e:
    print("\nFAILED")
    print(e)

Remaining: 10

SUCCESS
{
  "relevance": 5,
  "grounding": 5,
  "helpfulness": 4,
  "overall_quality": 4,
  "unsupported_claim": 0,
  "short_reason": "The reply is polite, relevant, and strongly grounded in the provided historical cases, offering a standard DM transition to troubleshoot the issues.",
  "major_issue": "none"
}

In [136]:
# ---------------------------------------------------------
# Finish the remaining LLM-as-judge evaluations
# ---------------------------------------------------------

import json
import time
import pandas as pd

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

judge_data = pd.read_csv(judge_path)

if "judge_completed" not in judge_data.columns:
    judge_data["judge_completed"] = False

judge_data["judge_completed"] = (
    judge_data["judge_completed"]
    .fillna(False)
    .astype(bool)
)

# ---------------------------------------------------------
# Save the successful test result
# ---------------------------------------------------------

test_id = test_row["evaluation_id"]

if not judge_data.loc[
    judge_data["evaluation_id"] == test_id,
    "judge_completed"
].iloc[0]:

    for key, value in test_judge_result.items():
        judge_data.loc[
            judge_data["evaluation_id"] == test_id,
            f"judge_{key}"
        ] = value

    judge_data.loc[
        judge_data["evaluation_id"] == test_id,
        "judge_completed"
    ] = True

    judge_data.to_csv(
        judge_path,
        index=False
    )

    print(
        f"Saved test judgment: Evaluation ID {test_id}"
    )

# ---------------------------------------------------------
# Find remaining
# ---------------------------------------------------------

pending_mask = (
    judge_data["draft_reply"].notna()
    & ~judge_data["judge_completed"]
)

pending_indices = judge_data[pending_mask].index.tolist()

print(
    "\nRemaining judge evaluations:",
    len(pending_indices)
)

successful = 0
daily_quota_hit = False

# ---------------------------------------------------------
# Process remaining examples
# ---------------------------------------------------------

for position, idx in enumerate(
    pending_indices,
    start=1
):

    row = judge_data.loc[idx]

    print(
        f"\n[{position}/{len(pending_indices)}] "
        f"Evaluation ID: {row['evaluation_id']}"
    )

    while True:

        try:

            formatted_cases = format_retrieved_cases(
                row["customer_message"],
                top_k=5
            )

            prompt = build_judge_prompt(
                row,
                formatted_cases
            )

            response = gemini_client.models.generate_content(
                model="gemini-3.5-flash",
                contents=prompt,
                config={
                    "temperature": 0.0,
                    "response_mime_type": "application/json"
                }
            )

            judge_result = parse_judge_response(
                response.text
            )

            # Save scores
            for key, value in judge_result.items():

                judge_data.loc[
                    idx,
                    f"judge_{key}"
                ] = value

            judge_data.loc[
                idx,
                "judge_completed"
            ] = True

            # Checkpoint
            judge_data.to_csv(
                judge_path,
                index=False
            )

            successful += 1

            print(
                "Overall quality:",
                judge_result["overall_quality"]
            )

            print(
                "Unsupported claim:",
                judge_result["unsupported_claim"]
            )

            # Stay below 5 requests/minute.
            time.sleep(15)

            break

        except Exception as e:

            error_text = str(e)

            print("\nRequest failed:")
            print(error_text)

            # Daily quota
            if (
                "GenerateRequestsPerDay" in error_text
                or "PerDayPerProject" in error_text
            ):

                print(
                    "\nDaily quota reached. "
                    "Stopping safely."
                )

                daily_quota_hit = True
                break

            # Per-minute quota
            if "429" in error_text:

                print(
                    "\nPer-minute limit reached."
                    "\nWaiting 35 seconds..."
                )

                time.sleep(35)
                continue

            # Other error
            judge_data.loc[
                idx,
                "judge_error"
            ] = error_text

            judge_data.to_csv(
                judge_path,
                index=False
            )

            print("Skipping this example.")
            break

    if daily_quota_hit:
        break


# ---------------------------------------------------------
# Final status
# ---------------------------------------------------------

judge_data = pd.read_csv(judge_path)

completed = (
    judge_data["judge_completed"]
    .fillna(False)
    .astype(bool)
)

print("\n" + "=" * 60)
print("FINAL JUDGE STATUS")
print("=" * 60)

print("Total examples:", len(judge_data))
print("Generated replies:", judge_data["draft_reply"].notna().sum())
print("Judged:", completed.sum())
print(
    "Remaining:",
    (
        judge_data["draft_reply"].notna()
        & ~completed
    ).sum()
)

print("\nSaved to:")
print(judge_path)

Saved test judgment: Evaluation ID 21

Remaining judge evaluations: 9

[1/9] Evaluation ID: 22
Overall quality: 5
Unsupported claim: 0

[2/9] Evaluation ID: 23
Overall quality: 5
Unsupported claim: 0

[3/9] Evaluation ID: 24
Overall quality: 5
Unsupported claim: 0

[4/9] Evaluation ID: 25
Overall quality: 5
Unsupported claim: 0

[5/9] Evaluation ID: 26
Overall quality: 5
Unsupported claim: 0

[6/9] Evaluation ID: 27
Overall quality: 5
Unsupported claim: 0

[7/9] Evaluation ID: 28
Overall quality: 5
Unsupported claim: 0

[8/9] Evaluation ID: 29
Overall quality: 5
Unsupported claim: 0

[9/9] Evaluation ID: 30
Overall quality: 4
Unsupported claim: 0

============================================================
FINAL JUDGE STATUS
============================================================
Total examples: 30
Generated replies: 30
Judged: 30
Remaining: 0

Saved to:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_llm_judge_30.csv

In [137]:
# ---------------------------------------------------------
# FINAL LLM-AS-JUDGE METRICS
# No API call
# ---------------------------------------------------------

import pandas as pd
import numpy as np

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

judge_data = pd.read_csv(judge_path)

judge_data["judge_completed"] = (
    judge_data["judge_completed"]
    .fillna(False)
    .astype(bool)
)

completed = judge_data[
    judge_data["judge_completed"]
].copy()

print("=" * 60)
print("FINAL LLM-AS-JUDGE RESULTS")
print("=" * 60)

print("Total evaluation examples:", len(judge_data))
print("Generated replies:", judge_data["draft_reply"].notna().sum())
print("Completed judgments:", len(completed))

# ---------------------------------------------------------
# Convert scores
# ---------------------------------------------------------

score_cols = [
    "judge_relevance",
    "judge_grounding",
    "judge_helpfulness",
    "judge_overall_quality",
    "judge_unsupported_claim"
]

for col in score_cols:
    completed[col] = pd.to_numeric(
        completed[col],
        errors="coerce"
    )

# ---------------------------------------------------------
# Overall metrics
# ---------------------------------------------------------

metrics = {
    "examples_judged": len(completed),
    "mean_relevance": completed["judge_relevance"].mean(),
    "mean_grounding": completed["judge_grounding"].mean(),
    "mean_helpfulness": completed["judge_helpfulness"].mean(),
    "mean_overall_quality": completed["judge_overall_quality"].mean(),
    "median_overall_quality": completed["judge_overall_quality"].median(),
    "unsupported_claim_rate": completed["judge_unsupported_claim"].mean()
}

print("\nOverall metrics:")

for key, value in metrics.items():

    if "rate" in key:
        print(f"{key}: {value:.1%}")

    elif "examples" in key:
        print(f"{key}: {value}")

    else:
        print(f"{key}: {value:.3f}")

# ---------------------------------------------------------
# Overall quality distribution
# ---------------------------------------------------------

print("\nOverall quality distribution:")

quality_distribution = (
    completed["judge_overall_quality"]
    .value_counts()
    .sort_index()
)

display(
    quality_distribution.rename(
        "count"
    ).to_frame()
)

# ---------------------------------------------------------
# Unsupported claims
# ---------------------------------------------------------

print("\nUnsupported claims:")

unsupported = (
    completed["judge_unsupported_claim"]
    .value_counts()
    .sort_index()
)

display(
    unsupported.rename(
        "count"
    ).to_frame()
)

============================================================
FINAL LLM-AS-JUDGE RESULTS
============================================================
Total evaluation examples: 30
Generated replies: 30
Completed judgments: 30

Overall metrics:
examples_judged: 30
mean_relevance: 4.967
mean_grounding: 5.000
mean_helpfulness: 4.767
mean_overall_quality: 4.767
median_overall_quality: 5.000
unsupported_claim_rate: 0.0%

Overall quality distribution:

                       count
judge_overall_quality
4.0                        7
5.0                       23

Unsupported claims:

                         count
judge_unsupported_claim
0.0                         30

In [138]:
# ---------------------------------------------------------
# LLM quality by predicted intent
# ---------------------------------------------------------

intent_quality = (
    completed
    .groupby("predicted_intent")
    .agg(
        examples=("evaluation_id", "count"),
        relevance=("judge_relevance", "mean"),
        grounding=("judge_grounding", "mean"),
        helpfulness=("judge_helpfulness", "mean"),
        overall_quality=("judge_overall_quality", "mean"),
        unsupported_claim_rate=(
            "judge_unsupported_claim",
            "mean"
        )
    )
    .sort_values(
        "overall_quality",
        ascending=False
    )
)

display(
    intent_quality.round(3)
)

,examples,relevance,grounding,helpfulness,overall_quality,unsupported_claim_rate
predicted_intent,,,,,,
audio,1,5.00,5.0,5.00,5.00,0.0
device_hardware,1,5.00,5.0,5.00,5.00,0.0
display_input,6,5.00,5.0,5.00,5.00,0.0
connectivity,1,5.00,5.0,5.00,5.00,0.0
ios_update,5,5.00,5.0,4.80,4.80,0.0
apple_services,8,5.00,5.0,4.75,4.75,0.0
account_authentication,2,5.00,5.0,4.50,4.50,0.0
battery_charging,2,5.00,5.0,4.50,4.50,0.0
apps_app_store,4,4.75,5.0,4.50,4.50,0.0

In [139]:
# ---------------------------------------------------------
# Lowest-quality generated responses
# ---------------------------------------------------------

worst_examples = (
    completed
    .sort_values(
        [
            "judge_overall_quality",
            "judge_grounding",
            "judge_helpfulness"
        ],
        ascending=True
    )
    [
        [
            "evaluation_id",
            "customer_message",
            "predicted_intent",
            "draft_reply",
            "judge_relevance",
            "judge_grounding",
            "judge_helpfulness",
            "judge_overall_quality",
            "judge_unsupported_claim",
            "judge_major_issue",
            "judge_short_reason"
        ]
    ]
)

display(
    worst_examples.head(10)
)

,evaluation_id,customer_message,predicted_intent,draft_reply,judge_relevance,judge_grounding,judge_helpfulness,judge_overall_quality,judge_unsupported_claim,judge_major_issue,judge_short_reason
0,1,Hey @115858 how can Siri really be my personal assistant if it won't integrate into 3rd party apps why can't I have it play Spotify where is the functionality?,apple_services,We understand wanting Siri to work with your favorite apps. Let's look into this together. Please send us a DM so we can help.,5.0,5.0,4.0,4.0,0.0,none,"The reply is highly relevant to the customer's query about Siri and third-party apps, and it aligns perfectly with the historical support cases which consistently direct customers to DM for assist..."
8,9,"@AppleSupport hey why is the remove episode option gone from the podcast app, subscribed podcasts keep popping up after I delete them",apps_app_store,We'd like to help. Does this issue with deleted episodes reappearing occur with all podcasts or a specific one? Please meet us in DM so we can look into this further.,5.0,5.0,4.0,4.0,0.0,none,"The reply is highly relevant, well-grounded in the provided historical cases (specifically Case 3), and offers a helpful next step by asking a clarifying question and inviting the customer to DM."
11,12,@AppleSupport my iMessage has not worked in over a month at this point. I’ve spent considerable amount of time with your customer support to get this solved but there has been no solution yet. Ple...,ios_update,We want to help get your iMessage working as soon as possible. Please send us a DM so we can look into this further and help find a solution.,5.0,5.0,4.0,4.0,0.0,none,"The reply is relevant and grounded in the historical cases, offering to continue the conversation in DM. However, it could have acknowledged the customer's frustration regarding their previous uns..."
14,15,Anyone know how to covert an existing iCloud account to a child account? My kids would hate to lose any game data. cc @AppleSupport,account_authentication,We'd love to help you with your family's iCloud accounts and make sure no game data is lost. Please join us in DM so we can gather more details and guide you through this: https://t.co/GDrqU22YpT,5.0,5.0,4.0,4.0,0.0,none,"The reply politely invites the customer to DM to resolve their specific account migration issue, which is consistent with how Apple Support handles complex account queries in the provided cases."
19,20,"@AppleSupport why offer app ""controls"" in a managed account when apple apps mysteriously enable themselves when login back, such as safari? #unbelievable",apps_app_store,We're here for you. Let's take a look at this further for you. Reach out to us in DM.,4.0,5.0,4.0,4.0,0.0,none,"The reply appropriately invites the customer to DM to troubleshoot the complex managed account issue further, which is strongly supported by the historical cases."
20,21,"@115858 please say your developers are hard at work on iOS 11.0.4 so that my headphones, charger and volume buttons work again, ughhhh 🙄🙄🙄🙄🙄",apple_services,"We want your device to work seamlessly. Join us in DM with more details about what's happening, and we'll take a look into this with you. https://t.co/GDrqU22YpT",5.0,5.0,4.0,4.0,0.0,none,"The reply is polite, relevant, and strongly grounded in the provided historical cases, offering a standard DM transition to troubleshoot the issues."
29,30,@AppleSupport The “done” button will not let me select my picture. It’s covered in the top right corner of the phone with the battery and wifi icons. It gets stuck and I have to close out the app.,battery_charging,We'd like to help look into this with you. Go ahead and reach out to us in DM and we'll continue there.,5.0,5.0,4.0,4.0,0.0,none,The reply is highly relevant and grounded in the historical cases where customers experiencing UI issues with photos are invited to DM. It could be improved by including a direct DM link.
1,2,@AppleSupport Was able to help him via iTunes. Still weird the OTA didn’t work,ios_update,"We're glad you were able to complete the update using iTunes. To help us look into why the over-the-air update didn't work, did you see any specific error messages? If you'd like to troubleshoot t...",5.0,5.0,5.0,5.0,0.0,none,"The AI-generated reply is highly relevant, acknowledging the successful iTunes update while addressing the OTA issue. It is well-grounded in the historical cases, which frequently ask about error ..."
2,3,@379507 @AppleSupport Having the same issue.,apple_services,"We'd like to look into this concern with you. Send us a DM with the details, and we'll continue there. https://t.co/GDrqU22YpT",5.0,5.0,5.0,5.0,0.0,none,"The AI-generated reply is highly relevant, perfectly grounded in the historical cases, and provides the correct next step for a customer reporting a generic issue."
3,4,Hey @AppleSupport iOS11 update made my $900 iPad Pro unusable. The battery lasts 1/2 day even if just sitting there in airplane mode. #SUCKS,battery_charging,We'd be happy to look into this with you. Please meet us in DM so we can gather some more information and better assist. https://t.co/GDrqU22YpT,5.0,5.0,5.0,5.0,0.0,none,"The AI-generated reply is highly relevant, helpful, and perfectly grounded in the provided historical cases, which frequently suggest moving to DMs to resolve battery issues."

In [140]:
# ---------------------------------------------------------
# Create a fixed 10-example human evaluation subset
# ---------------------------------------------------------

import pandas as pd

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

judge_data = pd.read_csv(judge_path)

completed = judge_data[
    judge_data["judge_completed"].fillna(False).astype(bool)
].copy()

# Fixed random sample for reproducibility.
human_subset = (
    completed
    .sample(
        n=10,
        random_state=2026
    )
    .sort_values("evaluation_id")
    .reset_index(drop=True)
)

# Keep only information a human evaluator needs.
human_review = human_subset[
    [
        "evaluation_id",
        "customer_message",
        "previous_message",
        "predicted_intent",
        "draft_reply"
    ]
].copy()

# Human scoring fields.
human_review["human_relevance"] = ""
human_review["human_grounding"] = ""
human_review["human_helpfulness"] = ""
human_review["human_overall_quality"] = ""
human_review["human_unsupported_claim"] = ""
human_review["human_notes"] = ""

human_review_path = (
    evaluation_dir /
    "apple_support_human_review_10.csv"
)

human_review.to_csv(
    human_review_path,
    index=False
)

print("Human review set created.")
print("Examples:", len(human_review))
print("\nEvaluation IDs:")
print(
    human_review["evaluation_id"].tolist()
)

print("\nSaved:")
print(human_review_path)

Human review set created.
Examples: 10

Evaluation IDs:
[4, 9, 10, 11, 12, 15, 19, 22, 23, 24]

Saved:
c:\Projects\hiver-support-agent\data\evaluation\apple_support_human_review_10.csv

In [141]:
# ---------------------------------------------------------
# Create a readable human-review interface
# No Gemini API calls
# ---------------------------------------------------------

import pandas as pd

judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

judge_data = pd.read_csv(judge_path)

completed = judge_data[
    judge_data["judge_completed"].fillna(False).astype(bool)
].copy()

# Same fixed 10 examples as before
human_subset = (
    completed
    .sample(
        n=10,
        random_state=2026
    )
    .sort_values("evaluation_id")
    .reset_index(drop=True)
)

print("=" * 80)
print("HUMAN REVIEW — 10 EXAMPLES")
print("=" * 80)

for i, row in human_subset.iterrows():

    print("\n" + "=" * 80)
    print(f"EXAMPLE {i + 1} / 10")
    print(f"Evaluation ID: {row['evaluation_id']}")
    print("=" * 80)

    print("\nCUSTOMER MESSAGE:")
    print("-" * 80)
    print(row["customer_message"])

    if (
        pd.notna(row["previous_message"])
        and str(row["previous_message"]).strip()
    ):
        print("\nPREVIOUS MESSAGE:")
        print("-" * 80)
        print(row["previous_message"])

    print("\nPREDICTED INTENT:")
    print("-" * 80)
    print(row["predicted_intent"])

    print("\nAI-GENERATED REPLY:")
    print("-" * 80)
    print(row["draft_reply"])

    print("\nYOUR SCORES:")
    print("-" * 80)
    print("Relevance       : 1-5")
    print("Grounding       : 1-5")
    print("Helpfulness     : 1-5")
    print("Overall quality : 1-5")
    print("Unsupported     : 0 = No, 1 = Yes")

    print("\n")

================================================================================
HUMAN REVIEW — 10 EXAMPLES
================================================================================

================================================================================
EXAMPLE 1 / 10
Evaluation ID: 4
================================================================================

CUSTOMER MESSAGE:
--------------------------------------------------------------------------------
Hey @AppleSupport iOS11 update made my $900 iPad Pro unusable. The battery lasts 1/2 day even if just sitting there in airplane mode. #SUCKS

PREDICTED INTENT:
--------------------------------------------------------------------------------
battery_charging

AI-GENERATED REPLY:
--------------------------------------------------------------------------------
We'd be happy to look into this with you. Please meet us in DM so we can gather some more information and better assist. https://t.co/GDrqU22YpT

YOUR SCORES:
--------------------------------------------------------------------------------
Relevance       : 1-5
Grounding       : 1-5
Helpfulness     : 1-5
Overall quality : 1-5
Unsupported     : 0 = No, 1 = Yes



================================================================================
EXAMPLE 2 / 10
Evaluation ID: 9
================================================================================

CUSTOMER MESSAGE:
--------------------------------------------------------------------------------
@AppleSupport hey why is the remove episode option gone from the podcast app, subscribed podcasts keep popping up after I delete them

PREDICTED INTENT:
--------------------------------------------------------------------------------
apps_app_store

AI-GENERATED REPLY:
--------------------------------------------------------------------------------
We'd like to help. Does this issue with deleted episodes reappearing occur with all podcasts or a specific one? Please meet us in DM so we can look into this further.

YOUR SCORES:
--------------------------------------------------------------------------------
Relevance       : 1-5
Grounding       : 1-5
Helpfulness     : 1-5
Overall quality : 1-5
Unsupported     : 0 = No, 1 = Yes



================================================================================
EXAMPLE 3 / 10
Evaluation ID: 10
================================================================================

CUSTOMER MESSAGE:
--------------------------------------------------------------------------------
Hi @AppleSupport ,Apple Watch 3 has bug, restarts when you ask Siri on weather.please address this

PREDICTED INTENT:
--------------------------------------------------------------------------------
apple_services

AI-GENERATED REPLY:
--------------------------------------------------------------------------------
We'd like to look into this with you. Please send us a DM with your watchOS version, and we'll get started there.

YOUR SCORES:
--------------------------------------------------------------------------------
Relevance       : 1-5
Grounding       : 1-5
Helpfulness     : 1-5
Overall quality : 1-5
Unsupported     : 0 = No, 1 = Yes



================================================================================
EXAMPLE 4 / 10
Evaluation ID: 11
================================================================================

CUSTOMER MESSAGE:
--------------------------------------------------------------------------------
Hey .@115858 - how about you fix the I️ glitch - I️ mean - I️t’s not like I️ use the letter I️ every time I type!!!

PREDICTED INTENT:
--------------------------------------------------------------------------------
display_input

AI-GENERATED REPLY:
--------------------------------------------------------------------------------
We want to help get things working smoothly. We recently released iOS 11.1.1, which contains a fix for this autocorrect issue. Please back up your device prior to updating: https://t.co/4f8hwT5to6. If you still need help, DM us.

YOUR SCORES:
--------------------------------------------------------------------------------
Relevance       : 1-5
Grounding       : 1-5
Helpfulness     : 1-5
Overall quality : 1-5
Unsupported     : 0 = No, 1 = Yes



================================================================================
EXAMPLE 5 / 10
Evaluation ID: 12
================================================================================

CUSTOMER MESSAGE:
--------------------------------------------------------------------------------
@AppleSupport my iMessage has not worked in over a month at this point. I’ve spent considerable amount of time with your customer support to get this solved but there has been no solution yet. Please work to solve this as soon as possible. This is extremely frustrating.

PREDICTED INTENT:
--------------------------------------------------------------------------------
ios_update

AI-GENERATED REPLY:
--------------------------------------------------------------------------------
We want to help get your iMessage working as soon as possible. Please send us a DM so we can look into this further and help find a solution.

YOUR SCORES:
--------------------------------------------------------------------------------
Relevance       : 1-5
Grounding       : 1-5
Helpfulness     : 1-5
Overall quality : 1-5
Unsupported     : 0 = No, 1 = Yes



================================================================================
EXAMPLE 6 / 10
Evaluation ID: 15
================================================================================

CUSTOMER MESSAGE:
--------------------------------------------------------------------------------
Anyone know how to covert an existing iCloud account to a child account? My kids would hate to lose any game data. cc @AppleSupport

PREDICTED INTENT:
--------------------------------------------------------------------------------
account_authentication

AI-GENERATED REPLY:
--------------------------------------------------------------------------------
We'd love to help you with your family's iCloud accounts and make sure no game data is lost. Please join us in DM so we can gather more details and guide you through this: https://t.co/GDrqU22YpT

YOUR SCORES:
--------------------------------------------------------------------------------
Relevance       : 1-5
Grounding       : 1-5
Helpfulness     : 1-5
Overall quality : 1-5
Unsupported     : 0 = No, 1 = Yes



================================================================================
EXAMPLE 7 / 10
Evaluation ID: 19
================================================================================

CUSTOMER MESSAGE:
--------------------------------------------------------------------------------
@AppleSupport help I got a green line on the left side of my iPhone X screen and restarting it doesn’t make it go away

PREDICTED INTENT:
--------------------------------------------------------------------------------
apple_services

AI-GENERATED REPLY:
--------------------------------------------------------------------------------
We'd like to help with the green line on your iPhone X. Please send us a DM with your location and the iOS version you are currently running so we can investigate further. https://t.co/GDrqU22YpT

YOUR SCORES:
--------------------------------------------------------------------------------
Relevance       : 1-5
Grounding       : 1-5
Helpfulness     : 1-5
Overall quality : 1-5
Unsupported     : 0 = No, 1 = Yes



================================================================================
EXAMPLE 8 / 10
Evaluation ID: 22
================================================================================

CUSTOMER MESSAGE:
--------------------------------------------------------------------------------
@AppleSupport It's 10.3.3. Although I'm convinced it's a screen issue rather than a software one.

PREVIOUS MESSAGE:
--------------------------------------------------------------------------------
@123511 We're happy to help. What version of iOS are you currently running? Find that in Settings &gt; General &gt; About.

PREDICTED INTENT:
--------------------------------------------------------------------------------
ios_update

AI-GENERATED REPLY:
--------------------------------------------------------------------------------
Understood. Let's hop in DM to look into this screen issue and continue there. Click here: https://t.co/GDrqU22YpT

YOUR SCORES:
--------------------------------------------------------------------------------
Relevance       : 1-5
Grounding       : 1-5
Helpfulness     : 1-5
Overall quality : 1-5
Unsupported     : 0 = No, 1 = Yes



================================================================================
EXAMPLE 9 / 10
Evaluation ID: 23
================================================================================

CUSTOMER MESSAGE:
--------------------------------------------------------------------------------
@AppleSupport Hello everyone, how do I unlock my account if I do not know the trust number? https://t.co/0fYns2ZzEA

PREDICTED INTENT:
--------------------------------------------------------------------------------
apple_services

AI-GENERATED REPLY:
--------------------------------------------------------------------------------
We know how important it is to have access to your account. If you do not know your trusted number, you may need the assistance of our specialized Account Security team. Please review the support options on the following page to get started: https://t.co/UJm15vmMM2

YOUR SCORES:
--------------------------------------------------------------------------------
Relevance       : 1-5
Grounding       : 1-5
Helpfulness     : 1-5
Overall quality : 1-5
Unsupported     : 0 = No, 1 = Yes



================================================================================
EXAMPLE 10 / 10
Evaluation ID: 24
================================================================================

CUSTOMER MESSAGE:
--------------------------------------------------------------------------------
@115858 every time I️ use the letter “I️” on my keyboard I️t turns into some weird symbol. IM PISSED

PREDICTED INTENT:
--------------------------------------------------------------------------------
display_input

AI-GENERATED REPLY:
--------------------------------------------------------------------------------
We're here to help. An update has been released that addresses this issue. If you haven't already, back up your device and update to iOS version 11.1.1. For more information, click here: https://t.co/xXaXeeSRt9 DM us if you have questions. https://t.co/GDrqU22YpT

YOUR SCORES:
--------------------------------------------------------------------------------
Relevance       : 1-5
Grounding       : 1-5
Helpfulness     : 1-5
Overall quality : 1-5
Unsupported     : 0 = No, 1 = Yes

In [142]:
import pandas as pd

human_scores = {
    4:  (5, 5, 3, 4, 0),
    9:  (5, 5, 4, 4, 0),
    10: (5, 5, 4, 4, 0),
    11: (5, 5, 5, 5, 0),
    12: (5, 4, 4, 3, 0),
    15: (5, 5, 4, 5, 0),
    19: (5, 4, 4, 4, 0),
    22: (5, 5, 5, 5, 0),
    23: (5, 5, 5, 5, 0),
    24: (5, 5, 5, 5, 0),
}

human_path = evaluation_dir / "apple_support_human_review_10.csv"

human_review = pd.read_csv(human_path)

# Remove accidental ** characters if they exist in column names
human_review.columns = (
    human_review.columns
    .str.replace("*", "", regex=False)
    .str.strip()
)

for eval_id, scores in human_scores.items():
    mask = human_review["evaluation_id"] == eval_id

    human_review.loc[mask, "human_relevance"] = scores[0]
    human_review.loc[mask, "human_grounding"] = scores[1]
    human_review.loc[mask, "human_helpfulness"] = scores[2]
    human_review.loc[mask, "human_overall_quality"] = scores[3]
    human_review.loc[mask, "human_unsupported_claim"] = scores[4]

human_review.to_csv(human_path, index=False)

print(human_review.to_string(index=False))

 evaluation_id                                                                                                                                                                                                                                                               customer_message                                                                                                           previous_message       predicted_intent                                                                                                                                                                                                                                                               draft_reply  human_relevance  human_grounding  human_helpfulness  human_overall_quality  human_unsupported_claim  human_notes
             4                                                                                                                                   Hey @AppleSupport iOS11 update made my $900 iPad Pro unusable. The battery lasts 1/2 day even if just sitting there in airplane mode. #SUCKS                                                                                                                        NaN       battery_charging                                                                                                                          We'd be happy to look into this with you. Please meet us in DM so we can gather some more information and better assist. https://t.co/GDrqU22YpT              5.0              5.0                3.0                    4.0                      0.0          NaN
             9                                                                                                                                          @AppleSupport hey why is the remove episode option gone from the podcast app, subscribed podcasts keep popping up after I delete them                                                                                                                        NaN         apps_app_store                                                                                                    We'd like to help. Does this issue with deleted episodes reappearing occur with all podcasts or a specific one? Please meet us in DM so we can look into this further.              5.0              5.0                4.0                    4.0                      0.0          NaN
            10                                                                                                                                                                             Hi @AppleSupport ,Apple Watch 3 has bug, restarts when you ask Siri on weather.please address this                                                                                                                        NaN         apple_services                                                                                                                                                         We'd like to look into this with you. Please send us a DM with your watchOS version, and we'll get started there.              5.0              5.0                4.0                    4.0                      0.0          NaN
            11                                                                                                                                                            Hey .@115858 - how about you fix the I️ glitch - I️ mean - I️t’s not like I️ use the letter I️ every time I type!!!                                                                                                                        NaN          display_input                                      We want to help get things working smoothly. We recently released iOS 11.1.1, which contains a fix for this autocorrect issue. Please back up your device prior to updating: https://t.co/4f8hwT5to6. If you still need help, DM us.              5.0              5.0                5.0                    5.0                      0.0          NaN
            12 @AppleSupport my iMessage has not worked in over a month at this point. I’ve spent considerable amount of time with your customer support to get this solved but there has been no solution yet. Please work to solve this as soon as possible. This is extremely frustrating.                                                                                                                        NaN             ios_update                                                                                                                             We want to help get your iMessage working as soon as possible. Please send us a DM so we can look into this further and help find a solution.              5.0              4.0                4.0                    3.0                      0.0          NaN
            15                                                                                                                                            Anyone know how to covert an existing iCloud account to a child account? My kids would hate to lose any game data. cc @AppleSupport                                                                                                                        NaN account_authentication                                                                       We'd love to help you with your family's iCloud accounts and make sure no game data is lost. Please join us in DM so we can gather more details and guide you through this: https://t.co/GDrqU22YpT              5.0              5.0                4.0                    5.0                      0.0          NaN
            19                                                                                                                                                         @AppleSupport help I got a green line on the left side of my iPhone X screen and restarting it doesn’t make it go away                                                                                                                        NaN         apple_services                                                                       We'd like to help with the green line on your iPhone X. Please send us a DM with your location and the iOS version you are currently running so we can investigate further. https://t.co/GDrqU22YpT              5.0              4.0                4.0                    4.0                      0.0          NaN
            22                                                                                                                                                                              @AppleSupport It's 10.3.3. Although I'm convinced it's a screen issue rather than a software one. @123511 We're happy to help. What version of iOS are you currently running? Find that in Settings &gt; General &gt; About.             ios_update                                                                                                                                                        Understood. Let's hop in DM to look into this screen issue and continue there. Click here: https://t.co/GDrqU22YpT              5.0              5.0                5.0                    5.0                      0.0          NaN
            23                                                                                                                                                            @AppleSupport Hello everyone, how do I unlock my account if I do not know the trust number? https://t.co/0fYns2ZzEA                                                                                                                        NaN         apple_services We know how important it is to have access to your account. If you do not know your trusted number, you may need the assistance of our specialized Account Security team. Please review the support options on the following page to get started: https://t.co/UJm15vmMM2              5.0              5.0                5.0                    5.0                      0.0          NaN
            24                                                                                                                                                                           @115858 every time I️ use the letter “I️” on my keyboard I️t turns into some weird symbol. IM PISSED                                                                                                                        NaN          display_input   We're here to help. An update has been released that addresses this issue. If you haven't already, back up your device and update to iOS version 11.1.1. For more information, click here: https://t.co/xXaXeeSRt9 DM us if you have questions. https://t.co/GDrqU22YpT              5.0              5.0                5.0                    5.0                      0.0          NaN

In [145]:
import pandas as pd
import numpy as np
from sklearn.metrics import cohen_kappa_score

# ---------------------------------------------------------
# Load files
# ---------------------------------------------------------

human_path = evaluation_dir / "apple_support_human_review_10.csv"
judge_path = evaluation_dir / "apple_support_llm_judge_30.csv"

human = pd.read_csv(human_path)
judge = pd.read_csv(judge_path)

# Clean column names
human.columns = (
    human.columns
    .str.replace("*", "", regex=False)
    .str.strip()
)

judge.columns = (
    judge.columns
    .str.replace("*", "", regex=False)
    .str.strip()
)

# ---------------------------------------------------------
# Merge human and LLM scores
# ---------------------------------------------------------

human_columns = [
    "evaluation_id",
    "human_relevance",
    "human_grounding",
    "human_helpfulness",
    "human_overall_quality",
    "human_unsupported_claim"
]

judge_columns = [
    "evaluation_id",
    "judge_relevance",
    "judge_grounding",
    "judge_helpfulness",
    "judge_overall_quality",
    "judge_unsupported_claim"
]

comparison = human[human_columns].merge(
    judge[judge_columns],
    on="evaluation_id",
    how="inner"
)

print("Matched examples:", len(comparison))

# ---------------------------------------------------------
# Calculate agreement
# ---------------------------------------------------------

dimensions = [
    ("Relevance", "human_relevance", "judge_relevance"),
    ("Grounding", "human_grounding", "judge_grounding"),
    ("Helpfulness", "human_helpfulness", "judge_helpfulness"),
    ("Overall Quality", "human_overall_quality", "judge_overall_quality"),
]

results = []

for name, human_col, judge_col in dimensions:

    human_scores = comparison[human_col].astype(int)
    judge_scores = comparison[judge_col].astype(int)

    exact_agreement = (
        human_scores == judge_scores
    ).mean()

    mean_absolute_difference = np.abs(
        human_scores - judge_scores
    ).mean()

    weighted_kappa = cohen_kappa_score(
        human_scores,
        judge_scores,
        weights="quadratic"
    )

    results.append({
        "dimension": name,
        "exact_agreement": exact_agreement,
        "mean_absolute_difference": mean_absolute_difference,
        "quadratic_weighted_kappa": weighted_kappa
    })

# ---------------------------------------------------------
# Unsupported claims
# ---------------------------------------------------------

human_scores = comparison["human_unsupported_claim"].astype(int)
judge_scores = comparison["judge_unsupported_claim"].astype(int)

results.append({
    "dimension": "Unsupported Claim",
    "exact_agreement": (
        human_scores == judge_scores
    ).mean(),
    "mean_absolute_difference": np.abs(
        human_scores - judge_scores
    ).mean(),
    "quadratic_weighted_kappa": cohen_kappa_score(
        human_scores,
        judge_scores
    )
})

# ---------------------------------------------------------
# Display results
# ---------------------------------------------------------

agreement_results = pd.DataFrame(results)

print("\n" + "=" * 80)
print("HUMAN vs LLM JUDGE AGREEMENT")
print("=" * 80)

print(
    agreement_results.to_string(
        index=False,
        formatters={
            "exact_agreement": "{:.1%}".format,
            "mean_absolute_difference": "{:.2f}".format,
            "quadratic_weighted_kappa": "{:.3f}".format,
        }
    )
)

Matched examples: 10

================================================================================
HUMAN vs LLM JUDGE AGREEMENT
================================================================================
        dimension exact_agreement mean_absolute_difference quadratic_weighted_kappa
        Relevance          100.0%                     0.00                      NaN
        Grounding           80.0%                     0.20                    0.000
      Helpfulness           70.0%                     0.40                    0.231
  Overall Quality           50.0%                     0.50                    0.324
Unsupported Claim          100.0%                     0.00                      NaN

c:\Projects\hiver-support-agent\.venv\Lib\site-packages\sklearn\metrics\_classification.py:614: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Projects\hiver-support-agent\.venv\Lib\site-packages\sklearn\utils\_param_validation.py:218: UndefinedMetricWarning: `y1`, `y2` and `labels` have only one label in common. `cohen_kappa_score` is undefined and set to the value defined by the the `replace_undefined_by` param, which is set to nan.
  return func(*args, **kwargs)
c:\Projects\hiver-support-agent\.venv\Lib\site-packages\sklearn\metrics\_classification.py:614: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
c:\Projects\hiver-support-agent\.venv\Lib\site-packages\sklearn\utils\_param_validation.py:218: UndefinedMetricWarning: `y1`, `y2` and `labels` have only one label in common. `cohen_kappa_score` is undefined and set to the value defined by the the `replace_undefined_by` param, which is set to nan.
  return func(*args, **kwargs)

In [146]:
# ---------------------------------------------------------
# Save human-vs-LLM agreement results
# ---------------------------------------------------------

agreement_path = evaluation_dir / "human_llm_judge_agreement.csv"

agreement_results.to_csv(
    agreement_path,
    index=False
)

print(f"Saved: {agreement_path}")
print("\nFinal agreement results:")
print(agreement_results)

Saved: c:\Projects\hiver-support-agent\data\evaluation\human_llm_judge_agreement.csv

Final agreement results:
           dimension  exact_agreement  mean_absolute_difference  \
0          Relevance              1.0                       0.0
1          Grounding              0.8                       0.2
2        Helpfulness              0.7                       0.4
3    Overall Quality              0.5                       0.5
4  Unsupported Claim              1.0                       0.0

   quadratic_weighted_kappa
0                       NaN
1                  0.000000
2                  0.230769
3                  0.324324
4                       NaN

In [147]:
print(pd.read_csv(agreement_path))

           dimension  exact_agreement  mean_absolute_difference  \
0          Relevance              1.0                       0.0
1          Grounding              0.8                       0.2
2        Helpfulness              0.7                       0.4
3    Overall Quality              0.5                       0.5
4  Unsupported Claim              1.0                       0.0

   quadratic_weighted_kappa
0                       NaN
1                  0.000000
2                  0.230769
3                  0.324324
4                       NaN

In [148]:
# ---------------------------------------------------------
# Failure analysis dataset
# ---------------------------------------------------------

oof_errors = oof_results[
    oof_results["true_intent"] != oof_results["predicted_intent"]
].copy()

print("Total classifier errors:", len(oof_errors))

print("\nTop confusion pairs:")
print(
    oof_errors
    .groupby(["true_intent", "predicted_intent"])
    .size()
    .sort_values(ascending=False)
    .head(15)
)

Total classifier errors: 100

Top confusion pairs:
true_intent      predicted_intent
connectivity     display_input       6
ios_update       display_input       6
display_input    ios_update          5
apple_services   connectivity        4
                 apps_app_store      4
                 ios_update          3
                 display_input       3
ios_update       connectivity        3
apps_app_store   apple_services      3
other_unclear    display_input       3
display_input    apple_services      3
audio            display_input       3
                 ios_update          2
                 apple_services      2
device_hardware  display_input       2
dtype: int64

In [154]:
# ---------------------------------------------------------
# Extract real examples for the top 5 failure modes
# ---------------------------------------------------------

failure_examples = oof_errors[
    [
        "customer_tweet_id",
        "customer_message",
        "previous_message",
        "true_intent",
        "predicted_intent",
        "margin"
    ]
].copy()

pairs_to_inspect = [
    ("connectivity", "display_input"),
    ("ios_update", "display_input"),
    ("display_input", "ios_update"),
    ("apple_services", "connectivity"),
    ("apple_services", "apps_app_store"),
]

for true_intent, predicted_intent in pairs_to_inspect:

    pair_errors = failure_examples[
        (failure_examples["true_intent"] == true_intent) &
        (failure_examples["predicted_intent"] == predicted_intent)
    ]

    examples = pair_errors.head(3)

    print("\n" + "=" * 80)
    print(f"TRUE: {true_intent}  →  PREDICTED: {predicted_intent}")
    print(f"Number of errors: {len(pair_errors)}")
    print("=" * 80)

    for _, row in examples.iterrows():

        print(f"\nTweet ID: {row['customer_tweet_id']}")
        print(f"Margin: {row['margin']:.4f}")

        print("\nCUSTOMER:")
        print(row["customer_message"])

        previous = str(row["previous_message"]).strip()

        if previous and previous.lower() != "nan":
            print("\nPREVIOUS MESSAGE:")
            print(previous)

================================================================================
TRUE: connectivity  →  PREDICTED: display_input
Number of errors: 6
================================================================================

Tweet ID: 146553.0
Margin: 0.5366

CUSTOMER:
@115858 @4792 CarPlay and iPhoneX and the 2017 M240i don‘t work together. When is a fix for that coming?

Tweet ID: 1437557.0
Margin: 0.0937

CUSTOMER:
Absolutely hate it when you airdrop a bunch of photos &amp; they go all jumbled up 😖 @115858 #whyyoutestingme

Tweet ID: 1484796.0
Margin: 0.0423

CUSTOMER:
@115858 you really need to fix this update or something because every time me and my friend try to FaceTime or call, the other person doesn’t get any notification for it at all and I’m gonna scream

================================================================================
TRUE: ios_update  →  PREDICTED: display_input
Number of errors: 6
================================================================================

Tweet ID: 400853.0
Margin: 0.0295

CUSTOMER:
@AppleSupport Was able to help him via iTunes. Still weird the OTA didn’t work

PREVIOUS MESSAGE:
@210813 Let us know if the update has issues through iTunes.

Tweet ID: 1687712.0
Margin: 0.0154

CUSTOMER:
Good afternoon, @AppleSupport! It’s always some shit with y’all and these iPhone updates, huh? https://t.co/cGR2qXnGNA

Tweet ID: 2873394.0
Margin: 0.0637

CUSTOMER:
@115858 can you do another update my shit keeps freezing.. what happens when I inevitably need to call 911 and this shit doesn’t work? Do I do cpr myself with the phone? Or just Lost it and hit myself in the ducking heart hella times til I come back to life

================================================================================
TRUE: display_input  →  PREDICTED: ios_update
Number of errors: 5
================================================================================

Tweet ID: 400851.0
Margin: 0.2824

CUSTOMER:
@AppleSupport  since updating to the useless software. Screen keeps auto rotating. Sort it out

Tweet ID: 2288513.0
Margin: 0.1487

CUSTOMER:
@AppleSupport Well when the hell are they going to release for an update that doesn’t turn my I️ into a fucking question mark box?

PREVIOUS MESSAGE:
@664874 iOS 11.1.1 was recently released and it includes a fix for autocorrect issues. Be sure to back up your device prior to updating, and let us know if the issue persists afterwards. How to back up: https://t.co/4f8hwT5to6
If you need more help, DM us. https://t.co/GDrqU22YpT

Tweet ID: 34645.0
Margin: 0.0128

CUSTOMER:
@AppleSupport It's 10.3.3. Although I'm convinced it's a screen issue rather than a software one.

PREVIOUS MESSAGE:
@123511 We're happy to help. What version of iOS are you currently running? Find that in Settings &gt; General &gt; About.

================================================================================
TRUE: apple_services  →  PREDICTED: connectivity
Number of errors: 4
================================================================================

Tweet ID: 2799435.0
Margin: 0.0095

CUSTOMER:
@115858 @6990 why isn’t FaceTime working right now? I need to see @107462 face 😭😭😭

Tweet ID: 1357275.0
Margin: 0.0643

CUSTOMER:
@AppleSupport Tried all manor of witchcraft and I can't get the bookmarks that are synced in iOS to appear in Safari on my laptop.

Tweet ID: 2744221.0
Margin: 0.0209

CUSTOMER:
@AppleSupport every time I open Twitter my music shuts off and won’t let me use both at same time... assistance please, iPhone X

================================================================================
TRUE: apple_services  →  PREDICTED: apps_app_store
Number of errors: 4
================================================================================

Tweet ID: 1099710.0
Margin: 0.0791

CUSTOMER:
@379507 @AppleSupport Having the same issue.

PREVIOUS MESSAGE:
@AppleSupport iOS 11.0.3. 2 different iPhone 7s in my family, multiple iPads too. Enter address in Maps &amp; driving directions fail to load—endless spinner.

Tweet ID: 1096904.0
Margin: 0.0582

CUSTOMER:
Yo @AppleSupport how do I leave group chat on the latest iOS for iPhone. Please help. Please.

Tweet ID: 2503732.0
Margin: 0.0359

CUSTOMER:
@AppleSupport I went on iTunes and re downloaded it and it still isn’t in my library. I turned my phone off for 1 hour then back on again and still nothing.

PREVIOUS MESSAGE:
@711875 We want to help. Can you tell us which steps you've tried so far? This way we won't have you do any steps over again.

In [152]:
print(oof_errors.columns.tolist())

['customer_tweet_id', 'customer_message', 'previous_message', 'has_context', 'true_intent', 'predicted_intent', 'top_score', 'second_score', 'margin', 'is_error']

In [155]:
# ---------------------------------------------------------
# One representative real example for each major failure
# ---------------------------------------------------------

pairs_to_inspect = [
    ("connectivity", "display_input"),
    ("ios_update", "display_input"),
    ("display_input", "ios_update"),
    ("apple_services", "connectivity"),
    ("apple_services", "apps_app_store"),
]

for true_intent, predicted_intent in pairs_to_inspect:

    pair_errors = oof_errors[
        (oof_errors["true_intent"] == true_intent) &
        (oof_errors["predicted_intent"] == predicted_intent)
    ].sort_values("margin")

    row = pair_errors.iloc[0]

    print("\n" + "=" * 80)
    print(f"{true_intent} → {predicted_intent}")
    print("=" * 80)
    print(f"Tweet ID: {row['customer_tweet_id']}")
    print(f"Margin: {row['margin']:.4f}")
    print(f"Customer: {row['customer_message']}")

    previous = str(row["previous_message"]).strip()

    if previous and previous.lower() != "nan":
        print(f"Previous: {previous}")

================================================================================
connectivity → display_input
================================================================================
Tweet ID: 308550.0
Margin: 0.0208
Customer: Completely fed up with bluetooth issues in iOS 11 - @115858, sort them out!

================================================================================
ios_update → display_input
================================================================================
Tweet ID: 1687712.0
Margin: 0.0154
Customer: Good afternoon, @AppleSupport! It’s always some shit with y’all and these iPhone updates, huh? https://t.co/cGR2qXnGNA

================================================================================
display_input → ios_update
================================================================================
Tweet ID: 34645.0
Margin: 0.0128
Customer: @AppleSupport It's 10.3.3. Although I'm convinced it's a screen issue rather than a software one.
Previous: @123511 We're happy to help. What version of iOS are you currently running? Find that in Settings &gt; General &gt; About.

================================================================================
apple_services → connectivity
================================================================================
Tweet ID: 2799435.0
Margin: 0.0095
Customer: @115858 @6990 why isn’t FaceTime working right now? I need to see @107462 face 😭😭😭

================================================================================
apple_services → apps_app_store
================================================================================
Tweet ID: 2503732.0
Margin: 0.0359
Customer: @AppleSupport I went on iTunes and re downloaded it and it still isn’t in my library. I turned my phone off for 1 hour then back on again and still nothing.
Previous: @711875 We want to help. Can you tell us which steps you've tried so far? This way we won't have you do any steps over again.

In [156]:
# ---------------------------------------------------------
# Headline Results
# ---------------------------------------------------------

headline_results = {
    "Intent classifier accuracy": "50.0%",
    "Intent classifier macro F1": "43.7%",
    "Intent classifier weighted F1": "46.6%",
    "Golden evaluation set": "200 examples / 12 intents",
    "Historical retrieval top-1 similarity": "0.809 mean",
    "Historical retrieval top-5 intent alignment": "95.5%*",
    "Auto-handle rate": "25.5%",
    "Auto-handled accuracy": "84.3%",
    "Classifier errors captured by escalation": "92.0%",
    "LLM judge overall quality": "4.77 / 5",
    "LLM judge unsupported-claim rate": "0.0%",
    "Human-vs-LLM relevance agreement": "100%",
    "Human-vs-LLM grounding agreement": "80%",
    "Human-vs-LLM helpfulness agreement": "70%",
    "Human-vs-LLM overall-quality agreement": "50%",
}

for metric, value in headline_results.items():
    print(f"{metric}: {value}")

print("\n* Retrieval intent alignment is a diagnostic using the classifier's")
print("  predicted intents, not independent ground-truth retrieval labels.")

Intent classifier accuracy: 50.0%
Intent classifier macro F1: 43.7%
Intent classifier weighted F1: 46.6%
Golden evaluation set: 200 examples / 12 intents
Historical retrieval top-1 similarity: 0.809 mean
Historical retrieval top-5 intent alignment: 95.5%*
Auto-handle rate: 25.5%
Auto-handled accuracy: 84.3%
Classifier errors captured by escalation: 92.0%
LLM judge overall quality: 4.77 / 5
LLM judge unsupported-claim rate: 0.0%
Human-vs-LLM relevance agreement: 100%
Human-vs-LLM grounding agreement: 80%
Human-vs-LLM helpfulness agreement: 70%
Human-vs-LLM overall-quality agreement: 50%

* Retrieval intent alignment is a diagnostic using the classifier's
  predicted intents, not independent ground-truth retrieval labels.

## What is misleading about my headline number?

The 50.0% intent-classification accuracy should not be interpreted as the overall
quality of the support agent.

First, the classifier was evaluated on only 200 manually reviewed examples
covering 12 intents. Several intents have very small support, so the estimate is
high variance and should not be treated as production-level accuracy.

Second, the headline accuracy hides substantial class imbalance and uneven
performance across intents. For example, battery_charging and camera_photos
performed substantially better than ios_update, audio, and other_unclear.

Third, the agent is not based on classification alone. It combines intent
classification, historical-case retrieval, an LLM response generator, and a
deterministic escalation policy. Therefore, classification accuracy is only one
component of the complete system.

The 92.0% error-capture figure is also easy to overinterpret. It means that,
on this 200-example development evaluation, the conservative escalation policy
routed 92 of the 100 classifier errors to a human. It does not mean that 92%
of all real-world support failures will be detected.

The escalation threshold was selected using the same 200-example development
set, so the reported coverage and error-capture figures are not an unbiased
estimate of production performance.

Similarly, the 4.77/5 LLM-judge score comes from only 30 generated responses.
The judge-human agreement audit contains only 10 examples, so it provides a
useful sanity check but is too small to establish strong judge reliability.

Finally, the historical retrieval "intent alignment" metric is a diagnostic
rather than an independent retrieval accuracy measure because the retrieved
cases were assigned intents using the same final classifier rather than
independent human labels.

## Next Week Plan

### 1. Expand the golden evaluation set
Increase the labeled evaluation set beyond 200 examples, with deliberate
coverage of minority intents and ambiguous boundary cases.

### 2. Improve intent boundaries
Focus additional annotation on the major confusion pairs:
- connectivity vs display_input
- ios_update vs display_input
- apple_services vs connectivity
- apple_services vs apps_app_store

### 3. Add context-aware classification
Use previous customer/brand context more systematically, while ensuring that
future customer messages are not contaminated by response information.

### 4. Improve escalation calibration
Tune the classifier-margin and retrieval-similarity thresholds on a separate
validation set rather than the same set used for final evaluation.

### 5. Improve retrieval evaluation
Create independently labeled retrieval relevance judgments instead of using
classifier predictions as a proxy for retrieved-case intent.

### 6. Improve response safety
Prevent raw historical social-media URLs from being copied into generated
responses unless they have been explicitly validated.

### 7. Strengthen LLM-judge validation
Increase the human audit set and measure agreement on a larger, independently
reviewed sample before relying on the judge for regression testing.

In [158]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Project root:", PROJECT_ROOT)

Project root: c:\Projects\hiver-support-agent

In [159]:
from src.intent_classifier import train_final_model

intent_model = train_final_model()

print("Model trained successfully.")

Model trained successfully.

In [160]:
from src.retrieval import build_retriever

retriever = build_retriever()

print("Retriever ready.")

Retrieval corpus size: 106,323

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/3323 [00:00<?, ?it/s]

Retriever ready.

In [161]:
results = retriever.retrieve(
    "My iPhone battery is draining really fast after the latest update.",
    top_k=5
)

for result in results:
    print("\nRank:", result["rank"])
    print("Similarity:", round(result["similarity"], 4))
    print("Customer:", result["customer_message"])
    print("Response:", result["brand_response"])

Rank: 1
Similarity: 0.8858
Customer: @115858 Why is my iPhone battery draining so rapidly after the update?
Response: @327697 We'd like to see what we can do to help. Are you running iOS 11.0.3? We released it just the other day.

Rank: 2
Similarity: 0.8644
Customer: @AppleSupport: after installing several updates on my iPhone, the battery is draining very quickly with minimal usage. Can you help, pls?
Response: @556995 We know how vital the battery is. Please check out this article: https://t.co/TpjqFp3jxD

DM us the result. https://t.co/GDrqU22YpT

Rank: 3
Similarity: 0.8567
Customer: My iPhone battery drains so quickly with this new update ! @AppleSupport @115858 FIX IT !!!!
Response: @664427 We want you to be able to rely on your battery. Have you had a chance to take a look at the tips here for maximizing your battery life: https://t.co/bivpdfBNJ6 Is the iOS version you're using iOS 11.1.1?

Rank: 4
Similarity: 0.847
Customer: @AppleSupport why is my battery draining sooo very fast since the latest iOS update?!
Response: @567897 That should not be happening. Let us help. Let us know which device and iOS version you're using via DM. https://t.co/GDrqU22YpT

Rank: 5
Similarity: 0.8464
Customer: @AppleSupport I have updated to the new iOS and now by battery is draining faster than the normal for my phone. I’m using iPhone 7
Response: @813384 Reliable power is definitely important. We're glad to look at this with you. Could you let us know when you updated and to which iOS version you installed? You can find this at Settings &gt; General &gt; About.

In [162]:
from src.escalation import decide_escalation

result = decide_escalation(
    intent="battery_charging",
    classifier_margin=0.89,
    top_similarity=0.89,
    customer_message=(
        "My iPhone battery is draining really fast "
        "after the latest update."
    ),
)

print(result)

{'escalate': False, 'escalation_reason': 'The issue has sufficient intent confidence and relevant historical support evidence for automated handling.'}

In [163]:
result = decide_escalation(
    intent="apple_services",
    classifier_margin=0.08,
    top_similarity=0.60,
    customer_message="Having the same issue",
)

print(result)

{'escalate': True, 'escalation_reason': 'The customer message does not provide enough specific information. The intent classifier is not sufficiently confident. No sufficiently similar historical support case was retrieved.'}

In [164]:
from src.agent import support_agent

result = support_agent(
    "My iPhone battery is draining really fast "
    "after the latest update."
)

print("Intent:", result["intent"])
print("Classifier margin:", result["classifier_margin"])
print("Retrieval similarity:", result["top_similarity"])
print("Escalate:", result["escalate"])
print("Reason:", result["escalation_reason"])
print("\nDraft reply:")
print(result["draft_reply"])

Training intent classifier...
Building historical retrieval index...
Retrieval corpus size: 106,323

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/3323 [00:00<?, ?it/s]

Agent initialized.
Intent: battery_charging
Classifier margin: 0.9161
Retrieval similarity: 0.8858
Escalate: False
Reason: The issue has sufficient intent confidence and relevant historical support evidence for automated handling.

Draft reply:
We want to make sure you can rely on your battery. We're glad to look at this with you. Could you send us a DM with your iPhone model and the iOS version you installed?

In [165]:
from src.retrieval import build_retriever

retriever = build_retriever()

Retrieval corpus size: 106,323

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/3323 [00:00<?, ?it/s]

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

c:\Projects\hiver-support-agent

In [2]:
from src.agent import create_agent

agent = create_agent()

print("Agent object created successfully.")

Agent object created successfully.

In [4]:
from pathlib import Path

cache_dir = Path.cwd().parent / "data" / "processed" / "retrieval_index"

print("Cache directory:", cache_dir)
print("Directory exists:", cache_dir.exists())

if cache_dir.exists():
    print("Files:")
    for file in cache_dir.iterdir():
        print(" -", file.name, file.stat().st_size / (1024 * 1024), "MB")

Cache directory: c:\Projects\hiver-support-agent\data\processed\retrieval_index
Directory exists: True
Files:

In [6]:
import src.retrieval
import inspect

print(src.retrieval.__file__)
print("Has caching:", "INDEX_PATH" in dir(src.retrieval))

c:\Projects\hiver-support-agent\src\retrieval.py
Has caching: True

In [7]:
print(inspect.getsource(src.retrieval.build_retriever))

def build_retriever(
    clean_path: Path = CLEAN_APPLE_PATH,
) -> HistoricalRetriever:
    """
    Load or build the historical retrieval index.

    First run:
        Build embeddings → save FAISS index.

    Later runs:
        Load the saved FAISS index directly.
    """

    RETRIEVAL_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ---------------------------------------------
    # Load cached index if available
    # ---------------------------------------------

    if INDEX_PATH.exists() and CORPUS_PATH.exists():

        print("Loading cached retrieval index...")

        corpus = pd.read_csv(
            CORPUS_PATH
        )

        index = faiss.read_index(
            str(INDEX_PATH)
        )

        print(
            f"Loaded retrieval index with "
            f"{index.ntotal:,} cases."
        )

        return HistoricalRetriever(
            corpus=corpus,
            index=index,
        )

    # ---------------------------------------------
    # Otherwise build the index
    # ---------------------------------------------

    if not clean_path.exists():
        raise FileNotFoundError(
            f"Clean dataset not found: {clean_path}"
        )

    clean_data = pd.read_csv(
        clean_path
    )

    retrieval_corpus = build_retrieval_corpus(
        clean_data
    )

    print(
        f"Retrieval corpus size: "
        f"{len(retrieval_corpus):,}"
    )

    retriever = HistoricalRetriever(
        corpus=retrieval_corpus
    )

    retriever.build_index()

    # Save artifacts
    print("Saving retrieval index...")

    faiss.write_index(
        retriever.index,
        str(INDEX_PATH),
    )

    retrieval_corpus.to_csv(
        CORPUS_PATH,
        index=False,
    )

    print(
        f"Saved index to: {INDEX_PATH}"
    )

    return retriever

In [8]:
from src.retrieval import build_retriever

retriever = build_retriever()

Retrieval corpus size: 106,323

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Encoding 106,323 historical messages...

Batches:   0%|          | 0/3323 [00:00<?, ?it/s]

Saving retrieval index...
Saved index to: C:\Projects\hiver-support-agent\data\processed\retrieval_index\apple_support.faiss

In [9]:
from pathlib import Path

cache_dir = Path.cwd().parent / "data" / "processed" / "retrieval_index"

for file in cache_dir.iterdir():
    print(
        file.name,
        round(file.stat().st_size / (1024 * 1024), 2),
        "MB"
    )

apple_support.faiss 155.75 MB
retrieval_corpus.csv 31.67 MB

In [10]:
from src.retrieval import build_retriever

retriever = build_retriever()

Loading cached retrieval index...
Loaded retrieval index with 106,323 cases.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [12]:
import pandas as pd
from src.config import GOLDEN_SET_PATH

golden_set = pd.read_csv(GOLDEN_SET_PATH)

print("Golden set shape:", golden_set.shape)
print("Intents:", golden_set["intent"].nunique())
print("Missing labels:", golden_set["intent"].isna().sum())

Golden set shape: (200, 6)
Intents: 12
Missing labels: 0

In [13]:
from src.evaluation import (
    evaluate_per_intent,
    build_word_char_svm,
)

per_intent, predictions = evaluate_per_intent(
    build_word_char_svm(),
    golden_set,
)

per_intent

                    intent  precision    recall        f1  support
0   account_authentication   0.619048  0.722222  0.666667     18.0
1           apple_services   0.333333  0.280000  0.304348     25.0
2           apps_app_store   0.583333  0.700000  0.636364     20.0
3                    audio   0.000000  0.000000  0.000000     12.0
4         battery_charging   0.761905  0.842105  0.800000     19.0
5            camera_photos   0.818182  0.818182  0.818182     11.0
6             connectivity   0.411765  0.333333  0.368421     21.0
7          device_hardware   0.363636  0.266667  0.307692     15.0
8            display_input   0.462963  0.714286  0.561798     35.0
9            icloud_backup   1.000000  0.333333  0.500000      6.0
10              ios_update   0.166667  0.153846  0.160000     13.0
11           other_unclear   0.000000  0.000000  0.000000      5.0

In [14]:
from src.evaluation import get_confusion_pairs

confusion_pairs = get_confusion_pairs(
    golden_set["intent"].values,
    predictions,
)

confusion_pairs

               true_intent        predicted_intent  count
0               ios_update           display_input      6
1             connectivity           display_input      5
2           apple_services           display_input      4
3            display_input              ios_update      4
4           apple_services            connectivity      4
5           apple_services          apps_app_store      4
6             connectivity          apple_services      3
7                    audio           display_input      3
8               ios_update            connectivity      3
9            display_input          apple_services      3
10           other_unclear           display_input      3
11         device_hardware           display_input      3
12          apple_services  account_authentication      2
13  account_authentication          apple_services      2
14            connectivity          apps_app_store      2